"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { RoadmapExperience } from "./RoadmapExperience";
import { RoadmapHub } from "./RoadmapHub";
import { roadmapCards } from "./roadmap-data";

type Lang="uz"|"en"; type View="home"|"roadmaps"|"roadmap"|"problems"|"problem"|"duel"|"leaderboard"|"profile"|"auth"|"admin";
const copy={uz:{home:"Bosh sahifa",roadmaps:"Yo‘l xaritalari",problems:"Masalalar",duel:"Duel",leaderboard:"Reyting",login:"Kirish",hero:"Algoritmlarni o‘rganing, bellashing va o‘sing.",sub:"Tushunarli o‘zbekcha darslar, haqiqiy kod tekshiruvchi va 30 daqiqalik jonli duellar — barchasi bitta maydonda.",start:"O‘rganishni boshlash",arena:"Duel maydoni",featured:"Mashhur yo‘l xaritalari",all:"Barchasini ko‘rish",tasks:"Masalalar banki",solve:"Yechish",submit:"Yechimni yuborish"},en:{home:"Home",roadmaps:"Roadmaps",problems:"Problems",duel:"Duel",leaderboard:"Leaderboard",login:"Sign in",hero:"Learn algorithms, compete, and grow.",sub:"Clear lessons, a real code checker, and live 30-minute duels — all in one focused arena.",start:"Start learning",arena:"Enter duel arena",featured:"Featured roadmaps",all:"View all",tasks:"Problem library",solve:"Solve",submit:"Submit solution"}};
const roads=[
 {icon:"O(n)",color:"#dfff74",uz:"Murakkablik tahlili",en:"Complexity analysis",descUz:"Tezlik va xotira chegaralarini tushuning.",descEn:"Understand time and memory limits.",units:8,progress:75},
 {icon:"↕",color:"#ffd4bd",uz:"Saralash",en:"Sorting",descUz:"Oddiy usullardan tezkor saralashgacha.",descEn:"From simple methods to quick sort.",units:10,progress:40},
 {icon:"⌕",color:"#dbe2ff",uz:"Ikkilik qidiruv",en:"Binary search",descUz:"Javob bo‘yicha qidirish sirlarini oching.",descEn:"Master searching over the answer.",units:7,progress:20},
 {icon:"◆",color:"#ffe8a3",uz:"Ochko‘z algoritmlar",en:"Greedy algorithms",descUz:"Mahalliy tanlovdan optimal yechimgacha.",descEn:"Turn local choices into optimal solutions.",units:9,progress:0},
 {icon:"⌘",color:"#c9f0de",uz:"Graflar",en:"Graphs",descUz:"BFS, DFS va eng qisqa yo‘llar.",descEn:"BFS, DFS, and shortest paths.",units:14,progress:0},
 {icon:"∑",color:"#ead8ff",uz:"Dinamik dasturlash",en:"Dynamic programming",descUz:"Holatlar, o‘tishlar va optimallashtirish.",descEn:"States, transitions, and optimization.",units:16,progress:0},
];
const allRoads=roadmapCards;
const problems=[
 {id:"A01",uz:"Ikki son yig‘indisi",en:"Sum of two numbers",difficulty:"easy",tag:"Boshlang‘ich",points:100},
 {id:"A02",uz:"Eng katta element",en:"Maximum element",difficulty:"easy",tag:"Massiv",points:100},
 {id:"A03",uz:"Juftlar soni",en:"Count the evens",difficulty:"easy",tag:"Massiv",points:100},
 {id:"B01",uz:"Yashirin son",en:"Hidden number",difficulty:"medium",tag:"Binary search",points:200},
 {id:"B02",uz:"Bekatlar",en:"Bus stops",difficulty:"medium",tag:"Greedy",points:200},
 {id:"B03",uz:"Labirint yo‘li",en:"Maze path",difficulty:"medium",tag:"BFS",points:200},
 {id:"C01",uz:"Qadimiy daraxt",en:"Ancient tree",difficulty:"hard",tag:"Graph",points:300},
 {id:"C02",uz:"Tanga strategiyasi",en:"Coin strategy",difficulty:"hard",tag:"DP",points:300},
 {id:"C03",uz:"Eng uzun yo‘l",en:"Longest route",difficulty:"hard",tag:"DAG",points:300},
];
const leaders=[{n:"Sardor",u:"@sardor_ioi",r:1864,w:42},{n:"Madina",u:"@madina_dev",r:1792,w:37},{n:"Azizbek",u:"@aziz_algo",r:1718,w:29},{n:"Siz",u:"@algoyolchi",r:1462,w:12},{n:"Nilufar",u:"@nilufar_py",r:1421,w:18}];
const cpp=`#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    long long a, b;\n    cin >> a >> b;\n    cout << a + b << "\\n";\n    return 0;\n}`;

/* ---- Supabase: rol (owner / admin / user) va profil ---- */
export type Role="user"|"admin"|"owner";
export type Profile={id:string;email:string;username:string;display_name:string;role:Role;duel_rating:number;solved_count:number};
export const supabaseConfig=()=>({url:process.env.NEXT_PUBLIC_SUPABASE_URL,key:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY});
export const supabaseReady=()=>{const {url,key}=supabaseConfig();return Boolean(url&&key)};
const readToken=()=>typeof window==="undefined"?null:sessionStorage.getItem("algoyol-access-token");
export async function fetchProfile(token:string):Promise<Profile|null>{
 const {url,key}=supabaseConfig();if(!url||!key||!token)return null;
 const headers={apikey:key,Authorization:`Bearer ${token}`};
 try{
  const account=await fetch(`${url}/auth/v1/user`,{headers});if(!account.ok)return null;
  const user=await account.json() as {id?:string;email?:string};if(!user.id)return null;
  const rows=await fetch(`${url}/rest/v1/profiles?id=eq.${user.id}&select=id,username,display_name,role,duel_rating,solved_count`,{headers});if(!rows.ok)return null;
  const list=await rows.json() as Array<Omit<Profile,"email">>;if(!list.length)return null;
  sessionStorage.setItem("algoyol-user-id",user.id);
  return {...list[0],email:user.email||""};
 }catch{return null}
}
export async function saveDuelRating(next:number){
 const {url,key}=supabaseConfig(),token=readToken(),id=typeof window==="undefined"?null:sessionStorage.getItem("algoyol-user-id");
 if(!url||!key||!token||!id)return;
 try{await fetch(`${url}/rest/v1/profiles?id=eq.${id}`,{method:"PATCH",headers:{apikey:key,Authorization:`Bearer ${token}`,"content-type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({duel_rating:next})})}catch{}
}
const roleLabel=(role:Role,lang:Lang)=>role==="owner"?(lang==="uz"?"EGA (OWNER)":"OWNER"):role==="admin"?"ADMIN":(lang==="uz"?"FOYDALANUVCHI":"USER");

export function AlgoYolApp(){
 const [lang,setLang]=useState<Lang>("uz"),[view,setView]=useState<View>("home"),[filter,setFilter]=useState("all"),[code,setCode]=useState(cpp),[codeLang,setCodeLang]=useState<"cpp20"|"python3">("cpp20"),[verdict,setVerdict]=useState(""),[signed,setSigned]=useState(false),[selectedRoadmap,setSelectedRoadmap]=useState("foundations"); const t=copy[lang];
 const [profile,setProfile]=useState<Profile|null>(null),[loadingProfile,setLoadingProfile]=useState(false);
 const loadProfile=async(token:string)=>{setLoadingProfile(true);const next=await fetchProfile(token);setProfile(next);setSigned(true);setLoadingProfile(false)};
 const signOut=()=>{sessionStorage.removeItem("algoyol-access-token");sessionStorage.removeItem("algoyol-user-id");setProfile(null);setSigned(false);setView("home")};
 useEffect(()=>{const saved=localStorage.getItem("algoyol-lang") as Lang|null;if(saved)setLang(saved)},[]);
 useEffect(()=>{const token=sessionStorage.getItem("algoyol-access-token");if(token&&supabaseReady())loadProfile(token)},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.hash.replace(/^#/,""));const token=params.get("access_token"),error=params.get("error_description");if(token){sessionStorage.setItem("algoyol-access-token",token);setSigned(true);setView("profile");loadProfile(token);window.history.replaceState({},"",window.location.pathname)}else if(error){setView("auth");window.history.replaceState({},"",window.location.pathname);window.setTimeout(()=>window.alert(decodeURIComponent(error.replace(/\+/g," "))),50)}},[]);
 useEffect(()=>{if(!verdict.startsWith("Qabul qilindi")&&!verdict.startsWith("Accepted"))return;const lesson=localStorage.getItem("algoyol-active-lesson");if(!lesson)return;let data={quizScores:{},solved:{}} as {quizScores:Record<string,number>;solved:Record<string,boolean>};try{data=JSON.parse(localStorage.getItem("algoyol-roadmap-progress")||JSON.stringify(data))}catch{}data.solved={...data.solved,[lesson]:true};localStorage.setItem("algoyol-roadmap-progress",JSON.stringify(data));localStorage.removeItem("algoyol-active-lesson");window.dispatchEvent(new Event("algoyol-progress"))},[verdict]);
 const go=(v:View)=>{setView(v);window.scrollTo({top:0,behavior:"smooth"})}; const swap=()=>{const n=lang==="uz"?"en":"uz";setLang(n);localStorage.setItem("algoyol-lang",n)};
 const openRoadmap=(slug:string)=>{setSelectedRoadmap(slug);go("roadmap")};
 const filtered=useMemo(()=>filter==="all"?problems:problems.filter(p=>p.difficulty===filter),[filter]);
 const judge=async()=>{setVerdict(lang==="uz"?"Navbatda… testlar tekshirilmoqda":"In queue… running hidden tests");try{const response=await fetch("/api/judge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({problemId:"sum-two",language:codeLang,sourceCode:code})});const r=await response.json();const names:Record<string,[string,string]>={ACCEPTED:["Qabul qilindi","Accepted"],WRONG_ANSWER:["Noto‘g‘ri javob","Wrong answer"],COMPILATION_ERROR:["Kompilyatsiya xatosi","Compilation error"],RUNTIME_ERROR:["Bajarilish xatosi","Runtime error"],TIME_LIMIT_EXCEEDED:["Vaqt chegarasi oshdi","Time limit exceeded"],MEMORY_LIMIT_EXCEEDED:["Xotira chegarasi oshdi","Memory limit exceeded"],JUDGE_ERROR:["Tekshiruvchi xatosi","Judge error"]};const title=(names[r.verdict]||names.JUDGE_ERROR)[lang==="uz"?0:1];const test=r.test?` · ${lang==="uz"?"test":"test"} #${r.test}`:"";const stats=r.verdict==="ACCEPTED"?` · ${r.passed}/${r.total} · ${r.runtimeMs} ms · ${r.memoryKb} KB`:"";setVerdict(`${title}${test}${stats}${r.details?`\n${String(r.details).slice(0,900)}`:""}`)}catch{setVerdict(lang==="uz"?"Tekshiruvchi bilan aloqa uzildi":"Judge connection failed")}};
 return <div className="shell"><header className="topbar"><button className="brand" onClick={()=>go("home")} style={{border:0,background:"transparent"}}><span className="brandmark">A›</span>AlgoYo‘l</button><nav className="nav">{(["home","roadmaps","problems","duel","leaderboard"] as View[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>go(v)}>{t[v as keyof typeof t]}</button>)}</nav><div className="actions"><button className="lang" onClick={swap}>{lang==="uz"?"EN":"UZ"}</button><button className="pill" onClick={()=>go(signed?"profile":"auth")}>{signed?(lang==="uz"?"Profil":"Profile"):t.login}</button><button className="primary" onClick={()=>go("duel")}>{lang==="uz"?"Duel topish":"Find duel"}</button></div></header>
 <main className="main">{view==="home"&&<Home lang={lang} go={go} openRoadmap={openRoadmap}/>} {view==="roadmaps"&&<RoadmapHub lang={lang} openRoadmap={openRoadmap}/>} {view==="roadmap"&&<RoadmapExperience slug={selectedRoadmap} lang={lang} onBack={()=>go("roadmaps")} onPractice={()=>go("problem")}/>} {view==="problems"&&<Problems lang={lang} filter={filter} setFilter={setFilter} items={filtered} go={go}/>} {view==="problem"&&<Problem lang={lang} code={code} setCode={setCode} codeLang={codeLang} setCodeLang={setCodeLang} verdict={verdict} submit={judge}/>} {view==="duel"&&<DuelMatchmaking lang={lang} profile={profile}/>} {view==="leaderboard"&&<Leaderboard lang={lang}/>} {view==="profile"&&<Profile lang={lang} go={go} profile={profile} loading={loadingProfile} signOut={signOut}/>} {view==="auth"&&<Auth lang={lang} done={token=>{if(token)loadProfile(token);else setSigned(true);go("profile")}}/>} {view==="admin"&&<Admin lang={lang} profile={profile}/>}</main>
 <nav className="mobile-nav">{(["home","roadmaps","problems","duel","leaderboard"] as View[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>go(v)}>{t[v as keyof typeof t]}</button>)}</nav><footer className="footer"><span>© 2026 AlgoYo‘l · Toshkent</span><span>{lang==="uz"?"Bilimdan natijagacha.":"From learning to results."}</span></footer></div>
}
function Home({lang,go,openRoadmap}:{lang:Lang,go:(v:View)=>void,openRoadmap:(slug:string)=>void}){const t=copy[lang];return <><section className="hero"><div className="hero-copy"><div className="eyebrow">{lang==="uz"?"O‘zbekiston dasturchilari uchun":"Built for Uzbekistan’s coders"}</div><h1>{lang==="uz"?<>Algoritmlarni <em>o‘rganing</em>, bellashing va o‘sing.</>:<>Learn algorithms, <em>compete</em>, and grow.</>}</h1><p>{t.sub}</p><div className="hero-cta"><button className="primary" onClick={()=>go("roadmaps")}>{t.start} →</button><button className="secondary" onClick={()=>go("duel")}>{t.arena}</button></div><div className="orbit"/></div><div className="hero-side"><div className="stat-card"><span className="eyebrow" style={{color:"#637068"}}>{lang==="uz"?"Bugun faol":"Active today"}</span><span className="big">1,284</span><div className="mini-row"><span className="avatar">S</span><span className="avatar">M</span><span className="avatar">A</span><span className="avatar">+9</span></div></div><div className="stat-card duel"><span className="eyebrow" style={{color:"#6f3516"}}>{lang==="uz"?"Jonli duellar":"Live duels"}</span><span className="big">24</span><span>{lang==="uz"?"Hozir bellashmoqda":"competing right now"} ⚡</span></div></div></section><section><div className="section-head"><div><p className="eyebrow" style={{color:"#637068"}}>{lang==="uz"?"Bosqichma-bosqich":"Step by step"}</p><h2>{t.featured}</h2></div><button className="secondary" onClick={()=>go("roadmaps")}>{t.all} →</button></div><RoadGrid lang={lang} roads={allRoads.slice(0,3)} openRoadmap={openRoadmap}/></section><section><div className="section-head"><div><p className="eyebrow" style={{color:"#637068"}}>100 · 200 · 300</p><h2>{t.tasks}</h2></div><button className="secondary" onClick={()=>go("problems")}>{t.all} →</button></div><ProblemList lang={lang} items={problems.slice(0,4)} go={go}/></section></>}
function RoadGrid({lang,roads,openRoadmap}:{lang:Lang,roads:typeof allRoads,openRoadmap:(slug:string)=>void}){return <div className="grid">{roads.map((r)=><button className="road-card" style={{textAlign:"left"}} key={r.en} onClick={()=>openRoadmap(r.slug)}><span className="road-icon" style={{background:r.color}}>{r.icon}</span><h3>{lang==="uz"?r.uz:r.en}</h3><p className="muted">{lang==="uz"?r.descUz:r.descEn}</p><div className="progress"><span style={{width:r.progress+"%"}}/></div><div className="meta"><span>{r.units} {lang==="uz"?"bosqich":"units"}</span><span>800 → 2200</span></div></button>)}</div>}
function ProblemList({lang,items,go}:{lang:Lang,items:typeof problems,go:(v:View)=>void}){return <div className="problem-list">{items.map(p=><button className="problem-row" style={{textAlign:"left"}} key={p.id} onClick={()=>go("problem")}><span className="num">{p.id}</span><span><h3>{lang==="uz"?p.uz:p.en}</h3><span className={`difficulty ${p.difficulty}`}>{p.difficulty.toUpperCase()} · {p.points}</span></span><span className="tag">{p.tag}</span><span>→</span></button>)}</div>}
function Problems({lang,filter,setFilter,items,go}:{lang:Lang,filter:string,setFilter:(x:string)=>void,items:typeof problems,go:(v:View)=>void}){return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>{lang==="uz"?"Mashq maydoni":"Practice arena"}</p><h1 className="page-title">{lang==="uz"?"Masalalar banki":"Problem library"}</h1><p className="muted">{lang==="uz"?"Osondan murakkabgacha — har kuni bir qadam.":"From easy to hard — one step every day."}</p></div><button className="secondary">{lang==="uz"?"Tasodifiy masala":"Random problem"}</button></div><div className="filters">{["all","easy","medium","hard"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f==="all"?(lang==="uz"?"Barchasi":"All"):f}</button>)}</div><ProblemList lang={lang} items={items} go={go}/></>}
function Problem({lang,code,setCode,codeLang,setCodeLang,verdict,submit}:{lang:Lang,code:string,setCode:(x:string)=>void,codeLang:"cpp20"|"python3",setCodeLang:(x:"cpp20"|"python3")=>void,verdict:string,submit:()=>void}){return <><div className="page-head"><div><span className="tag">A01 · EASY · 100</span><h1 className="page-title" style={{marginTop:12}}>{lang==="uz"?"Ikki son yig‘indisi":"Sum of two numbers"}</h1></div><span className="muted">1 s · 256 MB</span></div><div className="workspace"><article className="panel statement"><h2>{lang==="uz"?"Shart":"Statement"}</h2><p>{lang==="uz"?"Sizga ikkita butun a va b sonlari beriladi. Ularning yig‘indisini toping.":"You are given two integers a and b. Print their sum."}</p><h3>{lang==="uz"?"Kirish":"Input"}</h3><p>{lang==="uz"?"Bitta qatorda ikkita butun son: a va b (−10⁹ ≤ a, b ≤ 10⁹).":"One line contains two integers a and b (−10⁹ ≤ a, b ≤ 10⁹)."}</p><h3>{lang==="uz"?"Chiqish":"Output"}</h3><p>{lang==="uz"?"Yagona son — a + b ni chiqaring.":"Print a single integer — a + b."}</p><h3>{lang==="uz"?"Namuna":"Sample"}</h3><div className="sample">Input\n12 30\n\nOutput\n42</div></article><section className="editor"><div className="editor-top"><b>{codeLang==="cpp20"?"main.cpp":"main.py"}</b><select aria-label="Language" value={codeLang} onChange={e=>{const value=e.target.value as "cpp20"|"python3";setCodeLang(value);setCode(value==="cpp20"?cpp:"a, b = map(int, input().split())\nprint(a + b)")}}><option value="cpp20">C++20</option><option value="python3">Python 3</option></select></div><textarea aria-label="Code editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/><div className="editor-actions"><span className="verdict">{verdict||"● Judge0 online"}</span><button className="primary" onClick={submit}>{copy[lang].submit} →</button></div></section></div></>}
type DuelOpponent={name:string;handle:string;rating:number;wins:number;letter:string};
type DuelProblem={key:string;code:string;difficulty:"easy"|"medium"|"hard";points:number;uz:string;en:string;stUz:string;stEn:string;inUz:string;inEn:string;outUz:string;outEn:string;sample:string;cpp:string;py:string;bot:[number,number];fail:number};
type DuelClaim={by:"me"|"opp";at:number}|null;
type DuelEvent={at:number;by:"me"|"opp"|"sys";uz:string;en:string};
type DuelResultState=null|{reason:"time"|"sweep"|"forfeit";outcome:"win"|"loss"|"draw";delta:number;claims:DuelClaim[];at:number};
const DUEL_LENGTH=1800,DUEL_K=32;
const duelOpponents:DuelOpponent[]=[{name:"Jasur",handle:"@jasur_cpp",rating:1488,wins:18,letter:"J"},{name:"Nilufar",handle:"@nilufar_py",rating:1421,wins:18,letter:"N"},{name:"Bekzod",handle:"@bek_ds",rating:1395,wins:9,letter:"B"},{name:"Azizbek",handle:"@aziz_algo",rating:1718,wins:29,letter:"A"},{name:"Madina",handle:"@madina_dev",rating:1792,wins:37,letter:"M"},{name:"Sardor",handle:"@sardor_ioi",rating:1864,wins:42,letter:"S"}];
const duelProblems:DuelProblem[]=[
 {key:"sum-two",code:"A01",difficulty:"easy",points:100,uz:"Ikki son yig‘indisi",en:"Sum of two numbers",
  stUz:"Sizga ikkita butun a va b sonlari beriladi. Ularning yig‘indisini toping.",stEn:"You are given two integers a and b. Print their sum.",
  inUz:"Bitta qatorda ikkita butun son: a va b (−10⁹ ≤ a, b ≤ 10⁹).",inEn:"One line contains two integers a and b (−10⁹ ≤ a, b ≤ 10⁹).",
  outUz:"Yagona son — a + b ni chiqaring.",outEn:"Print a single integer — a + b.",
  sample:"Input\n12 30\n\nOutput\n42",
  cpp:`#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    long long a, b;\n    cin >> a >> b;\n    cout << a + b << "\\n";\n    return 0;\n}`,
  py:`a, b = map(int, input().split())\nprint(a + b)`,bot:[170,430],fail:.03},
 {key:"max-subarray",code:"B04",difficulty:"medium",points:200,uz:"Eng katta qism-yig‘indi",en:"Maximum subarray sum",
  stUz:"n ta butun sondan iborat massiv berilgan. Bo‘sh bo‘lmagan ketma-ket qism-massivning eng katta yig‘indisini toping.",stEn:"Given an array of n integers, find the largest sum of a non-empty contiguous subarray.",
  inUz:"Birinchi qatorda n (1 ≤ n ≤ 2·10⁵). Ikkinchi qatorda n ta butun son (−10⁹ ≤ aᵢ ≤ 10⁹).",inEn:"The first line contains n (1 ≤ n ≤ 2·10⁵). The second line contains n integers (−10⁹ ≤ aᵢ ≤ 10⁹).",
  outUz:"Yagona son — eng katta qism-yig‘indi.",outEn:"Print a single integer — the maximum subarray sum.",
  sample:"Input\n9\n-2 1 -3 4 -1 2 1 -5 4\n\nOutput\n6",
  cpp:`#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    // TODO: eng katta qism-yig'indini toping / find the maximum subarray sum\n    return 0;\n}`,
  py:`n = int(input())\na = list(map(int, input().split()))\n# TODO: eng katta qism-yig'indini toping / find the maximum subarray sum`,bot:[400,820],fail:.12},
 {key:"coin-change",code:"C04",difficulty:"hard",points:300,uz:"Minimal tangalar",en:"Minimum coins",
  stUz:"n xil nominaldagi tangalar va s summa berilgan. Har bir nominaldan cheksiz olish mumkin. s ni to‘plash uchun kerak bo‘lgan eng kam tangalar sonini toping, aks holda −1 chiqaring.",stEn:"You are given n coin values and a target sum s. Each value may be used any number of times. Print the minimum number of coins that add up to exactly s, or −1 if it is impossible.",
  inUz:"Birinchi qatorda n va s (1 ≤ n ≤ 100, 0 ≤ s ≤ 10⁴). Ikkinchi qatorda n ta nominal (1 ≤ cᵢ ≤ 10⁴).",inEn:"The first line contains n and s (1 ≤ n ≤ 100, 0 ≤ s ≤ 10⁴). The second line contains n coin values (1 ≤ cᵢ ≤ 10⁴).",
  outUz:"Eng kam tangalar soni yoki −1.",outEn:"The minimum number of coins, or −1.",
  sample:"Input\n3 11\n1 2 5\n\nOutput\n3",
  cpp:`#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n, s;\n    cin >> n >> s;\n    // TODO: dinamik dasturlash bilan yeching / solve with dynamic programming\n    return 0;\n}`,
  py:`n, s = map(int, input().split())\ncoins = list(map(int, input().split()))\n# TODO: dinamik dasturlash bilan yeching / solve with dynamic programming`,bot:[650,1250],fail:.3},
];
const clock=(total:number)=>`${String(Math.floor(Math.max(0,total)/60)).padStart(2,"0")}:${String(Math.max(0,total)%60).padStart(2,"0")}`;
const duelStarter=(index:number,codeLang:"cpp20"|"python3")=>codeLang==="cpp20"?duelProblems[index].cpp:duelProblems[index].py;
const expectedScore=(mine:number,theirs:number)=>1/(1+Math.pow(10,(theirs-mine)/400));
const scoreOf=(list:DuelClaim[],who:"me"|"opp")=>list.reduce((n,c,i)=>c&&c.by===who?n+duelProblems[i].points:n,0);

function Duel({lang,opponent,rating,matchId,onFinish,onRematch,onExit}:{lang:Lang;opponent:DuelOpponent;rating:number;matchId:number;onFinish:(next:number)=>void;onRematch:()=>void;onExit:()=>void}){
 const [elapsed,setElapsed]=useState(0),[stage,setStage]=useState(0),[claims,setClaims]=useState<DuelClaim[]>([null,null,null]);
 const [feed,setFeed]=useState<DuelEvent[]>([{at:0,by:"sys",uz:"Duel boshlandi · 1-masala ochildi",en:"Duel started · problem 1 unlocked"}]);
 const [attempts,setAttempts]=useState({me:0,opp:0}),[codeLang,setCodeLang]=useState<"cpp20"|"python3">("cpp20"),[code,setCode]=useState(duelProblems[0].cpp);
 const [verdict,setVerdict]=useState(""),[bad,setBad]=useState(false),[judging,setJudging]=useState(false);
 const [result,setResult]=useState<DuelResultState>(null);
 const plan=useRef<{stage:number;solveAt:number;missAt:number;missed:boolean;fails:boolean}|null>(null);
 const remaining=Math.max(0,DUEL_LENGTH-elapsed);
 const myScore=scoreOf(claims,"me"),oppScore=scoreOf(claims,"opp");
 const push=(by:DuelEvent["by"],uz:string,en:string,at:number)=>setFeed(f=>[{at,by,uz,en},...f].slice(0,40));
 const finish=(reason:"time"|"sweep"|"forfeit",final:DuelClaim[],at:number)=>{
  const mine=scoreOf(final,"me"),theirs=scoreOf(final,"opp");
  const outcome=reason==="forfeit"?"loss":mine>theirs?"win":mine<theirs?"loss":"draw";
  const delta=Math.round(DUEL_K*((outcome==="win"?1:outcome==="draw"?.5:0)-expectedScore(rating,opponent.rating)));
  plan.current=null;setResult({reason,outcome,delta,claims:final,at:Math.min(at,DUEL_LENGTH)});onFinish(rating+delta)};
 const claimStage=(by:"me"|"opp",at:number)=>{
  if(result||stage>2||claims[stage])return;
  const problem=duelProblems[stage],next=[...claims];next[stage]={by,at};setClaims(next);setStage(stage+1);
  push(by,by==="me"?`Siz ${problem.code} ni yechdingiz · +${problem.points}`:`${opponent.name} ${problem.code} ni yechdi · +${problem.points}`,by==="me"?`You solved ${problem.code} · +${problem.points}`:`${opponent.name} solved ${problem.code} · +${problem.points}`,at);
  if(stage<2){push("sys",`${stage+2}-masala ochildi`,`Problem ${stage+2} unlocked`,at);setCode(duelStarter(stage+1,codeLang));setVerdict("");setBad(false)}
  else finish("sweep",next,at)};
 useEffect(()=>{if(result||stage>2){plan.current=null;return}const problem=duelProblems[stage];const skill=Math.min(1.45,Math.max(.6,1-(opponent.rating-rating)/1800));const span=problem.bot[0]+Math.random()*(problem.bot[1]-problem.bot[0]);const duration=Math.max(45,Math.round(span*skill));plan.current={stage,solveAt:elapsed+duration,missAt:elapsed+Math.round(duration*.55),missed:false,fails:Math.random()<problem.fail}},[stage,result]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(result)return;const id=window.setInterval(()=>setElapsed(e=>Math.min(DUEL_LENGTH,e+1)),1000);return()=>window.clearInterval(id)},[result]);
 useEffect(()=>{if(result)return;
  if(elapsed>=DUEL_LENGTH){finish("time",claims,DUEL_LENGTH);return}
  const current=plan.current;if(!current||current.stage!==stage||claims[stage])return;
  if(!current.missed&&elapsed>=current.missAt){current.missed=true;setAttempts(a=>({...a,opp:a.opp+1}));push("opp",`${opponent.name} yechim yubordi — noto‘g‘ri javob`,`${opponent.name} submitted — wrong answer`,elapsed)}
  if(!current.fails&&elapsed>=current.solveAt)claimStage("opp",elapsed)},[elapsed]);// eslint-disable-line react-hooks/exhaustive-deps
 const submit=async()=>{if(judging||result||stage>2)return;setJudging(true);setBad(false);setVerdict(lang==="uz"?"Navbatda… testlar tekshirilmoqda":"In queue… running hidden tests");
  const at=elapsed;
  try{const response=await fetch("/api/judge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({problemId:duelProblems[stage].key,language:codeLang,sourceCode:code})});const r=await response.json();
   const names:Record<string,[string,string]>={ACCEPTED:["Qabul qilindi","Accepted"],WRONG_ANSWER:["Noto‘g‘ri javob","Wrong answer"],COMPILATION_ERROR:["Kompilyatsiya xatosi","Compilation error"],RUNTIME_ERROR:["Bajarilish xatosi","Runtime error"],TIME_LIMIT_EXCEEDED:["Vaqt chegarasi oshdi","Time limit exceeded"],MEMORY_LIMIT_EXCEEDED:["Xotira chegarasi oshdi","Memory limit exceeded"],JUDGE_ERROR:["Tekshiruvchi xatosi","Judge error"]};
   const title=(names[r.verdict]||names.JUDGE_ERROR)[lang==="uz"?0:1],test=r.test?` · test #${r.test}`:"",stats=r.verdict==="ACCEPTED"?` · ${r.passed}/${r.total} · ${r.runtimeMs} ms · ${r.memoryKb} KB`:"";
   setVerdict(`${title}${test}${stats}${r.details?`\n${String(r.details).slice(0,500)}`:""}`);
   if(r.verdict==="ACCEPTED"){setBad(false);claimStage("me",at)}
   else{setBad(true);setAttempts(a=>({...a,me:a.me+1}));push("me",`Siz yechim yubordingiz — ${title.toLowerCase()}`,`You submitted — ${title.toLowerCase()}`,at)}}
  catch{setBad(true);setVerdict(lang==="uz"?"Tekshiruvchi bilan aloqa uzildi":"Judge connection failed")}
  finally{setJudging(false)}};
 if(result)return <DuelResult lang={lang} opponent={opponent} result={result} attempts={attempts} rating={rating} onRematch={onRematch} onExit={onExit}/>;
 const problem=duelProblems[Math.min(stage,2)],leader=myScore>oppScore?"me":oppScore>myScore?"opp":"";
 return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>RATED DUEL · #{matchId}</p><h1 className="page-title">{lang==="uz"?"Duel maydoni":"Duel arena"}</h1></div><span className="tag">{lang==="uz"?"Ulangan":"Connected"} ●</span></div>
 <div className="duel-layout"><section className="arena"><div className="duel-top"><b>{lang==="uz"?"30 daqiqalik duel":"30-minute duel"}</b><span className={`timer ${remaining<=300?"low":""}`}>{clock(remaining)}</span></div>
  <div className="players"><div className={`player ${leader==="me"?"lead":""}`}><span className="sub">@algoyolchi · {rating}</span><div className="who">{lang==="uz"?"Siz":"You"}</div><span className="score">{myScore}</span></div><span className="versus">VS</span>
   <div className={`player ${leader==="opp"?"lead":""}`}><span className="sub">{opponent.handle} · {opponent.rating}</span><div className="who">{opponent.name}</div><span className="score">{oppScore}</span></div></div>
  <div className="duel-steps">{duelProblems.map((p,i)=>{const claim=claims[i],state=claim?(claim.by==="me"?"mine":"theirs"):i===stage?"open":"locked";return <div key={p.key} className={`step ${state}`}><b>{String(i+1).padStart(2,"0")} · {p.difficulty.toUpperCase()}</b><span>{p.points} {lang==="uz"?"ball":"points"}</span><span className="claim">{claim?`${claim.by==="me"?(lang==="uz"?"Siz":"You"):opponent.name} · ${clock(claim.at)}`:i===stage?(lang==="uz"?"Ochiq":"Open"):(lang==="uz"?"Qulflangan":"Locked")}</span></div>})}</div>
  <div className="duel-problem"><span className="tag">{problem.code} · {problem.difficulty.toUpperCase()} · {problem.points}</span><h2>{lang==="uz"?problem.uz:problem.en}</h2>
   <p className="muted">{lang==="uz"?problem.stUz:problem.stEn}</p>
   <p className="muted"><b>{lang==="uz"?"Kirish":"Input"}:</b> {lang==="uz"?problem.inUz:problem.inEn}</p>
   <p className="muted"><b>{lang==="uz"?"Chiqish":"Output"}:</b> {lang==="uz"?problem.outUz:problem.outEn}</p>
   <div className="sample">{problem.sample}</div>
   <div className="duel-editor"><div className="editor-top"><b>{codeLang==="cpp20"?"main.cpp":"main.py"}</b><select aria-label="Duel language" value={codeLang} onChange={e=>{const value=e.target.value as "cpp20"|"python3";setCodeLang(value);setCode(duelStarter(Math.min(stage,2),value))}}><option value="cpp20">C++20</option><option value="python3">Python 3</option></select></div>
    <textarea aria-label="Duel code editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/>
    <div className="editor-actions"><span className={`duel-verdict ${bad?"bad":""}`}>{verdict||(lang==="uz"?"● Birinchi Accepted barcha ballni oladi":"● First Accepted claims all the points")}</span>
     <button className="primary" disabled={judging} onClick={submit}>{judging?(lang==="uz"?"Tekshirilmoqda…":"Judging…"):(lang==="uz"?"Yuborish":"Submit")} →</button></div></div></div></section>
  <aside className="side-stack"><div className="duel-card"><h3>{lang==="uz"?"Jonli oqim":"Live feed"}</h3><div className="feed">{feed.map((e,i)=><div key={`${e.at}-${i}`} className={`feed-item ${e.by}`}><span className="feed-time">{clock(e.at)}</span><span>{lang==="uz"?e.uz:e.en}</span></div>)}</div></div>
   <div className="duel-card"><h3>{lang==="uz"?"Statistika":"Statistics"}</h3><div className="duel-stats"><div><b>{attempts.me}</b><small>{lang==="uz"?"sizning xato":"your fails"}</small></div><div><b>{attempts.opp}</b><small>{lang==="uz"?"raqib xato":"rival fails"}</small></div><div><b>{claims.filter(Boolean).length}/3</b><small>{lang==="uz"?"yechildi":"claimed"}</small></div></div></div>
   <div className="duel-card"><h3>{lang==="uz"?"Qoidalar":"Rules"}</h3><p className="muted">{lang==="uz"?"Masalalar ketma-ket ochiladi. Birinchi Accepted barcha ballni oladi. Teng ballda noto‘g‘ri urinishlar hal qiladi.":"Problems unlock in order. The first Accepted claims all the points. Failed attempts break ties at equal score."}</p>
    <button className="ghost" onClick={()=>{push("sys",lang==="uz"?"Siz duelni tark etdingiz":"You forfeited the duel",lang==="uz"?"Siz duelni tark etdingiz":"You forfeited the duel",elapsed);finish("forfeit",claims,elapsed)}}>{lang==="uz"?"Duelni tark etish":"Forfeit duel"}</button></div></aside></div></>
}

function DuelResult({lang,opponent,result,attempts,rating,onRematch,onExit}:{lang:Lang;opponent:DuelOpponent;result:NonNullable<DuelResultState>;attempts:{me:number;opp:number};rating:number;onRematch:()=>void;onExit:()=>void}){
 const {outcome,reason,delta,claims,at}=result,myScore=scoreOf(claims,"me"),oppScore=scoreOf(claims,"opp");
 const heading=outcome==="win"?(lang==="uz"?"G‘alaba!":"Victory!"):outcome==="loss"?(lang==="uz"?"Mag‘lubiyat":"Defeat"):(lang==="uz"?"Durrang":"Draw");
 const why=reason==="forfeit"?(lang==="uz"?"Siz duelni tark etdingiz.":"You forfeited the duel."):reason==="sweep"?(lang==="uz"?"Barcha masalalar yechildi.":"Every problem was claimed."):(lang==="uz"?"Vaqt tugadi.":"Time ran out.");
 return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>RATED DUEL · {lang==="uz"?"Yakun":"Result"}</p><h1 className="page-title">{lang==="uz"?"Duel yakunlandi":"Duel finished"}</h1></div><span className="tag">{clock(at)}</span></div>
 <div className="duel-result panel"><div className={`result-badge ${outcome}`}>{outcome==="win"?"★":outcome==="loss"?"✕":"="}</div><h2>{heading}</h2><p className="muted">{why}</p>
  <div className="result-score">{myScore} : {oppScore}</div>
  <p><span className="muted">{rating} → </span><b>{rating+delta}</b> <span className={`elo-delta ${delta>=0?"up":"down"}`}>{delta>=0?"+":""}{delta}</span> <span className="muted">Elo</span></p>
  <div className="stage-table">{duelProblems.map((p,i)=>{const claim=claims[i];return <div className="stage-row" key={p.key}><span className="tag">{p.code}</span><span>{lang==="uz"?p.uz:p.en}</span><span className="muted">{claim?`${claim.by==="me"?(lang==="uz"?"Siz":"You"):opponent.name} · ${clock(claim.at)}`:(lang==="uz"?"yechilmadi":"unclaimed")}</span><span className="pts">{claim?(claim.by==="me"?"+":"−")+p.points:"0"}</span></div>})}</div>
  <div className="duel-stats"><div><b>{attempts.me}</b><small>{lang==="uz"?"sizning xato urinish":"your failed attempts"}</small></div><div><b>{attempts.opp}</b><small>{lang==="uz"?"raqib xato urinish":"rival failed attempts"}</small></div><div><b>{opponent.rating}</b><small>{lang==="uz"?"raqib reytingi":"rival rating"}</small></div></div>
  <div className="match-actions"><button className="primary" onClick={onRematch}>{lang==="uz"?"Yangi duel":"New duel"} →</button><button className="secondary" onClick={onExit}>{lang==="uz"?"Maydondan chiqish":"Leave arena"}</button></div></div></>
}

function DuelMatchmaking({lang,profile}:{lang:Lang,profile?:Profile|null}){
 const [phase,setPhase]=useState<"idle"|"searching"|"found"|"active">("idle"),[rating,setRating]=useState(1462),[opponent,setOpponent]=useState<DuelOpponent>(duelOpponents[0]),[matchId,setMatchId]=useState(4821);
 useEffect(()=>{if(profile?.duel_rating){setRating(profile.duel_rating);return}const saved=Number(localStorage.getItem("algoyol-duel-rating"));if(saved>0)setRating(saved)},[profile]);
 useEffect(()=>{if(phase!=="searching")return;const found=window.setTimeout(()=>{const pool=[...duelOpponents].sort((a,b)=>Math.abs(a.rating-rating)-Math.abs(b.rating-rating)).slice(0,3);setOpponent(pool[Math.floor(Math.random()*pool.length)]);setMatchId(4000+Math.floor(Math.random()*1800));setPhase("found")},1800);return()=>window.clearTimeout(found)},[phase,rating]);
 const settle=(next:number)=>{setRating(next);localStorage.setItem("algoyol-duel-rating",String(next));void saveDuelRating(next)};
 if(phase==="active")return <Duel key={matchId} lang={lang} opponent={opponent} rating={rating} matchId={matchId} onFinish={settle} onRematch={()=>setPhase("searching")} onExit={()=>setPhase("idle")}/>;
 const gap=Math.abs(opponent.rating-rating);
 return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>RATED MATCHMAKING</p><h1 className="page-title">{lang==="uz"?"Duel uchun raqib toping":"Find a duel opponent"}</h1><p className="muted">{lang==="uz"?"Tizim sizga reytingi yaqin bo‘lgan raqibni qidiradi.":"We will match you with a player near your rating."}</p></div><span className="tag">ELO {rating}</span></div>
 <div className="matchmaking panel"><div className={`search-orb ${phase==="searching"?"pulse":""}`}>{phase==="found"?"✓":"⚡"}</div>
  <h2>{phase==="idle"?(lang==="uz"?"Bellashishga tayyormisiz?":"Ready to compete?"):phase==="searching"?(lang==="uz"?"Raqib qidirilmoqda…":"Searching for an opponent…"):(lang==="uz"?"Raqib topildi!":"Opponent found!")}</h2>
  {phase==="found"?<><div className="found-player"><span className="avatar">{opponent.letter}</span><span><b>{opponent.name} · {opponent.handle}</b><br/><span className="muted">{opponent.rating} Elo · {opponent.wins} {lang==="uz"?"g‘alaba":"wins"}</span></span></div>
   <p className="muted">{lang==="uz"?`Reyting farqi: ${gap}. Duel 30 daqiqa davom etadi.`:`Rating difference: ${gap}. The duel lasts 30 minutes.`}</p>
   <div className="match-actions"><button className="primary" onClick={()=>setPhase("active")}>{lang==="uz"?"Duelni boshlash":"Start duel"} →</button><button className="secondary" onClick={()=>setPhase("idle")}>{lang==="uz"?"Bekor qilish":"Cancel"}</button></div></>
  :<><p className="muted">{phase==="searching"?(lang==="uz"?"Odatda 10 soniyadan kam vaqt oladi.":"This usually takes less than 10 seconds."):(lang==="uz"?"Easy, Medium va Hard masalalar ketma-ket ochiladi.":"Easy, Medium, and Hard problems unlock in order.")}</p>
   <button className={phase==="searching"?"secondary":"primary"} onClick={()=>setPhase(phase==="searching"?"idle":"searching")}>{phase==="searching"?(lang==="uz"?"Qidiruvni bekor qilish":"Cancel search"):(lang==="uz"?"Raqib qidirish":"Search for competitor")} {phase==="idle"&&"→"}</button></>}</div></>
}
function Leaderboard({lang}:{lang:Lang}){return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>ELO · K=32</p><h1 className="page-title">{lang==="uz"?"Duel reytingi":"Duel leaderboard"}</h1><p className="muted">{lang==="uz"?"Eng kuchli AlgoYo‘lchilar safi.":"The strongest competitors on AlgoYo‘l."}</p></div></div><div className="leaderboard">{leaders.map((x,i)=><div className={`leader-row ${x.n==="Siz"?"me":""}`} key={x.u}><span className="rank">#{i+1}</span><span><b>{lang==="en"&&x.n==="Siz"?"You":x.n}</b><br/><span className="muted">{x.u}</span></span><span className="tag">{x.w} W</span><span className="rating">{x.r}</span></div>)}</div></>}
function Profile({lang,go,profile,loading,signOut}:{lang:Lang,go:(v:View)=>void,profile:Profile|null,loading:boolean,signOut:()=>void}){
 const role:Role=profile?.role||"user",staff=role==="admin"||role==="owner";
 const name=profile?.display_name||profile?.username||"AlgoYo‘lchi",handle=profile?`@${profile.username}`:"@algoyolchi";
 const initials=name.trim().slice(0,2).toUpperCase()||"AY";
 return <><div className="page-head"><h1 className="page-title">{lang==="uz"?"Mening profilim":"My profile"}</h1><div className="actions">{staff&&<button className="secondary" onClick={()=>go("admin")}>{lang==="uz"?"Boshqaruv":"Admin studio"}</button>}<button className="lang" onClick={signOut}>{lang==="uz"?"Chiqish":"Sign out"}</button></div></div>
 {!supabaseReady()&&<div className="notice" style={{marginBottom:18}}>{lang==="uz"?"Supabase ulanmagan — profil va rollar demo rejimida ko‘rsatilmoqda. .env.local faylga NEXT_PUBLIC_SUPABASE_URL va NEXT_PUBLIC_SUPABASE_ANON_KEY ni yozing.":"Supabase is not connected — the profile and roles are shown in demo mode. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to .env.local."}</div>}
 {supabaseReady()&&!profile&&!loading&&<div className="notice" style={{marginBottom:18}}>{lang==="uz"?"Profil topilmadi. Supabase’ga kiring — profil birinchi kirishda avtomatik yaratiladi.":"No profile found. Sign in to Supabase — the profile is created automatically on first login."}</div>}
 <div className="profile-grid"><div className="panel profile-card"><div className="profile-avatar">{initials}</div><h2>{name}</h2><p className="muted">{handle}{profile?.email?` · ${profile.email}`:" · Toshkent"}</p><span className={`tag role-${role}`}>{loading?"…":roleLabel(role,lang)}</span>
  <div className="kpis"><div className="kpi"><b>{profile?.duel_rating??1462}</b>Elo</div><div className="kpi"><b>{profile?.solved_count??27}</b>AC</div><div className="kpi"><b>{staff?"∞":"12"}</b>{staff?(lang==="uz"?"Huquq":"Access"):"W"}</div></div>
  <p className="muted" style={{marginTop:18,fontSize:13}}>{role==="owner"?(lang==="uz"?"Owner barcha masalalar, roadmap va adminlarni boshqaradi.":"The owner manages every problem, roadmap, and admin."):role==="admin"?(lang==="uz"?"Admin faqat o‘zi yaratgan masalalarni tahrirlaydi.":"Admins edit only the problems they created."):(lang==="uz"?"Foydalanuvchi darslarni o‘qiydi, masalalar yechadi va duellarda qatnashadi.":"Users read lessons, solve problems, and enter duels.")}</p></div>
 <div className="panel"><h2>{lang==="uz"?"O‘rganish davomiyligi":"Learning progress"}</h2>{roads.slice(0,4).map(r=><div key={r.en} style={{margin:"22px 0"}}><div className="meta"><b>{lang==="uz"?r.uz:r.en}</b><span>{r.progress}%</span></div><div className="progress"><span style={{width:r.progress+"%"}}/></div></div>)}</div></div></>}
function Auth({lang,done}:{lang:Lang,done:(token?:string)=>void}){
 const [mode,setMode]=useState<"login"|"signup"|"confirm">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[username,setUsername]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const config=()=>({url:process.env.NEXT_PUBLIC_SUPABASE_URL,key:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY});
 const authenticate=async()=>{const {url,key}=config();if(!url||!key){setMessage(lang==="uz"?"Email tasdiqlash xizmati hali ulanmagan. Supabase sozlamalarini kiriting.":"Email confirmation is not configured yet. Add the Supabase settings.");return}if(!email||password.length<6||(mode==="signup"&&!username)){setMessage(lang==="uz"?"Barcha maydonlarni to‘ldiring. Parol kamida 6 belgi bo‘lsin.":"Complete every field. Password must be at least 6 characters.");return}setBusy(true);setMessage(lang==="uz"?"So‘rov yuborilmoqda…":"Sending request…");const redirect=`${window.location.origin}/`;const endpoint=mode==="signup"?`signup?redirect_to=${encodeURIComponent(redirect)}`:"token?grant_type=password";try{const response=await fetch(`${url}/auth/v1/${endpoint}`,{method:"POST",headers:{apikey:key,"content-type":"application/json"},body:JSON.stringify({email,password,...(mode==="signup"?{data:{username,display_name:username}}:{})})});const result=await response.json();if(!response.ok){const text=result.error_description||result.msg||result.message||"Authentication failed";setMessage(String(text).toLowerCase().includes("confirm")?(lang==="uz"?"Avval emailingizdagi tasdiqlash havolasini bosing.":"Confirm your email before signing in."):text);return}if(mode==="signup"){if(result.access_token){setMessage(lang==="uz"?"Supabase’da Confirm Email sozlamasini yoqing. Tasdiqlanmagan kirish bloklandi.":"Enable Confirm Email in Supabase. Unverified entry was blocked.");return}setMode("confirm");setMessage(lang==="uz"?`Tasdiqlash xabari ${email} manziliga yuborildi.`:`A confirmation message was sent to ${email}.`);return}if(!result.user?.email_confirmed_at){setMode("confirm");setMessage(lang==="uz"?"Avval emailingizni tasdiqlang.":"Confirm your email before signing in.");return}sessionStorage.setItem("algoyol-access-token",result.access_token);done(result.access_token)}catch{setMessage(lang==="uz"?"Email xizmatiga ulanib bo‘lmadi.":"Could not connect to the email service.")}finally{setBusy(false)}};
 const resend=async()=>{const {url,key}=config();if(!url||!key)return;setBusy(true);const redirect=`${window.location.origin}/`;try{const response=await fetch(`${url}/auth/v1/resend?redirect_to=${encodeURIComponent(redirect)}`,{method:"POST",headers:{apikey:key,"content-type":"application/json"},body:JSON.stringify({type:"signup",email})});const result=await response.json();setMessage(response.ok?(lang==="uz"?"Tasdiqlash xabari qayta yuborildi.":"Confirmation email sent again."):(result.msg||result.message||"Could not resend"))}finally{setBusy(false)}};
 return <div className="auth"><div className="brand"><span className="brandmark">A›</span>AlgoYo‘l</div><h1>{mode==="login"?(lang==="uz"?"Xush kelibsiz":"Welcome back"):mode==="signup"?(lang==="uz"?"Hisob yarating":"Create account"):(lang==="uz"?"Emailingizni tekshiring":"Check your email")}</h1><p className="muted">{mode==="confirm"?(lang==="uz"?"Xabardagi yashil tasdiqlash tugmasini bosing. Shundan keyin AlgoYo‘l avtomatik ochiladi.":"Click the confirmation button in the email. AlgoYo‘l will open automatically afterward."):(lang==="uz"?"Tasdiqlangan hisob bilan natijalaringizni saqlang va duellarda qatnashing.":"Use a verified account to save progress and enter rated duels.")}</p>{message&&<div className="notice">{message}</div>}{mode==="signup"&&<div className="field"><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="algoyolchi"/></div>}{mode!=="confirm"&&<><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="siz@example.com"/></div><div className="field"><label>{lang==="uz"?"Parol":"Password"}</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} placeholder="••••••••"/></div><button disabled={busy} className="primary" style={{width:"100%"}} onClick={authenticate}>{busy?(lang==="uz"?"Kuting…":"Please wait…"):mode==="login"?(lang==="uz"?"Kirish":"Sign in"):(lang==="uz"?"Ro‘yxatdan o‘tish":"Create account")}</button></>}{mode==="confirm"&&<><button disabled={busy} className="primary" style={{width:"100%"}} onClick={resend}>{lang==="uz"?"Xabarni qayta yuborish":"Resend confirmation"}</button><button className="lang" style={{width:"100%",marginTop:10}} onClick={()=>setMode("login")}>{lang==="uz"?"Kirish sahifasiga qaytish":"Back to sign in"}</button></>}{mode!=="confirm"&&<button className="lang" style={{width:"100%",marginTop:10}} onClick={()=>{setMessage("");setMode(mode==="login"?"signup":"login")}}>{mode==="login"?(lang==="uz"?"Yangi hisob yaratish":"Create a new account"):(lang==="uz"?"Hisobim bor":"I already have an account")}</button>}</div>
}
function Admin({lang,profile}:{lang:Lang,profile:Profile|null}){
 const role:Role=profile?.role||"user";
 if(role!=="admin"&&role!=="owner")return <><div className="page-head"><div><span className="tag">ADMIN STUDIO</span><h1 className="page-title" style={{marginTop:12}}>{lang==="uz"?"Ruxsat yo‘q":"Access denied"}</h1></div></div><div className="panel"><div className="notice">{lang==="uz"?"Bu sahifa faqat admin va owner rollari uchun. Supabase’da profilingiz roli hozir: ":"This page is for the admin and owner roles only. Your Supabase profile role is currently: "}<b>{roleLabel(role,lang)}</b>.</div></div></>;
 return <><div className="page-head"><div><span className="tag">ADMIN STUDIO · {roleLabel(role,lang)}</span><h1 className="page-title" style={{marginTop:12}}>{lang==="uz"?"Yangi masala":"New problem"}</h1></div><button className="primary">{lang==="uz"?"Qoralamani saqlash":"Save draft"}</button></div><div className="panel"><div className="admin-grid"><div className="field"><label>O‘zbekcha nomi</label><input placeholder="Masala nomi"/></div><div className="field"><label>English title</label><input placeholder="Problem title"/></div><div className="field"><label>{lang==="uz"?"Qiyinlik":"Difficulty"}</label><select><option>Easy · 100</option><option>Medium · 200</option><option>Hard · 300</option></select></div><div className="field"><label>Taglar</label><input placeholder="binary-search, arrays"/></div></div><div className="admin-grid"><div className="field"><label>O‘zbekcha shart</label><textarea rows={9} placeholder="Masala shartini yozing…"/></div><div className="field"><label>English statement</label><textarea rows={9} placeholder="Write the problem statement…"/></div></div><div className="admin-grid"><div className="field"><label>{lang==="uz"?"Vaqt chegarasi":"Time limit"}</label><input value="1000 ms" readOnly/></div><div className="field"><label>{lang==="uz"?"Xotira chegarasi":"Memory limit"}</label><input value="256 MB" readOnly/></div></div><div className="field"><label>{lang==="uz"?"Yashirin testlar":"Hidden tests"}</label><textarea rows={5} placeholder="Input → Expected output"/></div><div className="notice">{lang==="uz"?"Admin faqat o‘zi yaratgan masalalarni tahrirlaydi. Owner barcha masalalarni boshqaradi.":"Admins edit only their own problems. The owner can manage all content."}</div></div></>}
