"use client";

import { useEffect, useMemo, useState } from "react";

type Lang="uz"|"en"; type View="home"|"roadmaps"|"problems"|"problem"|"duel"|"leaderboard"|"profile"|"auth"|"admin";
const copy={uz:{home:"Bosh sahifa",roadmaps:"Yo‘l xaritalari",problems:"Masalalar",duel:"Duel",leaderboard:"Reyting",login:"Kirish",hero:"Algoritmlarni o‘rganing, bellashing va o‘sing.",sub:"Tushunarli o‘zbekcha darslar, haqiqiy kod tekshiruvchi va 30 daqiqalik jonli duellar — barchasi bitta maydonda.",start:"O‘rganishni boshlash",arena:"Duel maydoni",featured:"Mashhur yo‘l xaritalari",all:"Barchasini ko‘rish",tasks:"Masalalar banki",solve:"Yechish",submit:"Yechimni yuborish"},en:{home:"Home",roadmaps:"Roadmaps",problems:"Problems",duel:"Duel",leaderboard:"Leaderboard",login:"Sign in",hero:"Learn algorithms, compete, and grow.",sub:"Clear lessons, a real code checker, and live 30-minute duels — all in one focused arena.",start:"Start learning",arena:"Enter duel arena",featured:"Featured roadmaps",all:"View all",tasks:"Problem library",solve:"Solve",submit:"Submit solution"}};
const roads=[
 {icon:"O(n)",color:"#dfff74",uz:"Murakkablik tahlili",en:"Complexity analysis",descUz:"Tezlik va xotira chegaralarini tushuning.",descEn:"Understand time and memory limits.",units:8,progress:75},
 {icon:"↕",color:"#ffd4bd",uz:"Saralash",en:"Sorting",descUz:"Oddiy usullardan tezkor saralashgacha.",descEn:"From simple methods to quick sort.",units:10,progress:40},
 {icon:"⌕",color:"#dbe2ff",uz:"Ikkilik qidiruv",en:"Binary search",descUz:"Javob bo‘yicha qidirish sirlarini oching.",descEn:"Master searching over the answer.",units:7,progress:20},
 {icon:"◆",color:"#ffe8a3",uz:"Ochko‘z algoritmlar",en:"Greedy algorithms",descUz:"Mahalliy tanlovdan optimal yechimgacha.",descEn:"Turn local choices into optimal solutions.",units:9,progress:0},
 {icon:"⌘",color:"#c9f0de",uz:"Graflar",en:"Graphs",descUz:"BFS, DFS va eng qisqa yo‘llar.",descEn:"BFS, DFS, and shortest paths.",units:14,progress:0},
 {icon:"∑",color:"#ead8ff",uz:"Dinamik dasturlash",en:"Dynamic programming",descUz:"Holatlar, o‘tishlar va optimallashtirish.",descEn:"States, transitions, and optimization.",units:16,progress:0},
];
const problems=[
 {id:"A01",uz:"Ikki son yig‘indisi",en:"Sum of two numbers",difficulty:"easy",tag:"Boshlang‘ich",points:100},
 {id:"A02",uz:"Eng katta element",en:"Maximum element",difficulty:"easy",tag:"Massiv",points:100},
 {id:"A03",uz:"Juftlar soni",en:"Count the evens",difficulty:"easy",tag:"Massiv",points:100},
 {id:"B01",uz:"Yashirin son",en:"Hidden number",difficulty:"medium",tag:"Binary search",points:200},
 {id:"B02",uz:"Bekatlar",en:"Bus stops",difficulty:"medium",tag:"Greedy",points:200},
 {id:"B03",uz:"Labirint yo‘li",en:"Maze path",difficulty:"medium",tag:"BFS",points:200},
 {id:"C01",uz:"Qadimiy daraxt",en:"Ancient tree",difficulty:"hard",tag:"Graph",points:300},
 {id:"C02",uz:"Tanga strategiyasi",en:"Coin strategy",difficulty:"hard",tag:"DP",points:300},
 {id:"C03",uz:"Eng uzun yo‘l",en:"Longest route",difficulty:"hard",tag:"DAG",points:300},
];
const leaders=[{n:"Sardor",u:"@sardor_ioi",r:1864,w:42},{n:"Madina",u:"@madina_dev",r:1792,w:37},{n:"Azizbek",u:"@aziz_algo",r:1718,w:29},{n:"Siz",u:"@algoyolchi",r:1462,w:12},{n:"Nilufar",u:"@nilufar_py",r:1421,w:18}];
const cpp=`#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    long long a, b;\n    cin >> a >> b;\n    cout << a + b << "\\n";\n    return 0;\n}`;

export function AlgoYolApp(){
 const [lang,setLang]=useState<Lang>("uz"),[view,setView]=useState<View>("home"),[filter,setFilter]=useState("all"),[code,setCode]=useState(cpp),[codeLang,setCodeLang]=useState<"cpp20"|"python3">("cpp20"),[verdict,setVerdict]=useState(""),[signed,setSigned]=useState(false); const t=copy[lang];
 useEffect(()=>{const saved=localStorage.getItem("algoyol-lang") as Lang|null;if(saved)setLang(saved)},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.hash.replace(/^#/,""));const token=params.get("access_token"),error=params.get("error_description");if(token){sessionStorage.setItem("algoyol-access-token",token);setSigned(true);setView("profile");window.history.replaceState({},"",window.location.pathname)}else if(error){setView("auth");window.history.replaceState({},"",window.location.pathname);window.setTimeout(()=>window.alert(decodeURIComponent(error.replace(/\+/g," "))),50)}},[]);
 const go=(v:View)=>{setView(v);window.scrollTo({top:0,behavior:"smooth"})}; const swap=()=>{const n=lang==="uz"?"en":"uz";setLang(n);localStorage.setItem("algoyol-lang",n)};
 const filtered=useMemo(()=>filter==="all"?problems:problems.filter(p=>p.difficulty===filter),[filter]);
 const judge=async()=>{setVerdict(lang==="uz"?"Navbatda… testlar tekshirilmoqda":"In queue… running hidden tests");try{const response=await fetch("/api/judge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({problemId:"sum-two",language:codeLang,sourceCode:code})});const r=await response.json();const names:Record<string,[string,string]>={ACCEPTED:["Qabul qilindi","Accepted"],WRONG_ANSWER:["Noto‘g‘ri javob","Wrong answer"],COMPILATION_ERROR:["Kompilyatsiya xatosi","Compilation error"],RUNTIME_ERROR:["Bajarilish xatosi","Runtime error"],TIME_LIMIT_EXCEEDED:["Vaqt chegarasi oshdi","Time limit exceeded"],MEMORY_LIMIT_EXCEEDED:["Xotira chegarasi oshdi","Memory limit exceeded"],JUDGE_ERROR:["Tekshiruvchi xatosi","Judge error"]};const title=(names[r.verdict]||names.JUDGE_ERROR)[lang==="uz"?0:1];const test=r.test?` · ${lang==="uz"?"test":"test"} #${r.test}`:"";const stats=r.verdict==="ACCEPTED"?` · ${r.passed}/${r.total} · ${r.runtimeMs} ms · ${r.memoryKb} KB`:"";setVerdict(`${title}${test}${stats}${r.details?`\n${String(r.details).slice(0,900)}`:""}`)}catch{setVerdict(lang==="uz"?"Tekshiruvchi bilan aloqa uzildi":"Judge connection failed")}};
 return <div className="shell"><header className="topbar"><button className="brand" onClick={()=>go("home")} style={{border:0,background:"transparent"}}><span className="brandmark">A›</span>AlgoYo‘l</button><nav className="nav">{(["home","roadmaps","problems","duel","leaderboard"] as View[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>go(v)}>{t[v as keyof typeof t]}</button>)}</nav><div className="actions"><button className="lang" onClick={swap}>{lang==="uz"?"EN":"UZ"}</button><button className="pill" onClick={()=>go(signed?"profile":"auth")}>{signed?(lang==="uz"?"Profil":"Profile"):t.login}</button><button className="primary" onClick={()=>go("duel")}>{lang==="uz"?"Duel topish":"Find duel"}</button></div></header>
 <main className="main">{view==="home"&&<Home lang={lang} go={go}/>} {view==="roadmaps"&&<Roadmaps lang={lang} go={go}/>} {view==="problems"&&<Problems lang={lang} filter={filter} setFilter={setFilter} items={filtered} go={go}/>} {view==="problem"&&<Problem lang={lang} code={code} setCode={setCode} codeLang={codeLang} setCodeLang={setCodeLang} verdict={verdict} submit={judge}/>} {view==="duel"&&<DuelMatchmaking lang={lang}/>} {view==="leaderboard"&&<Leaderboard lang={lang}/>} {view==="profile"&&<Profile lang={lang} go={go}/>} {view==="auth"&&<Auth lang={lang} done={()=>{setSigned(true);go("profile")}}/>} {view==="admin"&&<Admin lang={lang}/>}</main>
 <nav className="mobile-nav">{(["home","roadmaps","problems","duel","leaderboard"] as View[]).map(v=><button key={v} className={view===v?"active":""} onClick={()=>go(v)}>{t[v as keyof typeof t]}</button>)}</nav><footer className="footer"><span>© 2026 AlgoYo‘l · Toshkent</span><span>{lang==="uz"?"Bilimdan natijagacha.":"From learning to results."}</span></footer></div>
}
function Home({lang,go}:{lang:Lang,go:(v:View)=>void}){const t=copy[lang];return <><section className="hero"><div className="hero-copy"><div className="eyebrow">{lang==="uz"?"O‘zbekiston dasturchilari uchun":"Built for Uzbekistan’s coders"}</div><h1>{lang==="uz"?<>Algoritmlarni <em>o‘rganing</em>, bellashing va o‘sing.</>:<>Learn algorithms, <em>compete</em>, and grow.</>}</h1><p>{t.sub}</p><div className="hero-cta"><button className="primary" onClick={()=>go("roadmaps")}>{t.start} →</button><button className="secondary" onClick={()=>go("duel")}>{t.arena}</button></div><div className="orbit"/></div><div className="hero-side"><div className="stat-card"><span className="eyebrow" style={{color:"#637068"}}>{lang==="uz"?"Bugun faol":"Active today"}</span><span className="big">1,284</span><div className="mini-row"><span className="avatar">S</span><span className="avatar">M</span><span className="avatar">A</span><span className="avatar">+9</span></div></div><div className="stat-card duel"><span className="eyebrow" style={{color:"#6f3516"}}>{lang==="uz"?"Jonli duellar":"Live duels"}</span><span className="big">24</span><span>{lang==="uz"?"Hozir bellashmoqda":"competing right now"} ⚡</span></div></div></section><section><div className="section-head"><div><p className="eyebrow" style={{color:"#637068"}}>{lang==="uz"?"Bosqichma-bosqich":"Step by step"}</p><h2>{t.featured}</h2></div><button className="secondary" onClick={()=>go("roadmaps")}>{t.all} →</button></div><RoadGrid lang={lang} roads={roads.slice(0,3)} go={go}/></section><section><div className="section-head"><div><p className="eyebrow" style={{color:"#637068"}}>100 · 200 · 300</p><h2>{t.tasks}</h2></div><button className="secondary" onClick={()=>go("problems")}>{t.all} →</button></div><ProblemList lang={lang} items={problems.slice(0,4)} go={go}/></section></>}
function RoadGrid({lang,roads,go}:{lang:Lang,roads:typeof roads,go:(v:View)=>void}){return <div className="grid">{roads.map((r,i)=><button className="road-card" style={{textAlign:"left"}} key={r.en} onClick={()=>go("problems")}><span className="road-icon" style={{background:r.color}}>{r.icon}</span><h3>{lang==="uz"?r.uz:r.en}</h3><p className="muted">{lang==="uz"?r.descUz:r.descEn}</p><div className="progress"><span style={{width:r.progress+"%"}}/></div><div className="meta"><span>{r.units} {lang==="uz"?"dars":"lessons"}</span><span>{r.progress}%</span></div></button>)}</div>}
function Roadmaps({lang,go}:{lang:Lang,go:(v:View)=>void}){return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>0 → 2000</p><h1 className="page-title">{lang==="uz"?"Sizning o‘sish yo‘lingiz":"Your path to growth"}</h1><p className="muted">{lang==="uz"?"Har bir mavzu — tushuncha, namuna va saralangan mashqlar.":"Every topic combines concepts, examples, and curated practice."}</p></div><span className="tag">6 {lang==="uz"?"yo‘nalish":"tracks"}</span></div><RoadGrid lang={lang} roads={roads} go={go}/></>}
function ProblemList({lang,items,go}:{lang:Lang,items:typeof problems,go:(v:View)=>void}){return <div className="problem-list">{items.map(p=><button className="problem-row" style={{textAlign:"left"}} key={p.id} onClick={()=>go("problem")}><span className="num">{p.id}</span><span><h3>{lang==="uz"?p.uz:p.en}</h3><span className={`difficulty ${p.difficulty}`}>{p.difficulty.toUpperCase()} · {p.points}</span></span><span className="tag">{p.tag}</span><span>→</span></button>)}</div>}
function Problems({lang,filter,setFilter,items,go}:{lang:Lang,filter:string,setFilter:(x:string)=>void,items:typeof problems,go:(v:View)=>void}){return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>{lang==="uz"?"Mashq maydoni":"Practice arena"}</p><h1 className="page-title">{lang==="uz"?"Masalalar banki":"Problem library"}</h1><p className="muted">{lang==="uz"?"Osondan murakkabgacha — har kuni bir qadam.":"From easy to hard — one step every day."}</p></div><button className="secondary">{lang==="uz"?"Tasodifiy masala":"Random problem"}</button></div><div className="filters">{["all","easy","medium","hard"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f==="all"?(lang==="uz"?"Barchasi":"All"):f}</button>)}</div><ProblemList lang={lang} items={items} go={go}/></>}
function Problem({lang,code,setCode,codeLang,setCodeLang,verdict,submit}:{lang:Lang,code:string,setCode:(x:string)=>void,codeLang:"cpp20"|"python3",setCodeLang:(x:"cpp20"|"python3")=>void,verdict:string,submit:()=>void}){return <><div className="page-head"><div><span className="tag">A01 · EASY · 100</span><h1 className="page-title" style={{marginTop:12}}>{lang==="uz"?"Ikki son yig‘indisi":"Sum of two numbers"}</h1></div><span className="muted">1 s · 256 MB</span></div><div className="workspace"><article className="panel statement"><h2>{lang==="uz"?"Shart":"Statement"}</h2><p>{lang==="uz"?"Sizga ikkita butun a va b sonlari beriladi. Ularning yig‘indisini toping.":"You are given two integers a and b. Print their sum."}</p><h3>{lang==="uz"?"Kirish":"Input"}</h3><p>{lang==="uz"?"Bitta qatorda ikkita butun son: a va b (−10⁹ ≤ a, b ≤ 10⁹).":"One line contains two integers a and b (−10⁹ ≤ a, b ≤ 10⁹)."}</p><h3>{lang==="uz"?"Chiqish":"Output"}</h3><p>{lang==="uz"?"Yagona son — a + b ni chiqaring.":"Print a single integer — a + b."}</p><h3>{lang==="uz"?"Namuna":"Sample"}</h3><div className="sample">Input\n12 30\n\nOutput\n42</div></article><section className="editor"><div className="editor-top"><b>{codeLang==="cpp20"?"main.cpp":"main.py"}</b><select aria-label="Language" value={codeLang} onChange={e=>{const value=e.target.value as "cpp20"|"python3";setCodeLang(value);setCode(value==="cpp20"?cpp:"a, b = map(int, input().split())\nprint(a + b)")}}><option value="cpp20">C++20</option><option value="python3">Python 3</option></select></div><textarea aria-label="Code editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/><div className="editor-actions"><span className="verdict">{verdict||"● Judge0 online"}</span><button className="primary" onClick={submit}>{copy[lang].submit} →</button></div></section></div></>}
function Duel({lang,seconds}:{lang:Lang,seconds:number}){const min=String(Math.floor(seconds/60)).padStart(2,"0"),sec=String(seconds%60).padStart(2,"0");return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>RATED DUEL · #4821</p><h1 className="page-title">{lang==="uz"?"Duel maydoni":"Duel arena"}</h1></div><span className="tag">{lang==="uz"?"Ulangan":"Connected"} ●</span></div><div className="duel-layout"><section className="arena"><div className="duel-top"><b>{lang==="uz"?"30 daqiqalik duel":"30-minute duel"}</b><span className="timer">{min}:{sec}</span></div><div className="players"><div className="player"><span className="muted">@algoyolchi · 1462</span><div>Siz</div><span className="score">0</span></div><span className="versus">VS</span><div className="player"><span className="muted">@jasur_cpp · 1488</span><div>Jasur</div><span className="score">0</span></div></div><div className="duel-steps"><div className="step open"><b>01 · EASY</b><br/>100 {lang==="uz"?"ball":"points"}</div><div className="step locked"><b>02 · MEDIUM</b><br/>200 {lang==="uz"?"ball":"points"}</div><div className="step locked"><b>03 · HARD</b><br/>300 {lang==="uz"?"ball":"points"}</div></div><div style={{marginTop:20}} className="panel"><span className="tag">A01</span><h2>{lang==="uz"?"Ikki son yig‘indisi":"Sum of two numbers"}</h2><p className="muted">{lang==="uz"?"Birinchi bo‘lib qabul qilingan yechim 100 ball oladi.":"The first accepted solution claims 100 points."}</p><button className="primary">{lang==="uz"?"Yechishni boshlash":"Start solving"} →</button></div></section><aside className="side-stack"><div className="duel-card"><h3>{lang==="uz"?"Duel holati":"Duel status"}</h3><div className="status-line">● {lang==="uz"?"Jasur kod yozmoqda":"Jasur is coding"}</div><div className="status-line">● {lang==="uz"?"1-masala ochildi":"Problem 1 unlocked"}</div><div className="status-line muted">{lang==="uz"?"Duel boshlandi":"Duel started"} · 00:00</div></div><div className="duel-card"><h3>{lang==="uz"?"Qoidalar":"Rules"}</h3><p className="muted">{lang==="uz"?"Masalalar ketma-ket ochiladi. Birinchi AC barcha ballni oladi.":"Problems unlock in order. The first AC claims all points."}</p></div></aside></div></>}
function DuelMatchmaking({lang}:{lang:Lang}){const [phase,setPhase]=useState<"idle"|"searching"|"found"|"active">("idle"),[seconds,setSeconds]=useState(1800);useEffect(()=>{if(phase==="searching"){const found=setTimeout(()=>setPhase("found"),1800);return()=>clearTimeout(found)}if(phase==="active"){const timer=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(timer)}},[phase]);if(phase==="active")return <Duel lang={lang} seconds={seconds}/>;return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>RATED MATCHMAKING</p><h1 className="page-title">{lang==="uz"?"Duel uchun raqib toping":"Find a duel opponent"}</h1><p className="muted">{lang==="uz"?"Tizim sizga reytingi yaqin bo‘lgan raqibni qidiradi.":"We will match you with a player near your rating."}</p></div><span className="tag">ELO 1462</span></div><div className="matchmaking panel"><div className={`search-orb ${phase==="searching"?"pulse":""}`}>{phase==="found"?"✓":"⚡"}</div><h2>{phase==="idle"?(lang==="uz"?"Bellashishga tayyormisiz?":"Ready to compete?"):phase==="searching"?(lang==="uz"?"Raqib qidirilmoqda…":"Searching for an opponent…"):(lang==="uz"?"Raqib topildi!":"Opponent found!")}</h2>{phase==="found"?<><div className="found-player"><span className="avatar">J</span><span><b>Jasur · @jasur_cpp</b><br/><span className="muted">1488 Elo · 18 {lang==="uz"?"g‘alaba":"wins"}</span></span></div><p className="muted">{lang==="uz"?"Reyting farqi: 26. Duel 30 daqiqa davom etadi.":"Rating difference: 26. The duel lasts 30 minutes."}</p><div className="match-actions"><button className="primary" onClick={()=>setPhase("active")}>{lang==="uz"?"Duelni boshlash":"Start duel"} →</button><button className="secondary" onClick={()=>setPhase("idle")}>{lang==="uz"?"Bekor qilish":"Cancel"}</button></div></>:<><p className="muted">{phase==="searching"?(lang==="uz"?"Odatda 10 soniyadan kam vaqt oladi.":"This usually takes less than 10 seconds."):(lang==="uz"?"Easy, Medium va Hard masalalar ketma-ket ochiladi.":"Easy, Medium, and Hard problems unlock in order.")}</p><button className={phase==="searching"?"secondary":"primary"} onClick={()=>setPhase(phase==="searching"?"idle":"searching")}>{phase==="searching"?(lang==="uz"?"Qidiruvni bekor qilish":"Cancel search"):(lang==="uz"?"Raqib qidirish":"Search for competitor")} {phase==="idle"&&"→"}</button></>}</div></>}
function Leaderboard({lang}:{lang:Lang}){return <><div className="page-head"><div><p className="eyebrow" style={{color:"#637068"}}>ELO · K=32</p><h1 className="page-title">{lang==="uz"?"Duel reytingi":"Duel leaderboard"}</h1><p className="muted">{lang==="uz"?"Eng kuchli AlgoYo‘lchilar safi.":"The strongest competitors on AlgoYo‘l."}</p></div></div><div className="leaderboard">{leaders.map((x,i)=><div className={`leader-row ${x.n==="Siz"?"me":""}`} key={x.u}><span className="rank">#{i+1}</span><span><b>{lang==="en"&&x.n==="Siz"?"You":x.n}</b><br/><span className="muted">{x.u}</span></span><span className="tag">{x.w} W</span><span className="rating">{x.r}</span></div>)}</div></>}
function Profile({lang,go}:{lang:Lang,go:(v:View)=>void}){return <><div className="page-head"><h1 className="page-title">{lang==="uz"?"Mening profilim":"My profile"}</h1><button className="secondary" onClick={()=>go("admin")}>{lang==="uz"?"Boshqaruv":"Admin studio"}</button></div><div className="profile-grid"><div className="panel profile-card"><div className="profile-avatar">AY</div><h2>AlgoYo‘lchi</h2><p className="muted">@algoyolchi · Toshkent</p><span className="tag">USER</span><div className="kpis"><div className="kpi"><b>1462</b>Elo</div><div className="kpi"><b>27</b>AC</div><div className="kpi"><b>12</b>W</div></div></div><div className="panel"><h2>{lang==="uz"?"O‘rganish davomiyligi":"Learning progress"}</h2>{roads.slice(0,4).map(r=><div key={r.en} style={{margin:"22px 0"}}><div className="meta"><b>{lang==="uz"?r.uz:r.en}</b><span>{r.progress}%</span></div><div className="progress"><span style={{width:r.progress+"%"}}/></div></div>)}</div></div></>}
function Auth({lang,done}:{lang:Lang,done:()=>void}){
 const [mode,setMode]=useState<"login"|"signup"|"confirm">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[username,setUsername]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const config=()=>({url:process.env.NEXT_PUBLIC_SUPABASE_URL,key:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY});
 const authenticate=async()=>{const {url,key}=config();if(!url||!key){setMessage(lang==="uz"?"Email tasdiqlash xizmati hali ulanmagan. Supabase sozlamalarini kiriting.":"Email confirmation is not configured yet. Add the Supabase settings.");return}if(!email||password.length<6||(mode==="signup"&&!username)){setMessage(lang==="uz"?"Barcha maydonlarni to‘ldiring. Parol kamida 6 belgi bo‘lsin.":"Complete every field. Password must be at least 6 characters.");return}setBusy(true);setMessage(lang==="uz"?"So‘rov yuborilmoqda…":"Sending request…");const redirect=`${window.location.origin}/`;const endpoint=mode==="signup"?`signup?redirect_to=${encodeURIComponent(redirect)}`:"token?grant_type=password";try{const response=await fetch(`${url}/auth/v1/${endpoint}`,{method:"POST",headers:{apikey:key,"content-type":"application/json"},body:JSON.stringify({email,password,...(mode==="signup"?{data:{username,display_name:username}}:{})})});const result=await response.json();if(!response.ok){const text=result.error_description||result.msg||result.message||"Authentication failed";setMessage(String(text).toLowerCase().includes("confirm")?(lang==="uz"?"Avval emailingizdagi tasdiqlash havolasini bosing.":"Confirm your email before signing in."):text);return}if(mode==="signup"){if(result.access_token){setMessage(lang==="uz"?"Supabase’da Confirm Email sozlamasini yoqing. Tasdiqlanmagan kirish bloklandi.":"Enable Confirm Email in Supabase. Unverified entry was blocked.");return}setMode("confirm");setMessage(lang==="uz"?`Tasdiqlash xabari ${email} manziliga yuborildi.`:`A confirmation message was sent to ${email}.`);return}if(!result.user?.email_confirmed_at){setMode("confirm");setMessage(lang==="uz"?"Avval emailingizni tasdiqlang.":"Confirm your email before signing in.");return}sessionStorage.setItem("algoyol-access-token",result.access_token);done()}catch{setMessage(lang==="uz"?"Email xizmatiga ulanib bo‘lmadi.":"Could not connect to the email service.")}finally{setBusy(false)}};
 const resend=async()=>{const {url,key}=config();if(!url||!key)return;setBusy(true);const redirect=`${window.location.origin}/`;try{const response=await fetch(`${url}/auth/v1/resend?redirect_to=${encodeURIComponent(redirect)}`,{method:"POST",headers:{apikey:key,"content-type":"application/json"},body:JSON.stringify({type:"signup",email})});const result=await response.json();setMessage(response.ok?(lang==="uz"?"Tasdiqlash xabari qayta yuborildi.":"Confirmation email sent again."):(result.msg||result.message||"Could not resend"))}finally{setBusy(false)}};
 return <div className="auth"><div className="brand"><span className="brandmark">A›</span>AlgoYo‘l</div><h1>{mode==="login"?(lang==="uz"?"Xush kelibsiz":"Welcome back"):mode==="signup"?(lang==="uz"?"Hisob yarating":"Create account"):(lang==="uz"?"Emailingizni tekshiring":"Check your email")}</h1><p className="muted">{mode==="confirm"?(lang==="uz"?"Xabardagi yashil tasdiqlash tugmasini bosing. Shundan keyin AlgoYo‘l avtomatik ochiladi.":"Click the confirmation button in the email. AlgoYo‘l will open automatically afterward."):(lang==="uz"?"Tasdiqlangan hisob bilan natijalaringizni saqlang va duellarda qatnashing.":"Use a verified account to save progress and enter rated duels.")}</p>{message&&<div className="notice">{message}</div>}{mode==="signup"&&<div className="field"><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="algoyolchi"/></div>}{mode!=="confirm"&&<><div className="field"><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="siz@example.com"/></div><div className="field"><label>{lang==="uz"?"Parol":"Password"}</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} placeholder="••••••••"/></div><button disabled={busy} className="primary" style={{width:"100%"}} onClick={authenticate}>{busy?(lang==="uz"?"Kuting…":"Please wait…"):mode==="login"?(lang==="uz"?"Kirish":"Sign in"):(lang==="uz"?"Ro‘yxatdan o‘tish":"Create account")}</button></>}{mode==="confirm"&&<><button disabled={busy} className="primary" style={{width:"100%"}} onClick={resend}>{lang==="uz"?"Xabarni qayta yuborish":"Resend confirmation"}</button><button className="lang" style={{width:"100%",marginTop:10}} onClick={()=>setMode("login")}>{lang==="uz"?"Kirish sahifasiga qaytish":"Back to sign in"}</button></>}{mode!=="confirm"&&<button className="lang" style={{width:"100%",marginTop:10}} onClick={()=>{setMessage("");setMode(mode==="login"?"signup":"login")}}>{mode==="login"?(lang==="uz"?"Yangi hisob yaratish":"Create a new account"):(lang==="uz"?"Hisobim bor":"I already have an account")}</button>}</div>
}
function Admin({lang}:{lang:Lang}){return <><div className="page-head"><div><span className="tag">ADMIN STUDIO</span><h1 className="page-title" style={{marginTop:12}}>{lang==="uz"?"Yangi masala":"New problem"}</h1></div><button className="primary">{lang==="uz"?"Qoralamani saqlash":"Save draft"}</button></div><div className="panel"><div className="admin-grid"><div className="field"><label>O‘zbekcha nomi</label><input placeholder="Masala nomi"/></div><div className="field"><label>English title</label><input placeholder="Problem title"/></div><div className="field"><label>{lang==="uz"?"Qiyinlik":"Difficulty"}</label><select><option>Easy · 100</option><option>Medium · 200</option><option>Hard · 300</option></select></div><div className="field"><label>Taglar</label><input placeholder="binary-search, arrays"/></div></div><div className="admin-grid"><div className="field"><label>O‘zbekcha shart</label><textarea rows={9} placeholder="Masala shartini yozing…"/></div><div className="field"><label>English statement</label><textarea rows={9} placeholder="Write the problem statement…"/></div></div><div className="admin-grid"><div className="field"><label>{lang==="uz"?"Vaqt chegarasi":"Time limit"}</label><input value="1000 ms" readOnly/></div><div className="field"><label>{lang==="uz"?"Xotira chegarasi":"Memory limit"}</label><input value="256 MB" readOnly/></div></div><div className="field"><label>{lang==="uz"?"Yashirin testlar":"Hidden tests"}</label><textarea rows={5} placeholder="Input → Expected output"/></div><div className="notice">{lang==="uz"?"Admin faqat o‘zi yaratgan masalalarni tahrirlaydi. Owner barcha masalalarni boshqaradi.":"Admins edit only their own problems. The owner can manage all content."}</div></div></>}
