/* Level-check questions: the middle of the roadmap.
 * See placement-bank.ts for what makes a question good enough to be here. */

import type { PlacementQuestion } from "./placement-bank";

export const coreQuestions: PlacementQuestion[] = [
  /* =================================================== data-structures (1000 → 2100) */
  {
    id: "pb-ds-b1", track: "data-structures", tier: "basic", rating: 1000,
    uz: "`([]{})` kabi qavslar ketma-ketligi to‘g‘ri yopilganini tekshirish uchun qaysi tuzilma kerak?",
    en: "Which structure checks that a bracket sequence like `([]{})` is properly closed?",
    choicesUz: ["Stack", "Queue", "Set", "Priority queue"],
    correct: 0,
    whyUz: "Eng oxirgi ochilgan qavs birinchi yopilishi kerak — bu aynan LIFO. Ochiluvchini stekka qo‘yasiz, yopiluvchida tepadagisi mos kelishini tekshirib olib tashlaysiz. Oxirida stek bo‘sh bo‘lishi shart.",
    whyEn: "The most recently opened bracket must close first — that is LIFO. Push each opener; on a closer, check the top matches and pop it. The stack must be empty at the end.",
  },
  {
    id: "pb-ds-b2", track: "data-structures", tier: "basic", rating: 1050,
    uz: "Bu kod nima chiqaradi?",
    en: "What does this print?",
    code: "priority_queue<int> pq;\npq.push(3); pq.push(1); pq.push(5);\ncout << pq.top();",
    choicesUz: ["1", "3", "5", "Tartib aniqlanmagan"],
    choicesEn: ["1", "3", "5", "The order is undefined"],
    correct: 2,
    whyUz: "C++ dagi `priority_queue` sukut bo‘yicha max-heap — tepada eng katta element. Eng kichigi kerak bo‘lsa: `priority_queue<int, vector<int>, greater<int>>` yoki sonlarni manfiy qilib solish. Dijkstra da bu xato juda ko‘p uchraydi.",
    whyEn: "C++'s `priority_queue` is a max-heap by default — the largest element is on top. For the smallest use `priority_queue<int, vector<int>, greater<int>>` or push negated values. It is one of the most common Dijkstra bugs.",
  },
  {
    id: "pb-ds-b3", track: "data-structures", tier: "basic", rating: 1150,
    uz: "Kalitlarni qo‘shish-o‘chirish va «x dan katta eng kichik kalit» so‘rovi kerak. Qaysi konteyner?",
    en: "You insert and erase keys and ask for “the smallest key greater than x”. Which container?",
    choicesUz: ["`unordered_set`", "`set` — `upper_bound(x)` bilan", "`vector`, har so‘rovdan oldin `sort`", "`stack`"],
    choicesEn: ["`unordered_set`", "`set` — with `upper_bound(x)`", "`vector`, sorted before every query", "`stack`"],
    correct: 1,
    whyUz: "`set` elementlarni tartibda saqlaydi, shuning uchun qo‘shish, o‘chirish va `upper_bound` — hammasi O(log n). `unordered_set` tez, lekin tartibni bilmaydi — «keyingi kattaroq» degan savolga javob bera olmaydi.",
    whyEn: "`set` keeps its keys ordered, so insert, erase and `upper_bound` are all O(log n). `unordered_set` is fast but knows nothing of order, so it cannot answer “the next larger key”.",
  },
  {
    id: "pb-ds-c1", track: "data-structures", tier: "core", rating: 1400,
    uz: "Segment tree o‘rniga prefiks yig‘indilar massivi qachon yetarli?",
    en: "When is a prefix-sum array enough, making a segment tree unnecessary?",
    choicesUz: ["So‘rovlar orasida massiv o‘zgarmasa", "Massiv kichik bo‘lsa", "Faqat yig‘indi so‘ralsa", "Elementlar musbat bo‘lsa"],
    choicesEn: ["The array never changes between queries", "The array is small", "Only sums are asked for", "All elements are positive"],
    correct: 0,
    whyUz: "Prefiks yig‘indi statik massivda har so‘rovga O(1) beradi. Yangilash paydo bo‘lishi bilan uni qayta qurish O(n) — o‘shanda Fenwick tree yoki segment tree kerak. «Faqat yig‘indi» ham o‘zgarmaslikni kafolatlamaydi.",
    whyEn: "Prefix sums answer each query in O(1) on a static array. Once updates appear, rebuilding costs O(n), and that is what a Fenwick or segment tree is for. “Only sums” says nothing about updates.",
  },
  {
    id: "pb-ds-c2", track: "data-structures", tier: "core", rating: 1450,
    uz: "Grafga qirralar birma-bir qo‘shiladi va orada «u va v bog‘langanmi?» deb so‘raladi. Eng mos tuzilma?",
    en: "Edges are added to a graph one by one, and in between you are asked “are u and v connected?”. The best structure?",
    choicesUz: ["Har so‘rovda BFS", "DSU (disjoint set union)", "Segment tree", "Qo‘shnilik matritsasi"],
    choicesEn: ["A BFS per query", "DSU (disjoint set union)", "A segment tree", "An adjacency matrix"],
    correct: 1,
    whyUz: "DSU komponentlarni birlashtiradi va «qaysi komponentda?» degan savolga deyarli O(1) da javob beradi. Har so‘rovda BFS — O(n + m), q ta so‘rovda juda sekin. Qirralar faqat qo‘shilishi DSU uchun ideal holat.",
    whyEn: "DSU merges components and answers “which component?” in nearly O(1). A BFS per query costs O(n + m), far too slow over many queries. Edges that are only ever added are exactly DSU's case.",
  },
  {
    id: "pb-ds-c3", track: "data-structures", tier: "core", rating: 1500,
    uz: "Har element uchun o‘ng tomondagi birinchi kattaroq elementni O(n) da topish kerak. Qanday?",
    en: "For every element, find the first larger element to its right, in O(n). How?",
    choicesUz: ["Ikki ichma-ich sikl", "Monoton stek: yangi element kelganda undan kichiklarni stekdan olib, ularga javob yozish", "Saralab, binary search", "Priority queue"],
    choicesEn: ["Two nested loops", "A monotonic stack: when a new element arrives, pop everything smaller and record it as their answer", "Sort, then binary search", "A priority queue"],
    correct: 1,
    whyUz: "Stekda hali javobini topmagan elementlar kamayish tartibida turadi. Har element stekka bir marta kiradi va bir marta chiqadi — jami O(n). Saralash asl tartibni yo‘qotadi, «o‘ng tomonda» sharti esa aynan shu tartibga bog‘liq.",
    whyEn: "The stack holds the elements still waiting for an answer, in decreasing order. Each is pushed once and popped once — O(n) in total. Sorting destroys the original order, and “to the right” depends on exactly that order.",
  },
  {
    id: "pb-ds-d1", track: "data-structures", tier: "deep", rating: 1850,
    uz: "DSU da «union by rank (size)» va «path compression» birga nima beradi?",
    en: "What do union by rank (size) and path compression give a DSU together?",
    choicesUz: ["Amal boshiga O(log n)", "Amal boshiga amortizatsiyalangan α(n) — amalda o‘zgarmas", "O(n) qurish, keyin O(1)", "Faqat xotirani tejaydi"],
    choicesEn: ["O(log n) per operation", "Amortised α(n) per operation — constant in practice", "O(n) to build, then O(1)", "Only a memory saving"],
    correct: 1,
    whyUz: "Ikkalasi birga teskari Akkerman funksiyasi α(n) ni beradi — har qanday real n uchun 4 dan kichik. Bittasi yolg‘iz qolsa, O(log n) atrofida qoladi. Rollback kerak bo‘lganda esa path compression ishlatib bo‘lmaydi.",
    whyEn: "Together they give the inverse Ackermann α(n), below 4 for any real n. Either one alone leaves you around O(log n). When you need rollbacks, path compression has to go.",
  },
  {
    id: "pb-ds-d2", track: "data-structures", tier: "deep", rating: 1800,
    uz: "n, q ≤ 2·10^5: «[l, r] ga x qo‘sh» va «[l, r] yig‘indisi» so‘rovlari aralash keladi. Nima kerak?",
    en: "n, q ≤ 2·10^5, with mixed queries “add x to [l, r]” and “sum of [l, r]”. What do you need?",
    choicesUz: ["Oddiy segment tree, oraliqdagi har elementni alohida yangilab", "Lazy propagation'li segment tree", "Prefiks yig‘indilar", "Sparse table"],
    choicesEn: ["A plain segment tree, updating each element of the range", "A segment tree with lazy propagation", "Prefix sums", "A sparse table"],
    correct: 1,
    whyUz: "Har elementni alohida yangilash oraliq uzunligiga teng vaqt oladi — eng yomon holatda O(n) har so‘rovga. Lazy propagation yangilanishni to‘liq qoplangan tugunda «keyinga» qoldiradi va ikkala amalni O(log n) ga tushiradi. Sparse table va prefiks yig‘indi esa yangilanishni ko‘tarmaydi.",
    whyEn: "Updating element by element costs the range length — O(n) per query at worst. Lazy propagation parks the update on fully covered nodes and brings both operations to O(log n). Sparse tables and prefix sums cannot take updates at all.",
  },
  {
    id: "pb-ds-d3", track: "data-structures", tier: "deep", rating: 1900,
    uz: "Massiv o‘zgarmaydi, 10^6 ta «[l, r] dagi minimum» so‘rovi bor. Har so‘rovga O(1) beradigan tuzilma?",
    en: "The array never changes and there are 10^6 “minimum of [l, r]” queries. Which structure answers each in O(1)?",
    choicesUz: ["Segment tree", "Sparse table", "Fenwick tree", "Prefiks minimumlar massivi"],
    choicesEn: ["A segment tree", "A sparse table", "A Fenwick tree", "A prefix-minimum array"],
    correct: 1,
    whyUz: "Sparse table 2^k uzunlikdagi bo‘laklar minimumini saqlaydi; [l, r] ni ikki kesishuvchi bo‘lak qoplaydi, min esa takrorlanishga befarq. Prefiks minimumdan oraliq minimumini chiqarib bo‘lmaydi — min ni «ayirib» bo‘lmaydi. Segment tree esa O(log n).",
    whyEn: "A sparse table stores minimums of blocks of length 2^k; two overlapping blocks cover [l, r], and min does not mind the overlap. Prefix minimums cannot give a range minimum — min cannot be “subtracted”. A segment tree is O(log n).",
  },

  /* ===================================================== binary-search (900 → 1900) */
  {
    id: "pb-bs-b1", track: "binary-search", tier: "basic", rating: 1000,
    uz: "Binary search ishlashi uchun nima rost bo‘lishi kerak?",
    en: "What must be true for binary search to work?",
    choicesUz: ["Elementlar turli bo‘lishi", "Tekshirilayotgan shart monoton bo‘lishi: bir joygacha yolg‘on, keyin doim rost", "Elementlar musbat bo‘lishi", "Uzunlik 2 ning darajasi bo‘lishi"],
    choicesEn: ["The elements are distinct", "The predicate is monotone: false up to some point, true from then on", "The elements are positive", "The length is a power of two"],
    correct: 1,
    whyUz: "Asosiy talab — saralanganlik emas, monotonlik. Saralangan massiv buning bir xususiy holi xolos. Shuning uchun binary search javob ustida ham ishlaydi: «X vaqtda ulguramanmi?» — X oshgani sari yolg‘ondan rostga bir marta o‘tadi.",
    whyEn: "The real requirement is monotonicity, not sortedness; a sorted array is one special case. That is why you can binary search on the answer: “can I finish within X?” flips from false to true exactly once as X grows.",
  },
  {
    id: "pb-bs-b2", track: "binary-search", tier: "basic", rating: 1050,
    uz: "a = {1, 3, 3, 3, 7}. `upper_bound(3) − lower_bound(3)` (indekslar farqi) nechaga teng?",
    en: "a = {1, 3, 3, 3, 7}. What is `upper_bound(3) − lower_bound(3)` (as indices)?",
    choicesUz: ["1", "2", "3", "4"],
    correct: 2,
    whyUz: "`lower_bound` — ≥ 3 bo‘lgan birinchi element, indeks 1. `upper_bound` — > 3 bo‘lgan birinchi element, indeks 4. Farq 3 — bu 3 ning massivdagi soni. Saralangan massivda sanashning standart usuli.",
    whyEn: "`lower_bound` is the first element ≥ 3, index 1; `upper_bound` is the first > 3, index 4. The difference, 3, is how many 3s there are — the standard way to count in a sorted array.",
  },
  {
    id: "pb-bs-b3", track: "binary-search", tier: "basic", rating: 1100,
    uz: "`lo` va `hi` — `int`, qiymatlari 1.5·10^9 atrofida. `int mid = (lo + hi) / 2;` da nima xato?",
    en: "`lo` and `hi` are `int`s around 1.5·10^9. What is wrong with `int mid = (lo + hi) / 2;`?",
    choicesUz: ["Hech narsa", "`lo + hi` ≈ 3·10^9 — `int` toshadi; `lo + (hi − lo) / 2` yozish kerak", "Bo‘lish yaxlitlashda xato qiladi", "`mid` doim `lo` ga teng bo‘ladi"],
    choicesEn: ["Nothing", "`lo + hi` ≈ 3·10^9 overflows `int`; write `lo + (hi − lo) / 2`", "The division rounds incorrectly", "`mid` always equals `lo`"],
    correct: 1,
    whyUz: "Ikkala son alohida `int` ga sig‘adi, lekin yig‘indisi sig‘maydi va manfiy bo‘lib qoladi. `lo + (hi − lo) / 2` da hech qachon chegaradan oshmaydi. Yoki shunchaki `long long` ishlating.",
    whyEn: "Each fits in an `int` but their sum does not, and it wraps negative. `lo + (hi − lo) / 2` never exceeds the bound. Or simply use `long long`.",
  },
  {
    id: "pb-bs-c1", track: "binary-search", tier: "core", rating: 1350,
    uz: "Bu kod ba’zan cheksiz aylanadi. Qachon va nega?",
    en: "This loop sometimes never ends. When, and why?",
    code: "while (lo < hi) {\n    int mid = (lo + hi) / 2;\n    if (ok(mid)) lo = mid;\n    else hi = mid - 1;\n}",
    choicesUz: ["Hech qachon — kod to‘g‘ri", "hi = lo + 1 va ok(mid) rost bo‘lganda: mid = lo, lo o‘zgarmaydi; mid = (lo + hi + 1) / 2 kerak", "Birinchi elementni o‘tkazib yuboradi", "hi = mid bo‘lishi kerak"],
    choicesEn: ["Never — the code is correct", "When hi = lo + 1 and ok(mid) holds: mid = lo, so lo never moves; use mid = (lo + hi + 1) / 2", "It skips the first element", "It should be hi = mid"],
    correct: 1,
    whyUz: "`lo = mid` bo‘lsa, mid yuqoriga yaxlitlanishi shart, aks holda ikki elementli oraliqda mid = lo bo‘lib, hech narsa o‘zgarmaydi. Qoida: `lo = mid` ↔ yuqoriga yaxlitlash, `hi = mid` ↔ pastga.",
    whyEn: "With `lo = mid`, mid must round up; otherwise on a two-element range mid = lo and nothing changes. The rule: `lo = mid` pairs with rounding up, `hi = mid` with rounding down.",
  },
  {
    id: "pb-bs-c2", track: "binary-search", tier: "core", rating: 1400,
    uz: "n ta kitob ketma-ket turibdi, k ta kotib bor; har kotib ketma-ket kitoblar bo‘lagini oladi. Eng ko‘p sahifa olgan kotibning yuklamasini minimallash kerak. Qanday?",
    en: "n books stand in a row and k scribes each take a contiguous block. Minimise the largest number of pages any scribe gets. How?",
    choicesUz: ["O(n² · k) DP — boshqa yo‘l yo‘q", "Javob X ustida binary search: X berilsa, kerakli kotiblar sonini greedy bilan O(n) da sanash", "Kitoblarni saralab, teng bo‘lish", "Eng qalin kitobni birinchi kotibga berish"],
    choicesEn: ["An O(n² · k) DP — there is no other way", "Binary search on the answer X: for a given X, count the scribes needed greedily in O(n)", "Sort the books and split evenly", "Give the thickest book to the first scribe"],
    correct: 1,
    whyUz: "«X yuklama bilan k kotib yetadimi?» — X oshsa, javob yolg‘ondan rostga bir marta o‘tadi. Tekshiruv oddiy: kitoblarni X dan oshmaguncha yig‘ib, oshsa yangi kotib boshlash. Jami O(n log(Σ)). Tartib muhim bo‘lgani uchun saralash mumkin emas.",
    whyEn: "“Do k scribes suffice with load X?” flips from false to true once as X grows. The check is simple: keep adding books until X would be exceeded, then start a new scribe. O(n log Σ) in total. Order matters, so sorting is not allowed.",
  },
  {
    id: "pb-bs-c3", track: "binary-search", tier: "core", rating: 1500,
    uz: "Haqiqiy sonlar ustida binary search: `while (hi - lo > 1e-9)` ba’zan hech tugamaydi. Ishonchli yechim?",
    en: "Binary search over reals: `while (hi - lo > 1e-9)` sometimes never terminates. The reliable fix?",
    choicesUz: ["eps ni 1e-18 ga kamaytirish", "Belgilangan sonli iteratsiya — masalan, 100 marta", "`float` ga o‘tish", "`while (lo != hi)`"],
    choicesEn: ["Shrink eps to 1e-18", "A fixed number of iterations — say, 100", "Switch to `float`", "`while (lo != hi)`"],
    correct: 1,
    whyUz: "Qiymatlar katta bo‘lsa (masalan 10^9), `double` ning qo‘shni sonlari orasidagi masofa 1e-9 dan katta — farq hech qachon eps dan kichik bo‘lmaydi. 100 iteratsiya oraliqni 2^100 marta qisqartiradi, bu har qanday aniqlikka yetadi va doim tugaydi.",
    whyEn: "For large values (around 10^9, say) adjacent `double`s are more than 1e-9 apart, so the gap never drops below eps. 100 iterations shrink the range by 2^100 — enough for any precision — and always terminate.",
  },
  {
    id: "pb-bs-d1", track: "binary-search", tier: "deep", rating: 1650,
    uz: "Ternary search qanday funksiyada to‘g‘ri ishlaydi?",
    en: "On what kind of function does ternary search work correctly?",
    choicesUz: ["Istalgan uzluksiz funksiyada", "Qat’iy unimodal: bitta cho‘qqi, uning atrofida tekis joylarsiz", "Istalgan monoton funksiyada", "Faqat kvadrat funksiyada"],
    choicesEn: ["Any continuous function", "A strictly unimodal one: a single peak, with no flat stretches around it", "Any monotone function", "Only quadratics"],
    correct: 1,
    whyUz: "f(m1) < f(m2) bo‘lsa, cho‘qqi m1 dan chapda bo‘lmaydi — bu faqat unimodallikda to‘g‘ri. Agar f(m1) = f(m2) bo‘lib, ular tekis joyda tursa, qaysi tomonni tashlash kerakligi noma’lum. Diskret holatda ko‘pincha f(m) va f(m+1) ni taqqoslab oddiy binary search qilish ishonchliroq.",
    whyEn: "If f(m1) < f(m2), the peak is not left of m1 — true only for unimodal functions. If f(m1) = f(m2) on a plateau, you cannot tell which side to drop. In discrete settings, binary searching on f(m) vs f(m+1) is usually more reliable.",
  },
  {
    id: "pb-bs-d2", track: "binary-search", tier: "deep", rating: 1700,
    uz: "n × m matritsaning har qatori va har ustuni o‘suvchi. x bor-yo‘qligini eng tez qanday topasiz?",
    en: "Every row and every column of an n × m matrix is increasing. What is the fastest way to find x?",
    choicesUz: ["Har qatorda binary search — O(n log m), bundan tezi yo‘q", "O‘ng yuqori burchakdan zinapoya: katta bo‘lsa chapga, kichik bo‘lsa pastga — O(n + m)", "Butun matritsani saralash", "Diagonal bo‘yicha binary search — O(log n)"],
    choicesEn: ["Binary search each row — O(n log m); nothing is faster", "A staircase from the top-right corner: larger → left, smaller → down — O(n + m)", "Sort the whole matrix", "Binary search along the diagonal — O(log n)"],
    correct: 1,
    whyUz: "O‘ng yuqoridagi element — qatorining eng kattasi va ustunining eng kichigi. x undan kichik bo‘lsa, butun ustunni, katta bo‘lsa butun qatorni tashlaysiz. Har qadam bitta qator yoki ustunni yo‘q qiladi. Diagonal esa matritsani to‘liq tartiblamaydi.",
    whyEn: "The top-right element is the largest in its row and the smallest in its column. If x is smaller, the whole column goes; if larger, the whole row. Each step removes a row or a column. The diagonal does not order the matrix.",
  },
  {
    id: "pb-bs-d3", track: "binary-search", tier: "deep", rating: 1800,
    uz: "n × m ko‘paytirish jadvalida (katak (i, j) = i · j), n, m ≤ 5·10^5. k-kichik sonni qanday topasiz?",
    en: "In an n × m multiplication table (cell (i, j) = i · j), n, m ≤ 5·10^5, how do you find the k-th smallest value?",
    choicesUz: ["Barcha n · m sonni yozib saralash", "Qiymat x ustida binary search; ≤ x bo‘lganlar sonini har qator uchun min(m, x / i) bilan O(n) da sanash", "Priority queue dan k marta olish", "Formula bilan O(1)"],
    choicesEn: ["Write all n · m values and sort", "Binary search on the value x; count entries ≤ x as the sum of min(m, x / i) over rows, in O(n)", "Pop from a priority queue k times", "An O(1) formula"],
    correct: 1,
    whyUz: "n · m = 2.5·10^11 — yozib bo‘lmaydi, k esa shu qadar katta bo‘lishi mumkin. «≤ x bo‘lganlar soni ≥ k» sharti x bo‘yicha monoton, uni esa jadvalni qurmasdan sanash mumkin. Jami O(n log(nm)).",
    whyEn: "n · m = 2.5·10^11 cannot be written out, and k can be that large. “At least k entries ≤ x” is monotone in x, and counting it needs no table at all. O(n log(nm)) in total.",
  },

  /* ============================================================ greedy (1000 → 1900) */
  {
    id: "pb-greedy-b1", track: "greedy", tier: "basic", rating: 1100,
    uz: "Tangalar {1, 3, 4}. 6 ni eng kam tanga bilan to‘lash kerak. «Eng kattasidan boshlab» greedy nechta tanga beradi va optimal javob nechta?",
    en: "Coins are {1, 3, 4}. Pay 6 with as few coins as possible. How many does “largest first” greedy use, and what is optimal?",
    choicesUz: ["Greedy 2, optimal 2", "Greedy 3, optimal 2", "Greedy 3, optimal 3", "Greedy 2, optimal 3"],
    choicesEn: ["Greedy 2, optimal 2", "Greedy 3, optimal 2", "Greedy 3, optimal 3", "Greedy 2, optimal 3"],
    correct: 1,
    whyUz: "Greedy: 4 + 1 + 1 = 3 tanga. Optimal: 3 + 3 = 2 tanga. Greedy faqat ba’zi tanga tizimlarida (masalan 1, 2, 5, 10) to‘g‘ri. Umumiy holatda bu — DP masalasi.",
    whyEn: "Greedy: 4 + 1 + 1 = 3 coins. Optimal: 3 + 3 = 2. Greedy is right only for some coin systems (like 1, 2, 5, 10); in general this is a DP problem.",
  },
  {
    id: "pb-greedy-b2", track: "greedy", tier: "basic", rating: 1000,
    uz: "B so‘m byudjet bilan iloji boricha ko‘p buyum sotib olish kerak (har birining narxi ma’lum). Qaysi tartibda olasiz?",
    en: "With a budget of B you want to buy as many items as possible (each has a price). In what order do you buy?",
    choicesUz: ["Eng qimmatidan boshlab", "Eng arzonidan boshlab", "Kiritilgan tartibda", "DP shart, greedy ishlamaydi"],
    choicesEn: ["Most expensive first", "Cheapest first", "In input order", "It needs DP; greedy fails"],
    correct: 1,
    whyUz: "Maqsad — buyumlar soni, narxi emas. Istalgan optimal to‘plamdagi qimmatroq buyumni tashqaridagi arzonrog‘iga almashtirish sonni kamaytirmaydi va pul tejaydi. Bu «almashtirish argumenti» — greedy isbotining asosiy usuli.",
    whyEn: "The goal is the count, not the value. Swapping a pricier chosen item for a cheaper unchosen one keeps the count and saves money. That is the exchange argument — the standard way to prove a greedy.",
  },
  {
    id: "pb-greedy-b3", track: "greedy", tier: "basic", rating: 1100,
    uz: "Buyumlarni bo‘lib olish mumkin (fractional knapsack). Xaltaga qaysi tartibda solasiz?",
    en: "Items may be taken in fractions (fractional knapsack). In what order do you fill the bag?",
    choicesUz: ["Qiymati bo‘yicha kamayish tartibida", "Og‘irligi bo‘yicha o‘sish tartibida", "Qiymat / og‘irlik nisbati bo‘yicha kamayish tartibida", "Kiritilgan tartibda"],
    choicesEn: ["By value, highest first", "By weight, lightest first", "By value / weight ratio, highest first", "In input order"],
    correct: 2,
    whyUz: "Bo‘lish mumkin bo‘lsa, har kilogramm joyga eng qimmat «kilogramm» ni solish kerak — ya’ni nisbat bo‘yicha. Oxirgi buyum qisman olinadi. 0/1 knapsack da (bo‘lib bo‘lmaydi) bu greedy ishlamaydi.",
    whyEn: "When fractions are allowed, each unit of capacity should hold the most valuable unit of weight — the ratio. The last item is taken partially. For 0/1 knapsack, where items cannot be split, this greedy fails.",
  },
  {
    id: "pb-greedy-c1", track: "greedy", tier: "core", rating: 1300,
    uz: "Bir-biri bilan kesishmaydigan eng ko‘p tadbirni tanlash uchun tadbirlarni nima bo‘yicha saralaysiz?",
    en: "To pick the most pairwise non-overlapping activities, you sort them by what?",
    choicesUz: ["Boshlanish vaqti bo‘yicha", "Tugash vaqti bo‘yicha", "Davomiyligi bo‘yicha", "Kesishuvlar soni bo‘yicha"],
    choicesEn: ["Start time", "Finish time", "Duration", "Number of conflicts"],
    correct: 1,
    whyUz: "Eng erta tugaydiganini olish keyingilarga eng ko‘p vaqt qoldiradi. Boshlanish bo‘yicha: bitta uzun tadbir hammasini to‘sadi. Davomiylik bo‘yicha: qisqa tadbir ikki uzunning o‘rtasiga tushib, ikkalasini ham to‘sishi mumkin.",
    whyEn: "Taking the earliest finish leaves the most time for the rest. By start: one long activity can block everything. By duration: a short one can sit across two others and block both.",
  },
  {
    id: "pb-greedy-c2", track: "greedy", tier: "core", rating: 1350,
    uz: "Bitta mashina, n ta ish, har birining davomiyligi ma’lum. Tugash vaqtlari yig‘indisini minimallash uchun ishlarni qaysi tartibda bajarasiz?",
    en: "One machine, n jobs with known durations. To minimise the sum of completion times, in what order do you run them?",
    choicesUz: ["Eng uzunidan boshlab", "Eng qisqasidan boshlab", "Kiritilgan tartibda", "Farqi yo‘q — yig‘indi doim bir xil"],
    choicesEn: ["Longest first", "Shortest first", "In input order", "It does not matter — the sum is fixed"],
    correct: 1,
    whyUz: "Birinchi ish davomiyligi hamma n ta tugash vaqtiga qo‘shiladi, ikkinchisiniki n−1 tasiga va hokazo. Shuning uchun eng ko‘p takrorlanadigan o‘ringa eng qisqasini qo‘yish kerak. Qo‘shni ikkitasini almashtirib ko‘rsangiz, isbot ham chiqadi.",
    whyEn: "The first job's duration is added to all n completion times, the second's to n−1 of them, and so on — so the slot counted most often should hold the shortest job. Swapping two neighbours proves it.",
  },
  {
    id: "pb-greedy-c3", track: "greedy", tier: "core", rating: 1500,
    uz: "Sonlarni yonma-yon yozib eng katta son hosil qilish kerak: {3, 30, 34}. To‘g‘ri komparator qaysi?",
    en: "Concatenate the numbers to form the largest possible number: {3, 30, 34}. Which comparator is right?",
    choicesUz: ["Kattaroq son oldin", "Leksikografik kattaroq satr oldin", "a + b > b + a bo‘lsa a oldin (satr sifatida qo‘shib taqqoslash)", "Raqamlari kamroq son oldin"],
    choicesEn: ["The larger number first", "The lexicographically larger string first", "a before b if a + b > b + a (concatenated as strings)", "The number with fewer digits first"],
    correct: 2,
    whyUz: "Javob 34330. «Kattaroq oldin» va leksikografik tartib ikkalasi 34303 beradi, chunki «30» ni «3» dan oldin qo‘yadi. To‘g‘ri savol: «ikkalasining qaysi tartibi kattaroq?» — 330 > 303, demak 3 oldin.",
    whyEn: "The answer is 34330. “Larger first” and lexicographic order both give 34303, putting “30” before “3”. The right question is “which of the two orders is bigger?” — 330 > 303, so 3 goes first.",
  },
  {
    id: "pb-greedy-d1", track: "greedy", tier: "deep", rating: 1750,
    uz: "Ishlarning davomiyligi va deadline'i bor; maqsad — o‘z vaqtida tugaydigan ishlar soni maksimal. Deadline bo‘yicha saralab, ishlarni qo‘shib boryapsiz. Umumiy vaqt deadline'dan oshib ketsa nima qilasiz?",
    en: "Jobs have durations and deadlines; maximise how many finish on time. You sort by deadline and add jobs in turn. When the total time passes the current deadline, what do you do?",
    choicesUz: ["Yangi ishni tashlab yuborish", "Olinganlar ichidan eng uzunini chiqarib tashlash (max-heap bilan)", "Eng qisqasini chiqarib tashlash", "Hammasini boshidan qayta saralash"],
    choicesEn: ["Drop the new job", "Remove the longest job taken so far (with a max-heap)", "Remove the shortest one", "Re-sort everything from scratch"],
    correct: 1,
    whyUz: "Qaysi ishni chiqarsangiz ham son bittaga kamayadi, lekin eng uzunini chiqarish eng ko‘p vaqt bo‘shatadi va keyingilarga eng ko‘p imkon qoldiradi. Bu «regret greedy»: qarorni keyin arzonroq tarzda qaytarib olish.",
    whyEn: "Whichever job you remove, the count drops by one — but removing the longest frees the most time for what follows. This is regret greedy: taking a decision back later, at the cheapest price.",
  },
  {
    id: "pb-greedy-d2", track: "greedy", tier: "deep", rating: 1700,
    uz: "Qaysi masalada «har qadamda eng yaxshisini olish» isbotlangan holda optimal javob beradi?",
    en: "In which problem is “take the best option at each step” provably optimal?",
    choicesUz: ["0/1 knapsack", "Grafdagi eng uzun oddiy yo‘l", "Minimal ostov daraxt (Kruskal)", "Kommivoyajer masalasi"],
    choicesEn: ["0/1 knapsack", "The longest simple path in a graph", "Minimum spanning tree (Kruskal)", "The travelling salesman problem"],
    correct: 2,
    whyUz: "Kruskal qirralarni og‘irlik bo‘yicha oladi va sikl hosil qilmasa qo‘shadi. «Kesim xossasi» buni isbotlaydi: istalgan kesimdagi eng yengil qirra biror MST da bor. Grafning ostov o‘rmonlari matroid tuzilmasini hosil qiladi — greedy aynan matroidlarda kafolatlangan.",
    whyEn: "Kruskal takes edges by weight and keeps any that form no cycle. The cut property proves it: the lightest edge across any cut lies in some MST. A graph's spanning forests form a matroid, and matroids are exactly where greedy is guaranteed.",
  },
  {
    id: "pb-greedy-d3", track: "greedy", tier: "deep", rating: 1650,
    uz: "Sondan (masalan 1432219) k ta raqamni o‘chirib, eng kichik son hosil qilish kerak. Qanday?",
    en: "Remove k digits from a number (say 1432219) to make it as small as possible. How?",
    choicesUz: ["Eng katta k ta raqamni o‘chirish", "Chapdan yurib, oldingi raqam joriydan katta bo‘lsa (va k tugamagan bo‘lsa) uni o‘chirish — monoton stek", "Oxirgi k ta raqamni o‘chirish", "Barcha variantlarni sinash"],
    choicesEn: ["Remove the k largest digits", "Scan left to right; while the previous digit is larger than the current one (and k remains), delete it — a monotonic stack", "Remove the last k digits", "Try every combination"],
    correct: 1,
    whyUz: "Chapdagi raqam kattaroq vazn ko‘taradi, shuning uchun kattaroq raqam undan keyin kichikrog‘i kelganda o‘chirilishi kerak. k = 3 da javob 1219. «Eng katta raqamlarni o‘chirish» 4, 3 va 9 ni olib 1221 beradi — kattaroq.",
    whyEn: "Digits on the left carry more weight, so a digit followed by a smaller one should go. With k = 3 the answer is 1219. Removing the largest digits (4, 3, 9) leaves 1221 — bigger.",
  },

  /* ================================================= two-pointers (900 → 1800) */
  {
    id: "pb-tp-b1", track: "two-pointers", tier: "basic", rating: 1000,
    uz: "Saralangan massivda yig‘indisi X bo‘lgan juft bormi? O(n) usul qaysi?",
    en: "Does a sorted array contain a pair summing to X? Which method is O(n)?",
    choicesUz: ["Ikki ichma-ich sikl", "Ikki uchidan ko‘rsatkich: yig‘indi katta — o‘ngdagisini chapga, kichik — chapdagisini o‘ngga", "Faqat hash bilan O(n) bo‘ladi", "Har element uchun butun massivni aylanish"],
    choicesEn: ["Two nested loops", "Pointers at both ends: sum too big — move the right one left; too small — move the left one right", "Only hashing gives O(n)", "Scan the whole array for each element"],
    correct: 1,
    whyUz: "Yig‘indi katta bo‘lsa, o‘ngdagi element hech qanday chapdagi bilan to‘g‘ri juft bo‘la olmaydi — uni tashlash xavfsiz. Har qadamda bitta element tashlanadi, jami O(n). Saralanganlik aynan shu xulosaga imkon beradi.",
    whyEn: "If the sum is too big, the right element cannot pair with anything left of it, so dropping it is safe. One element goes per step — O(n) in total. Sortedness is what makes that conclusion valid.",
  },
  {
    id: "pb-tp-b2", track: "two-pointers", tier: "basic", rating: 950,
    uz: "Uzunligi k bo‘lgan barcha oynalarning yig‘indisini O(n) da qanday hisoblaysiz?",
    en: "How do you get the sums of all windows of length k in O(n)?",
    choicesUz: ["Har oynani qaytadan qo‘shib", "Oyna siljiganda yangi elementni qo‘shib, chiqib ketganini ayirish", "Saralab, eng kattalarini olish", "Faqat segment tree bilan"],
    choicesEn: ["Re-add every window from scratch", "When the window slides, add the element entering and subtract the one leaving", "Sort and take the largest", "Only with a segment tree"],
    correct: 1,
    whyUz: "Qo‘shni oynalar k−1 ta elementni bo‘lishadi. Har siljishda faqat ikki element o‘zgaradi, shuning uchun har oyna O(1) da yangilanadi. Qaytadan qo‘shish O(n · k).",
    whyEn: "Neighbouring windows share k−1 elements, and a slide changes only two of them, so each window updates in O(1). Re-adding costs O(n · k).",
  },
  {
    id: "pb-tp-b3", track: "two-pointers", tier: "basic", rating: 1000,
    uz: "Uzunliklari n va m bo‘lgan ikki saralangan massivni bitta saralangan massivga birlashtirish qancha vaqt oladi?",
    en: "How long does merging two sorted arrays of lengths n and m into one sorted array take?",
    choicesUz: ["O((n + m) log(n + m)) — yana saralash kerak", "O(n + m) — ikkala boshidan ko‘rsatkich, kichigini olib borish", "O(n · m)", "O(n log m)"],
    choicesEn: ["O((n + m) log(n + m)) — sorting is needed again", "O(n + m) — a pointer at each start, always taking the smaller", "O(n · m)", "O(n log m)"],
    correct: 1,
    whyUz: "Ikkala massivning eng kichik qolgan elementi doim ko‘rsatkichlar ostida turadi. Har qadamda bittasini olasiz — jami n + m qadam. Bu merge sort ning yuragi.",
    whyEn: "The smallest remaining element of each array always sits under its pointer. Take one per step — n + m steps in total. This is the heart of merge sort.",
  },
  {
    id: "pb-tp-c1", track: "two-pointers", tier: "core", rating: 1350,
    uz: "Sliding window bilan «yig‘indisi ≤ K bo‘lgan eng uzun qism-massiv» ni topyapsiz. Massivda manfiy sonlar bo‘lsa nima buziladi?",
    en: "You find the longest subarray with sum ≤ K using a sliding window. What breaks if the array has negative numbers?",
    choicesUz: ["Hech nima — usul baribir ishlaydi", "Oynani qisqartirish qoidasi noto‘g‘ri bo‘lib qoladi", "Faqat sekinlashadi", "Javob doim 0 chiqadi"],
    choicesEn: ["Nothing — it still works", "The rule for shrinking the window is no longer valid", "It only gets slower", "The answer is always 0"],
    correct: 1,
    whyUz: "Sliding window «kengaytirsam yig‘indi oshadi, qisqartirsam kamayadi» degan monotonlikka tayanadi. Manfiy son bo‘lsa, kengaytirish yig‘indini kamaytirishi mumkin — chapni oldinga surgan qaror noto‘g‘ri bo‘ladi. Bunda prefiks yig‘indilar va boshqa usul kerak.",
    whyEn: "A sliding window relies on monotonicity: extend and the sum grows, shrink and it falls. With negatives, extending can lower the sum, so moving the left pointer forward may be the wrong call. You need prefix sums and a different method.",
  },
  {
    id: "pb-tp-c2", track: "two-pointers", tier: "core", rating: 1400,
    uz: "Musbat sonlar massivida yig‘indisi ≤ S bo‘lgan qism-massivlar sonini sanayapsiz. Har r uchun oynani qisqartirib bo‘lgach, javobga nima qo‘shasiz?",
    en: "You count subarrays with sum ≤ S in an array of positive numbers. For each r, after shrinking the window, what do you add to the answer?",
    choicesUz: ["1", "r − l + 1", "l", "r"],
    correct: 1,
    whyUz: "[l, r] yaroqli bo‘lsa, r da tugaydigan barcha [l', r] (l ≤ l' ≤ r) ham yaroqli — ular kichikroq. Bunday oynalar r − l + 1 ta. Faqat 1 qo‘shish faqat eng uzunini sanaydi.",
    whyEn: "If [l, r] is valid, every [l', r] with l ≤ l' ≤ r is valid too — each is smaller. There are r − l + 1 of them. Adding 1 counts only the longest.",
  },
  {
    id: "pb-tp-c3", track: "two-pointers", tier: "core", rating: 1500,
    uz: "«Aynan K xil element bor qism-massivlar soni» ni to‘g‘ridan-to‘g‘ri sliding window bilan sanash qiyin. Qanday hiyla ishlatiladi?",
    en: "Counting subarrays with exactly K distinct values is awkward with a sliding window directly. What is the trick?",
    choicesUz: ["Barcha qism-massivlarni tekshirish", "atMost(K) − atMost(K − 1): «ko‘pi bilan K» ni sanash oson", "Massivni saralab olish", "K ta ko‘rsatkich ishlatish"],
    choicesEn: ["Check every subarray", "atMost(K) − atMost(K − 1): counting “at most K” is easy", "Sort the array first", "Use K pointers"],
    correct: 1,
    whyUz: "«Ko‘pi bilan K xil» monoton: yaroqli oynaning ichki bo‘lagi ham yaroqli, shuning uchun uni oddiy oyna bilan sanaysiz. «Aynan K» esa monoton emas. Ikki monoton sonning farqi aynan kerakli sonni beradi.",
    whyEn: "“At most K distinct” is monotone — a sub-window of a valid window is valid — so an ordinary window counts it. “Exactly K” is not monotone. The difference of two monotone counts gives exactly what you need.",
  },
  {
    id: "pb-tp-d1", track: "two-pointers", tier: "deep", rating: 1650,
    uz: "n = 10^6, har k uzunlikdagi oynaning maksimumi kerak. Eng tez usul?",
    en: "n = 10^6, and you need the maximum of every window of length k. The fastest method?",
    choicesUz: ["`multiset` — O(n log k), bundan tezi yo‘q", "Monoton deque: indekslar, qiymatlari kamayish tartibida — O(n)", "Har oynani qayta ko‘rish — O(n · k)", "Saralab, eng kattasini olish"],
    choicesEn: ["A `multiset` — O(n log k); nothing is faster", "A monotonic deque of indices with decreasing values — O(n)", "Rescan every window — O(n · k)", "Sort and take the largest"],
    correct: 1,
    whyUz: "Yangi element kelganda undan kichik oldingilar hech qachon maksimum bo‘lmaydi — ular deque oxiridan olib tashlanadi. Boshidagi element oynadan chiqsa, u ham olinadi. Har indeks bir marta kirib, bir marta chiqadi — O(n).",
    whyEn: "When a new element arrives, every smaller one before it can never be a maximum again, so they are popped from the back. The front leaves once it falls out of the window. Each index enters and leaves once — O(n).",
  },
  {
    id: "pb-tp-d2", track: "two-pointers", tier: "deep", rating: 1700,
    uz: "Oyna (two pointers) usuli to‘g‘ri ishlashi uchun «yaroqli oyna» sharti qanday xossaga ega bo‘lishi kerak?",
    en: "For the two-pointer window method to be correct, what property must “valid window” have?",
    choicesUz: ["Yaroqli oynaning har qanday ichki bo‘lagi ham yaroqli (va yaroqsizni kengaytirsa, yaroqsizligicha qoladi)", "Massiv saralangan bo‘lishi", "Elementlar turli bo‘lishi", "n juft bo‘lishi"],
    choicesEn: ["Every sub-window of a valid window is also valid (and extending an invalid one keeps it invalid)", "The array is sorted", "The elements are distinct", "n is even"],
    correct: 0,
    whyUz: "Shu xossa tufayli r oldinga yursa, eng yaxshi l hech qachon orqaga qaytmaydi — ikkala ko‘rsatkich faqat oldinga yuradi va jami O(n). Xossa bo‘lmasa (masalan manfiy sonli yig‘indi), l ni surish yaxshi yechimni yo‘qotishi mumkin.",
    whyEn: "Because of it, the best l never moves back as r advances — both pointers only go forward, O(n) in total. Without it (sums with negatives, say), moving l can throw away the best answer.",
  },
  {
    id: "pb-tp-d3", track: "two-pointers", tier: "deep", rating: 1750,
    uz: "s ichida t ning barcha belgilarini (takrorlari bilan) o‘z ichiga olgan eng qisqa oynani qidiryapsiz. Chap ko‘rsatkichni qachon surasiz?",
    en: "You want the shortest window of s containing every character of t (with multiplicity). When do you move the left pointer?",
    choicesUz: ["Oyna uzunligi |t| dan oshganda", "Oyna t ni to‘liq qamrab turgan ekan — javobni yangilab, chapdan qisqartirishda davom etasiz", "Takroriy belgi uchraganda", "Hech qachon, faqat o‘ngga kengaytirasiz"],
    choicesEn: ["When the window grows longer than |t|", "As long as the window still covers t — record the answer and keep shrinking from the left", "When a repeated character appears", "Never; you only extend to the right"],
    correct: 1,
    whyUz: "O‘ng ko‘rsatkich t qamralguncha kengaytiradi, chap esa qamrov buzilmaguncha qisqartiradi. Har qisqartirishdan oldin javob yangilanadi. Chastotalar massivi va «yetishmayotgan belgilar soni» hisoblagichi bilan hammasi O(|s|).",
    whyEn: "The right pointer extends until t is covered; the left shrinks while coverage holds, recording the answer before each step. With a frequency array and a “characters still missing” counter, it is all O(|s|).",
  },

  /* ============================================================ graphs (1000 → 2300) */
  {
    id: "pb-graph-b1", track: "graphs", tier: "basic", rating: 1100,
    uz: "Og‘irliksiz grafda (qirralar soni bo‘yicha) eng qisqa yo‘lni topishning eng sodda va tez usuli?",
    en: "In an unweighted graph, what is the simplest fast way to find shortest paths (by number of edges)?",
    choicesUz: ["DFS", "BFS", "Floyd-Warshall", "Barcha yo‘llarni sanab chiqish"],
    choicesEn: ["DFS", "BFS", "Floyd-Warshall", "Enumerate every path"],
    correct: 1,
    whyUz: "BFS tugunlarni masofa bo‘yicha qatlam-qatlam ochadi, shuning uchun birinchi yetib kelgan paytdagi masofa eng qisqasi — O(V + E). DFS esa uzun aylanma yo‘ldan birinchi yetib kelishi mumkin.",
    whyEn: "BFS opens nodes layer by layer in order of distance, so the first time it reaches a node is the shortest — O(V + E). DFS may reach a node first along a long detour.",
  },
  {
    id: "pb-graph-b2", track: "graphs", tier: "basic", rating: 1200,
    uz: "BFS da bitta tugun navbatga ikki marta tushib qolyapti. Nima esdan chiqqan?",
    en: "Your BFS puts the same node in the queue twice. What did you forget?",
    choicesUz: ["Navbat o‘rniga stek ishlatish", "Tugunni navbatga qo‘shayotgan paytda belgilash", "Qirralarni saralash", "Tugunni navbatdan olayotganda belgilash"],
    choicesEn: ["To use a stack instead of a queue", "To mark a node at the moment you enqueue it", "To sort the edges", "To mark a node when you dequeue it"],
    correct: 1,
    whyUz: "Belgilashni navbatdan olishga qoldirsangiz, tugun olinguncha bir necha qo‘shnisi uni qayta qo‘shib ulguradi. Belgilash qo‘shish paytida bo‘lishi kerak — shunda har tugun aynan bir marta kiradi.",
    whyEn: "If you mark on dequeue, several neighbours can enqueue a node before it is taken out. Mark at enqueue time and each node enters exactly once.",
  },
  {
    id: "pb-graph-b3", track: "graphs", tier: "basic", rating: 1150,
    uz: "n = 10^5 tugun, m = 2·10^5 qirra. Grafni qanday saqlaysiz?",
    en: "n = 10^5 nodes and m = 2·10^5 edges. How do you store the graph?",
    choicesUz: ["Qo‘shnilik matritsasi `bool g[n][n]`", "Qo‘shnilik ro‘yxati `vector<int> adj[n]` — O(n + m) xotira", "Faqat qirralar ro‘yxati, har so‘rovda hammasini aylanib", "`map<pair<int,int>, bool>`"],
    choicesEn: ["An adjacency matrix `bool g[n][n]`", "An adjacency list `vector<int> adj[n]` — O(n + m) memory", "Just an edge list, scanned in full every time", "A `map<pair<int,int>, bool>`"],
    correct: 1,
    whyUz: "Matritsa 10^10 katak — sig‘maydi, va har tugun qo‘shnilarini topish O(n) bo‘ladi. Ro‘yxat faqat bor qirralarni saqlaydi va BFS/DFS ni O(n + m) da yurgizadi. Matritsa faqat zich grafda, n ≈ 5000 gacha o‘rinli.",
    whyEn: "A matrix is 10^10 cells — it does not fit, and finding a node's neighbours costs O(n). A list stores only the real edges and runs BFS/DFS in O(n + m). A matrix makes sense only for dense graphs, n up to about 5000.",
  },
  {
    id: "pb-graph-c1", track: "graphs", tier: "core", rating: 1550,
    uz: "Dijkstra manfiy og‘irlikli qirra bo‘lsa nega noto‘g‘ri ishlaydi?",
    en: "Why does Dijkstra go wrong with a negative edge weight?",
    choicesUz: ["Priority queue manfiy sonni qabul qilmaydi", "Yakuniy deb belgilangan tugun keyinroq arzonroq bo‘lib qolishi mumkin", "Cheksiz siklga tushadi", "To‘g‘ri ishlaydi, faqat sekin"],
    choicesEn: ["The priority queue rejects negatives", "A node already marked final can later become cheaper", "It loops forever", "It works, just slowly"],
    correct: 1,
    whyUz: "Dijkstra «navbatdagi eng yaqin tugun yakuniy» degan taxminga tayanadi — keyingi yo‘llar faqat uzunroq bo‘ladi. Manfiy qirra shu taxminni buzadi. Bunday grafda Bellman-Ford (yoki SPFA) kerak.",
    whyEn: "Dijkstra assumes the nearest unfinished node is final, because any later path can only be longer. A negative edge breaks that. Such graphs need Bellman-Ford (or SPFA).",
  },
  {
    id: "pb-graph-c2", track: "graphs", tier: "core", rating: 1500,
    uz: "Kahn algoritmi (kirish darajasi 0 bo‘lganlarni navbat bilan olish) tugagach, hamma tugun navbatdan o‘tmagan bo‘lsa, bu nimani bildiradi?",
    en: "Kahn's algorithm (repeatedly taking nodes with in-degree 0) finishes, but not every node went through the queue. What does that mean?",
    choicesUz: ["Graf bog‘lanmagan", "Grafda yo‘naltirilgan sikl bor — topologik tartib mavjud emas", "Algoritmda xato bor", "Bir nechta topologik tartib bor"],
    choicesEn: ["The graph is disconnected", "The graph has a directed cycle — no topological order exists", "The algorithm has a bug", "There are several topological orders"],
    correct: 1,
    whyUz: "Sikldagi har tugunning kirish darajasi hech qachon 0 ga tushmaydi — ular bir-birini kutadi. Bog‘lanmaganlik esa muammo emas: har komponentning manbalari boshidanoq navbatda bo‘ladi. Bu siklni aniqlashning oson usuli.",
    whyEn: "Every node on a cycle waits on another, so its in-degree never reaches 0. Disconnection is no problem — each component's sources are in the queue from the start. It is an easy way to detect a cycle.",
  },
  {
    id: "pb-graph-c3", track: "graphs", tier: "core", rating: 1700,
    uz: "Qirralar og‘irligi faqat 0 yoki 1. Dijkstra dan tezroq usul?",
    en: "Every edge weighs 0 or 1. What beats Dijkstra here?",
    choicesUz: ["Oddiy BFS — og‘irliklarni hisobga olmasdan", "0-1 BFS: deque, 0 li qirra orqali — boshiga, 1 li orqali — oxiriga qo‘shish", "Floyd-Warshall", "DFS"],
    choicesEn: ["Plain BFS, ignoring the weights", "0-1 BFS: a deque — push to the front across a 0 edge, to the back across a 1 edge", "Floyd-Warshall", "DFS"],
    correct: 1,
    whyUz: "Deque doim masofa bo‘yicha tartibda qoladi: boshida d, oxirida d + 1. Shuning uchun priority queue kerak emas va hammasi O(V + E). Oddiy BFS 0 li qirralarni 1 deb hisoblab, noto‘g‘ri javob beradi.",
    whyEn: "The deque stays sorted by distance — d at the front, d + 1 at the back — so no priority queue is needed and it all runs in O(V + E). Plain BFS counts 0 edges as 1 and answers wrong.",
  },
  {
    id: "pb-graph-d1", track: "graphs", tier: "deep", rating: 1900,
    uz: "DFS daraxtidagi (u → v) qirra qachon ko‘prik bo‘ladi? (tin — kirish vaqti, low — v ning subtree'sidan erishiladigan eng kichik tin)",
    en: "When is a DFS-tree edge (u → v) a bridge? (tin is entry time; low is the smallest tin reachable from v's subtree)",
    choicesUz: ["low[v] ≥ tin[u]", "low[v] > tin[u]", "tin[v] > tin[u]", "low[u] > tin[v]"],
    correct: 1,
    whyUz: "low[v] > tin[u] — v ning subtree'si u ga ham, undan yuqoriga ham qaytib chiqa olmaydi, demak (u, v) yagona bog‘lovchi. low[v] ≥ tin[u] esa kesish nuqtasining (u ning) sharti — ikkalasini adashtirish klassik xato.",
    whyEn: "low[v] > tin[u] means v's subtree cannot climb back to u or above, so (u, v) is its only link. low[v] ≥ tin[u] is the articulation-point condition for u — mixing the two up is the classic mistake.",
  },
  {
    id: "pb-graph-d2", track: "graphs", tier: "deep", rating: 2000,
    uz: "Eng qisqa yo‘l kerak, lekin ko‘pi bilan k ta qirradan tekin o‘tish mumkin (k ≤ 10). Qanday yechasiz?",
    en: "Find the shortest path, but you may cross up to k edges for free (k ≤ 10). How?",
    choicesUz: ["Eng og‘ir k ta qirrani 0 qilib, Dijkstra", "(tugun, ishlatilgan tekinlar soni) holatlari grafida Dijkstra — n · (k + 1) tugun", "BFS", "Dijkstra ni k marta ishga tushirish"],
    choicesEn: ["Zero out the k heaviest edges, then Dijkstra", "Dijkstra over states (node, free passes used) — n · (k + 1) nodes", "BFS", "Run Dijkstra k times"],
    correct: 1,
    whyUz: "Qaysi qirralarni tekin qilish yo‘lning o‘ziga bog‘liq — oldindan tanlab bo‘lmaydi. Holatga «nechta tekin ishlatildi» ni qo‘shsangiz, har qirra ikki o‘tish beradi: to‘lab (j → j) yoki tekin (j → j + 1). Bu «qatlamli graf» usuli.",
    whyEn: "Which edges to make free depends on the path itself, so you cannot pick them in advance. Add “free passes used” to the state and each edge gives two moves: paid (j → j) or free (j → j + 1). This is the layered-graph technique.",
  },
  {
    id: "pb-graph-d3", track: "graphs", tier: "deep", rating: 2100,
    uz: "Grafdan eng kam qirra o‘chirib, s va t ni ajratish kerak. Qanday topasiz?",
    en: "Remove as few edges as possible so that s and t are disconnected. How do you find that number?",
    choicesUz: ["BFS bilan eng qisqa yo‘lni topib, uning qirralarini o‘chirish", "Barcha sig‘imlar 1 bo‘lgan tarmoqda s dan t ga maksimal oqim — u minimal kesimga teng", "Barcha ko‘priklarni o‘chirish", "Minimal ostov daraxtni qurish"],
    choicesEn: ["Find a shortest path with BFS and delete its edges", "The maximum flow from s to t with every capacity 1 — it equals the minimum cut", "Delete every bridge", "Build a minimum spanning tree"],
    correct: 1,
    whyUz: "Max-flow = min-cut teoremasi: s dan t ga qirra jihatdan kesishmaydigan yo‘llar soni aynan ularni ajratish uchun o‘chirilishi kerak bo‘lgan eng kam qirralar soniga teng. Bitta yo‘lni kesish boshqa yo‘llarni qoldiradi; ko‘prik esa s va t orasida umuman bo‘lmasligi mumkin.",
    whyEn: "Max-flow = min-cut: the number of edge-disjoint s–t paths equals the fewest edges whose removal separates them. Cutting one path leaves the others, and there may be no bridge between s and t at all.",
  },
];
