/* Level-check questions: the far end of the roadmap.
 * See placement-bank.ts for what makes a question good enough to be here. */

import type { PlacementQuestion } from "./placement-bank";

export const advancedQuestions: PlacementQuestion[] = [
  /* =========================================================== strings (1000 → 2200) */
  {
    id: "pb-str-b1", track: "strings", tier: "basic", rating: 1000,
    uz: "Bu kod nima chiqaradi?",
    en: "What does this print?",
    code: "string s = \"12\";\nint x = s[0] + s[1];\ncout << x;",
    choicesUz: ["3", "12", "99", "Kompilyatsiya xatosi"],
    choicesEn: ["3", "12", "99", "A compile error"],
    correct: 2,
    whyUz: "`s[0]` — raqam emas, `'1'` belgisi, uning kodi 49; `'2'` ning kodi 50. Yig‘indi 99. Raqam qiymati kerak bo‘lsa, `s[i] - '0'` yozing: (49 − 48) + (50 − 48) = 3.",
    whyEn: "`s[0]` is not the digit but the character `'1'`, code 49; `'2'` is 50. The sum is 99. For the digit value write `s[i] - '0'`: (49 − 48) + (50 − 48) = 3.",
  },
  {
    id: "pb-str-b2", track: "strings", tier: "basic", rating: 1100,
    uz: "Bu sikl n = 10^5 marta aylanadi. Umumiy murakkabligi?",
    en: "This loop runs n = 10^5 times. What is its total complexity?",
    code: "string s;\nfor (int i = 0; i < n; i++)\n    s = s + 'a';",
    choicesUz: ["O(n)", "O(n²) — har safar butun satr yangidan nusxalanadi", "O(n log n)", "O(1)"],
    choicesEn: ["O(n)", "O(n²) — the whole string is copied every time", "O(n log n)", "O(1)"],
    correct: 1,
    whyUz: "`s + 'a'` yangi satr yaratadi va s ning hamma belgilarini unga ko‘chiradi: 1 + 2 + … + n ≈ n²/2. `s += 'a'` yoki `s.push_back('a')` esa o‘rnida qo‘shadi — amortizatsiyalangan O(1).",
    whyEn: "`s + 'a'` builds a new string and copies all of s into it: 1 + 2 + … + n ≈ n²/2. `s += 'a'` or `s.push_back('a')` appends in place — amortised O(1).",
  },
  {
    id: "pb-str-b3", track: "strings", tier: "basic", rating: 1050,
    uz: "s ichida p necha marta uchrashini sanayapsiz, ustma-ust tushganlar ham hisobga olinadi. `aaaa` ichida `aa` necha marta bor?",
    en: "Counting occurrences of p in s, overlaps included: how many times does `aa` occur in `aaaa`?",
    choicesUz: ["2", "3", "4", "1"],
    correct: 1,
    whyUz: "Boshlanish pozitsiyalari 0, 1 va 2 — uchta. Har moslikdan keyin |p| belgi oldinga sakrasangiz 2 chiqadi va ustma-ust mosliklar yo‘qoladi. `find` bilan qidirganda keyingi qidiruvni `pos + 1` dan boshlang.",
    whyEn: "Starting positions 0, 1 and 2 — three. Jumping |p| characters after each match gives 2 and loses the overlaps. When searching with `find`, resume from `pos + 1`.",
  },
  {
    id: "pb-str-c1", track: "strings", tier: "core", rating: 1600,
    uz: "KMP dagi prefiks-funksiya π[i] nimani bildiradi?",
    en: "What does the KMP prefix function π[i] mean?",
    choicesUz: ["i-pozitsiyagacha bo‘lgan mosliklar soni", "s[0..i] ning ham prefiksi, ham suffiksi bo‘lgan eng uzun xos (to‘liq bo‘lmagan) bo‘lagi uzunligi", "Keyingi taqqoslanadigan pozitsiya", "Alifbodagi belgilar soni"],
    choicesEn: ["The number of matches up to position i", "The length of the longest proper prefix of s[0..i] that is also its suffix", "The next position to compare", "The alphabet size"],
    correct: 1,
    whyUz: "π[i] — «border» uzunligi. Moslik uzilganda aynan shu qiymat andozaning qaysi joyidan davom etishni aytadi, shuning uchun KMP matnda hech qachon orqaga qaytmaydi va O(n + m) ishlaydi.",
    whyEn: "π[i] is the border length. On a mismatch it tells you where in the pattern to resume, which is why KMP never steps back in the text and runs in O(n + m).",
  },
  {
    id: "pb-str-c2", track: "strings", tier: "core", rating: 1500,
    uz: "Satrning istalgan ikki qism-satri tengligini O(1) da tekshirish uchun nimani oldindan hisoblaysiz?",
    en: "What do you precompute to compare any two substrings for equality in O(1)?",
    choicesUz: ["Suffix array", "Prefiks xeshlar va asosning darajalari", "Z-funksiya", "Hech narsa — har safar belgilab solishtirish"],
    choicesEn: ["A suffix array", "Prefix hashes and powers of the base", "The Z-function", "Nothing — compare character by character each time"],
    correct: 1,
    whyUz: "h[r] − h[l] · B^(r−l) qism-satr xeshini beradi. Ikki qism-satr xeshlari teng bo‘lsa, katta ehtimol bilan ular teng. Z-funksiya faqat prefiks bilan solishtirishga javob beradi, istalgan ikki bo‘lak uchun emas.",
    whyEn: "h[r] − h[l] · B^(r−l) is a substring's hash; equal hashes mean equal substrings with high probability. The Z-function compares against the prefix only, not any two pieces.",
  },
  {
    id: "pb-str-c3", track: "strings", tier: "core", rating: 1650,
    uz: "p ni s ichidan Z-funksiya bilan topmoqchisiz. Z-funksiya qaysi satrga qo‘llanadi?",
    en: "You want to find p inside s with the Z-function. Which string do you run it on?",
    choicesUz: ["s + p", "p + '#' + s — bu yerda '#' ikkalasida ham uchramaydi", "s ning o‘ziga", "reverse(s) + p"],
    choicesEn: ["s + p", "p + '#' + s — where '#' appears in neither", "s alone", "reverse(s) + p"],
    correct: 1,
    whyUz: "z[i] — i dan boshlanuvchi va satr prefiksiga (ya’ni p ga) mos keladigan eng uzun bo‘lak. z[i] = |p| bo‘lgan joyda p uchraydi. Ajratuvchi '#' moslik p dan oshib ketishiga yo‘l qo‘ymaydi.",
    whyEn: "z[i] is the longest piece starting at i that matches the string's prefix — that is, p. Wherever z[i] = |p|, p occurs. The '#' separator stops a match from running past p.",
  },
  {
    id: "pb-str-d1", track: "strings", tier: "deep", rating: 1850,
    uz: "s ni biror t satrni k ≥ 2 marta takrorlab hosil qilish mumkinmi? Buni prefiks-funksiya bilan qanday aniqlaysiz (n = |s|)?",
    en: "Can s be written as some string t repeated k ≥ 2 times? How does the prefix function tell you (n = |s|)?",
    choicesUz: ["π[n−1] > 0 bo‘lsa", "p = n − π[n−1] bo‘lsin; p < n va n % p == 0 bo‘lsa — ha, t = s[0..p)", "π ning barcha qiymatlari teng bo‘lsa", "n juft bo‘lsa"],
    choicesEn: ["If π[n−1] > 0", "Let p = n − π[n−1]; if p < n and n % p == 0 — yes, with t = s[0..p)", "If all π values are equal", "If n is even"],
    correct: 1,
    whyUz: "Eng uzun border uzunligi π[n−1] bo‘lsa, s ning eng kichik davri p = n − π[n−1]. Davr n ni bo‘lsa, s aniq takrorlanishlardan iborat. Masalan `abab`: π = 2, p = 2, 4 % 2 = 0 — ha. `aba`: p = 2, 3 % 2 ≠ 0 — yo‘q, garchi π > 0 bo‘lsa ham.",
    whyEn: "With the longest border π[n−1], the smallest period of s is p = n − π[n−1]. If p divides n, s is an exact repetition. `abab`: π = 2, p = 2, 4 % 2 = 0 — yes. `aba`: p = 2, 3 % 2 ≠ 0 — no, even though π > 0.",
  },
  {
    id: "pb-str-d2", track: "strings", tier: "deep", rating: 1950,
    uz: "Xeshni `unsigned long long` toshishi bilan, ya’ni mod 2^64 bo‘yicha hisoblayapsiz. Tajribali test yozuvchilar buni qanday sindiradi?",
    en: "You compute hashes modulo 2^64, letting `unsigned long long` overflow. How do experienced problem setters break this?",
    choicesUz: ["Buni sindirib bo‘lmaydi — 2^64 juda katta", "Thue–Morse kabi maxsus satrlar istalgan asos uchun to‘qnashuv beradi — katta tub modul (yoki ikkita modul) kerak", "Faqat asos juft bo‘lsa sinadi", "Uzun satrlarda toshish natijani buzadi"],
    choicesEn: ["It cannot be broken — 2^64 is huge", "Special strings like Thue–Morse collide for any base — use a large prime modulus (or two)", "It only breaks when the base is even", "Overflow corrupts results on long strings"],
    correct: 1,
    whyUz: "2^64 ga bo‘lish tuzilmaviy zaif: Thue–Morse ketma-ketligidan qurilgan ikki xil satr (uzunligi ~2000) asosdan qat’i nazar bir xil xesh beradi. Tub modul (masalan 2^61 − 1) va tasodifiy asos bu hujumni amalda imkonsiz qiladi.",
    whyEn: "Reducing modulo 2^64 is structurally weak: two different strings built from the Thue–Morse sequence (length ~2000) collide whatever the base. A prime modulus (such as 2^61 − 1) with a random base makes the attack impractical.",
  },
  {
    id: "pb-str-d3", track: "strings", tier: "deep", rating: 2050,
    uz: "10^4 ta andoza (jami uzunligi 10^6) matn (uzunligi 10^6) ichida qayerlarda uchrashini topish kerak. Qanday?",
    en: "Find where 10^4 patterns (total length 10^6) occur in a text of length 10^6. How?",
    choicesUz: ["Har andoza uchun alohida KMP — O(k · |T|)", "Aho-Corasick: barcha andozalar uchun bitta avtomat, matndan bir marta o‘tish", "Matnning har pozitsiyasidan trie bo‘ylab yurish — O(|T| · max|p|)", "Har andoza uchun `find`"],
    choicesEn: ["A separate KMP per pattern — O(k · |T|)", "Aho-Corasick: one automaton for all patterns, one pass over the text", "Walk the trie from every text position — O(|T| · max|p|)", "`find` for each pattern"],
    correct: 1,
    whyUz: "Alohida KMP 10^4 · 10^6 = 10^10. Aho-Corasick trie ga suffiks-havolalar qo‘shadi (KMP ning ko‘p andozali varianti) va matndan bir marta o‘tadi: O(Σ|p| + |T| + mosliklar soni). Trie bo‘ylab har pozitsiyadan yurish uzun andozalarda sekin.",
    whyEn: "A KMP per pattern is 10^4 · 10^6 = 10^10. Aho-Corasick adds suffix links to the trie — KMP for many patterns — and makes a single pass: O(Σ|p| + |T| + matches). Walking the trie from every position is slow when patterns are long.",
  },

  /* ========================================================== geometry (1400 → 2500) */
  {
    id: "pb-geo-b1", track: "geometry", tier: "basic", rating: 1500,
    uz: "A, B, C nuqtalari berilgan. A → B → C yo‘lida chapga yoki o‘ngga burilishni qanday aniqlaysiz?",
    en: "Given points A, B, C, how do you tell whether A → B → C turns left or right?",
    choicesUz: ["Masofalarni taqqoslab", "(B − A) × (C − A) vektor ko‘paytmasining ishorasi bilan", "Burchaklarni `atan2` bilan hisoblab", "Skalyar ko‘paytma bilan"],
    choicesEn: ["By comparing distances", "By the sign of the cross product (B − A) × (C − A)", "By computing angles with `atan2`", "By the dot product"],
    correct: 1,
    whyUz: "Cross product musbat — chapga, manfiy — o‘ngga, nol — bir to‘g‘ri chiziqda. Butun koordinatalarda bu aniq javob beradi. `atan2` — haqiqiy sonlar va yaxlitlash xatolari; geometriyada iloji boricha butun sonlarda qoling.",
    whyEn: "Positive cross product — left; negative — right; zero — collinear. With integer coordinates the answer is exact. `atan2` brings floating point and rounding; in geometry, stay in integers wherever you can.",
  },
  {
    id: "pb-geo-b2", track: "geometry", tier: "basic", rating: 1450,
    uz: "Ikki vektorning skalyar ko‘paytmasi manfiy chiqdi. Bu nimani bildiradi?",
    en: "The dot product of two vectors is negative. What does that tell you?",
    choicesUz: ["Vektorlar parallel", "Ular orasidagi burchak 90° dan katta", "Vektorlar perpendikulyar", "Vektorlardan biri nol"],
    choicesEn: ["The vectors are parallel", "The angle between them is greater than 90°", "The vectors are perpendicular", "One of them is zero"],
    correct: 1,
    whyUz: "a · b = |a| · |b| · cos θ, uzunliklar musbat, demak ishora cos θ niki. Manfiy — o‘tmas burchak, nol — to‘g‘ri burchak, musbat — o‘tkir. Nuqtadan kesmagacha masofada «proyeksiya kesma ichidami?» degan savolga aynan shu javob beradi.",
    whyEn: "a · b = |a| · |b| · cos θ, and the lengths are positive, so the sign is cos θ's. Negative — obtuse; zero — right angle; positive — acute. It answers “does the projection fall inside the segment?” in point-to-segment distance.",
  },
  {
    id: "pb-geo-b3", track: "geometry", tier: "basic", rating: 1550,
    uz: "Ko‘pburchak uchlari aylanish tartibida berilgan, u qavariq bo‘lmasligi mumkin. Yuzasini qanday topasiz?",
    en: "A polygon's vertices are given in order around it, and it may be non-convex. How do you get its area?",
    choicesUz: ["Birinchi uchdan uchburchaklarga bo‘lib, har birini Geron formulasi bilan", "Shoelace: ½ · |Σ (x_i · y_{i+1} − x_{i+1} · y_i)|", "Eng uzoq ikki uch orasidagi masofa kvadrati", "Perimetrdan hisoblab"],
    choicesEn: ["Fan-triangulate from the first vertex and use Heron's formula on each", "Shoelace: ½ · |Σ (x_i · y_{i+1} − x_{i+1} · y_i)|", "The square of the distance between the two farthest vertices", "Derive it from the perimeter"],
    correct: 1,
    whyUz: "Shoelace — ishorali uchburchak yuzalari yig‘indisi: ko‘pburchakdan tashqaridagi qismlar manfiy ishora bilan qisqarib ketadi. Geron esa doim musbat yuza beradi — qavariq bo‘lmagan shaklda noto‘g‘ri — va `sqrt` tufayli aniqlik yo‘qoladi. Butun koordinatalarda ikkilangan yuza ham butun son.",
    whyEn: "Shoelace sums signed triangle areas, so parts outside the polygon cancel out. Heron gives unsigned areas — wrong for non-convex shapes — and loses precision through `sqrt`. With integer coordinates, twice the area is an integer too.",
  },
  {
    id: "pb-geo-c1", track: "geometry", tier: "core", rating: 1700,
    uz: "Koordinatalar butun, |x|, |y| ≤ 10^9. Vektor ko‘paytmani qaysi turda hisoblaysiz?",
    en: "Coordinates are integers with |x|, |y| ≤ 10^9. In which type do you compute cross products?",
    choicesUz: ["`int`", "`long long` — ko‘paytmalar ~10^18 gacha yetadi", "`double` yetarli", "`float`"],
    choicesEn: ["`int`", "`long long` — the products reach about 10^18", "`double` is enough", "`float`"],
    correct: 1,
    whyUz: "Ayirmalar 2·10^9 gacha, ko‘paytma 4·10^18 gacha — `long long` (~9.2·10^18) ga sig‘adi. `double` ning mantissasi 53 bit (~9·10^15) — bunday sonlarda oxirgi raqamlar yo‘qoladi va ishora noto‘g‘ri chiqishi mumkin.",
    whyEn: "Differences reach 2·10^9 and products 4·10^18, which fits in `long long` (~9.2·10^18). A `double` has a 53-bit mantissa (~9·10^15), so the low digits vanish and the sign can come out wrong.",
  },
  {
    id: "pb-geo-c2", track: "geometry", tier: "core", rating: 1850,
    uz: "Ikki kesma kesishishini tekshiryapsiz: har kesma uchlari ikkinchisini o‘z ichiga olgan to‘g‘ri chiziqning ikki tomonida bo‘lishi kerak. Qaysi holat alohida tekshiruv talab qiladi?",
    en: "You test segment intersection: each segment's endpoints must lie on opposite sides of the other's line. Which case needs a separate check?",
    choicesUz: ["Kesmalar perpendikulyar bo‘lganda", "Cross ko‘paytma 0 bo‘lganda — uch nuqta bir chiziqda; unda nuqta kesma ichidami, koordinatalar oralig‘i bilan tekshiriladi", "Kesmalar uzun bo‘lganda", "Koordinatalar manfiy bo‘lganda"],
    choicesEn: ["When the segments are perpendicular", "When a cross product is 0 — collinear points; then check whether the point lies within the segment's coordinate range", "When the segments are long", "When coordinates are negative"],
    correct: 1,
    whyUz: "Qat’iy «ikki tomonda» sharti uch nuqta bir chiziqda yotgan holatni o‘tkazib yuboradi: uch tegib turgan kesmalar yoki bir chiziqdagi ustma-ust kesmalar. Cross = 0 bo‘lsa, nuqta kesmaning koordinatalar to‘rtburchagi ichidami — shuni tekshirasiz.",
    whyEn: "The strict “opposite sides” test misses collinear configurations: an endpoint touching the other segment, or overlapping collinear segments. When a cross product is 0, check whether the point lies within the segment's bounding box.",
  },
  {
    id: "pb-geo-c3", track: "geometry", tier: "core", rating: 1950,
    uz: "Uchlari butun koordinatali ko‘pburchak ichida (chegarada emas) nechta butun nuqta bor? A — yuza, B — chegaradagi butun nuqtalar soni.",
    en: "How many lattice points lie strictly inside a polygon with integer vertices? A is the area, B the number of lattice points on the boundary.",
    choicesUz: ["I = A", "I = A − B/2 + 1, bunda B = Σ gcd(|dx|, |dy|) har tomon bo‘yicha", "I = A − B", "I = A + B/2 − 1"],
    choicesEn: ["I = A", "I = A − B/2 + 1, where B = Σ gcd(|dx|, |dy|) over the sides", "I = A − B", "I = A + B/2 − 1"],
    correct: 1,
    whyUz: "Pik teoremasi: A = I + B/2 − 1, bundan I = A − B/2 + 1. (dx, dy) tomonda gcd(|dx|, |dy|) + 1 ta butun nuqta bor; uchlarni ikki marta sanamaslik uchun har tomon gcd ni qo‘shadi. Oxirgi variant — teoremaning o‘zi, lekin A uchun, I uchun emas.",
    whyEn: "Pick's theorem: A = I + B/2 − 1, so I = A − B/2 + 1. A side (dx, dy) holds gcd(|dx|, |dy|) + 1 lattice points; to avoid double-counting vertices each side contributes the gcd. The last option is the theorem itself — solved for A, not I.",
  },
  {
    id: "pb-geo-d1", track: "geometry", tier: "deep", rating: 2100,
    uz: "Eng yaqin nuqtalar jufti (divide & conquer): bo‘luvchi chiziq atrofidagi polosada har nuqtani nechta nuqta bilan solishtirish kifoya?",
    en: "Closest pair of points (divide & conquer): in the strip around the dividing line, how many points must each point be compared with?",
    choicesUz: ["Polosadagi barcha nuqtalar bilan", "y bo‘yicha saralangandagi keyingi bir nechtasi (≤ 7) bilan", "log n ta nuqta bilan", "Faqat bittasi bilan"],
    choicesEn: ["Every point in the strip", "The next few (≤ 7) in y order", "log n points", "Just one"],
    correct: 1,
    whyUz: "Ikki yarmida ham nuqtalar bir-biridan kamida d uzoqda. Shuning uchun d × 2d to‘rtburchakka ko‘pi bilan 8 ta nuqta sig‘adi — har nuqta uchun keyingi o‘zgarmas sondagi nuqtalarni tekshirish yetadi. Birlashtirish O(n), jami O(n log n).",
    whyEn: "Points in each half are at least d apart, so a d × 2d rectangle holds at most 8 of them — each point needs only a constant number of successors checked. The merge is O(n), the total O(n log n).",
  },
  {
    id: "pb-geo-d2", track: "geometry", tier: "deep", rating: 2200,
    uz: "Qavariq qobiq tayyor, unda h ta uch bor. Bir-biridan eng uzoq ikki nuqtani (diametrni) qanday topasiz?",
    en: "The convex hull is built and has h vertices. How do you find the two points farthest apart (the diameter)?",
    choicesUz: ["Barcha juftlarni tekshirish — O(h²), boshqa yo‘l yo‘q", "Rotating calipers: qarama-qarshi uchlar juftligini qobiq bo‘ylab birga aylantirish — O(h)", "Eng chap va eng o‘ng nuqtani olish", "Markazdan eng uzoq ikki nuqtani olish"],
    choicesEn: ["Check every pair — O(h²); there is no other way", "Rotating calipers: rotate antipodal pairs together around the hull — O(h)", "Take the leftmost and rightmost points", "Take the two points farthest from the centre"],
    correct: 1,
    whyUz: "Diametr faqat antipodal (qarama-qarshi) uchlar orasida bo‘ladi, bunday juftlar esa O(h) ta. Bir ko‘rsatkich qobiq bo‘ylab yursa, ikkinchisi faqat oldinga yuradi — two pointers ning geometrik ko‘rinishi. Eng chap-o‘ng juftlik ko‘p shakllarda diametr emas.",
    whyEn: "The diameter is always between antipodal vertices, and there are O(h) such pairs. As one pointer walks the hull, the other only moves forward — two pointers in geometric form. Leftmost–rightmost is not the diameter for many shapes.",
  },
  {
    id: "pb-geo-d3", track: "geometry", tier: "deep", rating: 2300,
    uz: "Nuqtalarni koordinata boshiga nisbatan qutb burchagi bo‘yicha aniq saralash kerak. `atan2` o‘rniga nima ishlatasiz?",
    en: "You must sort points by polar angle around the origin, exactly. What do you use instead of `atan2`?",
    choicesUz: ["`atan2` har doim yetarlicha aniq", "Avval yarim tekislik bo‘yicha (yuqori / pastki), keyin bir yarimda cross product bilan taqqoslash", "y / x nisbati bo‘yicha", "Koordinata boshidan masofa bo‘yicha"],
    choicesEn: ["`atan2` is always precise enough", "First split by half-plane (upper / lower), then compare within a half by cross product", "By the ratio y / x", "By distance from the origin"],
    correct: 1,
    whyUz: "Bir yarim tekislikda burchaklar farqi 180° dan kichik, shuning uchun cross product ishorasi tartibni aniq beradi — faqat butun sonlarda. `atan2` 10^9 li koordinatalarda juda yaqin burchaklarni ajrata olmaydi; y / x esa x = 0 da bo‘linadi va choraklarni aralashtiradi.",
    whyEn: "Within one half-plane angles differ by less than 180°, so the cross product's sign orders them exactly, in integers. `atan2` cannot separate nearly equal angles at coordinates near 10^9; y / x divides by zero at x = 0 and confuses quadrants.",
  },

  /* ============================================= dynamic-programming (1100 → 2400) */
  {
    id: "pb-dp-b1", track: "dynamic-programming", tier: "basic", rating: 1100,
    uz: "Zinapoyaga har safar 1 yoki 2 pog‘ona chiqiladi. 5 pog‘onali zinapoyaga necha xil usulda chiqish mumkin?",
    en: "You climb stairs 1 or 2 steps at a time. In how many ways can you climb 5 steps?",
    choicesUz: ["5", "8", "10", "13"],
    correct: 1,
    whyUz: "Oxirgi qadam 1 yoki 2 pog‘onali, shuning uchun ways(n) = ways(n−1) + ways(n−2). ways(0) = 1, ways(1) = 1 dan: 2, 3, 5, 8. Masalani «oxirgi qadam nima bo‘lgan?» deb bo‘lish — DP ning asosiy fikri.",
    whyEn: "The last move is 1 or 2 steps, so ways(n) = ways(n−1) + ways(n−2). From ways(0) = 1 and ways(1) = 1: 2, 3, 5, 8. Splitting on “what was the last move?” is the core DP idea.",
  },
  {
    id: "pb-dp-b2", track: "dynamic-programming", tier: "basic", rating: 1200,
    uz: "n × m to‘rda chap yuqori burchakdan o‘ng pastkiga faqat o‘ngga va pastga yurib boriladigan yo‘llar soni. dp[i][j] = ?",
    en: "Count paths from the top-left to the bottom-right of an n × m grid, moving only right and down. dp[i][j] = ?",
    choicesUz: ["dp[i−1][j] · dp[i][j−1]", "dp[i−1][j] + dp[i][j−1]", "max(dp[i−1][j], dp[i][j−1]) + 1", "dp[i−1][j−1] + 1"],
    correct: 1,
    whyUz: "(i, j) ga faqat yuqoridan yoki chapdan kelinadi, va bu ikki yo‘l to‘plami kesishmaydi — shuning uchun qo‘shiladi. Ko‘paytirish mustaqil tanlovlar ketma-ketligida bo‘ladi, bu yerda esa «yoki» bor.",
    whyEn: "(i, j) is reached only from above or from the left, and those two sets of paths are disjoint — so they add. Multiplication is for independent choices in sequence; here it is an “or”.",
  },
  {
    id: "pb-dp-b3", track: "dynamic-programming", tier: "basic", rating: 1250,
    uz: "Fibonachchi sonini memoizatsiya bilan (hisoblangan qiymatni eslab qolib) rekursiv hisoblash murakkabligi?",
    en: "What is the complexity of recursive Fibonacci with memoization (remembering computed values)?",
    choicesUz: ["O(2^n)", "O(n)", "O(n²)", "O(log n)"],
    correct: 1,
    whyUz: "Har f(i) faqat bir marta hisoblanadi, keyingi chaqiruvlar tayyor javobni oladi. n ta holat × O(1) o‘tish = O(n). DP murakkabligi doim shunday baholanadi: holatlar soni × har holatdagi ish.",
    whyEn: "Each f(i) is computed once; later calls reuse it. n states × O(1) work = O(n). That is how every DP is costed: number of states × work per state.",
  },
  {
    id: "pb-dp-c1", track: "dynamic-programming", tier: "core", rating: 1600,
    uz: "0/1 knapsack ni bir o‘lchamli massivda yozyapsiz. Hajm bo‘yicha sikl o‘sish tartibida yurilsa nima bo‘ladi?",
    en: "You write 0/1 knapsack with a one-dimensional array. What happens if the capacity loop runs in increasing order?",
    code: "for (auto [w, v] : items)\n    for (int c = w; c <= W; c++)\n        dp[c] = max(dp[c], dp[c - w] + v);",
    choicesUz: ["Tezroq ishlaydi", "Har buyum bir necha marta olinishi mumkin bo‘lib qoladi", "Javob doim kichrayadi", "Hech narsa o‘zgarmaydi"],
    choicesEn: ["It runs faster", "Each item can end up taken more than once", "The answer only gets smaller", "Nothing changes"],
    correct: 1,
    whyUz: "O‘sish tartibida `dp[c - w]` shu buyum bilan allaqachon yangilangan bo‘ladi — bu cheksiz (unbounded) knapsack. 0/1 uchun hajm kamayish tartibida yurilishi shart: shunda `dp[c - w]` hali eski qatorga tegishli.",
    whyEn: "Going upward, `dp[c - w]` has already been updated with the same item — that is the unbounded knapsack. For 0/1 the sweep must go downward, so `dp[c - w]` still belongs to the previous row.",
  },
  {
    id: "pb-dp-c2", track: "dynamic-programming", tier: "core", rating: 1650,
    uz: "Tangalar bilan S ni hosil qilish usullari sonini sanayapsiz, tartib farq qilmaydi ({1, 2} va {2, 1} — bitta usul). Sikllar qanday joylashadi?",
    en: "You count the ways to make S from coins, where order does not matter ({1, 2} and {2, 1} are one way). How are the loops arranged?",
    choicesUz: ["Tashqi — summa, ichki — tangalar", "Tashqi — tangalar, ichki — summa", "Farqi yo‘q", "Ikkalasi ham noto‘g‘ri, faqat 2D DP ishlaydi"],
    choicesEn: ["Outer over sums, inner over coins", "Outer over coins, inner over sums", "It makes no difference", "Both are wrong; only a 2D DP works"],
    correct: 1,
    whyUz: "Tangalar tashqarida bo‘lsa, har usul tangalar ma’lum tartibda qo‘shilgan holda bir marta sanaladi — kombinatsiyalar. Summa tashqarida bo‘lsa, har summa uchun oxirgi tanga istalgani bo‘lishi mumkin — {1, 2} va {2, 1} alohida sanaladi (permutatsiyalar).",
    whyEn: "With coins outside, every way is built with coins in a fixed order and counted once — combinations. With sums outside, any coin can be the last one for each sum, so {1, 2} and {2, 1} are counted separately — permutations.",
  },
  {
    id: "pb-dp-c3", track: "dynamic-programming", tier: "core", rating: 1700,
    uz: "Eng uzun o‘suvchi qism-ketma-ketlik (LIS) uzunligi kerak, n = 2·10^5. Usul?",
    en: "You need the length of the longest increasing subsequence, n = 2·10^5. Which method?",
    choicesUz: ["O(n²) DP yetarli", "Har uzunlik uchun eng kichik oxirgi elementni saqlab, `lower_bound` bilan yangilash — O(n log n)", "Saralab, LCS hisoblash", "Greedy: doim kattarog‘ini olish"],
    choicesEn: ["An O(n²) DP is enough", "Keep the smallest tail for each length and update with `lower_bound` — O(n log n)", "Sort, then compute the LCS", "Greedy: always take the next larger element"],
    correct: 1,
    whyUz: "O(n²) = 4·10^10 — sig‘maydi. tails[k] — uzunligi k + 1 bo‘lgan o‘suvchi ketma-ketliklarning eng kichik oxirgi elementi; bu massiv o‘suvchi, shuning uchun har yangi son uchun binary search bilan joyi topiladi. Saralab LCS olish ham O(n²).",
    whyEn: "O(n²) = 4·10^10 does not fit. tails[k] is the smallest possible last element of an increasing subsequence of length k + 1; it is increasing, so each new value finds its slot by binary search. Sorting and taking the LCS is O(n²) too.",
  },
  {
    id: "pb-dp-d1", track: "dynamic-programming", tier: "deep", rating: 1950,
    uz: "Interval DP: dp[l][r] faqat [l, r] ichidagi kichikroq intervallarga bog‘liq. Hisoblash tartibi qanday bo‘lishi kerak?",
    en: "Interval DP: dp[l][r] depends only on smaller intervals inside [l, r]. In what order must you compute it?",
    choicesUz: ["l = 0..n−1 va r = l..n−1, ikkalasi ham o‘sish tartibida", "Interval uzunligi bo‘yicha o‘sish tartibida", "Tartib muhim emas", "r kamayish tartibida, l ixtiyoriy"],
    choicesEn: ["l = 0..n−1 and r = l..n−1, both increasing", "In increasing order of interval length", "The order does not matter", "r decreasing, l in any order"],
    correct: 1,
    whyUz: "dp[l][r] uchun dp[l+1][r] kabi qiymatlar kerak. l o‘sish tartibida yurilsa, dp[l+1][…] hali hisoblanmagan bo‘ladi. Uzunlik bo‘yicha yurish esa har bir ichki interval oldinroq tayyor bo‘lishini kafolatlaydi. (l ni kamayish, r ni o‘sish tartibida yurish ham ishlaydi.)",
    whyEn: "dp[l][r] needs values like dp[l+1][r]. With l increasing, dp[l+1][…] is not computed yet. Going by length guarantees every inner interval is ready first. (l decreasing with r increasing also works.)",
  },
  {
    id: "pb-dp-d2", track: "dynamic-programming", tier: "deep", rating: 2100,
    uz: "[L, R] oralig‘ida (R ≤ 10^18) raqamlari yig‘indisi 10 ga bo‘linadigan sonlar nechta?",
    en: "How many numbers in [L, R] (R ≤ 10^18) have a digit sum divisible by 10?",
    choicesUz: ["Barcha sonlarni aylanib chiqish", "f(R) − f(L − 1), bunda f — raqamlar bo‘yicha DP: holat (pozitsiya, yig‘indi mod 10, chegaraga tegib turibmizmi)", "Formula: (R − L + 1) / 10 aniq", "Binary search"],
    choicesEn: ["Iterate over every number", "f(R) − f(L − 1), where f is a digit DP with state (position, sum mod 10, still tight to the bound)", "Exactly (R − L + 1) / 10 by formula", "Binary search"],
    correct: 1,
    whyUz: "10^18 ta sonni aylanib bo‘lmaydi. Digit DP sonni raqamma-raqam quradi: 19 pozitsiya × 10 qoldiq × 2 «tight» holati — atigi bir necha yuz holat. «tight» bayrog‘i hozirgacha R ning prefiksi bilan tengmi — keyingi raqam cheklanganmi — shuni saqlaydi. Taxminiy formula esa oraliq chetlarida aniq emas.",
    whyEn: "You cannot iterate 10^18 numbers. A digit DP builds the number digit by digit: 19 positions × 10 residues × 2 tight flags — a few hundred states. The tight flag records whether the prefix so far equals R's, which limits the next digit. The rough formula is off at the range ends.",
  },
  {
    id: "pb-dp-d3", track: "dynamic-programming", tier: "deep", rating: 2300,
    uz: "dp[i] = min over j < i ( dp[j] + b[j] · a[i] ), n = 10^6, b[j] monoton kamayadi. O(n²) sig‘maydi. Nima qilasiz?",
    en: "dp[i] = min over j < i of ( dp[j] + b[j] · a[i] ), n = 10^6, with b[j] decreasing. O(n²) does not fit. What do you do?",
    choicesUz: ["Boshqa yo‘l yo‘q, O(n²)", "Convex Hull Trick: har j — y = b[j] · x + dp[j] to‘g‘ri chizig‘i, dp[i] — x = a[i] nuqtadagi minimum", "Segment tree da dp[j] minimumini saqlash", "Greedy: eng kichik dp[j] ni olish"],
    choicesEn: ["There is no way around O(n²)", "Convex Hull Trick: each j is the line y = b[j] · x + dp[j], and dp[i] is the minimum at x = a[i]", "Keep the minimum dp[j] in a segment tree", "Greedy: take the smallest dp[j]"],
    correct: 1,
    whyUz: "O‘tish a[i] ga ko‘paytirilgan hadni o‘z ichiga oladi, shuning uchun eng yaxshi j a[i] ga bog‘liq — oddiy minimum yetmaydi. Chiziqlar qiyaligi monoton bo‘lgani uchun ular pastki qobiqqa tartib bilan qo‘shiladi; so‘rov binary search bilan O(log n) yoki a[i] ham monoton bo‘lsa amortizatsiyalangan O(1).",
    whyEn: "The transition has a term multiplied by a[i], so the best j depends on a[i] — a plain minimum is not enough. With monotone slopes the lines join the lower hull in order; a query costs O(log n) by binary search, or amortised O(1) if a[i] is monotone too.",
  },

  /* ============================================================= trees (1100 → 2400) */
  {
    id: "pb-tree-b1", track: "trees", tier: "basic", rating: 1150,
    uz: "Graf bog‘langan, n ta tugun va aynan n − 1 ta qirra bor. Bu graf haqida nima deyish mumkin?",
    en: "A connected graph has n nodes and exactly n − 1 edges. What can you say about it?",
    choicesUz: ["Albatta sikl bor", "Bu daraxt — sikl yo‘q", "Bu faqat zanjir (yo‘l) bo‘lishi mumkin", "Aniqlab bo‘lmaydi"],
    choicesEn: ["It must contain a cycle", "It is a tree — there are no cycles", "It can only be a path", "Nothing can be concluded"],
    correct: 1,
    whyUz: "Bog‘langan grafga n − 1 ta qirra minimal zarur miqdor; sikl bo‘lsa, undan bitta qirrani olib tashlab ham bog‘langanlikni saqlash mumkin bo‘lardi — ya’ni n − 2 ta yetardi, bu mumkin emas. Daraxt yulduz, zanjir yoki istalgan shaklda bo‘lishi mumkin.",
    whyEn: "n − 1 edges is the minimum a connected graph needs; with a cycle you could drop one edge and stay connected on n − 2, which is impossible. A tree can be a star, a path or any other shape.",
  },
  {
    id: "pb-tree-b2", track: "trees", tier: "basic", rating: 1250,
    uz: "Har tugun subtree'sining o‘lchami sz[v] ni DFS bilan hisoblaysiz. Qaysi formula va qachon?",
    en: "You compute each node's subtree size sz[v] with DFS. Which formula, and when?",
    choicesUz: ["sz[v] = sz[ota] − 1, bolaga kirishdan oldin", "sz[v] = 1 + barcha bolalar sz yig‘indisi, bolalar tugagandan keyin", "sz[v] = chuqurlik[v] + 1", "sz[v] = qo‘shnilar soni"],
    choicesEn: ["sz[v] = sz[parent] − 1, before visiting the children", "sz[v] = 1 + the sum of the children's sz, after the children finish", "sz[v] = depth[v] + 1", "sz[v] = the number of neighbours"],
    correct: 1,
    whyUz: "Subtree o‘lchami bolalarnikiga bog‘liq, shuning uchun u pastdan yuqoriga — DFS dan qaytishda (post-order) hisoblanadi. Chuqurlik esa aksincha yuqoridan pastga, kirishda hisoblanadi. Qaysi qiymat qaysi yo‘nalishda oqishini ajratish — tree DP ning asosi.",
    whyEn: "A subtree's size depends on its children's, so it flows bottom-up — computed on the way out of DFS (post-order). Depth flows the other way, top-down, on the way in. Knowing which way each value flows is the basis of tree DP.",
  },
  {
    id: "pb-tree-b3", track: "trees", tier: "basic", rating: 1300,
    uz: "n = 10^6 tugunli daraxt uzun zanjir shaklida. Rekursiv DFS da qanday xavf bor?",
    en: "A tree with n = 10^6 nodes is shaped like a long chain. What is the risk with a recursive DFS?",
    choicesUz: ["Xavf yo‘q, DFS O(n)", "Rekursiya chuqurligi 10^6 — stek to‘lib, dastur yiqilishi mumkin; iterativ DFS yoki BFS tartibi kerak", "DFS O(n²) bo‘lib qoladi", "Faqat xotira ko‘proq ketadi, lekin ishlaydi"],
    choicesEn: ["No risk; DFS is O(n)", "Recursion depth reaches 10^6 — the stack can overflow and crash; use an iterative DFS or a BFS order", "DFS becomes O(n²)", "It uses more memory but works"],
    correct: 1,
    whyUz: "Vaqt O(n) ligicha qoladi, muammo — chuqurlik. Har rekursiv chaqiruv stekda joy oladi, ko‘p tizimlarda stek bir necha MB xolos. Aniq stek bilan iterativ DFS yoki BFS tartibida ota-bola bo‘yicha teskari yurish bu xavfni yo‘qotadi.",
    whyEn: "Time stays O(n); the problem is depth. Each recursive call takes stack space, and on many systems the stack is only a few MB. An iterative DFS with an explicit stack, or processing nodes in reverse BFS order, removes the risk.",
  },
  {
    id: "pb-tree-c1", track: "trees", tier: "core", rating: 1600,
    uz: "Daraxt diametrini ikki BFS bilan topish: birinchi BFS (ixtiyoriy tugundan) nimani beradi?",
    en: "Finding a tree's diameter with two BFS runs: what does the first one (from any node) give you?",
    choicesUz: ["Diametrning o‘zini", "Qandaydir diametrning bir uchi bo‘lgan tugunni", "Daraxt markazini", "Barglar sonini"],
    choicesEn: ["The diameter itself", "A node that is an endpoint of some diameter", "The centre of the tree", "The number of leaves"],
    correct: 1,
    whyUz: "Istalgan tugundan eng uzoqdagi tugun albatta biror diametrning uchi bo‘ladi — buni isbotlash mumkin. Ikkinchi BFS o‘sha uchdan boshlanadi va eng uzoq masofa diametr uzunligi bo‘ladi. Faqat manfiy bo‘lmagan og‘irliklarda ishlaydi.",
    whyEn: "The farthest node from any start is provably an endpoint of some diameter. The second BFS starts there, and its farthest distance is the diameter. This only holds for non-negative weights.",
  },
  {
    id: "pb-tree-c2", track: "trees", tier: "core", rating: 1700,
    uz: "LCA ni binary lifting bilan topasiz: up[k][v] — v dan 2^k qadam yuqoridagi ajdod. Xotira va har so‘rov qancha?",
    en: "You find LCA with binary lifting: up[k][v] is v's ancestor 2^k steps up. What are the memory and per-query costs?",
    choicesUz: ["O(n) xotira, O(1) so‘rov", "O(n log n) xotira, O(log n) so‘rov", "O(n²) xotira, O(1) so‘rov", "O(n) xotira, O(n) so‘rov"],
    choicesEn: ["O(n) memory, O(1) per query", "O(n log n) memory, O(log n) per query", "O(n²) memory, O(1) per query", "O(n) memory, O(n) per query"],
    correct: 1,
    whyUz: "Har tugun uchun log n ta ajdod saqlanadi. So‘rovda avval chuqurroq tugunni bir xil chuqurlikka ko‘tarasiz, keyin k ni kattasidan kichigiga qarab ikkalasini ajdodlari farq qilguncha ko‘tarasiz — har bosqichda bitta qadam, jami O(log n).",
    whyEn: "Each node stores log n ancestors. A query lifts the deeper node to the same depth, then, for k from large to small, lifts both while their ancestors differ — one step per level, O(log n) in total.",
  },
  {
    id: "pb-tree-c3", track: "trees", tier: "core", rating: 1750,
    uz: "So‘rovlar: «v subtree'sidagi barcha tugunlarga x qo‘sh» va «v subtree'si yig‘indisi». Daraxtni qanday qilib massivga aylantirasiz?",
    en: "Queries: “add x to every node in v's subtree” and “sum of v's subtree”. How do you turn the tree into an array?",
    choicesUz: ["BFS tartibida yozish", "Euler tour: DFS kirish vaqti tin bo‘yicha — har subtree [tin[v], tout[v]] uzluksiz oraliq bo‘ladi", "Tugunlarni raqami bo‘yicha", "Barglarni boshiga, ildizni oxiriga"],
    choicesEn: ["Write the nodes in BFS order", "An Euler tour by DFS entry time tin — every subtree becomes the contiguous range [tin[v], tout[v]]", "By node number", "Leaves first, root last"],
    correct: 1,
    whyUz: "DFS subtree'ni to‘liq aylanib chiqmaguncha undan chiqmaydi, shuning uchun subtree tugunlari kirish vaqtlari bo‘yicha ketma-ket turadi. Subtree so‘rovi oraliq so‘roviga aylanadi va segment tree yoki Fenwick bilan yechiladi. BFS tartibida subtree bo‘laklarga bo‘linib ketadi.",
    whyEn: "DFS does not leave a subtree until it has visited all of it, so the subtree's entry times are consecutive. A subtree query becomes a range query for a segment tree or Fenwick. In BFS order a subtree is scattered.",
  },
  {
    id: "pb-tree-d1", track: "trees", tier: "deep", rating: 2000,
    uz: "Har tugun uchun undan barcha tugunlargacha masofalar yig‘indisi kerak, n = 2·10^5. ans[ildiz] va sz[] tayyor. Bola c ga o‘tganda ans[c] qanday topiladi?",
    en: "For every node you need the sum of distances to all nodes, n = 2·10^5. ans[root] and sz[] are known. Moving to a child c, how do you get ans[c]?",
    choicesUz: ["Har tugundan BFS — O(n²)", "ans[c] = ans[v] + (n − sz[c]) − sz[c]", "ans[c] = ans[v] − 1", "ans[c] = ans[v] · sz[c] / n"],
    choicesEn: ["A BFS from every node — O(n²)", "ans[c] = ans[v] + (n − sz[c]) − sz[c]", "ans[c] = ans[v] − 1", "ans[c] = ans[v] · sz[c] / n"],
    correct: 1,
    whyUz: "v dan c ga o‘tganda c subtree'sidagi sz[c] ta tugun bittaga yaqinlashadi, qolgan n − sz[c] tasi bittaga uzoqlashadi. Bu «rerooting»: ikki DFS — biri pastga sz ni, ikkinchisi yuqoridan javobni tarqatadi — jami O(n).",
    whyEn: "Moving from v to c brings the sz[c] nodes of c's subtree one step closer and pushes the other n − sz[c] one step away. That is rerooting: two DFS passes — one gathers sz, the other pushes answers down — O(n) in total.",
  },
  {
    id: "pb-tree-d2", track: "trees", tier: "deep", rating: 2100,
    uz: "Har subtree'dagi turli ranglar sonini topish uchun bolalarning `set`larini birlashtiryapsiz. Doim kichik to‘plamni kattasiga qo‘shish nima beradi?",
    en: "To count distinct colours in every subtree you merge the children's `set`s. What does always merging the smaller set into the larger give you?",
    choicesUz: ["Hech narsa — baribir O(n²)", "Har element ko‘pi bilan O(log n) marta ko‘chadi — jami O(n log² n)", "O(n) — har element bir marta ko‘chadi", "Faqat xotirani tejaydi"],
    choicesEn: ["Nothing — it is still O(n²)", "Each element moves at most O(log n) times — O(n log² n) in total", "O(n) — each element moves once", "It only saves memory"],
    correct: 1,
    whyUz: "Element ko‘chirilganda u tushgan to‘plam avvalgisidan kamida ikki barobar katta bo‘ladi. To‘plam n dan oshmaydi, demak bitta element ko‘pi bilan log n marta ko‘chadi. Har ko‘chirish `set` da O(log n) — jami O(n log² n). Tartibsiz birlashtirish zanjirda O(n²) beradi.",
    whyEn: "Whenever an element moves, the set it joins is at least twice the size of the one it left. Sets never exceed n, so an element moves at most log n times. Each move costs O(log n) in a `set` — O(n log² n) overall. Merging in arbitrary order is O(n²) on a chain.",
  },
  {
    id: "pb-tree-d3", track: "trees", tier: "deep", rating: 2250,
    uz: "Uzunligi aniq k bo‘lgan yo‘llar sonini sanash kerak, n = 2·10^5. Klassik usul va nega u tez?",
    en: "Count the paths of length exactly k, n = 2·10^5. What is the classic method, and why is it fast?",
    choicesUz: ["Har tugundan DFS — O(n²)", "Centroid decomposition: har yo‘l o‘z centroidi orqali bir marta sanaladi, har tugun esa O(log n) darajada qatnashadi", "Heavy-light decomposition", "Tree diametri bo‘yicha"],
    choicesEn: ["A DFS from every node — O(n²)", "Centroid decomposition: each path is counted once at its centroid, and each node takes part in O(log n) levels", "Heavy-light decomposition", "Along the tree's diameter"],
    correct: 1,
    whyUz: "Centroid olib tashlansa, har bo‘lak n/2 dan kichik bo‘ladi — shuning uchun bo‘lish chuqurligi log n. Har darajada centroid orqali o‘tadigan yo‘llar chuqurliklar sanog‘i bilan chiziqli vaqtda sanaladi. Jami O(n log n). HLD yo‘l so‘rovlari uchun, sanash uchun emas.",
    whyEn: "Removing a centroid leaves pieces smaller than n/2, so the decomposition is log n deep. On each level, paths through the centroid are counted in linear time with depth counts. O(n log n) in total. HLD is for path queries, not for counting.",
  },

  /* ====================================================== advanced-cp (1900 → 3000) */
  {
    id: "pb-adv-b1", track: "advanced-cp", tier: "basic", rating: 1950,
    uz: "Nim o‘yini: uyumlarda 3, 4 va 5 ta tosh. Navbatda birinchi o‘yinchi. U to‘g‘ri o‘ynasa yutadimi?",
    en: "A game of Nim with piles of 3, 4 and 5 stones. The first player moves. Do they win with correct play?",
    choicesUz: ["Ha — 3 ⊕ 4 ⊕ 5 = 2 ≠ 0", "Yo‘q — 3 ⊕ 4 ⊕ 5 = 0", "Ha — toshlar yig‘indisi juft", "Yo‘q — uyumlar soni toq"],
    choicesEn: ["Yes — 3 ⊕ 4 ⊕ 5 = 2 ≠ 0", "No — 3 ⊕ 4 ⊕ 5 = 0", "Yes — the total number of stones is even", "No — the number of piles is odd"],
    correct: 0,
    whyUz: "Nim da holat yutqazuvchi faqat uyumlar XOR i 0 bo‘lganda. 3 ⊕ 4 = 7, 7 ⊕ 5 = 2 — nol emas, demak birinchi o‘yinchi XOR ni 0 ga keltiradigan yurish topa oladi (masalan 3 li uyumdan 2 ta tosh olib). Yig‘indi yoki uyumlar soni hech narsani hal qilmaydi.",
    whyEn: "A Nim position is losing exactly when the piles XOR to 0. 3 ⊕ 4 = 7 and 7 ⊕ 5 = 2 — not zero, so the first player has a move restoring XOR 0 (take 2 from the pile of 3). The sum and the pile count decide nothing.",
  },
  {
    id: "pb-adv-b2", track: "advanced-cp", tier: "basic", rating: 2000,
    uz: "Mo algoritmi: massiv statik, q ta so‘rov oldindan ma’lum, oynaga element qo‘shish/olish O(1). Umumiy murakkablik?",
    en: "Mo's algorithm: a static array, q queries known in advance, adding/removing an element costs O(1). The total complexity?",
    choicesUz: ["O(q · n)", "O((n + q) · √n)", "O(q log n)", "O(n log n + q)"],
    correct: 1,
    whyUz: "So‘rovlar √n uzunlikdagi bloklar bo‘yicha (l ning bloki, keyin r) saralanadi. Har blok ichida r faqat oldinga yuradi — O(n) bir blokka, √n blok — O(n√n). l har so‘rovda ko‘pi bilan √n siljiydi — O(q√n). Tartibsiz yurish esa O(q · n).",
    whyEn: "Queries are sorted by l's block of size √n, then by r. Within a block r only moves forward — O(n) per block, √n blocks, O(n√n). l moves at most √n per query — O(q√n). An unsorted walk would be O(q · n).",
  },
  {
    id: "pb-adv-b3", track: "advanced-cp", tier: "basic", rating: 2100,
    uz: "Har so‘rov [l, r] dagi turli qiymatlar sonini so‘raydi; massiv statik, barcha so‘rovlar oldindan ma’lum. Mo dan tezroq yondashuv?",
    en: "Each query asks for the number of distinct values in [l, r]; the array is static and all queries are known up front. What beats Mo?",
    choicesUz: ["Har so‘rovda `set` bilan oraliqni aylanish", "So‘rovlarni r bo‘yicha saralab, har qiymatning faqat oxirgi uchrashini Fenwick tree da belgilab borish — O((n + q) log n)", "Har so‘rovga binary search", "Prefiks yig‘indilar"],
    choicesEn: ["Walk each range with a `set`", "Sort queries by r and keep only each value's last occurrence marked in a Fenwick tree — O((n + q) log n)", "A binary search per query", "Prefix sums"],
    correct: 1,
    whyUz: "r o‘ngga siljiganda a[r] ning oldingi uchrashi o‘chiriladi va r belgilanadi. Endi [l, r] dagi belgilar soni — turli qiymatlar soni, bu esa Fenwick da prefiks so‘rovi. So‘rovlarning oldindan ma’lumligi — oflayn ishlashga ruxsat.",
    whyEn: "As r advances, a[r]'s previous occurrence is unmarked and r is marked. The marks inside [l, r] now count distinct values — a Fenwick prefix query. Knowing the queries up front is permission to go offline.",
  },
  {
    id: "pb-adv-c1", track: "advanced-cp", tier: "core", rating: 2200,
    uz: "Darajasi n = 10^5 bo‘lgan ikki ko‘phadni ko‘paytirish kerak. Qanday?",
    en: "Multiply two polynomials of degree n = 10^5. How?",
    choicesUz: ["Oddiy ko‘paytirish — O(n²)", "FFT yoki NTT — O(n log n)", "Karatsuba — O(n log n)", "Tez daraja"],
    choicesEn: ["Schoolbook multiplication — O(n²)", "FFT or NTT — O(n log n)", "Karatsuba — O(n log n)", "Fast exponentiation"],
    correct: 1,
    whyUz: "O(n²) = 10^10. FFT ko‘phadlarni birlik ildizlaridagi qiymatlarga o‘tkazadi, u yerda ko‘paytirish koeffitsiyentma-koeffitsiyent, keyin qaytaradi. Koeffitsiyentlar mod 998244353 bo‘yicha kerak bo‘lsa — NTT, yaxlitlash xatosiz. Karatsuba O(n^1.58).",
    whyEn: "O(n²) is 10^10. FFT moves polynomials to values at roots of unity, multiplies pointwise and transforms back. For coefficients modulo 998244353, NTT does the same without rounding error. Karatsuba is O(n^1.58).",
  },
  {
    id: "pb-adv-c2", track: "advanced-cp", tier: "core", rating: 2300,
    uz: "Daraxtda «u dan v gacha yo‘ldagi qiymatlar yig‘indisi» va «tugun qiymatini o‘zgartir» so‘rovlari. Heavy-Light decomposition bilan har so‘rov qancha?",
    en: "On a tree: “sum of values on the path from u to v” and “change a node's value”. With Heavy-Light decomposition, what does each query cost?",
    choicesUz: ["O(n)", "O(log² n) — yo‘l O(log n) ta zanjirga bo‘linadi, har biri segment tree da O(log n)", "O(1)", "O(√n)"],
    choicesEn: ["O(n)", "O(log² n) — the path splits into O(log n) chains, each O(log n) in the segment tree", "O(1)", "O(√n)"],
    correct: 1,
    whyUz: "Yengil qirradan o‘tganda subtree o‘lchami kamida ikki barobar kichrayadi, shuning uchun istalgan yo‘lda O(log n) ta yengil qirra — ya’ni O(log n) ta og‘ir zanjir bor. Har zanjir segment tree da uzluksiz oraliq.",
    whyEn: "Crossing a light edge at least halves the subtree size, so any path has O(log n) light edges — O(log n) heavy chains. Each chain is a contiguous range in the segment tree.",
  },
  {
    id: "pb-adv-c3", track: "advanced-cp", tier: "core", rating: 2350,
    uz: "Onlayn so‘rovlar (oldingi javobga bog‘liq): statik massivning [l, r] oralig‘idagi k-kichik element. Klassik yechim?",
    en: "Online queries (each depends on the previous answer): the k-th smallest element of [l, r] in a static array. The classic solution?",
    choicesUz: ["Mo algoritmi", "Prefikslar bo‘yicha persistent segment tree (qiymatlar ustida): r va l − 1 versiyalari farqi bo‘yicha pastga tushish", "Sparse table", "Har so‘rovga `nth_element`"],
    choicesEn: ["Mo's algorithm", "A persistent segment tree over values, one version per prefix: descend on the difference of versions r and l − 1", "A sparse table", "`nth_element` for each query"],
    correct: 1,
    whyUz: "i-versiya — a[0..i] dagi qiymatlar sanog‘i. Ikki versiya ayirmasi [l, r] dagi sanoqni beradi, va chap bolada k tadan ko‘p bo‘lsa chapga, aks holda o‘ngga tushasiz — O(log n). Har versiya faqat O(log n) yangi tugun qo‘shadi. Mo esa oflayn — onlayn so‘rovda ishlamaydi.",
    whyEn: "Version i counts the values in a[0..i]. The difference of two versions counts [l, r]; descend left if the left child holds at least k, right otherwise — O(log n). Each version adds only O(log n) nodes. Mo is offline and cannot handle online queries.",
  },
  {
    id: "pb-adv-d1", track: "advanced-cp", tier: "deep", rating: 2400,
    uz: "n = 20 bit. Har mask uchun uning barcha submaskalari bo‘yicha f yig‘indisi kerak. 3^n ≈ 3.5·10^9 — sekin. Tezroq usul?",
    en: "n = 20 bits. For every mask you need the sum of f over all its submasks. 3^n ≈ 3.5·10^9 is too slow. What is faster?",
    choicesUz: ["Submaskalarni `(s − 1) & m` bilan aylanish", "SOS DP: bitlar bo‘yicha birma-bir yig‘ish — O(n · 2^n)", "Inclusion–exclusion har mask uchun", "Bu masalani 3^n dan tez yechib bo‘lmaydi"],
    choicesEn: ["Iterate submasks with `(s − 1) & m`", "SOS DP: accumulate one bit at a time — O(n · 2^n)", "Inclusion–exclusion per mask", "It cannot be done faster than 3^n"],
    correct: 1,
    whyUz: "Har bit i uchun: agar mask da i-bit bor bo‘lsa, F[mask] += F[mask ^ (1 << i)]. Bu ko‘p o‘lchamli prefiks yig‘indi — har o‘lcham (bit) bo‘yicha alohida yig‘iladi. 20 · 2^20 ≈ 2·10^7.",
    whyEn: "For each bit i: if mask has bit i, F[mask] += F[mask ^ (1 << i)]. It is a multidimensional prefix sum, accumulated one dimension (bit) at a time. 20 · 2^20 ≈ 2·10^7.",
  },
  {
    id: "pb-adv-d2", track: "advanced-cp", tier: "deep", rating: 2500,
    uz: "To‘g‘ri chiziqlar ixtiyoriy qiyalik tartibida qo‘shiladi, orada «x nuqtada eng kichik qiymat» so‘raladi. Qaysi tuzilma?",
    en: "Lines are added with slopes in arbitrary order, and in between you are asked for the minimum value at a point x. Which structure?",
    choicesUz: ["Oddiy Convex Hull Trick (deque bilan)", "Li Chao tree — har qo‘shish va so‘rov O(log C)", "Segment tree da chiziqlar ro‘yxati", "Har so‘rovda barcha chiziqlarni tekshirish"],
    choicesEn: ["Plain Convex Hull Trick with a deque", "A Li Chao tree — O(log C) per insertion and query", "A segment tree holding lists of lines", "Check every line at each query"],
    correct: 1,
    whyUz: "Deque'li CHT chiziqlar qiyalik bo‘yicha tartibda kelishini talab qiladi. Li Chao tree x oralig‘i bo‘yicha segment tree: har tugunda o‘rtada yaxshiroq chiziq qoladi, yomoni faqat bitta yarmiga tushadi. Tartib shart emas, faqat x lar oralig‘i ma’lum bo‘lishi kerak.",
    whyEn: "Deque CHT needs lines to arrive in slope order. A Li Chao tree is a segment tree over x: each node keeps the line better at its midpoint and pushes the other into one half only. No order is required — just a known range of x.",
  },
  {
    id: "pb-adv-d3", track: "advanced-cp", tier: "deep", rating: 2500,
    uz: "Massivda 2·10^5 marta «[l, r] bo‘lagini teskari aylantir» amali va oraliq so‘rovlari. Qaysi tuzilma?",
    en: "An array receives 2·10^5 operations “reverse the segment [l, r]” plus range queries. Which structure?",
    choicesUz: ["Oddiy massiv, `reverse` bilan", "Implicit treap: bo‘lakni split bilan ajratib, lazy «teskari» bayrog‘ini qo‘yib, merge bilan qaytarish", "Lazy segment tree", "Sparse table"],
    choicesEn: ["A plain array with `reverse`", "An implicit treap: split out the segment, set a lazy “reversed” flag, merge it back", "A lazy segment tree", "A sparse table"],
    correct: 1,
    whyUz: "`reverse` har safar O(n). Segment tree elementlar joyini almashtira olmaydi — tuzilmasi qat’iy. Implicit treap da kalit — pozitsiya, u daraxtdagi o‘rnidan kelib chiqadi, shuning uchun split/merge bilan istalgan bo‘lakni O(log n) da ajratib, bolalarini dangasa almashtirish mumkin.",
    whyEn: "`reverse` costs O(n) every time. A segment tree cannot move elements — its shape is fixed. In an implicit treap the key is the position, implied by the node's place in the tree, so split/merge isolates any segment in O(log n) and its children can be swapped lazily.",
  },
];
