/* Level-check questions: the first five sections of the roadmap.
 * See placement-bank.ts for what makes a question good enough to be here. */

import type { PlacementQuestion } from "./placement-bank";

export const basicsQuestions: PlacementQuestion[] = [
  /* ================================================ programming-basics (0 → 900) */
  {
    id: "pb-basics-b1", track: "programming-basics", tier: "basic", rating: 800,
    uz: "`int` turidagi o‘zgaruvchiga 3 000 000 000 qiymatini bersangiz nima bo‘ladi?",
    en: "What happens if you store 3,000,000,000 in an `int`?",
    choicesUz: ["Kompilyatsiya xatosi bo‘ladi", "Qiymat toshib ketadi va boshqa son chiqadi", "Avtomatik `long long` ga o‘tadi", "Dastur ishlamay to‘xtaydi"],
    choicesEn: ["It fails to compile", "It overflows and becomes a different number", "It is promoted to `long long`", "The program crashes"],
    correct: 1,
    whyUz: "32-bitli `int` ~2.1 milliardgacha sig‘adi. Undan kattasi jimgina toshib ketadi — na xato, na ogohlantirish. Shuning uchun CP da katta sonlar uchun `long long` ishlatiladi.",
    whyEn: "A 32-bit `int` tops out near 2.1 billion. Anything larger wraps silently — no error, no warning. That is why competitive code reaches for `long long`.",
  },
  {
    id: "pb-basics-b2", track: "programming-basics", tier: "basic", rating: 800,
    uz: "Bu kod nima chiqaradi?",
    en: "What does this print?",
    code: "int a = 7, b = 2;\ncout << a / b << \" \" << a % b;",
    choicesUz: ["3.5 1", "3 1", "3 0", "4 1"],
    correct: 1,
    whyUz: "Ikki `int` ni bo‘lish butun bo‘lish: kasr qismi tashlab yuboriladi, 7 / 2 = 3. `%` esa qoldiq: 7 = 2·3 + 1. Kasr natija kerak bo‘lsa, bittasini `double` ga aylantirish kerak.",
    whyEn: "Dividing two `int`s is integer division: the fraction is dropped, 7 / 2 = 3. `%` is the remainder: 7 = 2·3 + 1. For a fractional result one operand must be a `double`.",
  },
  {
    id: "pb-basics-b3", track: "programming-basics", tier: "basic", rating: 850,
    uz: "`a` massivida n ta element bor. Bu siklda nima xato?",
    en: "The array `a` holds n elements. What is wrong with this loop?",
    code: "for (int i = 0; i <= n; i++)\n    s += a[i];",
    choicesUz: ["Oxirgi element qo‘shilmay qoladi", "`a[n]` o‘qiladi — bu massivdan tashqarida, natija oldindan aytib bo‘lmaydi", "Birinchi element ikki marta qo‘shiladi", "Hech qanday xato yo‘q"],
    choicesEn: ["The last element is never added", "It reads `a[n]` — outside the array, so the result is unpredictable", "The first element is added twice", "Nothing is wrong"],
    correct: 1,
    whyUz: "Indekslar 0 dan n−1 gacha. `i <= n` bitta ortiqcha qadam qiladi va massivdan tashqaridagi xotirani o‘qiydi. C++ buni tekshirmaydi — dastur ba’zan ishlaydi, ba’zan noto‘g‘ri javob beradi. Bu «off-by-one» xatosi.",
    whyEn: "Indices run from 0 to n−1. `i <= n` takes one step too many and reads memory past the array. C++ does not check this — the program sometimes works and sometimes answers wrong. It is the classic off-by-one.",
  },
  {
    id: "pb-basics-c1", track: "programming-basics", tier: "core", rating: 850,
    uz: "Bu kod nima chiqaradi?",
    en: "What does this print?",
    code: "void add(vector<int> v) { v.push_back(1); }\n\nint main() {\n    vector<int> a;\n    add(a);\n    add(a);\n    cout << a.size();\n}",
    choicesUz: ["0", "1", "2", "Kompilyatsiya xatosi"],
    choicesEn: ["0", "1", "2", "A compile error"],
    correct: 0,
    whyUz: "`vector<int> v` — qiymat bo‘yicha uzatish: funksiya `a` ning nusxasini oladi va nusxani o‘zgartiradi. `a` ga tegmaydi. O‘zgarishi uchun `vector<int>& v` (havola) kerak — bu nusxalash vaqtini ham tejaydi.",
    whyEn: "`vector<int> v` is pass-by-value: the function gets a copy of `a` and changes the copy. `a` is untouched. To change it you need `vector<int>& v` — a reference, which also saves the cost of copying.",
  },
  {
    id: "pb-basics-c2", track: "programming-basics", tier: "core", rating: 850,
    uz: "`double x = 0.1 + 0.2;` dan keyin `x == 0.3` sharti nima qaytaradi?",
    en: "After `double x = 0.1 + 0.2;`, what does `x == 0.3` evaluate to?",
    choicesUz: ["`true`", "`false`", "Kompilyatorga bog‘liq, lekin odatda `true`", "Kompilyatsiya xatosi"],
    choicesEn: ["`true`", "`false`", "Compiler-dependent, but usually `true`", "A compile error"],
    correct: 1,
    whyUz: "0.1 va 0.2 ikkilik sanoq tizimida aniq ifodalanmaydi, yig‘indi 0.30000000000000004 bo‘ladi. Haqiqiy sonlarni `==` bilan emas, `fabs(x - y) < eps` bilan taqqoslang — yoki umuman butun sonlarda qoling.",
    whyEn: "0.1 and 0.2 have no exact binary representation; the sum is 0.30000000000000004. Compare doubles with `fabs(x - y) < eps`, not `==` — or stay in integers altogether.",
  },
  {
    id: "pb-basics-c3", track: "programming-basics", tier: "core", rating: 900,
    uz: "10^6 ta sonni har birini alohida qatorga `cout << x << endl;` bilan chiqaryapsiz va vaqt limitidan chiqyapsiz. Asosiy sabab?",
    en: "You print 10^6 numbers, one per line, with `cout << x << endl;` and exceed the time limit. The main cause?",
    choicesUz: ["`cout` o‘zi sekin, faqat `printf` tez", "`endl` har safar buferni majburan bo‘shatadi (flush) — `'\\n'` yozish kerak", "10^6 ta qatorni bir soniyada chiqarib bo‘lmaydi", "Sonlarni avval stringga aylantirish kerak"],
    choicesEn: ["`cout` itself is slow, only `printf` is fast", "`endl` forces a buffer flush every time — write `'\\n'` instead", "10^6 lines cannot be printed in a second", "The numbers must be converted to strings first"],
    correct: 1,
    whyUz: "`endl` = yangi qator + flush. Million marta flush — million marta tizimga murojaat. `'\\n'` ishlating va boshida `ios::sync_with_stdio(false); cin.tie(nullptr);` yozing — shunda `cout` `printf` dan sekin emas.",
    whyEn: "`endl` is a newline plus a flush, and a million flushes is a million system calls. Use `'\\n'`, and start with `ios::sync_with_stdio(false); cin.tie(nullptr);` — then `cout` is no slower than `printf`.",
  },
  {
    id: "pb-basics-d1", track: "programming-basics", tier: "deep", rating: 900,
    uz: "`long long x = 1 << 40;` — nega x da 2^40 bo‘lmaydi?",
    en: "`long long x = 1 << 40;` — why does x not hold 2^40?",
    choicesUz: ["`long long` 2^40 ga sig‘maydi", "`1` — `int`, siljitish `int` ichida bajariladi va toshadi; `1LL << 40` kerak", "`<<` faqat 31 gacha ishlaydi, `pow(2, 40)` kerak", "Aslida x = 2^40, xato yo‘q"],
    choicesEn: ["`long long` cannot hold 2^40", "`1` is an `int`, so the shift happens in `int` and overflows; you need `1LL << 40`", "`<<` only works up to 31; use `pow(2, 40)`", "x really is 2^40; nothing is wrong"],
    correct: 1,
    whyUz: "Ifoda turi chap tomondagi o‘zgaruvchiga qarab emas, operandlarga qarab aniqlanadi. `1` — `int`, 40 bitga siljitish uning uzunligidan oshadi. Natija `long long` ga keyin yoziladi — kech bo‘ladi. `pow` esa `double` qaytaradi va katta sonlarda aniqlikni yo‘qotadi.",
    whyEn: "An expression's type comes from its operands, not from the variable it is stored in. `1` is an `int`, and shifting it by 40 exceeds its width; the result reaches `long long` too late. `pow` returns a `double` and loses precision on big values.",
  },
  {
    id: "pb-basics-d2", track: "programming-basics", tier: "deep", rating: 900,
    uz: "Musbat butun x uchun `(x & (x - 1)) == 0` sharti nimani tekshiradi?",
    en: "For a positive integer x, what does `(x & (x - 1)) == 0` test?",
    choicesUz: ["x juft son", "x — 2 ning darajasi", "x ning oxirgi biti 1", "x toq son"],
    choicesEn: ["x is even", "x is a power of two", "x ends in a 1 bit", "x is odd"],
    correct: 1,
    whyUz: "`x - 1` eng kichik 1-bitni 0 ga, undan pastdagi barcha bitlarni 1 ga aylantiradi, shuning uchun `x & (x - 1)` eng kichik 1-bitni o‘chiradi. Natija 0 bo‘lsa, x da faqat bitta 1-bit bo‘lgan — ya’ni x = 2^k.",
    whyEn: "`x - 1` turns the lowest set bit into 0 and every bit below it into 1, so `x & (x - 1)` clears the lowest set bit. If nothing remains, x had exactly one set bit — x = 2^k.",
  },
  {
    id: "pb-basics-d3", track: "programming-basics", tier: "deep", rating: 900,
    uz: "C++ da bu kod nima chiqaradi?",
    en: "What does this print in C++?",
    code: "cout << -7 / 2 << \" \" << -7 % 2;",
    choicesUz: ["-4 1", "-3 -1", "-3 1", "-4 -1"],
    correct: 1,
    whyUz: "C++ da bo‘lish nol tomonga yaxlitlanadi: -7 / 2 = -3, qoldiq esa bo‘linuvchining ishorasini oladi: -1. Python esa -4 va 1 beradi. Manfiy sonning modulini olishda `((x % m) + m) % m` yozing.",
    whyEn: "C++ division truncates toward zero, so -7 / 2 = -3, and the remainder takes the dividend's sign: -1. Python gives -4 and 1. For a non-negative modulus of a negative number write `((x % m) + m) % m`.",
  },

  /* ======================================================= foundations (800 → 1300) */
  {
    id: "pb-found-b1", track: "foundations", tier: "basic", rating: 850,
    uz: "n ≤ 10^5 va yechimingiz O(n²). Bir soniyaga sig‘adimi?",
    en: "n ≤ 10^5 and your solution is O(n²). Does it fit in one second?",
    choicesUz: ["Ha, 10^5 kichik son", "Yo‘q — taxminan 10^10 amal bo‘ladi", "Kompyuterga bog‘liq, aytib bo‘lmaydi", "Faqat C++ da sig‘adi"],
    choicesEn: ["Yes, 10^5 is small", "No — that is about 10^10 operations", "Impossible to say, it depends on the machine", "Only in C++"],
    correct: 1,
    whyUz: "(10^5)² = 10^10. Bir soniyada taxminan 10^8 oddiy amal bajariladi — bu 100 barobar ko‘p. Cheklovni o‘qib, qaysi murakkablik kerakligini aniqlash — masala yechishning birinchi qadami.",
    whyEn: "(10^5)² = 10^10. About 10^8 simple operations fit in a second, so this is 100× over. Reading the constraint to pick the complexity is the first move on any problem.",
  },
  {
    id: "pb-found-b2", track: "foundations", tier: "basic", rating: 900,
    uz: "Cheklov: n ≤ 20. Qaysi murakkablik ham bir soniyaga sig‘adi?",
    en: "The constraint is n ≤ 20. Which complexity still fits in a second?",
    choicesUz: ["Faqat O(n) yoki O(n log n)", "O(2^n · n) ham — bu taxminan 2·10^7", "O(n!) ham sig‘adi", "Faqat O(n²)"],
    choicesEn: ["Only O(n) or O(n log n)", "Even O(2^n · n) — about 2·10^7", "Even O(n!) fits", "Only O(n²)"],
    correct: 1,
    whyUz: "2^20 ≈ 10^6, n ga ko‘paytirsak ≈ 2·10^7 — bemalol sig‘adi. 20! esa ≈ 2.4·10^18. n ≤ 20 kabi kichik cheklov ko‘pincha «barcha qism to‘plamlarni ko‘rib chiq» degan ishora.",
    whyEn: "2^20 ≈ 10^6; times n is ≈ 2·10^7, comfortably in budget. 20! is ≈ 2.4·10^18. A constraint as small as n ≤ 20 is usually a hint to enumerate subsets.",
  },
  {
    id: "pb-found-b3", track: "foundations", tier: "basic", rating: 900,
    uz: "Har qadamda qidiruv maydonini yarmiga qisqartirsangiz, 10^9 ta variantdan bittasiga taxminan nechta qadamda yetasiz?",
    en: "If every step halves the search space, about how many steps take 10^9 candidates down to one?",
    choicesUz: ["~30", "~1000", "~31 623 (√10^9)", "~9"],
    correct: 0,
    whyUz: "2^30 ≈ 1.07·10^9, demak 30 ta yarmiga bo‘lish yetadi. Bu O(log n) ning ma’nosi: n ming barobar oshsa, qadamlar atigi ~10 taga ko‘payadi.",
    whyEn: "2^30 ≈ 1.07·10^9, so 30 halvings suffice. That is what O(log n) means: make n a thousand times bigger and you add only about 10 steps.",
  },
  {
    id: "pb-found-c1", track: "foundations", tier: "core", rating: 1000,
    uz: "Bu kodning murakkabligi qanday?",
    en: "What is the complexity of this code?",
    code: "for (int i = 1; i <= n; i *= 2)\n    for (int j = 0; j < n; j++)\n        work();",
    choicesUz: ["O(n²)", "O(n log n)", "O(log n)", "O(n)"],
    correct: 1,
    whyUz: "Tashqi sikl i ni har safar ikki barobar oshiradi — log n marta aylanadi. Ichki sikl har safar n marta. Jami n · log n. Tashqi sikl «n gacha» deb yozilgani uni n marta aylanadi degani emas.",
    whyEn: "The outer loop doubles i each time, so it runs log n times; the inner loop runs n times per pass. n · log n in total. An outer loop written “up to n” does not mean n iterations.",
  },
  {
    id: "pb-found-c2", track: "foundations", tier: "core", rating: 1150,
    uz: "Bu kodning murakkabligi qanday?",
    en: "What is the complexity of this code?",
    code: "for (int i = 1; i <= n; i++)\n    for (int j = i; j <= n; j += i)\n        work();",
    choicesUz: ["O(n²)", "O(n log n)", "O(n √n)", "O(n)"],
    correct: 1,
    whyUz: "Ichki sikl n / i marta aylanadi. Jami n/1 + n/2 + … + n/n = n · (1 + 1/2 + … + 1/n) ≈ n · ln n. Bu garmonik qator — g‘alvir va bo‘luvchilarni sanashda doim uchraydi.",
    whyEn: "The inner loop runs n / i times. The total n/1 + n/2 + … + n/n = n · (1 + 1/2 + … + 1/n) ≈ n · ln n — the harmonic series, which sits under every sieve and divisor count.",
  },
  {
    id: "pb-found-c3", track: "foundations", tier: "core", rating: 1050,
    uz: "Bu rekursiv funksiya f(n) ni hisoblash uchun taxminan nechta chaqiruv qiladi?",
    en: "Roughly how many calls does this recursive function make to compute f(n)?",
    code: "int f(int n) {\n    if (n <= 1) return 1;\n    return f(n - 1) + f(n - 2);\n}",
    choicesUz: ["O(n)", "O(n²)", "Eksponentsial — taxminan 1.6^n", "O(n log n)"],
    choicesEn: ["O(n)", "O(n²)", "Exponential — about 1.6^n", "O(n log n)"],
    correct: 2,
    whyUz: "Har chaqiruv ikkitaga tarmoqlanadi va bir xil qiymatlar qayta-qayta hisoblanadi. Chaqiruvlar soni Fibonachchi sonlari kabi o‘sadi — φ^n ≈ 1.6^n. n = 50 da bu soatlab ishlaydi. Natijalarni eslab qolish (memoization) uni O(n) ga tushiradi.",
    whyEn: "Each call branches in two and the same values are recomputed over and over. The call count grows like the Fibonacci numbers — φ^n ≈ 1.6^n; at n = 50 it runs for hours. Remembering results (memoization) brings it down to O(n).",
  },
  {
    id: "pb-found-d1", track: "foundations", tier: "deep", rating: 1200,
    uz: "a saralangan. Bu kodning umumiy murakkabligi qanday?",
    en: "a is sorted. What is the total complexity of this code?",
    code: "int j = 0;\nfor (int i = 0; i < n; i++)\n    while (j < n && a[j] < a[i] + k)\n        j++;",
    choicesUz: ["O(n²) — ichma-ich ikki sikl", "O(n) — j hech qachon kamaymaydi, jami ko‘pi bilan n marta oshadi", "O(n log n)", "O(n · k)"],
    choicesEn: ["O(n²) — two nested loops", "O(n) — j never decreases, so it grows at most n times in total", "O(n log n)", "O(n · k)"],
    correct: 1,
    whyUz: "Ichki sikl har i uchun qaytadan boshlanmaydi: j tashqi sikllar orasida saqlanadi va faqat oshadi. Butun dastur davomida `j++` ko‘pi bilan n marta bajariladi. Bu amortizatsiya — two pointers aynan shunga tayanadi.",
    whyEn: "The inner loop does not restart for each i: j survives between outer iterations and only moves forward, so `j++` runs at most n times over the whole program. That is amortisation, and it is exactly what two pointers relies on.",
  },
  {
    id: "pb-found-d2", track: "foundations", tier: "deep", rating: 1250,
    uz: "T(n) = 2·T(n/2) + O(1) rekurrentasi nimaga teng?",
    en: "What does the recurrence T(n) = 2·T(n/2) + O(1) solve to?",
    choicesUz: ["O(log n)", "O(n)", "O(n log n)", "O(n²)"],
    correct: 1,
    whyUz: "Rekursiya daraxtida 1 + 2 + 4 + … + n ≈ 2n ta tugun bor, har birida O(1) ish — jami O(n). O(n log n) esa har darajada O(n) ish bo‘lganda chiqadi: T(n) = 2T(n/2) + O(n), ya’ni merge sort.",
    whyEn: "The recursion tree has 1 + 2 + 4 + … + n ≈ 2n nodes, each doing O(1) work — O(n) in total. O(n log n) is what you get when every level does O(n) work: T(n) = 2T(n/2) + O(n), which is merge sort.",
  },
  {
    id: "pb-found-d3", track: "foundations", tier: "deep", rating: 1150,
    uz: "n = 10^5 uchun `int dp[n][n]` qancha xotira oladi?",
    en: "For n = 10^5, how much memory does `int dp[n][n]` take?",
    choicesUz: ["~40 MB", "~400 MB", "~40 GB — mumkin emas, holatni qisqartirish kerak", "~4 MB"],
    choicesEn: ["~40 MB", "~400 MB", "~40 GB — impossible; the state has to shrink", "~4 MB"],
    correct: 2,
    whyUz: "10^10 ta katak × 4 bayt = 4·10^10 bayt ≈ 40 GB. Odatiy xotira limiti 256 MB, ya’ni ~6·10^7 ta `int`. Vaqt kabi xotira ham cheklovdan hisoblanadi — ko‘pincha faqat oxirgi qatorni saqlash yetarli bo‘ladi.",
    whyEn: "10^10 cells × 4 bytes = 4·10^10 bytes ≈ 40 GB. A typical memory limit is 256 MB, about 6·10^7 `int`s. Memory is budgeted from the constraints just like time — often keeping only the last row is enough.",
  },

  /* ============================================================ sorting (800 → 1500) */
  {
    id: "pb-sort-b1", track: "sorting", tier: "basic", rating: 850,
    uz: "Qaysi saralash algoritmi eng yomon holatda ham O(n log n) ishlaydi?",
    en: "Which sorting algorithm stays O(n log n) even in the worst case?",
    choicesUz: ["Quicksort", "Merge sort", "Insertion sort", "Bubble sort"],
    correct: 1,
    whyUz: "Merge sort massivni doim teng ikkiga bo‘ladi — chuqurlik log n, har darajada O(n) ish. Quicksort esa omadsiz pivot bilan O(n²) ga tushadi; insertion va bubble sort — eng yomon holatda O(n²).",
    whyEn: "Merge sort always splits in half — log n levels of O(n) work each. Quicksort degrades to O(n²) with unlucky pivots; insertion and bubble sort are O(n²) in the worst case.",
  },
  {
    id: "pb-sort-b2", track: "sorting", tier: "basic", rating: 900,
    uz: "10^6 ta son bor, har biri 0 dan 100 gacha. Eng tez qanday saralaysiz?",
    en: "You have 10^6 numbers, each between 0 and 100. What is the fastest way to sort them?",
    choicesUz: ["`sort` — O(n log n) dan tezi yo‘q", "Counting sort: har qiymat necha marta uchraganini sanash — O(n + 101)", "Merge sort", "Insertion sort, chunki qiymatlar kichik"],
    choicesEn: ["`sort` — nothing beats O(n log n)", "Counting sort: count how often each value appears — O(n + 101)", "Merge sort", "Insertion sort, because the values are small"],
    correct: 1,
    whyUz: "O(n log n) chegarasi faqat taqqoslashga asoslangan saralash uchun. Qiymatlar kichik oraliqda bo‘lsa, ularni sanab chiqish mumkin: 101 ta hisoblagich va bitta yurish. Bu chegara emas, qo‘shimcha ma’lumotdan foydalanish.",
    whyEn: "The O(n log n) bound applies to comparison sorts only. With values in a tiny range you can count them instead: 101 counters and one pass. It does not break the bound; it uses information comparisons ignore.",
  },
  {
    id: "pb-sort-b3", track: "sorting", tier: "basic", rating: 900,
    uz: "Massivni saralab, keyin qo‘shni juftlarni tekshirsangiz, qaysi masalani O(n log n) da yechasiz?",
    en: "Sorting an array and then scanning adjacent pairs solves which problem in O(n log n)?",
    choicesUz: ["Eng katta qism-massiv yig‘indisi", "Istalgan ikki son orasidagi eng kichik farq", "Eng ko‘p uchraydigan elementning dastlabki o‘rni", "Massivdagi inversiyalar soni"],
    choicesEn: ["The maximum subarray sum", "The smallest difference between any two values", "The original position of the most frequent value", "The number of inversions"],
    correct: 1,
    whyUz: "Saralangandan keyin bir-biriga eng yaqin ikki son albatta qo‘shni bo‘ladi, shuning uchun n−1 ta juftni tekshirish kifoya. Qolganlari saralash natijasida yo‘qoladigan tartibga bog‘liq yoki umuman boshqa usul talab qiladi.",
    whyEn: "After sorting, the two closest values are necessarily neighbours, so checking n−1 pairs is enough. The others depend on the original order, which sorting destroys, or need a different method entirely.",
  },
  {
    id: "pb-sort-c1", track: "sorting", tier: "core", rating: 1100,
    uz: "Massiv deyarli saralangan: har element o‘z joyidan ko‘pi bilan 2 pozitsiya uzoqda. Insertion sort qancha ishlaydi?",
    en: "The array is nearly sorted: every element is at most 2 positions from its place. How long does insertion sort take?",
    choicesUz: ["O(n²) — insertion sort doim kvadratik", "O(n)", "O(n log n)", "O(log n)"],
    choicesEn: ["O(n²) — insertion sort is always quadratic", "O(n)", "O(n log n)", "O(log n)"],
    correct: 1,
    whyUz: "Insertion sort ishining hajmi — inversiyalar soni. Har element ko‘pi bilan 2 qadam siljiydi, jami O(n). Shuning uchun deyarli saralangan yoki juda kichik massivlarda u merge sort dan ham tez — `std::sort` ham kichik bo‘laklarda insertion sort ga o‘tadi.",
    whyEn: "Insertion sort's work equals the number of inversions. Each element moves at most 2 steps, so O(n) in total. That is why it beats merge sort on nearly-sorted or tiny arrays — `std::sort` switches to it on small pieces.",
  },
  {
    id: "pb-sort-c2", track: "sorting", tier: "core", rating: 1150,
    uz: "Talabalar avval ism bo‘yicha saralangan. Endi ularni ball bo‘yicha saralashingiz kerak, bir xil ballilar esa ism tartibida qolishi shart. Nima ishlatasiz?",
    en: "Students are already sorted by name. Now you sort by score, and students with equal scores must stay in name order. What do you use?",
    choicesUz: ["Istalgan saralash — tartib o‘zi saqlanadi", "Barqaror (stable) saralash, masalan `stable_sort`", "`sort` ni ikki marta chaqirish", "Quicksort — u eng tezi"],
    choicesEn: ["Any sort — the order is kept automatically", "A stable sort, such as `stable_sort`", "Call `sort` twice", "Quicksort — it is the fastest"],
    correct: 1,
    whyUz: "Barqaror saralash teng elementlarning oldingi tartibini buzmaydi. `std::sort` barqaror emas — teng ballilar aralashib ketishi mumkin. Muqobil: bitta `sort` ni (ball, ism) juftligi bo‘yicha komparator bilan chaqirish.",
    whyEn: "A stable sort keeps equal elements in their previous order. `std::sort` is not stable — equal scores may get shuffled. The alternative is a single `sort` with a comparator on the (score, name) pair.",
  },
  {
    id: "pb-sort-c3", track: "sorting", tier: "core", rating: 1250,
    uz: "n = 2·10^5 ta qiymat, lekin ular 10^9 gacha. Ularni massiv indeksi sifatida ishlatish kerak (masalan, sanash uchun). Nima qilasiz?",
    en: "There are n = 2·10^5 values, but they reach 10^9, and you need them as array indices (to count them, say). What do you do?",
    choicesUz: ["10^9 uzunlikdagi massiv ochish", "Koordinatalarni siqish: saralab, takrorlarni olib tashlab, har qiymatni `lower_bound` bilan 0..n−1 ga almashtirish", "Qiymatlarni 1000 ga bo‘lib qisqartirish", "Faqat `map` bilan ishlash mumkin, boshqa yo‘l yo‘q"],
    choicesEn: ["Allocate an array of size 10^9", "Coordinate compression: sort, drop duplicates, map each value to 0..n−1 with `lower_bound`", "Divide the values by 1000 to shrink them", "Only a `map` can do it; there is no other way"],
    correct: 1,
    whyUz: "Ko‘p masalada qiymatning o‘zi emas, faqat tartibi muhim. Siqishdan keyin qiymatlar 0..n−1 oralig‘ida, tartib saqlangan — oddiy massiv yoki Fenwick tree ishlatsa bo‘ladi. `map` ham ishlaydi, lekin har amalda log n va katta konstanta qo‘shadi.",
    whyEn: "In many problems only the order of values matters, not the values themselves. After compression they lie in 0..n−1 with order preserved, so a plain array or a Fenwick tree works. A `map` works too, but adds a log n and a heavy constant to every operation.",
  },
  {
    id: "pb-sort-d1", track: "sorting", tier: "deep", rating: 1350,
    uz: "Massivdagi inversiyalar sonini (i < j va a[i] > a[j] bo‘lgan juftlar) n = 2·10^5 da qanday sanaysiz?",
    en: "How do you count inversions (pairs i < j with a[i] > a[j]) for n = 2·10^5?",
    choicesUz: ["Ikki sikl bilan — O(n²)", "Merge sort davomida: o‘ng yarmidan element olinganda, chap yarmida qolganlar sonini qo‘shish — O(n log n)", "Saralab, joyi o‘zgargan elementlarni sanash", "Counting sort bilan O(n)"],
    choicesEn: ["Two nested loops — O(n²)", "During merge sort: when an element is taken from the right half, add how many remain in the left — O(n log n)", "Sort, then count the elements that moved", "Counting sort in O(n)"],
    correct: 1,
    whyUz: "Birlashtirishda o‘ng yarmidagi element chapdagi qolgan barcha elementlardan kichik — ularning har biri bilan inversiya hosil qiladi. Shu sonlarni qo‘shib borsak, saralash bilan birga sanash ham tugaydi. Fenwick tree bilan ham O(n log n) da sanasa bo‘ladi.",
    whyEn: "When merging, a right-half element taken first is smaller than everything left in the left half — an inversion with each. Adding those counts gives the answer as a by-product of sorting. A Fenwick tree also counts them in O(n log n).",
  },
  {
    id: "pb-sort-d2", track: "sorting", tier: "deep", rating: 1400,
    uz: "Bu komparator bilan `sort` chaqirilsa nima xavf bor?",
    en: "What is the danger in calling `sort` with this comparator?",
    code: "sort(a.begin(), a.end(), [](int x, int y) {\n    return x <= y;\n});",
    choicesUz: ["Xavf yo‘q — faqat teng elementlar tartibi o‘zgaradi", "Qat’iy tartib (strict weak ordering) buziladi — xatti-harakat aniqlanmagan, dastur yiqilishi mumkin", "Massiv kamayish tartibida saralanadi", "Sekinroq ishlaydi, lekin to‘g‘ri"],
    choicesEn: ["None — only the order of equal elements changes", "It breaks strict weak ordering — undefined behaviour; the program can crash", "The array is sorted in decreasing order", "It runs slower but correctly"],
    correct: 1,
    whyUz: "Komparator `comp(x, x)` uchun `false` qaytarishi shart. `<=` bilan `comp(x, x) = true`, va `std::sort` ichidagi chegara tekshiruvsiz sikllar teng elementlar ko‘p bo‘lganda massivdan tashqariga chiqib ketishi mumkin. Doim `<` ishlating.",
    whyEn: "A comparator must return `false` for `comp(x, x)`. With `<=` it returns `true`, and the unguarded loops inside `std::sort` can run off the end of the array when many elements are equal. Always use `<`.",
  },
  {
    id: "pb-sort-d3", track: "sorting", tier: "deep", rating: 1450,
    uz: "Massiv medianasi kerak, saralangan massiv esa kerak emas. Eng tejamkor usul?",
    en: "You need the median of an array, not the sorted array itself. What is the cheapest way?",
    choicesUz: ["Saralab, o‘rtadagisini olish — O(n log n)", "`nth_element` (quickselect) — o‘rtacha O(n)", "Hammasini `set` ga solish", "Qiymat ustida binary search qilish"],
    choicesEn: ["Sort and take the middle — O(n log n)", "`nth_element` (quickselect) — O(n) on average", "Insert everything into a `set`", "Binary search on the value"],
    correct: 1,
    whyUz: "Quickselect partition qilgach, faqat kerakli element tushgan tomonga davom etadi: n + n/2 + n/4 + … ≈ 2n. To‘liq saralash ortiqcha ish — sizga bitta pozitsiya kerak, butun tartib emas.",
    whyEn: "After partitioning, quickselect recurses only into the side holding the wanted position: n + n/2 + n/4 + … ≈ 2n. Sorting fully is wasted work — you need one position, not the whole order.",
  },

  /* ================================================== backtracking (900 → 1900) */
  {
    id: "pb-back-b1", track: "backtracking", tier: "basic", rating: 950,
    uz: "`sum(5)` chaqirilsa nima bo‘ladi?",
    en: "What happens when `sum(5)` is called?",
    code: "int sum(int n) {\n    return n + sum(n - 1);\n}",
    choicesUz: ["15 qaytaradi", "To‘xtash sharti yo‘q — cheksiz rekursiya, stek to‘lib dastur yiqiladi", "0 qaytaradi", "Kompilyatsiya xatosi"],
    choicesEn: ["It returns 15", "There is no base case — infinite recursion until the stack overflows and the program crashes", "It returns 0", "A compile error"],
    correct: 1,
    whyUz: "Har rekursiv funksiyaga to‘xtash sharti (base case) kerak: `if (n == 0) return 0;`. Usiz chaqiruvlar manfiy sonlarga ham davom etadi va har biri stekda joy egallaydi — oxiri «stack overflow».",
    whyEn: "Every recursive function needs a base case: `if (n == 0) return 0;`. Without it the calls continue into negative numbers, each taking stack space, until the stack overflows.",
  },
  {
    id: "pb-back-b2", track: "backtracking", tier: "basic", rating: 1000,
    uz: "n ta elementli to‘plamning barcha qism to‘plamlari nechta?",
    en: "How many subsets does a set of n elements have?",
    choicesUz: ["n²", "2^n", "n!", "2n"],
    correct: 1,
    whyUz: "Har element uchun ikki tanlov — olish yoki olmaslik: 2 · 2 · … · 2 = 2^n. n = 20 da ~10^6 (tez), n = 40 da ~10^12 (juda sekin). Permutatsiyalar esa n! ta — bu boshqa narsa.",
    whyEn: "Each element has two choices — in or out: 2 · 2 · … · 2 = 2^n. At n = 20 that is ~10^6 (fast); at n = 40, ~10^12 (far too slow). Permutations number n!, which is a different thing.",
  },
  {
    id: "pb-back-b3", track: "backtracking", tier: "basic", rating: 1050,
    uz: "Barcha permutatsiyalarni birma-bir ko‘rib chiqish taxminan qaysi n gacha 1 soniyaga sig‘adi?",
    en: "Up to roughly which n does enumerating every permutation fit in one second?",
    choicesUz: ["n ≤ 10–11", "n ≤ 20", "n ≤ 100", "n ≤ 5"],
    correct: 0,
    whyUz: "10! ≈ 3.6·10^6, 11! ≈ 4·10^7 — hali sig‘adi. 12! ≈ 4.8·10^8 — har permutatsiyada ish ham bo‘lsa, allaqachon sekin. 20 esa 2^n uchun chegara, n! uchun emas.",
    whyEn: "10! ≈ 3.6·10^6 and 11! ≈ 4·10^7 still fit. 12! ≈ 4.8·10^8 is already too slow once each permutation does any work. 20 is the limit for 2^n, not for n!.",
  },
  {
    id: "pb-back-c1", track: "backtracking", tier: "core", rating: 1250,
    uz: "Bu funksiya qism to‘plamlarni generatsiya qilishi kerak edi, lekin natijalar noto‘g‘ri. Nima yetishmaydi?",
    en: "This function should generate all subsets, but the results are wrong. What is missing?",
    code: "void go(int i) {\n    if (i == n) { use(); return; }\n    take[i] = true;\n    go(i + 1);\n    go(i + 1);   // i-elementsiz\n}",
    choicesUz: ["To‘xtash sharti", "Ikkinchi chaqiruvdan oldin `take[i] = false;` — tanlovni qaytarish", "`go(i - 1)` chaqiruvi", "Hech narsa, kod to‘g‘ri"],
    choicesEn: ["A base case", "`take[i] = false;` before the second call — undoing the choice", "A call to `go(i - 1)`", "Nothing, the code is correct"],
    correct: 1,
    whyUz: "Backtracking ning uch qadami: tanla → ichkariga kir → tanlovni qaytar. Qaytarish bo‘lmasa, «i-elementsiz» shox aslida uni hali ham olgan holda ishlaydi va hech qachon bo‘sh to‘plam chiqmaydi.",
    whyEn: "Backtracking is three steps: choose → recurse → undo. Without the undo, the “without element i” branch still has it taken, and the empty set never appears.",
  },
  {
    id: "pb-back-c2", track: "backtracking", tier: "core", rating: 1350,
    uz: "Backtracking da «pruning» (kesish) nimani anglatadi?",
    en: "In backtracking, what does pruning mean?",
    choicesUz: ["Rekursiya chuqurligini cheklash", "Yechimga olib bora olmasligi aniq bo‘lgan shoxni erta tashlab ketish", "Natijalarni keshda saqlash", "Rekursiyani sikl bilan almashtirish"],
    choicesEn: ["Capping the recursion depth", "Abandoning a branch as soon as it provably cannot lead to a solution", "Caching results", "Rewriting the recursion as a loop"],
    correct: 1,
    whyUz: "Pruning — holatlar daraxtining foydasiz qismini kesish, masalan joriy yig‘indi allaqachon maqsaddan oshib ketgan bo‘lsa. Chuqurlikni ko‘r-ko‘rona cheklash boshqa narsa va to‘g‘ri javoblarni ham yo‘qotadi.",
    whyEn: "Pruning cuts the useless part of the state tree — say, once the running sum already exceeds the target. Blindly capping depth is something else and throws correct answers away with it.",
  },
  {
    id: "pb-back-c3", track: "backtracking", tier: "core", rating: 1400,
    uz: "N-Queens da har yangi qirolichani qo‘yishda hujumni O(1) da tekshirish uchun nimalarni saqlaysiz?",
    en: "In N-Queens, what do you keep so that placing each new queen is checked for attacks in O(1)?",
    choicesUz: ["Butun taxtani, har safar O(n²) tekshirib", "Band ustunlar va ikki yo‘nalishdagi diagonallar: r + c va r − c", "Faqat band qatorlar", "Qirolichalar ro‘yxati va ular orasidagi masofalar"],
    choicesEn: ["The whole board, checked in O(n²) each time", "Occupied columns and both diagonal families: r + c and r − c", "Only occupied rows", "A list of queens and the distances between them"],
    correct: 1,
    whyUz: "Qatorma-qator qo‘yganda qator to‘qnashuvi bo‘lmaydi. Bitta diagonaldagi kataklarda r + c o‘zgarmas, ikkinchisida r − c. Uchta mantiqiy massiv har tekshiruvni O(1) ga tushiradi.",
    whyEn: "Placing row by row rules out row clashes. Along one diagonal r + c is constant, along the other r − c. Three boolean arrays make every check O(1).",
  },
  {
    id: "pb-back-d1", track: "backtracking", tier: "deep", rating: 1700,
    uz: "n = 40 ta son (har biri 10^9 gacha). Yig‘indisi aniq S bo‘lgan qism to‘plam bormi? 2^40 juda ko‘p. Nima qilasiz?",
    en: "There are n = 40 numbers (each up to 10^9). Is there a subset summing to exactly S? 2^40 is too many. What do you do?",
    choicesUz: ["Yig‘indi bo‘yicha knapsack DP", "Ikkiga bo‘lish: har yarmining 2^20 ta yig‘indisini hisoblab, birini saralab, ikkinchisidan binary search (meet in the middle)", "Greedy: kattasidan boshlab olish", "Tasodifiy qism to‘plamlarni sinash"],
    choicesEn: ["Knapsack DP over the sum", "Split in two: compute each half's 2^20 sums, sort one side, binary search from the other (meet in the middle)", "Greedy: take the largest first", "Try random subsets"],
    correct: 1,
    whyUz: "2^20 + 2^20 ≈ 2·10^6 holat, 2^40 ≈ 10^12 o‘rniga. Yig‘indi 10^9 · 40 gacha bo‘lgani uchun knapsack DP massivi sig‘maydi, greedy esa bu masalada umuman ishlamaydi.",
    whyEn: "2^20 + 2^20 ≈ 2·10^6 states instead of 2^40 ≈ 10^12. With sums up to 40 · 10^9 a knapsack array cannot fit, and greedy simply does not work here.",
  },
  {
    id: "pb-back-d2", track: "backtracking", tier: "deep", rating: 1800,
    uz: "n bitli barcha m maskalar uchun ularning barcha submaskalarini `for (s = m; s; s = (s - 1) & m)` bilan aylanib chiqish jami qancha vaqt oladi?",
    en: "Over every n-bit mask m, iterating all submasks with `for (s = m; s; s = (s - 1) & m)` costs how much in total?",
    choicesUz: ["O(4^n)", "O(3^n)", "O(2^n · n)", "O(2^n)"],
    correct: 1,
    whyUz: "Har bit uchun uch holat: m da yo‘q, m da bor lekin s da yo‘q, ikkalasida bor. Shunday juftliklar (m, s) soni aynan 3^n. n = 15 da ~1.4·10^7 — sig‘adi; 4^n deb o‘ylab bu usuldan qo‘rqmang.",
    whyEn: "Each bit is in one of three states: not in m, in m but not in s, in both. The number of (m, s) pairs is exactly 3^n — about 1.4·10^7 at n = 15, which fits. Do not rule it out thinking it is 4^n.",
  },
  {
    id: "pb-back-d3", track: "backtracking", tier: "deep", rating: 1750,
    uz: "Yechim chuqurligi noma’lum, lekin kichik. BFS xotiraga sig‘maydi, DFS esa chuqur noto‘g‘ri shoxga kirib ketadi. Qaysi usul?",
    en: "The solution depth is unknown but small. BFS runs out of memory, and DFS dives down a deep wrong branch. Which method?",
    choicesUz: ["Kattaroq stek bilan DFS", "Iterative deepening (IDDFS): chuqurlik chegarasi 1, 2, 3, … bilan DFS ni qayta ishga tushirish", "Faqat BFS, xotirani oshirib", "Tasodifiy yurish"],
    choicesEn: ["DFS with a bigger stack", "Iterative deepening (IDDFS): rerun DFS with depth limits 1, 2, 3, …", "BFS anyway, with more memory", "A random walk"],
    correct: 1,
    whyUz: "IDDFS xotirada DFS kabi faqat joriy yo‘lni saqlaydi, lekin BFS kabi eng sayoz yechimni birinchi topadi. Qayta ishga tushirish qimmat tuyuladi, lekin daraxt eksponentsial o‘sgani uchun oxirgi daraja umumiy ishning asosiy qismini tashkil qiladi.",
    whyEn: "IDDFS keeps only the current path in memory, like DFS, yet finds the shallowest solution first, like BFS. The restarts look wasteful, but because the tree grows exponentially the last level dominates the total work.",
  },

  /* ================================================================ math (900 → 2100) */
  {
    id: "pb-math-b1", track: "math", tier: "basic", rating: 1000,
    uz: "Javobni 10^9+7 bo‘yicha saqlayapsiz. Ayirishda `ans = (ans - x) % MOD;` nega xato bo‘lishi mumkin?",
    en: "You keep the answer modulo 10^9+7. Why can `ans = (ans - x) % MOD;` be wrong when subtracting?",
    choicesUz: ["Xato emas, doim to‘g‘ri", "`ans - x` manfiy bo‘lsa, C++ da `%` ham manfiy qaytaradi — `(ans - x + MOD) % MOD` kerak", "MOD tub bo‘lgani uchun ayirish mumkin emas", "`%` ayirishdan oldin bajariladi"],
    choicesEn: ["It is not wrong; it always works", "If `ans - x` is negative, C++ `%` returns a negative too — use `(ans - x + MOD) % MOD`", "Subtraction is impossible because MOD is prime", "`%` is applied before the subtraction"],
    correct: 1,
    whyUz: "C++ da -3 % 7 = -3, 4 emas. Manfiy qoldiq keyingi hisoblarda ham manfiy bo‘lib qolaveradi va javob noto‘g‘ri chiqadi. MOD qo‘shib qo‘yish natijani doim [0, MOD) oralig‘iga qaytaradi.",
    whyEn: "In C++, -3 % 7 is -3, not 4. The negative residue carries into later arithmetic and the answer comes out wrong. Adding MOD first keeps the result in [0, MOD).",
  },
  {
    id: "pb-math-b2", track: "math", tier: "basic", rating: 950,
    uz: "n ≤ 10^12 sonining tubligini tekshirish uchun bo‘luvchilarni qaysi songacha sinash kifoya?",
    en: "To test whether n ≤ 10^12 is prime, up to which number must you try divisors?",
    choicesUz: ["n / 2 gacha", "√n gacha, ya’ni 10^6", "log n gacha", "n − 1 gacha"],
    choicesEn: ["Up to n / 2", "Up to √n, which is 10^6", "Up to log n", "Up to n − 1"],
    correct: 1,
    whyUz: "Agar n = a · b bo‘lsa, a va b dan biri √n dan oshmaydi. Demak √n gacha bo‘luvchi topilmasa, n tub. 10^12 uchun bu atigi 10^6 ta tekshiruv.",
    whyEn: "If n = a · b, one of a and b is at most √n. So if nothing up to √n divides n, it is prime. For 10^12 that is only 10^6 checks.",
  },
  {
    id: "pb-math-b3", track: "math", tier: "basic", rating: 1100,
    uz: "a^b mod m ni hisoblash kerak, b ≤ 10^18. Qanday?",
    en: "You need a^b mod m with b ≤ 10^18. How?",
    choicesUz: ["a ni b marta ko‘paytirish", "Tez daraja: a^b = (a^(b/2))² — O(log b) ko‘paytirish", "`pow(a, b)` ni hisoblab, keyin `% m`", "Buni hisoblab bo‘lmaydi"],
    choicesEn: ["Multiply a by itself b times", "Fast exponentiation: a^b = (a^(b/2))² — O(log b) multiplications", "Compute `pow(a, b)` and then take `% m`", "It cannot be computed"],
    correct: 1,
    whyUz: "b ning ikkilik yozuvi bo‘yicha kvadratlab borish ~60 ta ko‘paytirishni talab qiladi. b marta ko‘paytirish 10^18 qadam. `pow` esa `double` qaytaradi — a^b ulkan son, aniqlik yo‘qoladi.",
    whyEn: "Squaring along the binary digits of b takes about 60 multiplications; multiplying b times takes 10^18 steps. `pow` returns a `double` — a^b is astronomically large and its precision is gone.",
  },
  {
    id: "pb-math-c1", track: "math", tier: "core", rating: 1400,
    uz: "(a / b) mod p kerak, p tub va b p ga bo‘linmaydi. To‘g‘ri usul?",
    en: "You need (a / b) mod p, where p is prime and b is not divisible by p. The right way?",
    choicesUz: ["`(a % p) / (b % p)`", "a · b^(p−2) mod p — Ferma kichik teoremasi bo‘yicha b ning teskarisi", "a / b ni `double` da hisoblab, keyin mod olish", "a · (p − b) mod p"],
    choicesEn: ["`(a % p) / (b % p)`", "a · b^(p−2) mod p — the inverse of b by Fermat's little theorem", "Compute a / b as a `double`, then take the mod", "a · (p − b) mod p"],
    correct: 1,
    whyUz: "Modul bo‘yicha bo‘lish — teskari elementga ko‘paytirish. b^(p−1) ≡ 1 bo‘lgani uchun b^(p−2) — b ning teskarisi; uni tez daraja bilan O(log p) da topasiz. Qoldiqlarni oddiy bo‘lish esa ma’nosiz natija beradi.",
    whyEn: "Division modulo p is multiplication by an inverse. Since b^(p−1) ≡ 1, b^(p−2) is b's inverse, found with fast exponentiation in O(log p). Dividing the residues directly produces nonsense.",
  },
  {
    id: "pb-math-c2", track: "math", tier: "core", rating: 1500,
    uz: "10^6 dan oshmaydigan 10^5 ta sonni tub ko‘paytuvchilarga ajratish kerak. Eng yaxshi usul?",
    en: "You must factorise 10^5 numbers, each at most 10^6. The best approach?",
    choicesUz: ["Har birini √x gacha bo‘lib ko‘rish", "G‘alvir bilan har son uchun eng kichik tub bo‘luvchini (SPF) oldindan hisoblab, keyin har sonni O(log x) da bo‘lish", "Har biri uchun Pollard rho", "Barcha tub sonlarni ro‘yxatga olib, har biriga bo‘lib ko‘rish"],
    choicesEn: ["Trial division up to √x for each", "Precompute each number's smallest prime factor (SPF) with a sieve, then factor each in O(log x)", "Pollard's rho for each", "List all primes and try dividing by every one"],
    correct: 1,
    whyUz: "SPF g‘alviri bir marta ~10^6 · log log qadam oladi. Keyin x = spf[x] · (x / spf[x]) — har bo‘lishda x kamida ikki barobar kichrayadi. √x bilan esa 10^5 · 1000 = 10^8 — chegarada.",
    whyEn: "The SPF sieve costs about 10^6 · log log once. Then x = spf[x] · (x / spf[x]), and each step at least halves x. Trial division is 10^5 · 1000 = 10^8 — right at the limit.",
  },
  {
    id: "pb-math-c3", track: "math", tier: "core", rating: 1600,
    uz: "10^5 ta so‘rov: C(n, k) mod 10^9+7, n ≤ 10^6. Qanday?",
    en: "10^5 queries of C(n, k) mod 10^9+7, with n ≤ 10^6. How?",
    choicesUz: ["Paskal uchburchagi — n × n jadval", "Faktoriallar va teskari faktoriallarni bir marta hisoblab, har so‘rovda n! · inv(k!) · inv((n−k)!) — O(1)", "Har so‘rovda formulani `double` da hisoblash", "Har so‘rovda k marta ko‘paytirib, k marta bo‘lish"],
    choicesEn: ["Pascal's triangle — an n × n table", "Precompute factorials and inverse factorials once, then n! · inv(k!) · inv((n−k)!) per query — O(1)", "Evaluate the formula in `double` for each query", "Multiply k times and divide k times per query"],
    correct: 1,
    whyUz: "Paskal jadvali 10^12 katak — sig‘maydi. Faktoriallar O(n), teskari faktoriallar esa oxiridan: inv((i−1)!) = inv(i!) · i. Oddiy bo‘lish mod bo‘yicha ishlamaydi, `double` esa aniqlikni yo‘qotadi.",
    whyEn: "Pascal's table would be 10^12 cells. Factorials take O(n), and inverse factorials run backwards: inv((i−1)!) = inv(i!) · i. Plain division does not work modulo p, and `double` loses precision.",
  },
  {
    id: "pb-math-d1", track: "math", tier: "deep", rating: 1700,
    uz: "1 dan N gacha (N ≤ 10^18) 2, 3 yoki 5 ga bo‘linadigan sonlar nechta?",
    en: "How many numbers from 1 to N (N ≤ 10^18) are divisible by 2, 3 or 5?",
    choicesUz: ["N/2 + N/3 + N/5", "N/2 + N/3 + N/5 − N/6 − N/10 − N/15 + N/30", "N − N/30", "N/30"],
    correct: 1,
    whyUz: "Kiritish-chiqarish prinsipi: 6 ga bo‘linadigan son ham 2 ga, ham 3 ga bo‘linadiganlar ichida ikki marta sanalgan — bir marta ayiramiz. 30 ga bo‘linadiganlar uch marta qo‘shilib, uch marta ayrildi — qaytarib qo‘shamiz. (Bu yerda / — butun bo‘lish.)",
    whyEn: "Inclusion–exclusion: a multiple of 6 was counted twice, once under 2 and once under 3, so subtract it once. Multiples of 30 were added three times and removed three times, so add them back. (Here / is integer division.)",
  },
  {
    id: "pb-math-d2", track: "math", tier: "deep", rating: 1900,
    uz: "a^(10^18) mod m kerak, m tub emas, lekin gcd(a, m) = 1. Darajani qanday kichraytirasiz?",
    en: "You need a^(10^18) mod m, where m is not prime but gcd(a, m) = 1. How do you shrink the exponent?",
    choicesUz: ["Darajani mod (m − 1) olish", "Darajani mod φ(m) olish — Eyler teoremasi", "Darajani mod m olish", "Qisqartirib bo‘lmaydi"],
    choicesEn: ["Take the exponent mod (m − 1)", "Take the exponent mod φ(m) — Euler's theorem", "Take the exponent mod m", "It cannot be reduced"],
    correct: 1,
    whyUz: "gcd(a, m) = 1 bo‘lsa a^φ(m) ≡ 1 (mod m), shuning uchun daraja φ(m) bo‘yicha davriy. m − 1 faqat m tub bo‘lganda φ(m) ga teng — tub bo‘lmagan m da bu xato. (Aslida 10^18 ni tez daraja ham ~60 qadamda hisoblaydi; bu usul daraja ulkan bo‘lganda, masalan a^(b^c) da kerak.)",
    whyEn: "With gcd(a, m) = 1, a^φ(m) ≡ 1 (mod m), so the exponent is periodic modulo φ(m). m − 1 equals φ(m) only when m is prime — wrong here. (Fast exponentiation handles 10^18 itself in ~60 steps; this is for exponents like b^c that are too big to write down.)",
  },
  {
    id: "pb-math-d3", track: "math", tier: "deep", rating: 1800,
    uz: "n ta odam shlyapalarini aralashtirib, har biri tasodifan bittadan oladi. O‘z shlyapasini olganlar sonining kutilgan qiymati?",
    en: "n people mix their hats and each takes one at random. What is the expected number who get their own hat?",
    choicesUz: ["1", "n / 2", "1 / n", "n / e"],
    correct: 0,
    whyUz: "Kutilgan qiymatning chiziqliligi: i-odam o‘z shlyapasini olish ehtimoli 1/n. n ta odam uchun yig‘indi n · 1/n = 1 — hodisalar bog‘liq bo‘lsa ham. Bu usul murakkab taqsimotni hisoblamasdan ko‘p masalani yechadi.",
    whyEn: "Linearity of expectation: person i gets their own hat with probability 1/n. Summed over n people that is n · 1/n = 1, even though the events are dependent. It solves many problems without ever computing the distribution.",
  },
];
