// AlgoYo'l problem bank.
//
// Original AlgoYo'l problems — statements are written for this platform, not
// copied from another judge (neeed.md section 26). Each entry carries a public
// sample; the hidden tests live server-side in app/api/judge/tests.ts.
//
// `judge` is the key the judge API runs, so every problem here is actually
// solvable rather than decorative.

export type BankProblem={
 id:string;uz:string;en:string;difficulty:"easy"|"medium"|"hard";tag:string;points:number;topic:string;
 judge?:string;statementUz?:string;statementEn?:string;inputUz?:string;inputEn?:string;
 outputUz?:string;outputEn?:string;constraints?:string;sample?:{input:string;output:string};
};

export const bankProblems:BankProblem[]=[
 {id:"D01",uz:"Juft va toq sonlar",en:"Even and odd counts",difficulty:"easy",tag:"Boshlang‘ich",points:100,topic:"programming-basics",judge:"count-parity",statementUz:"Massivdagi juft va toq sonlar nechtaligini toping.",statementEn:"Count how many numbers in the array are even and how many are odd.",inputUz:"Birinchi qatorda n. Ikkinchi qatorda n ta butun son.",inputEn:"First line n. Second line n integers.",outputUz:"Juftlar soni va toqlar soni, probel bilan.",outputEn:"The count of evens and the count of odds, separated by a space.",constraints:"1 ≤ n ≤ 10^5, |a_i| ≤ 10^9",sample:{input:"6\n1 2 3 4 5 6\n",output:"3 3\n"}},
 {id:"D02",uz:"Raqamlar yig‘indisi",en:"Digit sum",difficulty:"easy",tag:"Boshlang‘ich",points:100,topic:"programming-basics",judge:"digit-sum",statementUz:"Berilgan sonning raqamlari yig‘indisini toping.",statementEn:"Find the sum of the digits of the given number.",inputUz:"Bitta manfiy bo‘lmagan butun son n.",inputEn:"A single non-negative integer n.",outputUz:"Raqamlar yig‘indisi.",outputEn:"The sum of the digits.",constraints:"0 ≤ n ≤ 10^18",sample:{input:"9875\n",output:"29\n"}},
 {id:"D03",uz:"Massivni teskari o‘girish",en:"Reverse the array",difficulty:"easy",tag:"Massiv",points:100,topic:"programming-basics",judge:"array-reverse",statementUz:"Massiv elementlarini teskari tartibda chiqaring.",statementEn:"Print the array elements in reverse order.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"Teskari tartibdagi massiv.",outputEn:"The reversed array.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"5\n1 2 3 4 5\n",output:"5 4 3 2 1\n"}},
 {id:"D04",uz:"Eng katta va eng kichik farqi",en:"Range spread",difficulty:"easy",tag:"Massiv",points:100,topic:"foundations",judge:"range-spread",statementUz:"Massivdagi eng katta va eng kichik element farqini toping.",statementEn:"Find the difference between the largest and smallest element.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"Farq.",outputEn:"The difference.",constraints:"1 ≤ n ≤ 10^5, |a_i| ≤ 10^9",sample:{input:"5\n3 9 1 7 4\n",output:"8\n"}},
 {id:"D05",uz:"Unlilar soni",en:"Vowel count",difficulty:"easy",tag:"Satr",points:100,topic:"strings",judge:"vowel-count",statementUz:"Satrdagi ingliz unli harflari (a, e, i, o, u) sonini toping.",statementEn:"Count the English vowels (a, e, i, o, u) in the string.",inputUz:"Kichik lotin harflaridan iborat satr.",inputEn:"A string of lowercase Latin letters.",outputUz:"Unlilar soni.",outputEn:"The number of vowels.",constraints:"1 ≤ |s| ≤ 10^5",sample:{input:"algoritm\n",output:"3\n"}},
 {id:"D06",uz:"Faktorial modul bo‘yicha",en:"Factorial modulo",difficulty:"easy",tag:"Matematika",points:100,topic:"math",judge:"factorial-mod",statementUz:"n! ni 10^9+7 modulida hisoblang.",statementEn:"Compute n! modulo 10^9+7.",inputUz:"Bitta butun son n.",inputEn:"A single integer n.",outputUz:"n! mod (10^9+7).",outputEn:"n! mod (10^9+7).",constraints:"1 ≤ n ≤ 10^5",sample:{input:"5\n",output:"120\n"}},
 {id:"D07",uz:"3 va 5 karralilari",en:"Multiples of 3 and 5",difficulty:"easy",tag:"Matematika",points:100,topic:"math",judge:"multiples-sum",statementUz:"n dan kichik va 3 yoki 5 ga bo‘linadigan sonlar yig‘indisini toping.",statementEn:"Sum all numbers below n divisible by 3 or 5.",inputUz:"Bitta butun son n.",inputEn:"A single integer n.",outputUz:"Yig‘indi.",outputEn:"The sum.",constraints:"1 ≤ n ≤ 10^6",sample:{input:"10\n",output:"23\n"}},
 {id:"D08",uz:"Palindrom so‘z",en:"Palindrome word",difficulty:"easy",tag:"Satr",points:100,topic:"strings",judge:"palindrome-word",statementUz:"Satr palindrom ekanini aniqlang.",statementEn:"Decide whether the string is a palindrome.",inputUz:"Kichik lotin harflaridan iborat satr.",inputEn:"A string of lowercase Latin letters.",outputUz:"Palindrom bo‘lsa YES, aks holda NO.",outputEn:"YES if it is a palindrome, otherwise NO.",constraints:"1 ≤ |s| ≤ 10^5",sample:{input:"level\n",output:"YES\n"}},
 {id:"D09",uz:"EKUB va EKUK",en:"GCD and LCM",difficulty:"easy",tag:"Matematika",points:100,topic:"math",judge:"gcd-lcm",statementUz:"Ikki sonning EKUB va EKUK ini toping.",statementEn:"Find the GCD and the LCM of two numbers.",inputUz:"Ikkita musbat butun son a va b.",inputEn:"Two positive integers a and b.",outputUz:"EKUB va EKUK, probel bilan.",outputEn:"The GCD and the LCM, separated by a space.",constraints:"1 ≤ a, b ≤ 10^9",sample:{input:"12 18\n",output:"6 36\n"}},
 {id:"D10",uz:"O‘suvchi maksimum",en:"Running maximum",difficulty:"easy",tag:"Massiv",points:100,topic:"foundations",judge:"running-max",statementUz:"Har bir prefiks uchun maksimal elementni chiqaring.",statementEn:"For every prefix print the maximum element so far.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"n ta son — har bir prefiks maksimumi.",outputEn:"n numbers — the maximum of each prefix.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"5\n3 1 4 1 5\n",output:"3 3 4 4 5\n"}},
 {id:"M01",uz:"Prefiks yig‘indi so‘rovlari",en:"Prefix sum queries",difficulty:"medium",tag:"Prefix sum",points:200,topic:"two-pointers",judge:"prefix-queries",statementUz:"q ta so‘rov uchun [l, r] oralig‘idagi yig‘indini toping.",statementEn:"For q queries report the sum on the range [l, r].",inputUz:"n va q. Keyin n ta son. Keyin q ta l r juftlik.",inputEn:"n and q. Then n integers. Then q pairs l r.",outputUz:"Har bir so‘rov uchun yig‘indi, alohida qatorda.",outputEn:"One sum per query, each on its own line.",constraints:"1 ≤ n, q ≤ 10^5",sample:{input:"5 3\n1 2 3 4 5\n1 3\n2 5\n1 5\n",output:"6\n14\n15\n"}},
 {id:"M02",uz:"x dan kichik bo‘lmagan birinchi element",en:"First element not less than x",difficulty:"medium",tag:"Binary search",points:200,topic:"binary-search",judge:"first-not-less",statementUz:"O‘sib boruvchi massivda x dan kichik bo‘lmagan birinchi elementning o‘rnini toping.",statementEn:"In a sorted array find the position of the first element not less than x.",inputUz:"n va x. Keyin o‘sib boruvchi n ta son.",inputEn:"n and x. Then n integers in non-decreasing order.",outputUz:"1 dan boshlangan o‘rin, topilmasa -1.",outputEn:"The 1-based position, or -1 if there is none.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"5 4\n1 3 5 7 9\n",output:"3\n"}},
 {id:"M03",uz:"Yig‘indisi k ga teng juftliklar",en:"Pairs with sum k",difficulty:"medium",tag:"Two pointers",points:200,topic:"two-pointers",judge:"pair-sum-count",statementUz:"Yig‘indisi k ga teng bo‘lgan (i, j), i < j juftliklar sonini toping.",statementEn:"Count pairs (i, j) with i < j whose sum equals k.",inputUz:"n va k. Keyin n ta son.",inputEn:"n and k. Then n integers.",outputUz:"Juftliklar soni.",outputEn:"The number of pairs.",constraints:"1 ≤ n ≤ 2000, |a_i| ≤ 10^9",sample:{input:"5 6\n1 2 3 4 5\n",output:"2\n"}},
 {id:"M04",uz:"Takrorlanmas eng uzun bo‘lak",en:"Longest substring without repeats",difficulty:"medium",tag:"Sliding window",points:200,topic:"two-pointers",judge:"longest-distinct",statementUz:"Belgilari takrorlanmaydigan eng uzun ketma-ket bo‘lak uzunligini toping.",statementEn:"Find the length of the longest substring with no repeated character.",inputUz:"Kichik lotin harflaridan iborat satr.",inputEn:"A string of lowercase Latin letters.",outputUz:"Uzunlik.",outputEn:"The length.",constraints:"1 ≤ |s| ≤ 10^5",sample:{input:"abcabcbb\n",output:"3\n"}},
 {id:"M05",uz:"Qavslar muvozanati",en:"Balanced brackets",difficulty:"medium",tag:"Stack",points:200,topic:"data-structures",judge:"balanced-brackets",statementUz:"Qavslar ketma-ketligi to‘g‘ri joylashganini aniqlang.",statementEn:"Decide whether the bracket sequence is balanced.",inputUz:"( ) [ ] { } belgilaridan iborat satr.",inputEn:"A string made of ( ) [ ] { }.",outputUz:"To‘g‘ri bo‘lsa YES, aks holda NO.",outputEn:"YES if balanced, otherwise NO.",constraints:"1 ≤ |s| ≤ 10^5",sample:{input:"([])\n",output:"YES\n"}},
 {id:"M06",uz:"k-chi eng katta element",en:"k-th largest element",difficulty:"medium",tag:"Saralash",points:200,topic:"sorting",judge:"kth-largest",statementUz:"Massivdagi k-chi eng katta elementni toping (takrorlanishlar hisobga olinadi).",statementEn:"Find the k-th largest element, counting duplicates.",inputUz:"n va k. Keyin n ta son.",inputEn:"n and k. Then n integers.",outputUz:"k-chi eng katta element.",outputEn:"The k-th largest element.",constraints:"1 ≤ k ≤ n ≤ 10^5",sample:{input:"5 2\n3 1 4 1 5\n",output:"4\n"}},
 {id:"M07",uz:"Kesishuvchi oraliqlar",en:"Merge intervals",difficulty:"medium",tag:"Saralash",points:200,topic:"sorting",judge:"merge-intervals",statementUz:"Kesishuvchi oraliqlarni birlashtirgandan keyin nechta oraliq qolishini toping.",statementEn:"Report how many intervals remain after merging every overlap.",inputUz:"Birinchi qatorda n. Keyin n ta l r juftlik.",inputEn:"First line n. Then n pairs l r.",outputUz:"Birlashtirilgan oraliqlar soni.",outputEn:"The number of merged intervals.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"4\n1 3\n2 6\n8 10\n15 18\n",output:"3\n"}},
 {id:"M08",uz:"k uzunlikdagi eng katta yig‘indi",en:"Best window of length k",difficulty:"medium",tag:"Sliding window",points:200,topic:"two-pointers",judge:"window-sum",statementUz:"Ketma-ket k ta elementning eng katta yig‘indisini toping.",statementEn:"Find the largest sum of k consecutive elements.",inputUz:"n va k. Keyin n ta son.",inputEn:"n and k. Then n integers.",outputUz:"Eng katta yig‘indi.",outputEn:"The largest sum.",constraints:"1 ≤ k ≤ n ≤ 10^5",sample:{input:"6 3\n1 2 3 4 5 6\n",output:"15\n"}},
 {id:"M09",uz:"Tub sonlar soni",en:"Count the primes",difficulty:"medium",tag:"Sieve",points:200,topic:"math",judge:"prime-count",statementUz:"n dan katta bo‘lmagan tub sonlar sonini toping.",statementEn:"Count the primes not greater than n.",inputUz:"Bitta butun son n.",inputEn:"A single integer n.",outputUz:"Tub sonlar soni.",outputEn:"The number of primes.",constraints:"1 ≤ n ≤ 10^6",sample:{input:"10\n",output:"4\n"}},
 {id:"M10",uz:"Tez darajaga ko‘tarish",en:"Fast exponentiation",difficulty:"medium",tag:"Matematika",points:200,topic:"math",judge:"fast-power",statementUz:"a^b ni m modulida hisoblang.",statementEn:"Compute a^b modulo m.",inputUz:"Uchta butun son a, b, m.",inputEn:"Three integers a, b and m.",outputUz:"a^b mod m.",outputEn:"a^b mod m.",constraints:"0 ≤ a, b ≤ 10^9, 1 ≤ m ≤ 10^9",sample:{input:"2 10 1000\n",output:"24\n"}},
 {id:"M11",uz:"Panjarada eng qisqa yo‘l",en:"Shortest path in a grid",difficulty:"medium",tag:"BFS",points:200,topic:"graphs",judge:"grid-shortest",statementUz:"Yuqori chap burchakdan pastki o‘ng burchakka eng kam qadamni toping. '#' — devor.",statementEn:"Find the fewest steps from the top-left cell to the bottom-right cell. '#' is a wall.",inputUz:"r va c. Keyin r ta qator, har birida c ta '.' yoki '#'.",inputEn:"r and c. Then r rows of c characters, '.' or '#'.",outputUz:"Qadamlar soni, yo‘l bo‘lmasa -1.",outputEn:"The number of steps, or -1 if unreachable.",constraints:"1 ≤ r, c ≤ 1000",sample:{input:"3 3\n...\n.#.\n...\n",output:"4\n"}},
 {id:"M12",uz:"Bog‘lamlar soni",en:"Connected components",difficulty:"medium",tag:"DSU",points:200,topic:"graphs",judge:"components-count",statementUz:"Yo‘naltirilmagan grafdagi bog‘lam (komponenta) sonini toping.",statementEn:"Count the connected components of an undirected graph.",inputUz:"n va m. Keyin m ta qirra a b.",inputEn:"n and m. Then m edges a b.",outputUz:"Komponentalar soni.",outputEn:"The number of components.",constraints:"1 ≤ n ≤ 10^5, 0 ≤ m ≤ 2·10^5",sample:{input:"5 3\n1 2\n2 3\n4 5\n",output:"2\n"}},
 {id:"M13",uz:"Eng uzun o‘suvchi ketma-ketlik",en:"Longest increasing subsequence",difficulty:"medium",tag:"DP",points:200,topic:"dynamic-programming",judge:"lis-length",statementUz:"Eng uzun qat’iy o‘suvchi qism-ketma-ketlik uzunligini toping.",statementEn:"Find the length of the longest strictly increasing subsequence.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"Uzunlik.",outputEn:"The length.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"6\n10 9 2 5 3 7\n",output:"3\n"}},
 {id:"M14",uz:"0/1 ryukzak",en:"0/1 knapsack",difficulty:"medium",tag:"DP",points:200,topic:"dynamic-programming",judge:"knapsack-01",statementUz:"Sig‘imi W bo‘lgan ryukzakka joylab, eng katta qiymatni toping.",statementEn:"Maximise the value carried in a knapsack of capacity W.",inputUz:"n va W. Keyin n ta w v juftlik.",inputEn:"n and W. Then n pairs w v.",outputUz:"Eng katta qiymat.",outputEn:"The maximum value.",constraints:"1 ≤ n ≤ 100, 0 ≤ W ≤ 10^4",sample:{input:"3 5\n2 3\n3 4\n4 5\n",output:"7\n"}},
 {id:"M15",uz:"Bo‘lak necha marta uchraydi",en:"Count substring occurrences",difficulty:"medium",tag:"Satr",points:200,topic:"strings",judge:"substring-occurrences",statementUz:"p bo‘lagi s satrida necha marta uchrashini toping (kesishuvlar ham hisoblanadi).",statementEn:"Count how many times p occurs in s, including overlaps.",inputUz:"Birinchi qatorda s, ikkinchi qatorda p.",inputEn:"First line s, second line p.",outputUz:"Uchrashlar soni.",outputEn:"The number of occurrences.",constraints:"1 ≤ |p| ≤ |s| ≤ 10^5",sample:{input:"ababab\nab\n",output:"3\n"}},
 {id:"M16",uz:"Topologik tartib mumkinmi",en:"Is a topological order possible",difficulty:"medium",tag:"Topological sort",points:200,topic:"graphs",judge:"topological-possible",statementUz:"Yo‘naltirilgan grafda sikl yo‘qligini, ya’ni topologik tartib borligini aniqlang.",statementEn:"Decide whether the directed graph is acyclic, so a topological order exists.",inputUz:"n va m. Keyin m ta yo‘naltirilgan qirra a b.",inputEn:"n and m. Then m directed edges a b.",outputUz:"Mumkin bo‘lsa YES, aks holda NO.",outputEn:"YES if possible, otherwise NO.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"3 2\n1 2\n2 3\n",output:"YES\n"}},
 {id:"M17",uz:"Eng ko‘p tadbir",en:"Maximum activities",difficulty:"medium",tag:"Greedy",points:200,topic:"greedy",judge:"activity-select",statementUz:"Vaqti kesishmaydigan eng ko‘p tadbirni tanlang.",statementEn:"Select the largest set of activities whose times do not overlap.",inputUz:"Birinchi qatorda n. Keyin n ta s e juftlik.",inputEn:"First line n. Then n pairs s e.",outputUz:"Tanlangan tadbirlar soni.",outputEn:"The number of selected activities.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"3\n1 3\n2 5\n4 7\n",output:"2\n"}},
 {id:"M18",uz:"Keyingi katta element",en:"Next greater element",difficulty:"medium",tag:"Monotonic stack",points:200,topic:"data-structures",judge:"stack-next-greater",statementUz:"Har bir element uchun undan o‘ngda turgan birinchi kattaroq elementni toping.",statementEn:"For each element find the first greater element to its right.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"n ta son; bo‘lmasa -1.",outputEn:"n numbers; -1 when there is none.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"5\n2 1 2 4 3\n",output:"4 2 4 -1 -1\n"}},
 {id:"M19",uz:"Yig‘indisi t ga eng yaqin juftlik",en:"Pair sum closest to t",difficulty:"medium",tag:"Two pointers",points:200,topic:"two-pointers",judge:"two-pointer-closest",statementUz:"O‘sib boruvchi massivda yig‘indisi t ga eng yaqin juftlikning yig‘indisini toping.",statementEn:"In a sorted array find the pair sum closest to t.",inputUz:"n va t. Keyin o‘sib boruvchi n ta son.",inputEn:"n and t. Then n integers in non-decreasing order.",outputUz:"Eng yaqin yig‘indi.",outputEn:"The closest sum.",constraints:"2 ≤ n ≤ 10^5",sample:{input:"5 8\n1 3 4 7 10\n",output:"8\n"}},
 {id:"M20",uz:"Eng ko‘p uchragan son",en:"Most frequent value",difficulty:"medium",tag:"Hash map",points:200,topic:"data-structures",judge:"frequency-mode",statementUz:"Eng ko‘p uchragan sonni toping; bir nechta bo‘lsa eng kichigini chiqaring.",statementEn:"Find the most frequent value; if several tie, print the smallest.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"Eng ko‘p uchragan son.",outputEn:"The most frequent value.",constraints:"1 ≤ n ≤ 10^5",sample:{input:"6\n1 3 3 2 3 1\n",output:"3\n"}},
 {id:"M21",uz:"Matritsani spiral bo‘ylab o‘qish",en:"Spiral order of a matrix",difficulty:"medium",tag:"Massiv",points:200,topic:"foundations",judge:"matrix-spiral",statementUz:"Matritsani soat yo‘nalishi bo‘yicha spiral tartibda chiqaring.",statementEn:"Print the matrix in clockwise spiral order.",inputUz:"r va c. Keyin r ta qator, har birida c ta son.",inputEn:"r and c. Then r rows of c integers.",outputUz:"Spiral tartibdagi sonlar.",outputEn:"The values in spiral order.",constraints:"1 ≤ r, c ≤ 1000",sample:{input:"3 3\n1 2 3\n4 5 6\n7 8 9\n",output:"1 2 3 6 9 8 7 4 5\n"}},
 {id:"H01",uz:"Tahrirlash masofasi",en:"Edit distance",difficulty:"hard",tag:"DP",points:300,topic:"dynamic-programming",judge:"edit-distance",statementUz:"Bir satrni ikkinchisiga aylantirish uchun kerak bo‘lgan eng kam amal sonini toping.",statementEn:"Find the fewest operations that turn one string into the other.",inputUz:"Ikki qatorda ikkita satr.",inputEn:"Two lines, one string each.",outputUz:"Eng kam amal soni.",outputEn:"The minimum number of operations.",constraints:"0 ≤ |a|, |b| ≤ 2000",sample:{input:"kitten\nsitting\n",output:"3\n"}},
 {id:"H02",uz:"Tanga kombinatsiyalari",en:"Coin combinations",difficulty:"hard",tag:"DP",points:300,topic:"dynamic-programming",judge:"coin-ways",statementUz:"Tangalar bilan t summani nechta usulda yig‘ish mumkinligini toping. Tartib muhim emas.",statementEn:"Count the ways to make t from the coins. Order does not matter.",inputUz:"n va t. Keyin n ta tanga qiymati.",inputEn:"n and t. Then n coin values.",outputUz:"Usullar soni.",outputEn:"The number of ways.",constraints:"1 ≤ n ≤ 100, 0 ≤ t ≤ 10^4",sample:{input:"3 4\n1 2 3\n",output:"4\n"}},
 {id:"H03",uz:"Inversiyalar soni",en:"Count inversions",difficulty:"hard",tag:"Saralash",points:300,topic:"sorting",judge:"inversion-count",statementUz:"i < j va a_i > a_j shartini qanoatlantiruvchi juftliklar sonini toping.",statementEn:"Count pairs with i < j and a_i > a_j.",inputUz:"Birinchi qatorda n, keyin n ta son.",inputEn:"First line n, then n integers.",outputUz:"Inversiyalar soni.",outputEn:"The number of inversions.",constraints:"1 ≤ n ≤ 2000",sample:{input:"5\n5 4 3 2 1\n",output:"10\n"}},
 {id:"H04",uz:"Eng qisqa yo‘l (vaznli)",en:"Shortest path with weights",difficulty:"hard",tag:"Dijkstra",points:300,topic:"graphs",judge:"dijkstra-shortest",statementUz:"1-tugundan n-tugungacha eng qisqa yo‘l og‘irligini toping.",statementEn:"Find the shortest path weight from node 1 to node n.",inputUz:"n va m. Keyin m ta a b w qirra.",inputEn:"n and m. Then m edges a b w.",outputUz:"Eng qisqa masofa, yo‘l bo‘lmasa -1.",outputEn:"The shortest distance, or -1 if unreachable.",constraints:"1 ≤ n ≤ 10^5, 1 ≤ w ≤ 10^9",sample:{input:"4 4\n1 2 1\n2 3 2\n1 3 5\n3 4 1\n",output:"4\n"}},
 {id:"H05",uz:"Daraxt diametri",en:"Tree diameter",difficulty:"hard",tag:"Daraxt",points:300,topic:"trees",judge:"tree-diameter",statementUz:"Daraxtdagi eng uzoq ikki tugun orasidagi qirralar sonini toping.",statementEn:"Find the number of edges on the longest path in the tree.",inputUz:"Birinchi qatorda n. Keyin n-1 ta qirra a b.",inputEn:"First line n. Then n-1 edges a b.",outputUz:"Diametr.",outputEn:"The diameter.",constraints:"2 ≤ n ≤ 10^5",sample:{input:"4\n1 2\n2 3\n3 4\n",output:"3\n"}},
 {id:"H06",uz:"Bo‘laklarning eng kichik maksimumi",en:"Minimise the largest part",difficulty:"hard",tag:"Binary search on answer",points:300,topic:"binary-search",judge:"binary-answer-split",statementUz:"Massivni k ta ketma-ket bo‘lakka bo‘lib, bo‘lak yig‘indilarining maksimumini eng kichik qiling.",statementEn:"Split the array into k consecutive parts so the largest part sum is as small as possible.",inputUz:"n va k. Keyin n ta musbat son.",inputEn:"n and k. Then n positive integers.",outputUz:"Mumkin bo‘lgan eng kichik maksimum.",outputEn:"The smallest achievable maximum.",constraints:"1 ≤ k ≤ n ≤ 10^5",sample:{input:"5 2\n1 2 3 4 5\n",output:"9\n"}},
 {id:"H07",uz:"Qism to‘plam yig‘indisi",en:"Subset sum",difficulty:"hard",tag:"Backtracking",points:300,topic:"backtracking",judge:"subset-sum-exists",statementUz:"Yig‘indisi aynan t ga teng bo‘lgan qism to‘plam bormi?",statementEn:"Does a subset with sum exactly t exist?",inputUz:"n va t. Keyin n ta musbat son.",inputEn:"n and t. Then n positive integers.",outputUz:"Bo‘lsa YES, aks holda NO.",outputEn:"YES if it exists, otherwise NO.",constraints:"1 ≤ n ≤ 40, 0 ≤ t ≤ 10^5",sample:{input:"4 9\n3 34 4 12\n",output:"NO\n"}},
];
