// AlgoYo'l problem bank -- the index.
//
// This module is in the client bundle: the problem list, the filters, the
// search box, the roadmap and the duel all need to know that a problem exists
// before anybody asks to read it. So it carries only what those screens
// render -- the id, both titles, the rating and its difficulty label, the tag,
// the topic, the points, the judge key and the limits. Eleven small fields per
// problem.
//
// The prose -- statement, input, output, constraints, samples and
// their notes -- lives in app/api/problem/details.ts and is fetched one problem
// at a time by app/ui/problem-detail.ts. It used to live here, which meant
// every visitor downloaded all 302 statements in both languages in order to
// read one of them.
//
// Original AlgoYo'l problems: statements are written for this platform, never
// copied from another judge (section 26).
//
// A statement is meant to read like a Codeforces one, which means it answers
// every question a solver would otherwise have to guess at:
//
//   statement    the task in full: what the input describes, what is being
//                asked, and every definition the question leans on. It used to
//                be preceded by a `legend` -- an italic paragraph of topic
//                framing above the task -- which was removed from all 302
//                problems: it was read first and needed last, and the solver
//                had to get past it to learn what to compute. Whatever belongs
//                to the task is stated in the task.
//   input        line by line, in the order the lines actually arrive
//   output       exactly what to print, including how many lines
//   limits       time and memory, because they decide which algorithm fits
//   constraints  one bound per variable -- these choose the complexity class
//   samples      at least two, with a note explaining why each answer is what
//                it is, not just restating it
//
// Every sample output is produced by RUNNING the reference solution, never
// typed by hand. A sample that disagrees with the judge is worse than a terse
// statement: the solver copies it, gets WA, and has no way to see that the
// problem is the thing that is wrong. tools/problem-authoring owns that.
//
// Difficulty follows the rating rather than being set by hand, so the label and
// the number can never disagree: easy below 1200, medium below 1800, hard
// through 2000, insane at 2100 and above. `difficultyOf` in rating.ts is the
// same rule, and it is the one that decides.
//
// Hidden tests live server-side in app/api/judge/tests.ts.

export type ProblemSample={input:string;output:string};

/* The index entry -- what the client gets for all 302 problems. */
export type BankProblem={
 id:string;uz:string;en:string;difficulty:"easy"|"medium"|"hard"|"insane";rating:number;tag:string;points:number;
 topic:string;judge?:string;timeLimitMs?:number;memoryMb?:number;
};

/* The prose half, served by /api/problem?id=... and rendered by
 * ProblemStatement. Every field is optional: this is the shape the client gets
 * back over the network, and a problem that has not been rewritten yet is
 * missing most of it.
 *
 * The old single `constraints` string and `noteUz/En` are kept
 * so nothing that reads them breaks; `constraintList` and `sampleNotes*` are
 * what the problem page renders when a problem has been rewritten.
 * `constraintListUz` is the Uzbek counterpart of `constraintList`, so the
 * constraints are not the one section left in English on an Uzbek page.
 */
export type ProblemDetail={
 statementUz?:string;statementEn?:string;inputUz?:string;inputEn?:string;
 outputUz?:string;outputEn?:string;constraints?:string;
 constraintList?:string[];constraintListUz?:string[];
 noteUz?:string;noteEn?:string;sampleNotesUz?:string[];sampleNotesEn?:string[];
 samples?:ProblemSample[];
};

export const bankProblems:BankProblem[]=[
 {id:"A01",uz:"Massivni teskari o‘girish",en:"Reverse the array",difficulty:"easy",rating:800,tag:"Arrays",points:100,topic:"programming-basics",judge:"array-reverse",timeLimitMs:1000,memoryMb:256},
 {id:"A02",uz:"Juft va toq sonlar",en:"Even and odd counts",difficulty:"easy",rating:800,tag:"Arrays",points:100,topic:"programming-basics",judge:"count-parity",timeLimitMs:1000,memoryMb:256},
 {id:"A03",uz:"Raqamlar yig‘indisi",en:"Digit sum",difficulty:"easy",rating:800,tag:"Math",points:100,topic:"math",judge:"digit-sum",timeLimitMs:1000,memoryMb:256},
 {id:"A04",uz:"3 va 5 karralilari",en:"Multiples of 3 and 5",difficulty:"easy",rating:800,tag:"Math",points:100,topic:"math",judge:"multiples-sum",timeLimitMs:1000,memoryMb:256},
 {id:"A05",uz:"Eng katta va eng kichik farqi",en:"Range spread",difficulty:"easy",rating:800,tag:"Arrays",points:100,topic:"foundations",judge:"range-spread",timeLimitMs:1000,memoryMb:256},
 {id:"A06",uz:"Ikki son yig‘indisi",en:"Sum of two numbers",difficulty:"easy",rating:800,tag:"Implementation",points:100,topic:"programming-basics",judge:"sum-two",timeLimitMs:1000,memoryMb:256},
 {id:"A07",uz:"O‘rtacha harorat",en:"Average temperature",difficulty:"easy",rating:800,tag:"Math",points:100,topic:"foundations",judge:"temperature-average",timeLimitMs:1000,memoryMb:256},
 {id:"A08",uz:"Unlilar soni",en:"Vowel count",difficulty:"easy",rating:800,tag:"Strings",points:100,topic:"strings",judge:"vowel-count",timeLimitMs:1000,memoryMb:256},
 {id:"A09",uz:"Faktorial modul bo‘yicha",en:"Factorial modulo",difficulty:"easy",rating:900,tag:"Math",points:100,topic:"math",judge:"factorial-mod",timeLimitMs:1000,memoryMb:256},
 {id:"A10",uz:"EKUB va EKUK",en:"GCD and LCM",difficulty:"easy",rating:900,tag:"Number theory",points:100,topic:"math",judge:"gcd-lcm",timeLimitMs:1000,memoryMb:256},
 {id:"A11",uz:"Palindrom so‘z",en:"Palindrome word",difficulty:"easy",rating:900,tag:"Strings",points:100,topic:"strings",judge:"palindrome-word",timeLimitMs:1000,memoryMb:256},
 {id:"A12",uz:"Ikkining darajasimi",en:"Is it a power of two",difficulty:"easy",rating:900,tag:"Bit manipulation",points:100,topic:"math",judge:"power-of-two",timeLimitMs:1000,memoryMb:256},
 {id:"A13",uz:"O‘suvchi maksimum",en:"Running maximum",difficulty:"easy",rating:900,tag:"Prefix",points:100,topic:"foundations",judge:"running-max",timeLimitMs:1000,memoryMb:256},
 {id:"A14",uz:"Ikkinchi eng katta",en:"Second largest",difficulty:"easy",rating:900,tag:"Arrays",points:100,topic:"foundations",judge:"second-largest",timeLimitMs:1000,memoryMb:256},
 {id:"A15",uz:"Anagramlarmi",en:"Anagram check",difficulty:"easy",rating:1000,tag:"Strings",points:100,topic:"strings",judge:"anagram-check",timeLimitMs:1000,memoryMb:256},
 {id:"A16",uz:"Birlar soni",en:"Count set bits",difficulty:"easy",rating:1000,tag:"Bit manipulation",points:100,topic:"math",judge:"bit-count",timeLimitMs:1000,memoryMb:256},
 {id:"A17",uz:"Eng ko‘p uchragan harf",en:"Most frequent letter",difficulty:"easy",rating:1000,tag:"Counting",points:100,topic:"strings",judge:"char-frequency",timeLimitMs:1000,memoryMb:256},
 {id:"A18",uz:"Nechta xil qiymat bor",en:"Count distinct values",difficulty:"easy",rating:1000,tag:"Hash set",points:100,topic:"data-structures",judge:"count-distinct",timeLimitMs:1000,memoryMb:256},
 {id:"A19",uz:"So‘zlar soni",en:"Word count",difficulty:"easy",rating:1000,tag:"Parsing",points:100,topic:"strings",judge:"word-count",timeLimitMs:1000,memoryMb:256},
 {id:"A20",uz:"Sezar shifri",en:"Caesar shift",difficulty:"easy",rating:1100,tag:"Implementation",points:100,topic:"strings",judge:"caesar-shift",timeLimitMs:1000,memoryMb:256},
 {id:"A21",uz:"Diagonallar yig‘indisi",en:"Diagonal sums",difficulty:"easy",rating:1100,tag:"Matrices",points:100,topic:"foundations",judge:"diagonal-sum",timeLimitMs:1000,memoryMb:256},
 {id:"A22",uz:"Eng ko‘p uchragan son",en:"Most frequent value",difficulty:"easy",rating:1100,tag:"Hash map",points:100,topic:"data-structures",judge:"frequency-mode",timeLimitMs:1000,memoryMb:256},
 {id:"A23",uz:"Kvadratlar yig‘indisi",en:"Sum of squares",difficulty:"easy",rating:1100,tag:"Math",points:100,topic:"math",judge:"sum-of-squares",timeLimitMs:1000,memoryMb:256},
 {id:"B24",uz:"Qavslar muvozanati",en:"Balanced brackets",difficulty:"medium",rating:1200,tag:"Stack",points:200,topic:"data-structures",judge:"balanced-brackets",timeLimitMs:1000,memoryMb:256},
 {id:"B25",uz:"Bo‘luvchilar soni",en:"Count divisors",difficulty:"medium",rating:1200,tag:"Number theory",points:200,topic:"math",judge:"count-divisors",timeLimitMs:1000,memoryMb:256},
 {id:"B26",uz:"x dan kichik bo‘lmagan birinchi element",en:"First element not less than x",difficulty:"medium",rating:1200,tag:"Binary search",points:200,topic:"binary-search",judge:"first-not-less",timeLimitMs:1000,memoryMb:256},
 {id:"B27",uz:"k-chi eng katta element",en:"k-th largest element",difficulty:"medium",rating:1200,tag:"Sorting",points:200,topic:"sorting",judge:"kth-largest",timeLimitMs:1000,memoryMb:256},
 {id:"B28",uz:"Eng uzun bir xil blok",en:"Longest equal run",difficulty:"medium",rating:1200,tag:"Implementation",points:200,topic:"foundations",judge:"longest-equal-run",timeLimitMs:1000,memoryMb:256},
 {id:"B29",uz:"Matritsani transponirlash",en:"Transpose a matrix",difficulty:"medium",rating:1200,tag:"Matrices",points:200,topic:"foundations",judge:"matrix-transpose",timeLimitMs:1000,memoryMb:256},
 {id:"B30",uz:"Mukammal son",en:"Perfect number",difficulty:"medium",rating:1200,tag:"Number theory",points:200,topic:"math",judge:"perfect-number",timeLimitMs:1000,memoryMb:256},
 {id:"B31",uz:"Prefix sum so‘rovlari",en:"Prefix sum queries",difficulty:"medium",rating:1200,tag:"Prefix sum",points:200,topic:"two-pointers",judge:"prefix-queries",timeLimitMs:1000,memoryMb:256},
 {id:"B32",uz:"Takrorlarni olib tashlash",en:"Remove duplicates",difficulty:"medium",rating:1200,tag:"Two pointers",points:200,topic:"two-pointers",judge:"remove-duplicates-sorted",timeLimitMs:1000,memoryMb:256},
 {id:"B33",uz:"Takrorlarni siqish",en:"Run-length encoding",difficulty:"medium",rating:1200,tag:"Implementation",points:200,topic:"strings",judge:"run-length",timeLimitMs:1000,memoryMb:256},
 {id:"B34",uz:"Zinapoyaga chiqish usullari",en:"Ways to climb stairs",difficulty:"medium",rating:1200,tag:"DP",points:200,topic:"dynamic-programming",judge:"stairs-ways",timeLimitMs:1000,memoryMb:256},
 {id:"B35",uz:"k uzunlikdagi eng katta yig‘indi",en:"Best window of length k",difficulty:"medium",rating:1200,tag:"Sliding window",points:200,topic:"two-pointers",judge:"window-sum",timeLimitMs:1000,memoryMb:256},
 {id:"B36",uz:"Qavslarning maksimal chuqurligi",en:"Maximum bracket depth",difficulty:"medium",rating:1300,tag:"Stack",points:200,topic:"data-structures",judge:"bracket-depth",timeLimitMs:1000,memoryMb:256},
 {id:"B37",uz:"Kollatz qadamlari",en:"Collatz steps",difficulty:"medium",rating:1300,tag:"Simulation",points:200,topic:"math",judge:"collatz-steps",timeLimitMs:1000,memoryMb:256},
 {id:"B38",uz:"Kichik diapazonli sorting",en:"Counting sort",difficulty:"medium",rating:1300,tag:"Counting sort",points:200,topic:"sorting",judge:"count-sort-range",timeLimitMs:1000,memoryMb:256},
 {id:"B39",uz:"Fibonachchi soni",en:"Fibonacci number",difficulty:"medium",rating:1300,tag:"DP",points:200,topic:"math",judge:"fibonacci-mod",timeLimitMs:1000,memoryMb:256},
 {id:"B40",uz:"Matritsani spiral bo‘ylab o‘qish",en:"Spiral order of a matrix",difficulty:"medium",rating:1300,tag:"Simulation",points:200,topic:"foundations",judge:"matrix-spiral",timeLimitMs:1000,memoryMb:256},
 {id:"B41",uz:"Eng katta qism-yig‘indi",en:"Maximum subarray sum",difficulty:"medium",rating:1300,tag:"Kadane",points:200,topic:"dynamic-programming",judge:"max-subarray",timeLimitMs:1000,memoryMb:256},
 {id:"B42",uz:"Yig‘indisi k ga teng juftliklar",en:"Pairs with a given sum",difficulty:"medium",rating:1300,tag:"Two pointers",points:200,topic:"two-pointers",judge:"pair-sum-count",timeLimitMs:1000,memoryMb:256},
 {id:"B43",uz:"Tub sonlar soni",en:"Count the primes",difficulty:"medium",rating:1300,tag:"Sieve",points:200,topic:"math",judge:"prime-count",timeLimitMs:1000,memoryMb:256},
 {id:"B44",uz:"Queue simulyatsiyasi",en:"Queue simulation",difficulty:"medium",rating:1300,tag:"Queue",points:200,topic:"data-structures",judge:"queue-simulation",timeLimitMs:1000,memoryMb:256},
 {id:"B45",uz:"Massivni aylantirish",en:"Rotate the array",difficulty:"medium",rating:1300,tag:"Implementation",points:200,topic:"foundations",judge:"rotate-array",timeLimitMs:1000,memoryMb:256},
 {id:"B46",uz:"Uchburchak yuzi",en:"Triangle area",difficulty:"medium",rating:1300,tag:"Geometry",points:200,topic:"geometry",judge:"triangle-area",timeLimitMs:1000,memoryMb:256},
 {id:"B47",uz:"1 dan n gacha XOR",en:"XOR from 1 to n",difficulty:"medium",rating:1300,tag:"Bit manipulation",points:200,topic:"math",judge:"xor-range",timeLimitMs:1000,memoryMb:256},
 {id:"B48",uz:"Butun kvadrat ildiz",en:"Integer square root",difficulty:"medium",rating:1400,tag:"Binary search on answer",points:200,topic:"binary-search",judge:"binary-search-sqrt",timeLimitMs:1000,memoryMb:256},
 {id:"B49",uz:"Bog‘lamlar soni",en:"Connected components",difficulty:"medium",rating:1400,tag:"DSU",points:200,topic:"graphs",judge:"components-count",timeLimitMs:1000,memoryMb:256},
 {id:"B50",uz:"Tez darajaga ko‘tarish",en:"Fast exponentiation",difficulty:"medium",rating:1400,tag:"Binary exponentiation",points:200,topic:"math",judge:"fast-power",timeLimitMs:1000,memoryMb:256},
 {id:"B51",uz:"Eng katta orol",en:"Largest island",difficulty:"medium",rating:1400,tag:"Flood fill",points:200,topic:"graphs",judge:"flood-fill-area",timeLimitMs:1000,memoryMb:256},
 {id:"B52",uz:"Eng yaqin ikki nuqta (Manhattan)",en:"Closest pair by Manhattan distance",difficulty:"medium",rating:1400,tag:"Geometry",points:200,topic:"geometry",judge:"manhattan-closest",timeLimitMs:1000,memoryMb:256},
 {id:"B53",uz:"Kesishuvchi oraliqlar",en:"Merge intervals",difficulty:"medium",rating:1400,tag:"Sorting",points:200,topic:"sorting",judge:"merge-intervals",timeLimitMs:1000,memoryMb:256},
 {id:"B54",uz:"Cho‘qqi element",en:"Find a peak",difficulty:"medium",rating:1400,tag:"Binary search",points:200,topic:"binary-search",judge:"peak-element",timeLimitMs:1000,memoryMb:256},
 {id:"B55",uz:"Aylantirilgan satrmi",en:"Is it a rotation",difficulty:"medium",rating:1400,tag:"Strings",points:200,topic:"strings",judge:"string-rotation",timeLimitMs:1000,memoryMb:256},
 {id:"B56",uz:"Barglar soni",en:"Count the leaves",difficulty:"medium",rating:1400,tag:"Tree",points:200,topic:"trees",judge:"tree-leaf-count",timeLimitMs:1000,memoryMb:256},
 {id:"B57",uz:"Yig‘indisi t ga eng yaqin juftlik",en:"Pair sum closest to t",difficulty:"medium",rating:1400,tag:"Two pointers",points:200,topic:"two-pointers",judge:"two-pointer-closest",timeLimitMs:1000,memoryMb:256},
 {id:"B58",uz:"Eng ko‘p tadbir",en:"Maximum activities",difficulty:"medium",rating:1500,tag:"Greedy",points:200,topic:"greedy",judge:"activity-select",timeLimitMs:1000,memoryMb:256},
 {id:"B59",uz:"Tugungacha masofa",en:"Distance to every node",difficulty:"medium",rating:1500,tag:"BFS",points:200,topic:"graphs",judge:"bfs-levels",timeLimitMs:1000,memoryMb:256},
 {id:"B60",uz:"Eng ko‘p vazifa",en:"Maximum tasks by deadline",difficulty:"medium",rating:1500,tag:"Greedy",points:200,topic:"greedy",judge:"fractional-tasks",timeLimitMs:1000,memoryMb:256},
 {id:"B61",uz:"Panjaradagi yo‘llar soni",en:"Count paths in a grid",difficulty:"medium",rating:1500,tag:"Grid DP",points:200,topic:"dynamic-programming",judge:"grid-paths",timeLimitMs:1000,memoryMb:256},
 {id:"B62",uz:"Panjarada eng qisqa yo‘l",en:"Shortest path in a grid",difficulty:"medium",rating:1500,tag:"BFS",points:200,topic:"graphs",judge:"grid-shortest",timeLimitMs:1000,memoryMb:256},
 {id:"B63",uz:"Qo‘shni bo‘lmagan maksimal yig‘indi",en:"Maximum non-adjacent sum",difficulty:"medium",rating:1500,tag:"DP",points:200,topic:"dynamic-programming",judge:"house-robber",timeLimitMs:1000,memoryMb:256},
 {id:"B64",uz:"Takrorlanmas eng uzun bo‘lak",en:"Longest substring without repeats",difficulty:"medium",rating:1500,tag:"Sliding window",points:200,topic:"two-pointers",judge:"longest-distinct",timeLimitMs:1000,memoryMb:256},
 {id:"B65",uz:"Eng katta k ta sonning yig‘indisi",en:"Sum of the k largest",difficulty:"medium",rating:1500,tag:"Heap",points:200,topic:"data-structures",judge:"max-heap-k",timeLimitMs:1000,memoryMb:256},
 {id:"B66",uz:"Ruxsatlar sonini sanash",en:"Count valid permutations",difficulty:"medium",rating:1500,tag:"Backtracking",points:200,topic:"backtracking",judge:"permutations-count",timeLimitMs:1000,memoryMb:256},
 {id:"B67",uz:"Chastota bo‘yicha sorting",en:"Sort by frequency",difficulty:"medium",rating:1500,tag:"Custom comparator",points:200,topic:"sorting",judge:"sort-by-frequency",timeLimitMs:1000,memoryMb:256},
 {id:"B68",uz:"Keyingi katta element",en:"Next greater element",difficulty:"medium",rating:1500,tag:"Monotonic stack",points:200,topic:"data-structures",judge:"stack-next-greater",timeLimitMs:1000,memoryMb:256},
 {id:"B69",uz:"Bo‘lak necha marta uchraydi",en:"Count substring occurrences",difficulty:"medium",rating:1500,tag:"Pattern matching",points:200,topic:"strings",judge:"substring-occurrences",timeLimitMs:1000,memoryMb:256},
 {id:"B70",uz:"Minimal tangalar",en:"Minimum coins",difficulty:"medium",rating:1600,tag:"DP",points:200,topic:"dynamic-programming",judge:"coin-change",timeLimitMs:1000,memoryMb:256},
 {id:"B71",uz:"Grafda sikl bormi",en:"Does the graph contain a cycle",difficulty:"medium",rating:1600,tag:"DFS",points:200,topic:"graphs",judge:"cycle-detect-undirected",timeLimitMs:1000,memoryMb:256},
 {id:"B72",uz:"Inversiyalar soni",en:"Count inversions",difficulty:"medium",rating:1600,tag:"Inversions",points:200,topic:"sorting",judge:"inversion-count",timeLimitMs:1000,memoryMb:256},
 {id:"B73",uz:"Panjarada eng arzon yo‘l",en:"Cheapest path in a grid",difficulty:"medium",rating:1600,tag:"Grid DP",points:200,topic:"dynamic-programming",judge:"min-path-sum",timeLimitMs:1000,memoryMb:256},
 {id:"B74",uz:"Nechta perron kerak",en:"Minimum platforms",difficulty:"medium",rating:1600,tag:"Greedy",points:200,topic:"greedy",judge:"min-platforms",timeLimitMs:1000,memoryMb:256},
 {id:"B75",uz:"Yig‘indisi k ga teng qism-massivlar",en:"Subarrays with sum k",difficulty:"medium",rating:1600,tag:"Prefix sum",points:200,topic:"two-pointers",judge:"subarray-sum-k",timeLimitMs:1000,memoryMb:256},
 {id:"B76",uz:"Topologik tartib mumkinmi",en:"Is a topological order possible",difficulty:"medium",rating:1600,tag:"Topological sort",points:200,topic:"graphs",judge:"topological-possible",timeLimitMs:1000,memoryMb:256},
 {id:"B77",uz:"Graf ikki bo‘lakli mi",en:"Is the graph bipartite",difficulty:"medium",rating:1700,tag:"Bipartite",points:200,topic:"graphs",judge:"bipartite-check",timeLimitMs:1000,memoryMb:256},
 {id:"B78",uz:"Konfet taqsimoti",en:"Candy distribution",difficulty:"medium",rating:1700,tag:"Greedy",points:200,topic:"greedy",judge:"candy-distribution",timeLimitMs:1000,memoryMb:256},
 {id:"B79",uz:"Tanga kombinatsiyalari",en:"Coin combinations",difficulty:"medium",rating:1700,tag:"DP",points:200,topic:"dynamic-programming",judge:"coin-ways",timeLimitMs:1000,memoryMb:256},
 {id:"B80",uz:"Birlashtirish va so‘rov",en:"Union and find",difficulty:"medium",rating:1700,tag:"DSU",points:200,topic:"data-structures",judge:"dsu-queries",timeLimitMs:1000,memoryMb:256},
 {id:"B81",uz:"0/1 ryukzak",en:"0/1 knapsack",difficulty:"medium",rating:1700,tag:"Knapsack",points:200,topic:"dynamic-programming",judge:"knapsack-01",timeLimitMs:1000,memoryMb:256},
 {id:"B82",uz:"Eng uzun o‘suvchi ketma-ketlik",en:"Longest increasing subsequence",difficulty:"medium",rating:1700,tag:"LIS",points:200,topic:"dynamic-programming",judge:"lis-length",timeLimitMs:1000,memoryMb:256},
 {id:"B83",uz:"Massiv medianasi",en:"Median of the array",difficulty:"medium",rating:1700,tag:"Heap",points:200,topic:"data-structures",judge:"median-stream",timeLimitMs:1000,memoryMb:256},
 {id:"B84",uz:"Eng kam sakrash",en:"Minimum jumps",difficulty:"medium",rating:1700,tag:"Greedy DP",points:200,topic:"dynamic-programming",judge:"min-jumps",timeLimitMs:1000,memoryMb:256},
 {id:"B85",uz:"Modul bo‘yicha teskari element",en:"Modular inverse",difficulty:"medium",rating:1700,tag:"Number theory",points:200,topic:"math",judge:"modular-inverse",timeLimitMs:1000,memoryMb:256},
 {id:"B86",uz:"Eng katta subtree",en:"Largest subtree",difficulty:"medium",rating:1700,tag:"Tree DP",points:200,topic:"trees",judge:"tree-subtree-sizes",timeLimitMs:1000,memoryMb:256},
 {id:"B87",uz:"Eng katta suv idishi",en:"Container with most water",difficulty:"medium",rating:1700,tag:"Two pointers",points:200,topic:"two-pointers",judge:"water-container",timeLimitMs:1000,memoryMb:256},
 {id:"C88",uz:"Bo‘laklarning eng kichik maksimumi",en:"Minimise the largest part",difficulty:"hard",rating:1800,tag:"Binary search on answer",points:300,topic:"binary-search",judge:"binary-answer-split",timeLimitMs:1000,memoryMb:256},
 {id:"C89",uz:"Binomial koeffitsiyent",en:"Binomial coefficient",difficulty:"hard",rating:1800,tag:"Combinatorics",points:300,topic:"math",judge:"binomial-mod",timeLimitMs:1000,memoryMb:256},
 {id:"C90",uz:"Farqli bo‘laklar soni",en:"Count distinct substrings",difficulty:"hard",rating:1800,tag:"Hashing",points:300,topic:"strings",judge:"distinct-substrings-small",timeLimitMs:1000,memoryMb:256},
 {id:"C91",uz:"Oraliqni qoplash",en:"Cover the segment",difficulty:"hard",rating:1800,tag:"Greedy",points:300,topic:"greedy",judge:"interval-cover",timeLimitMs:1000,memoryMb:256},
 {id:"C92",uz:"Eng uzun umumiy qism-ketma-ketlik",en:"Longest common subsequence",difficulty:"hard",rating:1800,tag:"DP on strings",points:300,topic:"dynamic-programming",judge:"lcs-length",timeLimitMs:1000,memoryMb:256},
 {id:"C93",uz:"Teng ikkiga bo‘lish",en:"Equal partition",difficulty:"hard",rating:1800,tag:"Subset sum",points:300,topic:"dynamic-programming",judge:"partition-equal",timeLimitMs:1000,memoryMb:256},
 {id:"C94",uz:"Qism to‘plam yig‘indisi",en:"Subset sum",difficulty:"hard",rating:1800,tag:"Subset sum",points:300,topic:"backtracking",judge:"subset-sum-exists",timeLimitMs:1000,memoryMb:256},
 {id:"C95",uz:"Tree diametri",en:"Tree diameter",difficulty:"hard",rating:1800,tag:"Tree",points:300,topic:"trees",judge:"tree-diameter",timeLimitMs:1000,memoryMb:256},
 {id:"C96",uz:"Eng qisqa yo‘l (vaznli)",en:"Shortest path with weights",difficulty:"hard",rating:1900,tag:"Dijkstra",points:300,topic:"graphs",judge:"dijkstra-shortest",timeLimitMs:1000,memoryMb:256},
 {id:"C97",uz:"Tahrirlash masofasi",en:"Edit distance",difficulty:"hard",rating:1900,tag:"DP on strings",points:300,topic:"dynamic-programming",judge:"edit-distance",timeLimitMs:1000,memoryMb:256},
 {id:"C98",uz:"Eng uzun palindrom qism-ketma-ketlik",en:"Longest palindromic subsequence",difficulty:"hard",rating:1900,tag:"DP on strings",points:300,topic:"dynamic-programming",judge:"longest-palindrome-sub",timeLimitMs:1000,memoryMb:256},
 {id:"C99",uz:"Minimum spanning tree",en:"Minimum spanning tree",difficulty:"hard",rating:1900,tag:"MST",points:300,topic:"graphs",judge:"mst-weight",timeLimitMs:1000,memoryMb:256},
 {id:"C100",uz:"Farzinlar masalasi",en:"N queens",difficulty:"hard",rating:1900,tag:"Backtracking",points:300,topic:"backtracking",judge:"nqueens-count",timeLimitMs:1000,memoryMb:256},
 {id:"C101",uz:"To‘plangan yomg‘ir suvi",en:"Trapping rain water",difficulty:"hard",rating:1900,tag:"Two pointers",points:300,topic:"two-pointers",judge:"trapping-rain",timeLimitMs:1000,memoryMb:256},
 {id:"B102",uz:"Nuqta to‘rtburchak ichidami",en:"Point inside a rectangle",difficulty:"medium",rating:1200,tag:"Geometry",points:200,topic:"geometry",judge:"point-in-rect",timeLimitMs:1000,memoryMb:256},
 {id:"B103",uz:"Daraxt balandligi",en:"Tree height",difficulty:"medium",rating:1300,tag:"Tree",points:200,topic:"trees",judge:"tree-height",timeLimitMs:1000,memoryMb:256},
 {id:"B104",uz:"Shartga mos qism to‘plamlar",en:"Subsets meeting a bound",difficulty:"medium",rating:1400,tag:"Backtracking",points:200,topic:"backtracking",judge:"subset-generate-count",timeLimitMs:1000,memoryMb:256},
 {id:"B105",uz:"Ikki saralangan massivni birlashtirish",en:"Merge two sorted arrays",difficulty:"medium",rating:1400,tag:"Merge sort",points:200,topic:"sorting",judge:"merge-sort-manual",timeLimitMs:1000,memoryMb:256},
 {id:"B106",uz:"Ko‘pburchak yuzi",en:"Polygon area",difficulty:"medium",rating:1500,tag:"Geometry",points:200,topic:"geometry",judge:"polygon-area2",timeLimitMs:1000,memoryMb:256},
 {id:"B107",uz:"Ikki kalit bo‘yicha tartiblash",en:"Sort by two keys",difficulty:"medium",rating:1500,tag:"Custom comparator",points:200,topic:"sorting",judge:"bucket-by-key",timeLimitMs:1000,memoryMb:256},
 {id:"B108",uz:"Haqiqiy son ustida qidiruv",en:"Binary search on reals",difficulty:"medium",rating:1600,tag:"Real binary search",points:200,topic:"binary-search",judge:"bs-sqrt-real",timeLimitMs:1000,memoryMb:256},
 {id:"B109",uz:"O‘rin almashtirish tartibi",en:"Permutation rank",difficulty:"medium",rating:1700,tag:"Combinatorics",points:200,topic:"backtracking",judge:"permutation-rank",timeLimitMs:1000,memoryMb:256},
 {id:"C110",uz:"Nim o‘yini",en:"Nim",difficulty:"hard",rating:1800,tag:"Game theory",points:300,topic:"advanced-cp",judge:"game-nim",timeLimitMs:1000,memoryMb:256},
 {id:"C111",uz:"Eng kichik sig‘im",en:"Smallest workable capacity",difficulty:"hard",rating:1800,tag:"Binary search on answer",points:300,topic:"binary-search",judge:"bs-min-capacity",timeLimitMs:1000,memoryMb:256},
 {id:"C112",uz:"Statik oraliq minimumi",en:"Static range minimum",difficulty:"hard",rating:1900,tag:"Sparse table",points:300,topic:"advanced-cp",judge:"sparse-min",timeLimitMs:1000,memoryMb:256},
 {id:"C113",uz:"Qavariq qobiq uchlari",en:"Convex hull size",difficulty:"hard",rating:1900,tag:"Convex hull",points:300,topic:"geometry",judge:"convex-hull-size",timeLimitMs:1000,memoryMb:256},
 {id:"C114",uz:"Daraxt markazi",en:"Tree centroid",difficulty:"hard",rating:1900,tag:"Tree",points:300,topic:"trees",judge:"tree-centroid",timeLimitMs:1000,memoryMb:256},
 {id:"C115",uz:"Oraliqdagi farqli qiymatlar",en:"Distinct values in a range",difficulty:"hard",rating:2000,tag:"Offline queries",points:400,topic:"advanced-cp",judge:"mo-offline-distinct",timeLimitMs:1000,memoryMb:256},
 {id:"C116",uz:"Katta Fibonachchi",en:"Fibonacci at scale",difficulty:"hard",rating:2000,tag:"Matrix exponentiation",points:400,topic:"advanced-cp",judge:"matrix-power-fib",timeLimitMs:1000,memoryMb:256},
 {id:"C117",uz:"Ikki shartli qanoatlantirish",en:"Two-clause satisfiability",difficulty:"insane",rating:2100,tag:"2-SAT",points:400,topic:"advanced-cp",judge:"two-sat-simple",timeLimitMs:1000,memoryMb:256},
 {id:"C118",uz:"Daraxtdagi yo‘l yig‘indisi",en:"Path sum on a tree",difficulty:"insane",rating:2100,tag:"Tree paths",points:400,topic:"advanced-cp",judge:"hld-path-sum",timeLimitMs:1000,memoryMb:256},
 {id:"A119",uz:"n ta sonni o‘qib yig‘ing",en:"Read n numbers and sum them",difficulty:"easy",rating:800,tag:"Implementation",points:100,topic:"programming-basics",judge:"io-echo-sum",timeLimitMs:1000,memoryMb:256},
 {id:"A120",uz:"Ikki qiymatni almashtirish",en:"Swap two values",difficulty:"easy",rating:800,tag:"Implementation",points:100,topic:"programming-basics",judge:"var-swap",timeLimitMs:1000,memoryMb:256},
 {id:"A121",uz:"Baho aniqlash",en:"Assign a grade",difficulty:"easy",rating:800,tag:"Conditions",points:100,topic:"programming-basics",judge:"cond-grade",timeLimitMs:1000,memoryMb:256},
 {id:"A122",uz:"k ga bo‘linadiganlar",en:"Multiples of k",difficulty:"easy",rating:800,tag:"Loops",points:100,topic:"programming-basics",judge:"loop-multiples",timeLimitMs:1000,memoryMb:256},
 {id:"A123",uz:"Uchta sonning eng kichigi",en:"Minimum of three",difficulty:"easy",rating:800,tag:"Functions",points:100,topic:"programming-basics",judge:"func-min-of-three",timeLimitMs:1000,memoryMb:256},
 {id:"A124",uz:"Ikkining darajalari",en:"Powers of two",difficulty:"easy",rating:900,tag:"Loops",points:100,topic:"programming-basics",judge:"loop-power-table",timeLimitMs:1000,memoryMb:256},
 {id:"A125",uz:"Indeks bo‘yicha so‘rov",en:"Query by index",difficulty:"easy",rating:900,tag:"Arrays",points:100,topic:"programming-basics",judge:"array-index-query",timeLimitMs:1000,memoryMb:256},
 {id:"A126",uz:"x dan kattalar soni",en:"Count values greater than x",difficulty:"easy",rating:900,tag:"Arrays",points:100,topic:"programming-basics",judge:"array-count-greater",timeLimitMs:1000,memoryMb:256},
 {id:"A127",uz:"Katta harfga o‘tkazish",en:"Convert to uppercase",difficulty:"easy",rating:900,tag:"Strings",points:100,topic:"programming-basics",judge:"string-upper",timeLimitMs:1000,memoryMb:256},
 {id:"A128",uz:"Belgi necha marta uchraydi",en:"Count a character",difficulty:"easy",rating:900,tag:"Strings",points:100,topic:"programming-basics",judge:"string-count-char",timeLimitMs:1000,memoryMb:256},
 {id:"A129",uz:"Satrlar yig‘indisi",en:"Row sums",difficulty:"easy",rating:1000,tag:"Matrices",points:100,topic:"programming-basics",judge:"matrix-row-sums",timeLimitMs:1000,memoryMb:256},
 {id:"A130",uz:"Saralab, takrorlarni olib tashlash",en:"Sort and deduplicate",difficulty:"easy",rating:1000,tag:"STL",points:100,topic:"programming-basics",judge:"stl-sort-unique",timeLimitMs:1000,memoryMb:256},
 {id:"A131",uz:"Amallar sonini baholash",en:"Estimate the operation count",difficulty:"easy",rating:1000,tag:"Complexity",points:100,topic:"foundations",judge:"complexity-ops",timeLimitMs:1000,memoryMb:256},
 {id:"A132",uz:"Eng yomon holatda nechta solishtirish",en:"Comparisons in the worst case",difficulty:"easy",rating:1000,tag:"Complexity",points:100,topic:"foundations",judge:"worst-case-scan",timeLimitMs:1000,memoryMb:256},
 {id:"A133",uz:"Xotira hajmini baholash",en:"Estimate memory use",difficulty:"easy",rating:1100,tag:"Memory",points:100,topic:"foundations",judge:"memory-estimate",timeLimitMs:1000,memoryMb:256},
 {id:"A134",uz:"Cheklovga mos murakkablik",en:"Pick the complexity",difficulty:"easy",rating:1100,tag:"Constraints",points:100,topic:"foundations",judge:"constraint-pick",timeLimitMs:1000,memoryMb:256},
 {id:"A135",uz:"Nechta bo‘linish kerak",en:"How many halvings",difficulty:"easy",rating:1100,tag:"Complexity",points:100,topic:"foundations",judge:"log-steps",timeLimitMs:1000,memoryMb:256},
 {id:"B136",uz:"Vektor kengayishi",en:"Vector growth",difficulty:"medium",rating:1200,tag:"Amortised analysis",points:200,topic:"foundations",judge:"amortized-doubling",timeLimitMs:1000,memoryMb:256},
 {id:"B137",uz:"Eng ko‘p qo‘shnisi bor tugun",en:"Highest degree vertex",difficulty:"medium",rating:1200,tag:"Graph basics",points:200,topic:"graphs",judge:"graph-degree-max",timeLimitMs:1000,memoryMb:256},
 {id:"B138",uz:"Navbatni aylantirish",en:"Rotate a queue",difficulty:"medium",rating:1300,tag:"Queue",points:200,topic:"data-structures",judge:"queue-rotate",timeLimitMs:1000,memoryMb:256},
 {id:"B139",uz:"Yo‘q bo‘lgan eng kichik musbat son",en:"Smallest missing positive",difficulty:"medium",rating:1300,tag:"Set",points:200,topic:"data-structures",judge:"set-missing-smallest",timeLimitMs:1000,memoryMb:256},
 {id:"B140",uz:"Eng ko‘p uchragan so‘z",en:"Most frequent word",difficulty:"medium",rating:1300,tag:"Hash map",points:200,topic:"data-structures",judge:"map-word-freq",timeLimitMs:1000,memoryMb:256},
 {id:"B141",uz:"Yo‘l bormi",en:"Is there a path",difficulty:"medium",rating:1300,tag:"DFS",points:200,topic:"graphs",judge:"graph-path-exists",timeLimitMs:1000,memoryMb:256},
 {id:"B142",uz:"Qirralar og‘irligi yig‘indisi",en:"Total edge weight",difficulty:"medium",rating:1300,tag:"Graph basics",points:200,topic:"graphs",judge:"graph-weight-total",timeLimitMs:1000,memoryMb:256},
 {id:"B143",uz:"Postfiks ifodani hisoblash",en:"Evaluate postfix",difficulty:"medium",rating:1400,tag:"Stack",points:200,topic:"data-structures",judge:"stack-postfix",timeLimitMs:1000,memoryMb:256},
 {id:"B144",uz:"Graf daraxtmi",en:"Is the graph a tree",difficulty:"medium",rating:1400,tag:"Graph basics",points:200,topic:"graphs",judge:"graph-count-edges-tree",timeLimitMs:1000,memoryMb:256},
 {id:"B145",uz:"Boshlang‘ich vazifalar",en:"Tasks with no prerequisite",difficulty:"medium",rating:1400,tag:"Topological sort",points:200,topic:"graphs",judge:"graph-indegree-zero",timeLimitMs:1000,memoryMb:256},
 {id:"B146",uz:"Eng katta to‘plam",en:"Largest set",difficulty:"medium",rating:1600,tag:"DSU",points:200,topic:"data-structures",judge:"dsu-largest-set",timeLimitMs:1000,memoryMb:256},
 {id:"B147",uz:"Orollar soni",en:"Count the islands",difficulty:"medium",rating:1600,tag:"Flood fill",points:200,topic:"graphs",judge:"grid-count-islands",timeLimitMs:1000,memoryMb:256},
 {id:"B148",uz:"Eng uzoq tugun",en:"Farthest vertex",difficulty:"medium",rating:1600,tag:"BFS",points:200,topic:"graphs",judge:"graph-farthest",timeLimitMs:1000,memoryMb:256},
 {id:"B149",uz:"Birlashtirish narxi",en:"Cost of merging",difficulty:"medium",rating:1700,tag:"Heap",points:200,topic:"data-structures",judge:"heap-merge-cost",timeLimitMs:1000,memoryMb:256},
 {id:"B150",uz:"Ikki bo‘lak hajmi",en:"Sizes of the two sides",difficulty:"medium",rating:1700,tag:"Bipartite",points:200,topic:"graphs",judge:"graph-bfs-bipartite-sides",timeLimitMs:1000,memoryMb:256},
 {id:"C151",uz:"Oynadagi minimum",en:"Sliding window minimum",difficulty:"hard",rating:1800,tag:"Deque",points:300,topic:"data-structures",judge:"deque-window-min",timeLimitMs:1000,memoryMb:256},
 {id:"C152",uz:"Ikki o‘lchovli prefiks yig‘indi",en:"2D prefix sums",difficulty:"hard",rating:1800,tag:"2D prefix sum",points:300,topic:"data-structures",judge:"prefix-2d-sum",timeLimitMs:1000,memoryMb:256},
 {id:"C153",uz:"Yangilanadigan prefiks yig‘indi",en:"Prefix sums with updates",difficulty:"hard",rating:1900,tag:"Fenwick tree",points:300,topic:"data-structures",judge:"bit-fenwick-sum",timeLimitMs:1000,memoryMb:256},
 {id:"C154",uz:"Barcha tugunlargacha masofa",en:"Distance to every vertex",difficulty:"hard",rating:1900,tag:"Dijkstra",points:300,topic:"graphs",judge:"dijkstra-all-dist",timeLimitMs:1000,memoryMb:256},
 {id:"A155",uz:"Kamayish tartibida saralash",en:"Sort in descending order",difficulty:"easy",rating:1000,tag:"Sorting",points:100,topic:"sorting",judge:"sort-descending",timeLimitMs:1000,memoryMb:256},
 {id:"B156",uz:"Modul bo‘yicha saralash",en:"Sort by absolute value",difficulty:"medium",rating:1200,tag:"Custom comparator",points:200,topic:"sorting",judge:"sort-abs",timeLimitMs:1000,memoryMb:256},
 {id:"B157",uz:"Uzunlik bo‘yicha saralash",en:"Sort by length",difficulty:"medium",rating:1200,tag:"Custom comparator",points:200,topic:"sorting",judge:"sort-by-length",timeLimitMs:1000,memoryMb:256},
 {id:"B158",uz:"Kanonik tanga tizimi",en:"Canonical coin system",difficulty:"medium",rating:1300,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-coin-canonical",timeLimitMs:1000,memoryMb:256},
 {id:"B159",uz:"Birinchi buzuq versiya",en:"First bad version",difficulty:"medium",rating:1300,tag:"Binary search",points:200,topic:"binary-search",judge:"bs-first-bad",timeLimitMs:1000,memoryMb:256},
 {id:"B160",uz:"Eng kichik juftlik farqi",en:"Smallest adjacent difference",difficulty:"medium",rating:1400,tag:"Sorting",points:200,topic:"sorting",judge:"sort-median-pairs",timeLimitMs:1000,memoryMb:256},
 {id:"B161",uz:"k-chi eng kichik",en:"k-th smallest",difficulty:"medium",rating:1400,tag:"Sorting",points:200,topic:"sorting",judge:"sort-kth-smallest",timeLimitMs:1000,memoryMb:256},
 {id:"B162",uz:"Eng ko‘p juftlik",en:"Maximum pairings",difficulty:"medium",rating:1400,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-max-pairs",timeLimitMs:1000,memoryMb:256},
 {id:"B163",uz:"Element necha marta uchraydi",en:"Count occurrences",difficulty:"medium",rating:1400,tag:"Binary search",points:200,topic:"binary-search",judge:"bs-count-occurrences",timeLimitMs:1000,memoryMb:256},
 {id:"B164",uz:"Anagram guruhlari",en:"Anagram groups",difficulty:"medium",rating:1500,tag:"Sorting",points:200,topic:"sorting",judge:"sort-anagram-group",timeLimitMs:1000,memoryMb:256},
 {id:"B165",uz:"Berilgan tartib bo‘yicha saralash",en:"Sort by a given order",difficulty:"medium",rating:1500,tag:"Custom comparator",points:200,topic:"sorting",judge:"sort-relative-order",timeLimitMs:1000,memoryMb:256},
 {id:"B166",uz:"Bir kunda eng ko‘p tadbir",en:"Most events in a day",difficulty:"medium",rating:1500,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-max-events",timeLimitMs:1000,memoryMb:256},
 {id:"B167",uz:"Yig‘indisi k dan kichik juftliklar",en:"Pairs summing below k",difficulty:"medium",rating:1600,tag:"Two pointers",points:200,topic:"sorting",judge:"sort-count-pairs-less",timeLimitMs:1000,memoryMb:256},
 {id:"B168",uz:"Yoqilg‘i bekatlari",en:"Refuelling stops",difficulty:"medium",rating:1600,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-min-jumps-fuel",timeLimitMs:1000,memoryMb:256},
 {id:"B169",uz:"Eng kam antenna",en:"Fewest transmitters",difficulty:"medium",rating:1600,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-station-cover",timeLimitMs:1000,memoryMb:256},
 {id:"B170",uz:"k ta raqamni olib tashlash",en:"Remove k digits",difficulty:"medium",rating:1700,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-remove-digits",timeLimitMs:1000,memoryMb:256},
 {id:"B171",uz:"Aylantirilgan massiv minimumi",en:"Minimum of a rotated array",difficulty:"medium",rating:1700,tag:"Binary search",points:200,topic:"binary-search",judge:"bs-rotated-min",timeLimitMs:1000,memoryMb:256},
 {id:"C172",uz:"Eng katta minimal masofa",en:"Largest minimum distance",difficulty:"hard",rating:1900,tag:"Binary search on answer",points:300,topic:"binary-search",judge:"bs-max-min-distance",timeLimitMs:1000,memoryMb:256},
 {id:"B173",uz:"Barcha ikkilik satrlar",en:"All binary strings",difficulty:"medium",rating:1200,tag:"Backtracking",points:200,topic:"backtracking",judge:"bt-generate-binary",timeLimitMs:1000,memoryMb:256},
 {id:"B174",uz:"Kvadrat masofa",en:"Squared distance",difficulty:"medium",rating:1200,tag:"Geometry",points:200,topic:"geometry",judge:"geo-distance-int",timeLimitMs:1000,memoryMb:256},
 {id:"B175",uz:"Ko‘pburchak perimetri",en:"Polygon perimeter",difficulty:"medium",rating:1300,tag:"Geometry",points:200,topic:"geometry",judge:"geo-perimeter",timeLimitMs:1000,memoryMb:256},
 {id:"B176",uz:"Umumiy prefiks",en:"Longest common prefix",difficulty:"medium",rating:1300,tag:"Strings",points:200,topic:"strings",judge:"str-longest-common-prefix",timeLimitMs:1000,memoryMb:256},
 {id:"B177",uz:"So‘zlarni teskari tartibda",en:"Reverse the word order",difficulty:"medium",rating:1300,tag:"Strings",points:200,topic:"strings",judge:"str-reverse-words",timeLimitMs:1000,memoryMb:256},
 {id:"B178",uz:"Uch nuqta bir chiziqdami",en:"Are three points collinear",difficulty:"medium",rating:1400,tag:"Geometry",points:200,topic:"geometry",judge:"geo-collinear",timeLimitMs:1000,memoryMb:256},
 {id:"B179",uz:"Radius ichidagi nuqtalar",en:"Points inside the radius",difficulty:"medium",rating:1400,tag:"Geometry",points:200,topic:"geometry",judge:"geo-manhattan-circle",timeLimitMs:1000,memoryMb:256},
 {id:"B180",uz:"Tugun chuqurligi",en:"Depth of a node",difficulty:"medium",rating:1400,tag:"Tree",points:200,topic:"trees",judge:"tree-parent-depth",timeLimitMs:1000,memoryMb:256},
 {id:"B181",uz:"Qatorni to‘ldirish",en:"Complete the row",difficulty:"medium",rating:1500,tag:"Constraints",points:200,topic:"backtracking",judge:"bt-sudoku-row",timeLimitMs:1000,memoryMb:256},
 {id:"B182",uz:"Devorlar orasidan yo‘llar",en:"Paths around walls",difficulty:"medium",rating:1500,tag:"Grid search",points:200,topic:"backtracking",judge:"bt-count-paths-grid",timeLimitMs:1000,memoryMb:256},
 {id:"B183",uz:"Farqli o‘rin almashtirishlar",en:"Distinct permutations",difficulty:"medium",rating:1500,tag:"Backtracking",points:200,topic:"backtracking",judge:"bt-string-permutations",timeLimitMs:1000,memoryMb:256},
 {id:"B184",uz:"To‘rtburchaklar kesishuvi",en:"Rectangle overlap",difficulty:"medium",rating:1500,tag:"Geometry",points:200,topic:"geometry",judge:"geo-rect-overlap",timeLimitMs:1000,memoryMb:256},
 {id:"B185",uz:"Qo‘shni birlarsiz satrlar",en:"Strings with no adjacent ones",difficulty:"medium",rating:1600,tag:"Backtracking",points:200,topic:"backtracking",judge:"bt-no-adjacent-ones",timeLimitMs:1000,memoryMb:256},
 {id:"B186",uz:"Yig‘indisi n ga teng kombinatsiyalar",en:"Combinations summing to n",difficulty:"medium",rating:1600,tag:"Backtracking",points:200,topic:"backtracking",judge:"bt-sum-combinations",timeLimitMs:1000,memoryMb:256},
 {id:"B187",uz:"Ruxlarni joylash",en:"Place the rooks",difficulty:"medium",rating:1600,tag:"Backtracking",points:200,topic:"backtracking",judge:"bt-place-rooks",timeLimitMs:1000,memoryMb:256},
 {id:"B188",uz:"Kesmadagi butun nuqtalar",en:"Lattice points on a segment",difficulty:"medium",rating:1600,tag:"Number theory",points:200,topic:"geometry",judge:"geo-grid-lattice",timeLimitMs:1000,memoryMb:256},
 {id:"B189",uz:"Uzunligi 2 bo‘lgan yo‘llar",en:"Paths of length two",difficulty:"medium",rating:1600,tag:"Tree",points:200,topic:"trees",judge:"tree-count-paths-len2",timeLimitMs:1000,memoryMb:256},
 {id:"B190",uz:"Qism-daraxt yig‘indisi",en:"Subtree sums",difficulty:"medium",rating:1600,tag:"Tree DP",points:200,topic:"trees",judge:"tree-sum-subtree",timeLimitMs:1000,memoryMb:256},
 {id:"B191",uz:"Panjarada so‘z qidirish",en:"Find a word in the grid",difficulty:"medium",rating:1700,tag:"Grid search",points:200,topic:"backtracking",judge:"bt-word-paths",timeLimitMs:1000,memoryMb:256},
 {id:"B192",uz:"Ot eng kam yurishda",en:"Knight in fewest moves",difficulty:"medium",rating:1700,tag:"Search",points:200,topic:"backtracking",judge:"bt-knight-moves",timeLimitMs:1000,memoryMb:256},
 {id:"B193",uz:"Muvozanatli daraxtmi",en:"Is the tree balanced",difficulty:"medium",rating:1700,tag:"Tree",points:200,topic:"trees",judge:"tree-is-balanced",timeLimitMs:1000,memoryMb:256},
 {id:"C194",uz:"k ta teng qismga bo‘lish",en:"Split into k equal parts",difficulty:"hard",rating:1800,tag:"Backtracking",points:300,topic:"backtracking",judge:"bt-partition-into-k",timeLimitMs:1000,memoryMb:256},
 {id:"C195",uz:"Bir cho‘qqili funksiya maksimumi",en:"Peak of a unimodal array",difficulty:"hard",rating:1800,tag:"Ternary search",points:300,topic:"binary-search",judge:"bs-peak-ternary",timeLimitMs:1000,memoryMb:256},
 {id:"C196",uz:"Eng katta ko‘paytma",en:"Maximum product subarray",difficulty:"hard",rating:1900,tag:"DP",points:300,topic:"dynamic-programming",judge:"dp-max-product-subarray",timeLimitMs:1000,memoryMb:256},
 {id:"C197",uz:"Katta massivda inversiyalar",en:"Inversions at scale",difficulty:"hard",rating:2000,tag:"Divide and conquer",points:400,topic:"advanced-cp",judge:"adv-inversions-fast",timeLimitMs:1000,memoryMb:256},
 {id:"C198",uz:"Katta massivda LIS",en:"LIS at scale",difficulty:"hard",rating:2000,tag:"Divide and conquer",points:400,topic:"advanced-cp",judge:"adv-lis-nlogn",timeLimitMs:1000,memoryMb:256},
 {id:"C199",uz:"Kutilayotgan tashlashlar",en:"Expected number of rolls",difficulty:"hard",rating:2000,tag:"Probability",points:400,topic:"advanced-cp",judge:"adv-expected-rolls",timeLimitMs:1000,memoryMb:256},
 {id:"C200",uz:"Raqamlari yig‘indisi bo‘yicha sanash",en:"Count by digit sum",difficulty:"insane",rating:2100,tag:"Digit DP",points:400,topic:"advanced-cp",judge:"adv-digit-dp-count",timeLimitMs:1000,memoryMb:256},
 {id:"C201",uz:"Satrning eng qisqa davri",en:"Shortest period of a string",difficulty:"insane",rating:2100,tag:"Prefix function",points:400,topic:"strings",judge:"string-min-period",timeLimitMs:2000,memoryMb:256},
 {id:"C202",uz:"Satrning barcha chegaralari",en:"Every border of a string",difficulty:"insane",rating:2100,tag:"Prefix function",points:400,topic:"strings",judge:"string-all-borders",timeLimitMs:2000,memoryMb:256},
 {id:"C203",uz:"Eng uzun palindrom bo'lak",en:"Longest palindromic substring",difficulty:"insane",rating:2300,tag:"Manacher",points:400,topic:"strings",judge:"manacher-longest-pal",timeLimitMs:2000,memoryMb:256},
 {id:"C204",uz:"Palindrom bo'laklar soni",en:"Counting palindromic substrings",difficulty:"insane",rating:2400,tag:"Manacher",points:400,topic:"strings",judge:"count-palindromic-substrings",timeLimitMs:2000,memoryMb:256},
 {id:"C205",uz:"Nuqtaviy o'zgartirish, oraliqdagi maksimum",en:"Point update, range maximum",difficulty:"insane",rating:2100,tag:"Segment tree",points:400,topic:"data-structures",judge:"segtree-point-max",timeLimitMs:2000,memoryMb:256},
 {id:"C206",uz:"Oraliqqa qo'shish, oraliq yig'indisi",en:"Range add, range sum",difficulty:"insane",rating:2400,tag:"Lazy propagation",points:400,topic:"data-structures",judge:"segtree-lazy-range-add",timeLimitMs:2000,memoryMb:256},
 {id:"C207",uz:"O'zgarmas massivda oraliq minimumi",en:"Range minimum on a static array",difficulty:"insane",rating:2200,tag:"Sparse table",points:400,topic:"data-structures",judge:"sparse-table-rmq",timeLimitMs:2000,memoryMb:256},
 {id:"C208",uz:"Eng katta XOR juftlik",en:"Largest XOR of a pair",difficulty:"insane",rating:2200,tag:"Binary trie",points:400,topic:"data-structures",judge:"trie-max-xor",timeLimitMs:2000,memoryMb:256},
 {id:"C209",uz:"Kuchli bog'langan komponentalar soni",en:"Counting strongly connected components",difficulty:"insane",rating:2300,tag:"Strongly connected components",points:400,topic:"graphs",judge:"scc-count",timeLimitMs:2000,memoryMb:256},
 {id:"C210",uz:"Ko'priklar soni",en:"Counting bridges",difficulty:"insane",rating:2400,tag:"Bridges",points:400,topic:"graphs",judge:"bridges-count",timeLimitMs:2000,memoryMb:256},
 {id:"C211",uz:"Ajratuvchi tugunlar soni",en:"Counting articulation points",difficulty:"insane",rating:2400,tag:"Articulation points",points:400,topic:"graphs",judge:"articulation-count",timeLimitMs:2000,memoryMb:256},
 {id:"C212",uz:"Nol va bir vaznli eng qisqa yo'l",en:"Shortest path with 0 and 1 weights",difficulty:"hard",rating:2000,tag:"0-1 BFS",points:300,topic:"graphs",judge:"zero-one-bfs",timeLimitMs:2000,memoryMb:256},
 {id:"C213",uz:"Daraxtdagi ikki tugun orasidagi masofa",en:"Distance between two vertices of a tree",difficulty:"insane",rating:2300,tag:"Binary lifting",points:400,topic:"trees",judge:"lca-binary-lifting",timeLimitMs:2000,memoryMb:256},
 {id:"C214",uz:"Pastki daraxt yig'indisi va qiymat o'zgarishi",en:"Subtree sums with updates",difficulty:"insane",rating:2200,tag:"Euler tour",points:400,topic:"trees",judge:"euler-tour-subtree-sum",timeLimitMs:2000,memoryMb:256},
 {id:"C215",uz:"Daraxtdagi eng og'ir mustaqil to'plam",en:"Heaviest independent set in a tree",difficulty:"insane",rating:2200,tag:"Tree DP",points:400,topic:"trees",judge:"tree-dp-independent-set",timeLimitMs:2000,memoryMb:256},
 {id:"C216",uz:"Har bir tugundan boshqalargacha masofalar yig'indisi",en:"Sum of distances from every vertex",difficulty:"insane",rating:2500,tag:"Rerooting",points:400,topic:"trees",judge:"tree-rerooting-distances",timeLimitMs:2000,memoryMb:256},
 {id:"C217",uz:"Sayyoh yo'li (bitmaskali DP)",en:"The travelling salesman route",difficulty:"insane",rating:2300,tag:"Bitmask DP",points:400,topic:"dynamic-programming",judge:"tsp-bitmask",timeLimitMs:2000,memoryMb:256},
 {id:"C218",uz:"Ishchilarni vazifalarga taqsimlash",en:"Assigning workers to jobs",difficulty:"insane",rating:2200,tag:"Bitmask DP",points:400,topic:"dynamic-programming",judge:"bitmask-assignment",timeLimitMs:2000,memoryMb:256},
 {id:"C219",uz:"Barcha juftliklar orasidagi eng qisqa yo'llar",en:"Shortest paths between all pairs",difficulty:"insane",rating:2100,tag:"Floyd-Warshall",points:400,topic:"graphs",judge:"floyd-all-pairs",timeLimitMs:2000,memoryMb:256},
 {id:"C220",uz:"Manfiy halqa bormi?",en:"Is there a negative cycle?",difficulty:"insane",rating:2100,tag:"Bellman-Ford",points:400,topic:"graphs",judge:"bellman-negative-cycle",timeLimitMs:2000,memoryMb:256},
 {id:"C221",uz:"Eng katta juftlashtirish",en:"Maximum bipartite matching",difficulty:"insane",rating:2400,tag:"Bipartite matching",points:400,topic:"graphs",judge:"bipartite-matching-kuhn",timeLimitMs:2000,memoryMb:256},
 {id:"C222",uz:"Leksikografik eng kichik topologik tartib",en:"Lexicographically smallest topological order",difficulty:"insane",rating:2100,tag:"Topological sort",points:400,topic:"graphs",judge:"topo-lexicographic",timeLimitMs:2000,memoryMb:256},
 {id:"C223",uz:"Yo'ldagi eng og'ir qirrani kichraytirish",en:"Minimising the heaviest edge on a path",difficulty:"insane",rating:2300,tag:"Minimax path",points:400,topic:"graphs",judge:"minimax-path",timeLimitMs:2000,memoryMb:256},
 {id:"C224",uz:"Eng qisqa yo'llar soni",en:"Counting shortest paths",difficulty:"insane",rating:2200,tag:"Dijkstra",points:400,topic:"graphs",judge:"dijkstra-count-paths",timeLimitMs:2000,memoryMb:256},
 {id:"C225",uz:"Chiziqli diofant tenglama",en:"A linear Diophantine equation",difficulty:"insane",rating:2100,tag:"Extended Euclid",points:400,topic:"math",judge:"ext-gcd-diophantine",timeLimitMs:1000,memoryMb:256},
 {id:"C226",uz:"Ikki taqqoslamani birlashtirish",en:"Merging two congruences",difficulty:"insane",rating:2400,tag:"Chinese remainder theorem",points:400,topic:"math",judge:"crt-two-congruences",timeLimitMs:1000,memoryMb:256},
 {id:"C227",uz:"Eyler funksiyasining yig'indisi",en:"Summing Euler's totient",difficulty:"insane",rating:2100,tag:"Euler totient",points:400,topic:"math",judge:"euler-phi-sum",timeLimitMs:2000,memoryMb:256},
 {id:"C228",uz:"Katta sonning tubligi",en:"Primality of a large number",difficulty:"insane",rating:2400,tag:"Miller-Rabin",points:400,topic:"math",judge:"miller-rabin-prime",timeLimitMs:2000,memoryMb:256},
 {id:"C229",uz:"O'zaro tub juftliklar soni",en:"Counting coprime pairs",difficulty:"insane",rating:2300,tag:"Mobius inversion",points:400,topic:"math",judge:"count-coprime-pairs",timeLimitMs:2000,memoryMb:256},
 {id:"C230",uz:"Chiziqli rekurrentning uzoq hadi",en:"A distant term of a linear recurrence",difficulty:"insane",rating:2300,tag:"Matrix exponentiation",points:400,topic:"math",judge:"matrix-power-linear-rec",timeLimitMs:2000,memoryMb:256},
 {id:"C232",uz:"Eng yaqin ikki nuqta",en:"The closest pair of points",difficulty:"insane",rating:2500,tag:"Sweep line",points:400,topic:"geometry",judge:"closest-pair-points",timeLimitMs:3000,memoryMb:256},
 {id:"C233",uz:"Nuqta qavariq ko'pburchak ichidami?",en:"Is the point inside the convex polygon?",difficulty:"insane",rating:2300,tag:"Convex polygon",points:400,topic:"geometry",judge:"point-in-convex-polygon",timeLimitMs:2000,memoryMb:256},
 {id:"C234",uz:"Ikki kesma kesishadimi?",en:"Do two segments intersect?",difficulty:"insane",rating:2200,tag:"Segment intersection",points:400,topic:"geometry",judge:"segment-intersection",timeLimitMs:1000,memoryMb:256},
 {id:"C235",uz:"Ko'pburchak ichidagi butun nuqtalar",en:"Lattice points inside a polygon",difficulty:"insane",rating:2200,tag:"Pick's theorem",points:400,topic:"geometry",judge:"picks-theorem-interior",timeLimitMs:1000,memoryMb:256},
 {id:"C236",uz:"Ayirish o'yini",en:"The subtraction game",difficulty:"insane",rating:2300,tag:"Sprague-Grundy",points:400,topic:"math",judge:"grundy-subtraction-game",timeLimitMs:2000,memoryMb:256},
 {id:"C231",uz:"Nuqtalar to'plamining diametri",en:"Diameter of a point set",difficulty:"insane",rating:2400,tag:"Rotating calipers",points:400,topic:"geometry",judge:"polygon-diameter",timeLimitMs:2000,memoryMb:256},
 {id:"C237",uz:"Eng uzun takrorlanuvchi bo'lak",en:"Longest repeated substring",difficulty:"insane",rating:2700,tag:"Suffix array",points:400,topic:"advanced-cp",judge:"suffix-array-lrs",timeLimitMs:3000,memoryMb:256},
 {id:"C238",uz:"Ko'p naqshni bir yo'la qidirish",en:"Searching for many patterns at once",difficulty:"insane",rating:2600,tag:"Aho-Corasick",points:400,topic:"strings",judge:"aho-corasick-count",timeLimitMs:3000,memoryMb:256},
 {id:"C239",uz:"Pastki daraxtdagi turli ranglar",en:"Distinct colours in each subtree",difficulty:"insane",rating:2600,tag:"Small to large",points:400,topic:"trees",judge:"subtree-distinct-colors",timeLimitMs:3000,memoryMb:256},
 {id:"C240",uz:"Uzunligi k dan oshmagan yo'llar",en:"Paths no longer than k",difficulty:"insane",rating:2800,tag:"Centroid decomposition",points:400,topic:"advanced-cp",judge:"centroid-paths-within-k",timeLimitMs:3000,memoryMb:256},
 {id:"C241",uz:"Sakrashlar narxi (chiziqlar qobig'i)",en:"The cost of jumping (convex hull trick)",difficulty:"insane",rating:2700,tag:"Convex hull trick",points:400,topic:"advanced-cp",judge:"convex-hull-trick-dp",timeLimitMs:3000,memoryMb:256},
 {id:"C242",uz:"Massivni k qismga bo'lish",en:"Splitting an array into k parts",difficulty:"insane",rating:2600,tag:"Divide and conquer DP",points:400,topic:"advanced-cp",judge:"divide-conquer-dp-split",timeLimitMs:3000,memoryMb:256},
 {id:"C243",uz:"Massivni kamaymaydigan qilish",en:"Making an array non-decreasing",difficulty:"insane",rating:2700,tag:"Slope trick",points:400,topic:"advanced-cp",judge:"slope-trick-nondecreasing",timeLimitMs:2000,memoryMb:256},
 {id:"C244",uz:"Tarmoqdagi maksimal oqim",en:"Maximum flow in a network",difficulty:"insane",rating:2600,tag:"Max flow",points:400,topic:"graphs",judge:"dinic-max-flow",timeLimitMs:3000,memoryMb:256},
 {id:"C245",uz:"Ko'plikdagi k-chi element",en:"The k-th element of a multiset",difficulty:"insane",rating:2300,tag:"Fenwick descent",points:400,topic:"data-structures",judge:"fenwick-kth-element",timeLimitMs:2000,memoryMb:256},
 {id:"C246",uz:"Ko'phadlarni ko'paytirish",en:"Multiplying polynomials",difficulty:"insane",rating:2800,tag:"NTT",points:400,topic:"advanced-cp",judge:"ntt-polynomial-multiply",timeLimitMs:3000,memoryMb:256},
 {id:"C247",uz:"Z-funksiya qiymatlari yig'indisi",en:"Summing the Z-function",difficulty:"insane",rating:2200,tag:"Z-function",points:400,topic:"strings",judge:"z-function-sum",timeLimitMs:2000,memoryMb:256},
 {id:"C248",uz:"Oraliqqa qo'shish, oxirida o'qish",en:"Range additions, read at the end",difficulty:"hard",rating:1800,tag:"Difference array",points:300,topic:"data-structures",judge:"diff-array-range-add",timeLimitMs:1000,memoryMb:256},
 {id:"C249",uz:"Matritsadagi to'rtburchak yig'indisi",en:"Rectangle sums in a matrix",difficulty:"hard",rating:1800,tag:"2D prefix sums",points:300,topic:"data-structures",judge:"prefix-sum-2d",timeLimitMs:2000,memoryMb:256},
 {id:"C250",uz:"Siljuvchi oynaning minimumi",en:"Minimum of a sliding window",difficulty:"hard",rating:1900,tag:"Monotonic deque",points:300,topic:"two-pointers",judge:"sliding-window-min",timeLimitMs:2000,memoryMb:256},
 {id:"C251",uz:"Ko'pi bilan k xil qiymatli eng uzun bo'lak",en:"Longest stretch with at most k distinct values",difficulty:"hard",rating:1800,tag:"Sliding window",points:300,topic:"two-pointers",judge:"longest-k-distinct",timeLimitMs:1000,memoryMb:256},
 {id:"C252",uz:"Eng katta yig'indili to'rtburchak",en:"The rectangle with the largest sum",difficulty:"hard",rating:2000,tag:"Kadane 2D",points:300,topic:"dynamic-programming",judge:"max-submatrix-sum",timeLimitMs:2000,memoryMb:256},
 {id:"C253",uz:"Eng yaqin manbagacha masofa",en:"Distance to the nearest source",difficulty:"hard",rating:1800,tag:"Multi-source BFS",points:300,topic:"graphs",judge:"multi-source-bfs",timeLimitMs:2000,memoryMb:256},
 {id:"C254",uz:"Eng qisqa halqa uzunligi",en:"The length of the shortest cycle",difficulty:"hard",rating:2000,tag:"Girth",points:300,topic:"graphs",judge:"graph-girth",timeLimitMs:3000,memoryMb:256},
 {id:"C255",uz:"Tugunning k-chi ajdodi",en:"The k-th ancestor of a vertex",difficulty:"hard",rating:1900,tag:"Binary lifting",points:300,topic:"trees",judge:"tree-kth-ancestor",timeLimitMs:2000,memoryMb:256},
 {id:"C256",uz:"Barcha oraliqlarni teshib chiqish",en:"Stabbing every interval",difficulty:"hard",rating:1800,tag:"Greedy",points:300,topic:"greedy",judge:"interval-stabbing",timeLimitMs:1000,memoryMb:256},
 {id:"C257",uz:"Muddatli ishlar va foyda",en:"Deadlines and profit",difficulty:"hard",rating:1900,tag:"Greedy with a heap",points:300,topic:"greedy",judge:"job-deadline-profit",timeLimitMs:2000,memoryMb:256},
 {id:"C258",uz:"Eng katta birlashma",en:"The largest concatenation",difficulty:"hard",rating:1800,tag:"Custom comparator",points:300,topic:"sorting",judge:"largest-concatenation",timeLimitMs:2000,memoryMb:256},
 {id:"C259",uz:"Chiziqlar maksimumining minimumi",en:"Minimising the maximum of some lines",difficulty:"hard",rating:1900,tag:"Ternary search",points:300,topic:"binary-search",judge:"ternary-search-lines",timeLimitMs:2000,memoryMb:256},
 {id:"C260",uz:"Eng kichik oraliqni kattalashtirish",en:"Making the smallest gap as large as possible",difficulty:"hard",rating:1900,tag:"Binary search on the answer",points:300,topic:"binary-search",judge:"max-min-spacing",timeLimitMs:2000,memoryMb:256},
 {id:"C261",uz:"O'rtada uchrashish",en:"Meeting in the middle",difficulty:"hard",rating:2000,tag:"Meet in the middle",points:300,topic:"backtracking",judge:"meet-in-middle-subset",timeLimitMs:3000,memoryMb:256},
 {id:"C262",uz:"Eng uzun umumiy bo'lak",en:"Longest common substring",difficulty:"hard",rating:1900,tag:"Dynamic programming",points:300,topic:"strings",judge:"longest-common-substring",timeLimitMs:2000,memoryMb:256},
 {id:"C263",uz:"Tartiblangan massiv kvadratlari",en:"Squares of a sorted array",difficulty:"medium",rating:1200,tag:"Two pointers",points:200,topic:"two-pointers",judge:"sorted-squares",timeLimitMs:1000,memoryMb:256},
 {id:"C264",uz:"Birliklarni bir joyga yig'ish",en:"Gathering the ones together",difficulty:"medium",rating:1500,tag:"Sliding window",points:200,topic:"two-pointers",judge:"min-swaps-group-ones",timeLimitMs:1000,memoryMb:256},
 {id:"C265",uz:"k ta nolni o'zgartirib eng uzun birliklar",en:"Longest run of ones after k flips",difficulty:"medium",rating:1600,tag:"Sliding window",points:200,topic:"two-pointers",judge:"longest-ones-k-flips",timeLimitMs:1000,memoryMb:256},
 {id:"C267",uz:"Barcha harflarni qamrovchi eng qisqa oyna",en:"The shortest window covering every letter",difficulty:"medium",rating:1700,tag:"Sliding window",points:200,topic:"two-pointers",judge:"min-window-substring",timeLimitMs:2000,memoryMb:256},
 {id:"C268",uz:"Kemaning eng kichik sig'imi",en:"The smallest ship that will do",difficulty:"medium",rating:1600,tag:"Binary search on the answer",points:200,topic:"binary-search",judge:"bs-ship-capacity",timeLimitMs:2000,memoryMb:256},
 {id:"C269",uz:"Ko'paytirish jadvalidagi k-chi son",en:"The k-th number in a multiplication table",difficulty:"medium",rating:1700,tag:"Binary search on the answer",points:200,topic:"binary-search",judge:"bs-kth-multiplication-table",timeLimitMs:2000,memoryMb:256},
 {id:"C270",uz:"Ikki tomonlama tartiblangan matritsada qidirish",en:"Searching a doubly sorted matrix",difficulty:"medium",rating:1300,tag:"Staircase search",points:200,topic:"binary-search",judge:"bs-matrix-search",timeLimitMs:2000,memoryMb:256},
 {id:"C271",uz:"Eng kam yoqilg'i to'xtashlari",en:"The fewest refuelling stops",difficulty:"medium",rating:1600,tag:"Greedy with a heap",points:200,topic:"greedy",judge:"greedy-min-refuel",timeLimitMs:2000,memoryMb:256},
 {id:"C272",uz:"Sovish vaqtli vazifalar",en:"Tasks with a cooldown",difficulty:"medium",rating:1600,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-task-cooldown",timeLimitMs:1000,memoryMb:256},
 {id:"C273",uz:"Qayiqlarga joylashtirish",en:"Loading the boats",difficulty:"medium",rating:1400,tag:"Two pointers",points:200,topic:"greedy",judge:"greedy-boat-pairs",timeLimitMs:1000,memoryMb:256},
 {id:"C274",uz:"Qaytimni bera olasizmi?",en:"Can you make the change?",difficulty:"medium",rating:1300,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-lemonade-change",timeLimitMs:1000,memoryMb:256},
 {id:"C275",uz:"Daraxtni qatlamma-qatlam o'qish",en:"Reading a tree level by level",difficulty:"medium",rating:1300,tag:"BFS",points:200,topic:"trees",judge:"tree-level-order",timeLimitMs:2000,memoryMb:256},
 {id:"C277",uz:"Vaznli daraxtning diametri",en:"Diameter of a weighted tree",difficulty:"medium",rating:1700,tag:"Two traversals",points:200,topic:"trees",judge:"tree-diameter-weighted",timeLimitMs:2000,memoryMb:256},
 {id:"C278",uz:"h-indeks",en:"The h-index",difficulty:"medium",rating:1400,tag:"Sorting",points:200,topic:"sorting",judge:"sort-h-index",timeLimitMs:1000,memoryMb:256},
 {id:"C279",uz:"Natijalar bo'yicha o'rinlar",en:"Ranking the results",difficulty:"medium",rating:1400,tag:"Sorting with indices",points:200,topic:"sorting",judge:"sort-relative-ranks",timeLimitMs:1000,memoryMb:256},
 {id:"C280",uz:"Qism ketma-ketlikmi?",en:"Is it a subsequence?",difficulty:"medium",rating:1300,tag:"Two pointers",points:200,topic:"strings",judge:"str-is-subsequence",timeLimitMs:1000,memoryMb:256},
 {id:"C281",uz:"Rim raqamlarini o'girish",en:"Reading a Roman numeral",difficulty:"medium",rating:1300,tag:"Simulation",points:200,topic:"strings",judge:"str-roman-to-int",timeLimitMs:1000,memoryMb:256},
 {id:"C282",uz:"Haqiqiy sonlarda ikkilik qidiruv",en:"Binary search over the reals",difficulty:"medium",rating:1500,tag:"Binary search on reals",points:200,topic:"binary-search",judge:"bs-monotone-cube-root",timeLimitMs:1000,memoryMb:256},
 {id:"C266",uz:"Yig'indisi nolga teng uchliklar",en:"Triples summing to zero",difficulty:"medium",rating:1700,tag:"Two pointers",points:200,topic:"two-pointers",judge:"three-sum-zero-count",timeLimitMs:3000,memoryMb:256},
 {id:"C276",uz:"Ildizdan bargcha yig'indi",en:"A root-to-leaf sum",difficulty:"medium",rating:1500,tag:"Tree traversal",points:200,topic:"trees",judge:"tree-path-sum-exists",timeLimitMs:2000,memoryMb:256},
 {id:"C283",uz:"Almashinuvchi yig'indi",en:"Alternating sum",difficulty:"easy",rating:800,tag:"Arrays",points:100,topic:"programming-basics",judge:"array-alternating-sum",timeLimitMs:1000,memoryMb:256},
 {id:"C284",uz:"Harflar registrini almashtirish",en:"Swapping the case of letters",difficulty:"easy",rating:800,tag:"Characters",points:100,topic:"strings",judge:"string-swap-case",timeLimitMs:1000,memoryMb:256},
 {id:"C285",uz:"Kabisa yili",en:"A leap year",difficulty:"easy",rating:800,tag:"Conditionals",points:100,topic:"math",judge:"leap-year-check",timeLimitMs:1000,memoryMb:256},
 {id:"C286",uz:"Qo'shnilar orasidagi eng katta farq",en:"The largest gap between neighbours",difficulty:"easy",rating:900,tag:"Arrays",points:100,topic:"programming-basics",judge:"max-adjacent-difference",timeLimitMs:1000,memoryMb:256},
 {id:"C287",uz:"Sonning raqamlarini teskari o'girish",en:"Reversing the digits of a number",difficulty:"easy",rating:900,tag:"Digits",points:100,topic:"math",judge:"reverse-number-digits",timeLimitMs:1000,memoryMb:256},
 {id:"C288",uz:"Armstrong soni",en:"An Armstrong number",difficulty:"easy",rating:1000,tag:"Digits",points:100,topic:"math",judge:"armstrong-number",timeLimitMs:1000,memoryMb:256},
 {id:"C289",uz:"Ikki songa karrali sonlar yig'indisi",en:"Summing the multiples of two numbers",difficulty:"easy",rating:900,tag:"Arithmetic series",points:100,topic:"math",judge:"sum-multiples-two",timeLimitMs:1000,memoryMb:256},
 {id:"C290",uz:"Birlik matritsami?",en:"Is it the identity matrix?",difficulty:"easy",rating:1000,tag:"Matrices",points:100,topic:"data-structures",judge:"matrix-identity-check",timeLimitMs:2000,memoryMb:256},
 {id:"C291",uz:"Massivning eng katta umumiy bo'luvchisi",en:"The greatest common divisor of an array",difficulty:"easy",rating:1100,tag:"GCD",points:100,topic:"math",judge:"gcd-of-array",timeLimitMs:1000,memoryMb:256},
 {id:"C292",uz:"Sanoq sistemasini o'zgartirish",en:"Changing the number base",difficulty:"medium",rating:1300,tag:"Number bases",points:200,topic:"math",judge:"base-convert-any",timeLimitMs:1000,memoryMb:256},
 {id:"C293",uz:"Minimumni biladigan stek",en:"A stack that knows its minimum",difficulty:"medium",rating:1300,tag:"Stack",points:200,topic:"data-structures",judge:"stack-min-tracking",timeLimitMs:2000,memoryMb:256},
 {id:"C294",uz:"Yig'indisi berilgan songa teng juftlik",en:"The pair that adds up",difficulty:"medium",rating:1200,tag:"Hash map",points:200,topic:"data-structures",judge:"hash-two-sum-indices",timeLimitMs:2000,memoryMb:256},
 {id:"C295",uz:"Birlashma va kesishma o'lchamlari",en:"Sizes of the union and the intersection",difficulty:"easy",rating:1100,tag:"Sets",points:100,topic:"data-structures",judge:"set-union-intersection",timeLimitMs:2000,memoryMb:256},
 {id:"C296",uz:"Eng yaqin ikki son",en:"The two closest numbers",difficulty:"medium",rating:1200,tag:"Sorting",points:200,topic:"sorting",judge:"sort-min-abs-difference",timeLimitMs:2000,memoryMb:256},
 {id:"C297",uz:"Muvozanat nuqtasi",en:"The equilibrium point",difficulty:"medium",rating:1200,tag:"Prefix sums",points:200,topic:"data-structures",judge:"prefix-equilibrium-index",timeLimitMs:1000,memoryMb:256},
 {id:"C298",uz:"So'zlarni bosh harf bilan boshlash",en:"Capitalising every word",difficulty:"easy",rating:1100,tag:"Strings",points:100,topic:"strings",judge:"str-capitalize-words",timeLimitMs:1000,memoryMb:256},
 {id:"C299",uz:"Ichma-ich sikl necha marta aylanadi?",en:"How many times does a nested loop run?",difficulty:"easy",rating:1100,tag:"Complexity",points:100,topic:"foundations",judge:"nested-loop-iterations",timeLimitMs:1000,memoryMb:256},
 {id:"C300",uz:"Berilgan harf bilan boshlanuvchi so'zlar",en:"Words beginning with a given letter",difficulty:"easy",rating:1000,tag:"Strings",points:100,topic:"strings",judge:"count-words-with-prefix",timeLimitMs:1000,memoryMb:256},
 {id:"C301",uz:"Ikki stekdan navbat yasash",en:"A queue built from two stacks",difficulty:"medium",rating:1200,tag:"Stacks and queues",points:200,topic:"data-structures",judge:"queue-from-two-stacks",timeLimitMs:2000,memoryMb:256},
 {id:"C302",uz:"Massivni bir qadam chapga surish",en:"Shifting an array one step left",difficulty:"easy",rating:800,tag:"Arrays",points:100,topic:"programming-basics",judge:"array-shift-left-one",timeLimitMs:1000,memoryMb:256},
 {id:"A303",uz:"Raqamlar ko‘paytmasi",en:"Product of the digits",difficulty:"easy",rating:800,tag:"Digits",points:100,topic:"math",judge:"digit-product",timeLimitMs:1000,memoryMb:256},
 {id:"A304",uz:"Sondagi raqamlar soni",en:"How many digits",difficulty:"easy",rating:800,tag:"Loops",points:100,topic:"programming-basics",judge:"count-digits",timeLimitMs:1000,memoryMb:256},
 {id:"A305",uz:"Juft o‘rinlardagi yig‘indi",en:"Sum at the even positions",difficulty:"easy",rating:800,tag:"Arrays",points:100,topic:"programming-basics",judge:"sum-even-positions",timeLimitMs:1000,memoryMb:256},
 {id:"A306",uz:"n-chi uchburchak son",en:"The n-th triangular number",difficulty:"easy",rating:800,tag:"Formulas",points:100,topic:"math",judge:"nth-triangular",timeLimitMs:1000,memoryMb:256},
 {id:"A307",uz:"Hamming masofasi",en:"Hamming distance",difficulty:"easy",rating:900,tag:"Strings",points:100,topic:"strings",judge:"hamming-distance",timeLimitMs:1000,memoryMb:256},
 {id:"A308",uz:"Oraliqdagi karralilar soni",en:"Multiples inside a range",difficulty:"easy",rating:900,tag:"Divisibility",points:100,topic:"math",judge:"count-multiples-range",timeLimitMs:1000,memoryMb:256},
 {id:"A309",uz:"Katta va kichik harflar soni",en:"Uppercase and lowercase counts",difficulty:"easy",rating:900,tag:"Characters",points:100,topic:"strings",judge:"count-letter-case",timeLimitMs:1000,memoryMb:256},
 {id:"A310",uz:"Son tubmi",en:"Is the number prime",difficulty:"easy",rating:1000,tag:"Primality",points:100,topic:"math",judge:"is-prime-single",timeLimitMs:1000,memoryMb:256},
 {id:"A311",uz:"Takrorlanmagan birinchi harf",en:"First character that never repeats",difficulty:"easy",rating:1000,tag:"Counting",points:100,topic:"strings",judge:"string-first-unique",timeLimitMs:1000,memoryMb:256},
 {id:"A312",uz:"Chetlarni tashlab o‘rtacha",en:"The mean with its extremes removed",difficulty:"easy",rating:1100,tag:"Aggregation",points:100,topic:"foundations",judge:"average-drop-extremes",timeLimitMs:1000,memoryMb:256},
 {id:"B313",uz:"Eng katta bo‘shliq",en:"The largest gap",difficulty:"medium",rating:1200,tag:"Sorting",points:200,topic:"sorting",judge:"sort-largest-gap",timeLimitMs:1000,memoryMb:256},
 {id:"B314",uz:"Yig‘indisi k ga bo‘linadigan juftliklar",en:"Pairs whose sum divides by k",difficulty:"medium",rating:1200,tag:"Remainders",points:200,topic:"math",judge:"count-pairs-divisible-k",timeLimitMs:1000,memoryMb:256},
 {id:"B315",uz:"Zinapoyaning eng arzon yo‘li",en:"Cheapest way up the stairs",difficulty:"medium",rating:1300,tag:"DP",points:200,topic:"dynamic-programming",judge:"dp-min-cost-stairs",timeLimitMs:1000,memoryMb:256},
 {id:"B316",uz:"Juft-toq almashinuvchi eng uzun bo‘lak",en:"Longest run of alternating parity",difficulty:"medium",rating:1300,tag:"Scanning",points:200,topic:"two-pointers",judge:"longest-alternating-parity",timeLimitMs:1000,memoryMb:256},
 {id:"B317",uz:"Barchasini tenglashtirish narxi",en:"Making every value equal",difficulty:"medium",rating:1400,tag:"Median",points:200,topic:"greedy",judge:"min-ops-equalise",timeLimitMs:1000,memoryMb:256},
 {id:"B318",uz:"Yig‘indisi toq bo‘lgan qism massivlar",en:"Subarrays with an odd sum",difficulty:"medium",rating:1400,tag:"Prefix sums",points:200,topic:"data-structures",judge:"count-subarrays-odd-sum",timeLimitMs:1000,memoryMb:256},
 {id:"B319",uz:"Yuk mashinasiga eng ko‘p buyum",en:"Filling the truck",difficulty:"medium",rating:1500,tag:"Greedy",points:200,topic:"greedy",judge:"greedy-max-units-boxes",timeLimitMs:1000,memoryMb:256},
 {id:"B320",uz:"Guldastalar uchun eng kam kun",en:"Days until the bouquets are ready",difficulty:"medium",rating:1500,tag:"Binary search on the answer",points:200,topic:"binary-search",judge:"bs-min-days-bouquets",timeLimitMs:1000,memoryMb:256},
 {id:"B321",uz:"Qo‘shni teng harflarni yo‘qotish",en:"Cancelling equal neighbours",difficulty:"medium",rating:1500,tag:"Stack",points:200,topic:"data-structures",judge:"stack-remove-adjacent-equal",timeLimitMs:1000,memoryMb:256},
 {id:"B322",uz:"Berilgan chuqurlikdagi tugunlar",en:"Nodes at a given depth",difficulty:"medium",rating:1600,tag:"BFS",points:200,topic:"trees",judge:"tree-count-depth-k",timeLimitMs:1000,memoryMb:256},
];
