import { bankProblems } from "./problem-bank";

export type LessonUnit={id:string;titleUz:string;titleEn:string;summaryUz:string;summaryEn:string;rating:string;minutes:number;complexity:string;cpp:string;python:string;quiz:{questionUz:string;questionEn:string;choicesUz:string[];choicesEn:string[];correct:number};problemId:string};
export type RoadmapDifficulty="beginner"|"intermediate"|"advanced"|"expert";
export type MasteryRoadmap={slug:string;icon:string;color:string;titleUz:string;titleEn:string;descriptionUz:string;descriptionEn:string;level:string;difficulty:RoadmapDifficulty;category:string;categoryUz:string;prereqs:string[];prerequisiteUz:string;prerequisiteEn:string;units:LessonUnit[]};

type Def={slug:string;icon:string;color:string;uz:string;en:string;descUz:string;descEn:string;level:string;difficulty:RoadmapDifficulty;cat:string;catUz:string;prereqs:string[];units:string[];unitsEn:string[];cpp:string;python:string;complexity:string};

const defs:Def[]=[
 {slug:"programming-basics",icon:"</>",color:"#9df2e0",uz:"Dasturlash asoslari",en:"Programming Basics",descUz:"C++ tili, STL va musobaqa muhitini o‘rnatish.",descEn:"Set up C++, STL, and the contest environment.",level:"0 → 900",difficulty:"beginner",cat:"Basics",catUz:"Asoslar",prereqs:[],units:["Muhitni sozlash va birinchi dastur","Kirish va chiqish","O‘zgaruvchilar va tiplar","Overflow va aniqlik","Operatorlar va ifodalar","Shart operatorlari: if/else","Switch va uchlik operator","For sikli","While va do-while","Massivlar asoslari","Ko‘p o‘lchovli massivlar","Stringlar bilan ishlash","Funksiyalar va parametrlar","Qiymat va havola orqali uzatish","Vector va asosiy STL","Bit amallari","Xatolarni topish va debug"],unitsEn:["Setup and first program","Input and output","Variables and types","Overflow and precision","Operators and expressions","Conditionals: if/else","Switch and the ternary operator","The for loop","While and do-while","Arrays basics","Multi-dimensional arrays","Working with strings","Functions and parameters","Pass by value vs. reference","Vector and essential STL","Bit operations","Finding bugs and debugging"],cpp:"#include <bits/stdc++.h>\nusing namespace std;",python:"import sys\ninput = sys.stdin.readline",complexity:"O(1) asosiy amallar"},
 {slug:"foundations",icon:"O(n)",color:"#c8ff76",uz:"Asoslar va complexity",en:"Foundations & Complexity",descUz:"Algoritm tezligi, xotira va to‘g‘ri baholash.",descEn:"Reason about runtime, memory, and constraints.",level:"800 → 1300",difficulty:"beginner",cat:"Basics",catUz:"Asoslar",prereqs:["programming-basics"],units:["Nega murakkablik muhim","Cheklovlarni o‘qish va byudjet","Big O, Omega, Theta","Eng yomon, eng yaxshi, o‘rtacha holat","Konstant va chiziqli: O(1), O(n)","Logarifmik murakkablik: O(log n)","O(n log n) murakkablik","Kvadratik va kub: O(n²), O(n³)","Eksponentsial va faktorial","Sikllar orqali murakkablikni hisoblash","Rekursiya murakkabligi","Xotira murakkabligi","Amortizatsiya","Murakkablikdan algoritm tanlash","Master teorema va rekurrent munosabatlar","Konstanta omillar va kesh","Yakuniy tahlil"],unitsEn:["Why complexity matters","Reading constraints and the budget","Big O, Omega, Theta","Worst, best, and average case","Constant and linear: O(1), O(n)","Logarithmic complexity: O(log n)","O(n log n) complexity","Quadratic and cubic: O(n²), O(n³)","Exponential and factorial","Analyzing loops for complexity","Recursion complexity","Memory complexity","Amortization","Choosing an algorithm from the budget","The Master Theorem and recurrences","Constant factors and the cache","Final analysis"],cpp:"for (int i = 0; i < n; ++i) sum += a[i];",python:"total = sum(a)",complexity:"O(n) vaqt · O(1) xotira"},
 {slug:"sorting",icon:"↕",color:"#ffbd8f",uz:"Sorting algoritmlari",en:"Sorting Algorithms",descUz:"Sorting usullarini tanlash va qo‘llash.",descEn:"Choose and apply the right sorting method.",level:"800 → 1500",difficulty:"beginner",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["foundations"],units:["Sorting nima uchun kerak","Selection sort","Bubble sort","Insertion sort","Counting sort","Merge sort: bo‘lib-yengish","Inversiyalarni sanash","Quicksort: partition va pivot","Heap sort","Nega O(n log n) pastki chegara","Barqarorlik (stability)","Custom komparatorlar","Ko‘p kalitli tartiblash","STL sorting vositalari","Sortingni masalalarga qo‘llash","Radix sort","Koordinatalarni siqish","Quickselect va nth_element"],unitsEn:["Why sorting matters","Selection sort","Bubble sort","Insertion sort","Counting sort","Merge sort: divide and conquer","Counting inversions","Quicksort: partition and pivot","Heap sort","Why O(n log n) is a lower bound","Stability","Custom comparators","Multi-key sorting","STL sorting tools","Applying sorting to problems","Radix sort","Coordinate compression","Quickselect and nth_element"],cpp:"sort(a.begin(), a.end());",python:"a.sort()",complexity:"O(n log n) vaqt"},
 {slug:"backtracking",icon:"↩",color:"#f5a6ff",uz:"Recursion va backtracking",en:"Recursion & Backtracking",descUz:"Holat daraxtini xavfsiz kezish.",descEn:"Explore state trees safely.",level:"900 → 1900",difficulty:"intermediate",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["foundations"],units:["Rekursiya asoslari","Rekursiya turlari","Rekursiya vs iteratsiya","Backtracking g‘oyasi","Qism to‘plamlar generatsiyasi","Permutatsiyalar","Kombinatsiyalar","N ta qirolicha masalasi","Grid bo‘ylab backtracking","Pruning: budnik kesish","Fail-first va CSP evristikalari","Meet in the middle","Memoizatsiyaga kirish","Konstruksiya masalalari","Submasklar bo‘yicha yurish","Rekursiyani aniq stack bilan almashtirish","Iterative deepening (IDDFS)","Qaysi usulni tanlash"],unitsEn:["Recursion basics","Types of recursion","Recursion vs. iteration","The backtracking idea","Generating subsets","Permutations","Combinations","The N-Queens problem","Backtracking over a grid","Pruning","Fail-first and CSP heuristics","Meet in the middle","Intro to memoization","Construction problems","Iterating over submasks","Replacing recursion with an explicit stack","Iterative deepening (IDDFS)","Choosing the right method"],cpp:"void dfs(int v) { choose(v); dfs(v + 1); undo(v); }",python:"def dfs(v):\n    choose(v); dfs(v + 1); undo(v)",complexity:"O(b^d) eng yomon holat"},
 {slug:"math",icon:"π",color:"#ffb36f",uz:"Math va number theory",en:"Math & Number Theory",descUz:"Musobaqalar uchun arifmetika va kombinatorika.",descEn:"Build contest-ready arithmetic and combinatorics.",level:"900 → 2100",difficulty:"intermediate",cat:"Math",catUz:"Matematika",prereqs:["foundations"],units:["Modul arifmetikasi","EKUB va EKUK","Kengaytirilgan Evklid algoritmi","Tub sonlar va g‘alvir","Tub faktorlash va bo‘luvchilar","Tez daraja","Kombinatorika: C(n,k)","Modular inverse","Xitoy qoldiqlar teoremasi","Eyler funksiyasi","Diofant tenglamalari","Ehtimollik va kutilgan qiymat","Katalan sonlari","Matritsa darajasi","Kiritish-chiqarish prinsipi","Ko‘paytuvchi funksiyalar va g‘alvir","Miller–Rabin va Pollard’s rho","Qaysi vositani tanlash"],unitsEn:["Modular arithmetic","GCD and LCM","Extended Euclidean algorithm","Primes and the sieve","Prime factorization and divisors","Fast exponentiation","Combinatorics: C(n,k)","Modular inverse","Chinese Remainder Theorem","Euler's totient function","Linear Diophantine equations","Probability and expected value","Catalan numbers","Matrix exponentiation","Inclusion-exclusion","Multiplicative functions and sieves","Miller–Rabin and Pollard’s rho","Choosing the right tool"],cpp:"long long ans = binpow(a, b, mod);",python:"answer = pow(a, b, mod)",complexity:"O(log b) vaqt"},
 {slug:"data-structures",icon:"▦",color:"#8ad8ff",uz:"Data structures",en:"Data Structures",descUz:"Ma’lumotni tez so‘rash va yangilash.",descEn:"Query and update data efficiently.",level:"1000 → 2100",difficulty:"intermediate",cat:"Data Structures",catUz:"Data structures",prereqs:["foundations"],units:["Dynamic array (vector) ichki tuzilishi","Bog‘langan ro‘yxat","Stack va uning qo‘llanishlari","Queue va deque","Monotonik stack va queue","Hashing: hash table ichki tuzilishi","Set va map: tartiblangan kalitlar","Binary heap va priority_queue","Disjoint Set Union (DSU)","DSU qo‘llanishlari va kengaytmalari","Sparse table: statik RMQ","Fenwick tree (BIT) asoslari","Fenwick tree: oraliq yangilash va 2D BIT","Segment tree: qurish va oraliq so‘rov","Segment tree: lazy propagation","Segment tree variatsiyalari","Trie (prefix tree)","Qaysi tuzilmani tanlash"],unitsEn:["Dynamic array (vector) internals","Linked lists","Stack and its applications","Queue and deque","Monotonic stack and queue","Hashing: hash table internals","Set and map: ordered keys","Binary heap and priority_queue","Disjoint Set Union (DSU)","DSU applications and extensions","Sparse table: static RMQ","Fenwick tree (BIT) basics","Fenwick tree: range updates and 2D BIT","Segment tree: build and range query","Segment tree: lazy propagation","Segment tree variations","Trie (prefix tree)","Choosing the right structure"],cpp:"priority_queue<int> pq; pq.push(x);",python:"heappush(pq, x)",complexity:"O(log n) yangilash"},
 {slug:"binary-search",icon:"⌕",color:"#98b5ff",uz:"Binary search",en:"Binary Search",descUz:"Qidiruv maydonini yarmiga qisqartirish.",descEn:"Cut the search space in half.",level:"900 → 1900",difficulty:"beginner",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["sorting"],units:["Tartiblangan qidiruvning asosiy sxemasi","Lower va upper bound","«Birinchi rost qiymat» universal sxemasi","Javob bo‘yicha qidiruv (binary search on answer)","Haqiqiy sonlar ustida qidiruv","Ternary search: unimodal funksiya ekstremumi","Diskret unimodal massivda cho‘qqi qidirish","Ikki o‘lchamli monoton matritsada qidiruv","Kompozit (ko‘p shartli) predikatlar","Parallel binary search","Qaysi usulni tanlash"],unitsEn:["Ordered search: the core scheme","Lower and upper bound","The universal “first true value” scheme","Binary search on answer","Search over real numbers","Ternary search: unimodal function extrema","Peak finding in a discrete unimodal array","Binary search on a 2D monotonic matrix","Composite (multi-condition) predicates","Parallel binary search","Choosing the right method"],cpp:"auto it = lower_bound(a.begin(), a.end(), x);",python:"i = bisect_left(a, x)",complexity:"O(log n) vaqt"},
 {slug:"greedy",icon:"◆",color:"#ffd76d",uz:"Greedy algoritmlar",en:"Greedy Algorithms",descUz:"Mahalliy tanlovdan global optimumga.",descEn:"Turn local choices into global optima.",level:"1000 → 1900",difficulty:"intermediate",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["sorting"],units:["Greedy tanlov g‘oyasi","To‘g‘rilik isboti: exchange argument","Faoliyat tanlash (Activity Selection)","Interval qamrash va birlashtirish","Ishlarni deadline bilan rejalashtirish","Priority queue bilan greedy: Huffman coding","Fractional knapsack","Ikki kalitli comparator greedy","Greedy + two pointers gibrid","Greedy qachon ishlamaydi","Qaysi holatda greedy tanlash"],unitsEn:["The greedy choice idea","Correctness proofs: the exchange argument","Activity selection","Interval covering and merging","Job scheduling with deadlines","Greedy with a priority queue: Huffman coding","Fractional knapsack","Custom-comparator greedy","Greedy + two pointers hybrid","When greedy fails","Choosing when to use greedy"],cpp:"sort(jobs.begin(), jobs.end(), byFinish);",python:"jobs.sort(key=lambda job: job.finish)",complexity:"O(n log n) vaqt"},
 {slug:"graphs",icon:"⌘",color:"#7ee59b",uz:"Graph algoritmlari",en:"Graph Algorithms",descUz:"Tugunlar va qirralar orasidagi yo‘llar.",descEn:"Navigate nodes, edges, and paths.",level:"1000 → 2300",difficulty:"advanced",cat:"Graphs",catUz:"Graflar",prereqs:["data-structures","backtracking"],units:["Graph modeli","BFS","DFS","Topologik tartib","Kuchli bog‘langan komponentlar (SCC)","Bipartiteness va graph coloring","Kesish nuqtalari va ko‘priklar","Dijkstra","Bellman-Ford va manfiy sikl","Floyd-Warshall","0-1 BFS va maxsus holatlar","Minimum spanning tree: Kruskal","Minimum spanning tree: Prim","Eyler yo‘li va davri","DAG bo‘yicha dynamic programming","Maksimal oqim (Max Flow)","Ikki bo‘lakli moslashtirish","Qaysi algoritmni tanlash"],unitsEn:["Graph modeling","BFS","DFS","Topological order","Strongly connected components (SCC)","Bipartiteness and graph coloring","Articulation points and bridges","Dijkstra","Bellman-Ford and negative cycles","Floyd-Warshall","0-1 BFS and special cases","Minimum spanning tree: Kruskal","Minimum spanning tree: Prim","Eulerian path and circuit","Dynamic programming on a DAG","Maximum flow","Bipartite matching","Choosing the right algorithm"],cpp:"queue<int> q; q.push(source);",python:"q = deque([source])",complexity:"O(V + E) vaqt"},
 {slug:"strings",icon:"Aa",color:"#ff9eae",uz:"String algoritmlari",en:"String Algorithms",descUz:"Matn ichidan andozalarni tez topish.",descEn:"Find patterns inside text efficiently.",level:"1000 → 2200",difficulty:"advanced",cat:"Strings",catUz:"Satrlar",prereqs:["data-structures"],units:["String asoslari","Hashing","Prefix function","KMP","Z algoritmi","Manacher algoritmi","Aho-Corasick","Suffix array qurish va LCP","Suffix array qo‘llanishlari","Suffix automaton asoslari","Stringlarda dynamic programming","Qaysi vositani tanlash"],unitsEn:["String basics","Hashing","Prefix function","KMP","Z algorithm","Manacher's algorithm","Aho-Corasick","Building a suffix array and LCP","Suffix array applications","Suffix automaton basics","Dynamic programming on strings","Choosing the right tool"],cpp:"vector<int> pi = prefix_function(s);",python:"pi = prefix_function(s)",complexity:"O(n) vaqt"},
 {slug:"geometry",icon:"△",color:"#a8e6a1",uz:"Computational geometry",en:"Computational Geometry",descUz:"Nuqtalar, vektorlar va qavariq qobiqlar.",descEn:"Points, vectors, and convex hulls.",level:"1400 → 2500",difficulty:"advanced",cat:"Geometry",catUz:"Geometriya",prereqs:["math"],units:["Nuqta va vektor","Skalyar ko‘paytma","Vektor ko‘paytma","Kesishuvchi kesmalar","Ko‘pburchak yuzi","Qavariq qobiq","Rotating calipers","Eng yaqin nuqtalar jufti","Aylana geometriyasi","Qutb burchagi va Pick teoremasi","Qaysi vositani tanlash"],unitsEn:["Points and vectors","Dot product","Cross product","Segment intersection","Polygon area","Convex hull","Rotating calipers","Closest pair of points","Circle geometry","Polar angle sort and Pick's theorem","Choosing the right tool"],cpp:"long long cross(Point a, Point b) { return a.x*b.y - a.y*b.x; }",python:"def cross(a, b):\n    return a[0]*b[1] - a[1]*b[0]",complexity:"O(n log n) qavariq qobiq"},
 {slug:"two-pointers",icon:"⇄",color:"#78e9cf",uz:"Two pointers va sliding window",en:"Two Pointers & Sliding Window",descUz:"Chiziqli yurish bilan segmentlarni boshqarish.",descEn:"Manage ranges in linear time.",level:"900 → 1800",difficulty:"intermediate",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["binary-search"],units:["Opposite pointers","Bir yo‘nalishli yurish","Two pointers ikki massiv ustida","Belgilangan uzunlikdagi oyna","O‘zgaruvchan oyna","Oynada monotonik deque: min/max","«Aynan K» ni «ko‘pi bilan K» orqali hisoblash","Prefix bilan birga","Aralash masalalar"],unitsEn:["Opposite pointers","Forward (read/write) pointers","Two pointers over two arrays","Fixed-length window","Variable window","Monotonic deque in a window: min/max","“Exactly K” via “at most K”","Combined with prefix sums","Mixed patterns"],cpp:"while (r < n) { add(a[r++]); while (bad()) remove(a[l++]); }",python:"while r < n:\n    add(a[r]); r += 1\n    while bad(): remove(a[l]); l += 1",complexity:"O(n) vaqt"},
 {slug:"dynamic-programming",icon:"∑",color:"#c2a4ff",uz:"Dynamic programming",en:"Dynamic Programming",descUz:"Holat va o‘tishlar orqali qayta hisoblashni yo‘qotish.",descEn:"Eliminate repeated work with states and transitions.",level:"1100 → 2400",difficulty:"advanced",cat:"DP",catUz:"DP",prereqs:["backtracking","greedy"],units:["DP g‘oyasi va intuitsiya","Overlapping subproblems","Optimal substructure","Rekursiya va memoization","Bottom-up DP","Holatni aniqlash","O‘tishlarni qurish","1D DP","2D DP","Knapsack patternlari","LIS","Interval DP","Tree DP","Bitmask DP","Ilg‘or DP optimallashtirish"],unitsEn:["DP concept and intuition","Overlapping subproblems","Optimal substructure","Recursion and memoization","Bottom-up DP","State definition","Building transitions","1D DP","2D DP","Knapsack patterns","LIS","Interval DP","Tree DP","Bitmask DP","Advanced DP optimizations"],cpp:"dp[i] = min(dp[i], dp[j] + cost);",python:"dp[i] = min(dp[i], dp[j] + cost)",complexity:"holatlar × o‘tishlar"},
 {slug:"trees",icon:"♧",color:"#d1b0ff",uz:"Tree algoritmlari",en:"Tree Algorithms",descUz:"Ierarxik graflarda samarali hisoblash.",descEn:"Compute efficiently on hierarchical graphs.",level:"1100 → 2400",difficulty:"advanced",cat:"Graphs",catUz:"Graflar",prereqs:["graphs"],units:["Tree asoslari","Subtree hisoblari","Binary lifting","LCA","Tree diameter","Kichikni kattaga birlashtirish","Tree DP va rerooting","Centroid decomposition","Qaysi vositani tanlash"],unitsEn:["Tree basics","Subtree values","Binary lifting","LCA","Tree diameter","Small-to-large merging","Tree DP and rerooting","Centroid decomposition","Choosing the right tool"],cpp:"depth[to] = depth[v] + 1; dfs(to, v);",python:"depth[to] = depth[v] + 1\ndfs(to, v)",complexity:"O(n) kezish"},
 {slug:"advanced-cp",icon:"✦",color:"#ffd9a8",uz:"Advanced algoritmlar",en:"Advanced Algorithms",descUz:"Expert darajadagi tuzilmalar va optimallashtirishlar.",descEn:"Expert-level structures and optimizations.",level:"1900 → 3000",difficulty:"expert",cat:"Advanced",catUz:"Ilg‘or",prereqs:["dynamic-programming","graphs"],units:["Persistent segment tree","Treap va implicit treap","Mo algoritmi","Heavy-Light decomposition","FFT va NTT","O‘yinlar nazariyasi","SOS DP: qism to‘plamlar yig‘indisi","Convex Hull Trick va Li Chao tree","2-SAT","Qaysi vositani tanlash"],unitsEn:["Persistent segment tree","Treap and implicit treap","Mo's algorithm","Heavy-Light decomposition","FFT and NTT","Game theory","SOS DP: sum over subsets","Convex Hull Trick and Li Chao tree","2-SAT","Choosing the right tool"],cpp:"struct Node { int l, r, sum; } st[MAXN * 20];",python:"# persistent segtree nodes\nnodes = [(0, 0, 0)]",complexity:"O(log n) so‘rov"},
];

// Only 7 problems exist in the bank today, so most roadmaps have no
// topic-matched problem of their own yet. Rather than cycling the same six
// IDs across every roadmap regardless of subject, walk up the prereq chain
// to the nearest ancestor that does have matched problems — a Trees unit
// links to a Graphs problem (its prereq), not to an unrelated Binary Search
// one. Writing dedicated problems per topic is a separate, larger task.
// Derived from the real bank rather than hardcoded. The old literal still
// listed ids from the 11-problem era (B01..B04 no longer exist), so most
// units linked to a dead id and every unit of a roadmap shared one problem.
const problemsByTopic:Record<string,string[]>=bankProblems.reduce((acc,p)=>{
 (acc[p.topic]||=[]).push(p.id); return acc;
},{} as Record<string,string[]>);
const nearestProblemSet=(slug:string,seen=new Set<string>()):string[]=>{
 if(seen.has(slug))return [];
 seen.add(slug);
 if(problemsByTopic[slug])return problemsByTopic[slug];
 const d=defs.find(x=>x.slug===slug);if(!d)return [];
 for(const prereq of d.prereqs){const found=nearestProblemSet(prereq,seen);if(found.length)return found}
 return [];
};

export const roadmapCatalog:MasteryRoadmap[]=defs.map(d=>({
 slug:d.slug,icon:d.icon,color:d.color,titleUz:d.uz,titleEn:d.en,descriptionUz:d.descUz,descriptionEn:d.descEn,level:d.level,difficulty:d.difficulty,category:d.cat,categoryUz:d.catUz,prereqs:d.prereqs,
 prerequisiteUz:d.prereqs.length?d.prereqs.map(s=>defs.find(x=>x.slug===s)?.uz||s).join(" + "):"Yo‘q — boshlanish nuqtasi",
 prerequisiteEn:d.prereqs.length?d.prereqs.map(s=>defs.find(x=>x.slug===s)?.en||s).join(" + "):"None — starting point",
 units:d.units.map((titleUz,index)=>{
  // Spread each unit's rating band evenly across the roadmap's own level
  // range (parsed from "1100 → 2400") instead of a fixed per-index step,
  // so roadmaps with more than six units still land on realistic numbers.
  const [lo,hi]=d.level.split("→").map(s=>parseInt(s.trim(),10)),n=d.units.length,step=(hi-lo)/n;
  return {
  id:`${d.slug}-${index+1}`,titleUz,titleEn:d.unitsEn[index],
  summaryUz:`${titleUz} mavzusining asosiy g‘oyasi, qachon ishlatilishi va xatolarini bosqichma-bosqich o‘rganing.`,
  summaryEn:`Learn the core idea behind ${d.unitsEn[index]}, when to use it, and the mistakes to avoid.`,
  rating:`${Math.round(lo+index*step)} → ${Math.round(lo+(index+1)*step)}`,minutes:15+Math.round(index*(30/n)),complexity:d.complexity,cpp:d.cpp,python:d.python,
  quiz:{questionUz:`${titleUz} uchun eng muhim birinchi qadam qaysi?`,questionEn:`What is the most important first step for ${d.unitsEn[index]}?`,choicesUz:["Cheklov va invariantni aniqlash","Tasodifiy kod yozish","Har doim O(n²) ishlatish","Testlarni e’tiborsiz qoldirish"],choicesEn:["Identify constraints and the invariant","Write random code","Always use O(n²)","Ignore test cases"],correct:0},
  problemId:(()=>{const set=nearestProblemSet(d.slug);return set.length?set[index%set.length]:"A01"})()
 }})
}));

export const roadmapCards=roadmapCatalog.map(r=>({slug:r.slug,icon:r.icon,color:r.color,uz:r.titleUz,en:r.titleEn,descUz:r.descriptionUz,descEn:r.descriptionEn,units:r.units.length,level:r.level,progress:0}));
