export type LessonUnit={id:string;titleUz:string;titleEn:string;summaryUz:string;summaryEn:string;rating:string;minutes:number;complexity:string;cpp:string;python:string;quiz:{questionUz:string;questionEn:string;choicesUz:string[];choicesEn:string[];correct:number};problemId:string};
export type MasteryRoadmap={slug:string;icon:string;color:string;titleUz:string;titleEn:string;descriptionUz:string;descriptionEn:string;level:string;prerequisiteUz:string;prerequisiteEn:string;units:LessonUnit[]};

const definitions=[
 ["foundations","O(n)","#c8ff76","Asoslar va murakkablik","Foundations & Complexity","Algoritm tezligi, xotira va to‘g‘ri baholash.","Reason about runtime, memory, and constraints.","800 → 1100",["Kirish va cheklovlar","Big O belgisi","Massiv va sikllar","Xotira murakkabligi","Amortizatsiya","Yakuniy tahlil"]],
 ["sorting","↕","#ffbd8f","Saralash algoritmlari","Sorting Algorithms","Saralash usullarini tanlash va qo‘llash.","Choose and apply the right sorting method.","800 → 1400",["Saralash g‘oyasi","Selection va Bubble","Insertion sort","Merge sort","Quick sort","Custom comparator"]],
 ["binary-search","⌕","#98b5ff","Ikkilik qidiruv","Binary Search","Qidiruv maydonini yarmiga qisqartirish.","Cut the search space in half.","900 → 1600",["Tartiblangan qidiruv","Lower va upper bound","Birinchi rost qiymat","Javob bo‘yicha qidiruv","Haqiqiy sonlar","Murakkab shartlar"]],
 ["two-pointers","⇄","#78e9cf","Ikki ko‘rsatkich va oyna","Two Pointers & Sliding Window","Chiziqli yurish bilan segmentlarni boshqarish.","Manage ranges in linear time.","900 → 1600",["Qarama-qarshi ko‘rsatkichlar","Bir yo‘nalishli yurish","Sliding window","O‘zgaruvchan oyna","Prefix bilan birga","Aralash masalalar"]],
 ["greedy","◆","#ffd76d","Ochko‘z algoritmlar","Greedy Algorithms","Mahalliy tanlovdan global optimumga.","Turn local choices into global optima.","1000 → 1800",["Greedy tanlov","To‘g‘rilik isboti","Faoliyat tanlash","Interval masalalari","Rejalashtirish","Murakkab greedy"]],
 ["backtracking","↩","#f5a6ff","Rekursiya va backtracking","Recursion & Backtracking","Holat daraxtini xavfsiz kezish.","Explore state trees safely.","900 → 1700",["Rekursiya asoslari","Tanlash daraxti","Permutatsiyalar","Kombinatsiyalar","Pruning","Meet-in-the-middle"]],
 ["data-structures","▦","#8ad8ff","Ma’lumot tuzilmalari","Data Structures","Ma’lumotni tez so‘rash va yangilash.","Query and update data efficiently.","1000 → 1900",["Stack va queue","Set va map","Heap","Disjoint Set Union","Fenwick tree","Segment tree"]],
 ["graphs","⌘","#7ee59b","Graf algoritmlari","Graph Algorithms","Tugunlar va qirralar orasidagi yo‘llar.","Navigate nodes, edges, and paths.","1000 → 2100",["Graf modeli","BFS","DFS","Topologik tartib","Dijkstra","Minimum spanning tree"]],
 ["trees","♧","#d1b0ff","Daraxt algoritmlari","Tree Algorithms","Ierarxik graflarda samarali hisoblash.","Compute efficiently on hierarchical graphs.","1100 → 2200",["Daraxt asoslari","Subtree hisoblari","Binary lifting","LCA","Tree diameter","Tree DP"]],
 ["dynamic-programming","∑","#c2a4ff","Dinamik dasturlash","Dynamic Programming","Holat va o‘tishlar orqali qayta hisoblashni yo‘qotish.","Eliminate repeated work with states and transitions.","1100 → 2200",["Memoization","Tabulation","Knapsack","Grid DP","LIS va ketma-ketlik","Bitmask DP"]],
 ["strings","Aa","#ff9eae","Satr algoritmlari","String Algorithms","Matn ichidan andozalarni tez topish.","Find patterns inside text efficiently.","1000 → 2100",["Satr asoslari","Hashing","Prefix function","KMP","Z algoritmi","Trie"]],
 ["math","π","#ffb36f","Matematika va sonlar nazariyasi","Math & Number Theory","Musobaqalar uchun arifmetika va kombinatorika.","Build contest-ready arithmetic and combinatorics.","900 → 2000",["Modul arifmetikasi","EKUB va EKUK","Tub sonlar","Tez daraja","Kombinatorika","Modular inverse"]],
] as const;

const code:Record<string,{cpp:string;python:string;complexity:string}>={
 foundations:{cpp:"for (int i = 0; i < n; ++i) sum += a[i];",python:"total = sum(a)",complexity:"O(n) vaqt · O(1) xotira"},
 sorting:{cpp:"sort(a.begin(), a.end());",python:"a.sort()",complexity:"O(n log n) vaqt"},
 "binary-search":{cpp:"auto it = lower_bound(a.begin(), a.end(), x);",python:"i = bisect_left(a, x)",complexity:"O(log n) vaqt"},
 "two-pointers":{cpp:"while (r < n) { add(a[r++]); while (bad()) remove(a[l++]); }",python:"while r < n:\n    add(a[r]); r += 1\n    while bad(): remove(a[l]); l += 1",complexity:"O(n) vaqt"},
 greedy:{cpp:"sort(jobs.begin(), jobs.end(), byFinish);",python:"jobs.sort(key=lambda job: job.finish)",complexity:"O(n log n) vaqt"},
 backtracking:{cpp:"void dfs(int v) { choose(v); dfs(v + 1); undo(v); }",python:"def dfs(v):\n    choose(v); dfs(v + 1); undo(v)",complexity:"O(b^d) eng yomon holat"},
 "data-structures":{cpp:"priority_queue<int> pq; pq.push(x);",python:"heappush(pq, x)",complexity:"O(log n) yangilash"},
 graphs:{cpp:"queue<int> q; q.push(source);",python:"q = deque([source])",complexity:"O(V + E) vaqt"},
 trees:{cpp:"depth[to] = depth[v] + 1; dfs(to, v);",python:"depth[to] = depth[v] + 1\ndfs(to, v)",complexity:"O(n) kezish"},
 "dynamic-programming":{cpp:"dp[i] = min(dp[i], dp[j] + cost);",python:"dp[i] = min(dp[i], dp[j] + cost)",complexity:"holatlar × o‘tishlar"},
 strings:{cpp:"vector<int> pi = prefix_function(s);",python:"pi = prefix_function(s)",complexity:"O(n) vaqt"},
 math:{cpp:"long long ans = binpow(a, b, mod);",python:"answer = pow(a, b, mod)",complexity:"O(log b) vaqt"},
};

const englishTitles:Record<string,string[]>={
 foundations:["Input and constraints","Big O notation","Arrays and loops","Memory complexity","Amortization","Final analysis"],sorting:["Why sorting matters","Selection and Bubble","Insertion sort","Merge sort","Quick sort","Custom comparators"],"binary-search":["Ordered search","Lower and upper bound","First true value","Binary search on answer","Real-valued search","Complex predicates"],"two-pointers":["Opposite pointers","Forward pointers","Sliding window","Variable window","With prefix sums","Mixed patterns"],greedy:["Greedy choice","Correctness proofs","Activity selection","Interval problems","Scheduling","Advanced greedy"],backtracking:["Recursion basics","Decision trees","Permutations","Combinations","Pruning","Meet in the middle"],"data-structures":["Stack and queue","Set and map","Heap","Disjoint Set Union","Fenwick tree","Segment tree"],graphs:["Graph modeling","BFS","DFS","Topological order","Dijkstra","Minimum spanning tree"],trees:["Tree basics","Subtree values","Binary lifting","LCA","Tree diameter","Tree DP"],"dynamic-programming":["Memoization","Tabulation","Knapsack","Grid DP","LIS and sequences","Bitmask DP"],strings:["String basics","Hashing","Prefix function","KMP","Z algorithm","Trie"],math:["Modular arithmetic","GCD and LCM","Prime numbers","Fast exponentiation","Combinatorics","Modular inverse"]
};

export const roadmapCatalog:MasteryRoadmap[]=definitions.map((d)=>{const [slug,icon,color,titleUz,titleEn,descriptionUz,descriptionEn,level,titles]=d;return {slug,icon,color,titleUz,titleEn,descriptionUz,descriptionEn,level,prerequisiteUz:slug==="foundations"?"Dasturlash asoslari":"Oldingi asosiy yo‘llar",prerequisiteEn:slug==="foundations"?"Programming basics":"Earlier foundation paths",units:titles.map((titleUz,index)=>({id:`${slug}-${index+1}`,titleUz,titleEn:englishTitles[slug][index],summaryUz:`${titleUz} mavzusining asosiy g‘oyasi, qachon ishlatilishi va xatolarini bosqichma-bosqich o‘rganing.`,summaryEn:`Learn the core idea behind ${englishTitles[slug][index]}, when to use it, and the mistakes to avoid.`,rating:`${800+index*100} → ${1100+index*150}`,minutes:18+index*4,complexity:code[slug].complexity,cpp:code[slug].cpp,python:code[slug].python,quiz:{questionUz:`${titleUz} uchun eng muhim birinchi qadam qaysi?`,questionEn:`What is the most important first step for ${englishTitles[slug][index]}?`,choicesUz:["Cheklov va invariantni aniqlash","Tasodifiy kod yozish","Har doim O(n²) ishlatish","Testlarni e’tiborsiz qoldirish"],choicesEn:["Identify constraints and the invariant","Write random code","Always use O(n²)","Ignore test cases"],correct:0},problemId:["A01","A02","A03","B01","B02","B03"][index]}) )};});

export const roadmapCards=roadmapCatalog.map(r=>({slug:r.slug,icon:r.icon,color:r.color,uz:r.titleUz,en:r.titleEn,descUz:r.descriptionUz,descEn:r.descriptionEn,units:r.units.length,progress:0}));
