export type LessonUnit={id:string;titleUz:string;titleEn:string;summaryUz:string;summaryEn:string;rating:string;minutes:number;complexity:string;cpp:string;python:string;quiz:{questionUz:string;questionEn:string;choicesUz:string[];choicesEn:string[];correct:number};problemId:string};
export type RoadmapDifficulty="beginner"|"intermediate"|"advanced"|"expert";
export type MasteryRoadmap={slug:string;icon:string;color:string;titleUz:string;titleEn:string;descriptionUz:string;descriptionEn:string;level:string;difficulty:RoadmapDifficulty;category:string;categoryUz:string;prereqs:string[];prerequisiteUz:string;prerequisiteEn:string;units:LessonUnit[]};

type Def={slug:string;icon:string;color:string;uz:string;en:string;descUz:string;descEn:string;level:string;difficulty:RoadmapDifficulty;cat:string;catUz:string;prereqs:string[];units:string[];unitsEn:string[];cpp:string;python:string;complexity:string};

const defs:Def[]=[
 {slug:"programming-basics",icon:"</>",color:"#9df2e0",uz:"Dasturlash asoslari",en:"Programming Basics",descUz:"C++ tili, STL va musobaqa muhitini o‘rnatish.",descEn:"Set up C++, STL, and the contest environment.",level:"0 → 800",difficulty:"beginner",cat:"Basics",catUz:"Asoslar",prereqs:[],units:["Muhitni sozlash","Kirish va chiqish","O‘zgaruvchilar va tiplar","Shart operatorlari","Sikllar","Funksiyalar, massivlar va STL"],unitsEn:["Environment setup","Input and output","Variables and types","Conditions","Loops","Functions, arrays and STL"],cpp:"#include <bits/stdc++.h>\nusing namespace std;",python:"import sys\ninput = sys.stdin.readline",complexity:"O(1) asosiy amallar"},
 {slug:"foundations",icon:"O(n)",color:"#c8ff76",uz:"Asoslar va murakkablik",en:"Foundations & Complexity",descUz:"Algoritm tezligi, xotira va to‘g‘ri baholash.",descEn:"Reason about runtime, memory, and constraints.",level:"800 → 1100",difficulty:"beginner",cat:"Basics",catUz:"Asoslar",prereqs:["programming-basics"],units:["Kirish va cheklovlar","Big O belgisi","Massiv va sikllar","Xotira murakkabligi","Amortizatsiya","Yakuniy tahlil"],unitsEn:["Input and constraints","Big O notation","Arrays and loops","Memory complexity","Amortization","Final analysis"],cpp:"for (int i = 0; i < n; ++i) sum += a[i];",python:"total = sum(a)",complexity:"O(n) vaqt · O(1) xotira"},
 {slug:"sorting",icon:"↕",color:"#ffbd8f",uz:"Saralash algoritmlari",en:"Sorting Algorithms",descUz:"Saralash usullarini tanlash va qo‘llash.",descEn:"Choose and apply the right sorting method.",level:"800 → 1400",difficulty:"beginner",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["foundations"],units:["Saralash g‘oyasi","Selection va Bubble","Insertion sort","Merge sort","Quick sort","Custom comparator"],unitsEn:["Why sorting matters","Selection and Bubble","Insertion sort","Merge sort","Quick sort","Custom comparators"],cpp:"sort(a.begin(), a.end());",python:"a.sort()",complexity:"O(n log n) vaqt"},
 {slug:"backtracking",icon:"↩",color:"#f5a6ff",uz:"Rekursiya va backtracking",en:"Recursion & Backtracking",descUz:"Holat daraxtini xavfsiz kezish.",descEn:"Explore state trees safely.",level:"900 → 1700",difficulty:"intermediate",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["foundations"],units:["Rekursiya asoslari","Tanlash daraxti","Permutatsiyalar","Kombinatsiyalar","Pruning","Meet-in-the-middle"],unitsEn:["Recursion basics","Decision trees","Permutations","Combinations","Pruning","Meet in the middle"],cpp:"void dfs(int v) { choose(v); dfs(v + 1); undo(v); }",python:"def dfs(v):\n    choose(v); dfs(v + 1); undo(v)",complexity:"O(b^d) eng yomon holat"},
 {slug:"math",icon:"π",color:"#ffb36f",uz:"Matematika va sonlar nazariyasi",en:"Math & Number Theory",descUz:"Musobaqalar uchun arifmetika va kombinatorika.",descEn:"Build contest-ready arithmetic and combinatorics.",level:"900 → 2000",difficulty:"intermediate",cat:"Math",catUz:"Matematika",prereqs:["foundations"],units:["Modul arifmetikasi","EKUB va EKUK","Tub sonlar","Tez daraja","Kombinatorika","Modular inverse"],unitsEn:["Modular arithmetic","GCD and LCM","Prime numbers","Fast exponentiation","Combinatorics","Modular inverse"],cpp:"long long ans = binpow(a, b, mod);",python:"answer = pow(a, b, mod)",complexity:"O(log b) vaqt"},
 {slug:"data-structures",icon:"▦",color:"#8ad8ff",uz:"Ma’lumot tuzilmalari",en:"Data Structures",descUz:"Ma’lumotni tez so‘rash va yangilash.",descEn:"Query and update data efficiently.",level:"1000 → 1900",difficulty:"intermediate",cat:"Data Structures",catUz:"Ma’lumot tuzilmalari",prereqs:["foundations"],units:["Stack va queue","Set va map","Heap","Disjoint Set Union","Fenwick tree","Segment tree"],unitsEn:["Stack and queue","Set and map","Heap","Disjoint Set Union","Fenwick tree","Segment tree"],cpp:"priority_queue<int> pq; pq.push(x);",python:"heappush(pq, x)",complexity:"O(log n) yangilash"},
 {slug:"binary-search",icon:"⌕",color:"#98b5ff",uz:"Ikkilik qidiruv",en:"Binary Search",descUz:"Qidiruv maydonini yarmiga qisqartirish.",descEn:"Cut the search space in half.",level:"900 → 1600",difficulty:"beginner",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["sorting"],units:["Tartiblangan qidiruv","Lower va upper bound","Birinchi rost qiymat","Javob bo‘yicha qidiruv","Haqiqiy sonlar","Murakkab shartlar"],unitsEn:["Ordered search","Lower and upper bound","First true value","Binary search on answer","Real-valued search","Complex predicates"],cpp:"auto it = lower_bound(a.begin(), a.end(), x);",python:"i = bisect_left(a, x)",complexity:"O(log n) vaqt"},
 {slug:"greedy",icon:"◆",color:"#ffd76d",uz:"Ochko‘z algoritmlar",en:"Greedy Algorithms",descUz:"Mahalliy tanlovdan global optimumga.",descEn:"Turn local choices into global optima.",level:"1000 → 1800",difficulty:"intermediate",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["sorting"],units:["Greedy tanlov","To‘g‘rilik isboti","Faoliyat tanlash","Interval masalalari","Rejalashtirish","Murakkab greedy"],unitsEn:["Greedy choice","Correctness proofs","Activity selection","Interval problems","Scheduling","Advanced greedy"],cpp:"sort(jobs.begin(), jobs.end(), byFinish);",python:"jobs.sort(key=lambda job: job.finish)",complexity:"O(n log n) vaqt"},
 {slug:"graphs",icon:"⌘",color:"#7ee59b",uz:"Graf algoritmlari",en:"Graph Algorithms",descUz:"Tugunlar va qirralar orasidagi yo‘llar.",descEn:"Navigate nodes, edges, and paths.",level:"1000 → 2100",difficulty:"advanced",cat:"Graphs",catUz:"Graflar",prereqs:["data-structures","backtracking"],units:["Graf modeli","BFS","DFS","Topologik tartib","Dijkstra","Minimum spanning tree"],unitsEn:["Graph modeling","BFS","DFS","Topological order","Dijkstra","Minimum spanning tree"],cpp:"queue<int> q; q.push(source);",python:"q = deque([source])",complexity:"O(V + E) vaqt"},
 {slug:"strings",icon:"Aa",color:"#ff9eae",uz:"Satr algoritmlari",en:"String Algorithms",descUz:"Matn ichidan andozalarni tez topish.",descEn:"Find patterns inside text efficiently.",level:"1000 → 2100",difficulty:"advanced",cat:"Strings",catUz:"Satrlar",prereqs:["data-structures"],units:["Satr asoslari","Hashing","Prefix function","KMP","Z algoritmi","Trie"],unitsEn:["String basics","Hashing","Prefix function","KMP","Z algorithm","Trie"],cpp:"vector<int> pi = prefix_function(s);",python:"pi = prefix_function(s)",complexity:"O(n) vaqt"},
 {slug:"geometry",icon:"△",color:"#a8e6a1",uz:"Hisoblash geometriyasi",en:"Computational Geometry",descUz:"Nuqtalar, vektorlar va qavariq qobiqlar.",descEn:"Points, vectors, and convex hulls.",level:"1400 → 2400",difficulty:"advanced",cat:"Geometry",catUz:"Geometriya",prereqs:["math"],units:["Nuqta va vektor","Skalyar ko‘paytma","Vektor ko‘paytma","Kesishuvchi kesmalar","Ko‘pburchak yuzi","Qavariq qobiq"],unitsEn:["Points and vectors","Dot product","Cross product","Segment intersection","Polygon area","Convex hull"],cpp:"long long cross(Point a, Point b) { return a.x*b.y - a.y*b.x; }",python:"def cross(a, b):\n    return a[0]*b[1] - a[1]*b[0]",complexity:"O(n log n) qavariq qobiq"},
 {slug:"two-pointers",icon:"⇄",color:"#78e9cf",uz:"Ikki ko‘rsatkich va oyna",en:"Two Pointers & Sliding Window",descUz:"Chiziqli yurish bilan segmentlarni boshqarish.",descEn:"Manage ranges in linear time.",level:"900 → 1600",difficulty:"intermediate",cat:"Algorithms",catUz:"Algoritmlar",prereqs:["binary-search"],units:["Qarama-qarshi ko‘rsatkichlar","Bir yo‘nalishli yurish","Sliding window","O‘zgaruvchan oyna","Prefix bilan birga","Aralash masalalar"],unitsEn:["Opposite pointers","Forward pointers","Sliding window","Variable window","With prefix sums","Mixed patterns"],cpp:"while (r < n) { add(a[r++]); while (bad()) remove(a[l++]); }",python:"while r < n:\n    add(a[r]); r += 1\n    while bad(): remove(a[l]); l += 1",complexity:"O(n) vaqt"},
 {slug:"dynamic-programming",icon:"∑",color:"#c2a4ff",uz:"Dinamik dasturlash",en:"Dynamic Programming",descUz:"Holat va o‘tishlar orqali qayta hisoblashni yo‘qotish.",descEn:"Eliminate repeated work with states and transitions.",level:"1100 → 2200",difficulty:"advanced",cat:"DP",catUz:"DP",prereqs:["backtracking","greedy"],units:["Memoization","Tabulation","Knapsack","Grid DP","LIS va ketma-ketlik","Bitmask DP"],unitsEn:["Memoization","Tabulation","Knapsack","Grid DP","LIS and sequences","Bitmask DP"],cpp:"dp[i] = min(dp[i], dp[j] + cost);",python:"dp[i] = min(dp[i], dp[j] + cost)",complexity:"holatlar × o‘tishlar"},
 {slug:"trees",icon:"♧",color:"#d1b0ff",uz:"Daraxt algoritmlari",en:"Tree Algorithms",descUz:"Ierarxik graflarda samarali hisoblash.",descEn:"Compute efficiently on hierarchical graphs.",level:"1100 → 2200",difficulty:"advanced",cat:"Graphs",catUz:"Graflar",prereqs:["graphs"],units:["Daraxt asoslari","Subtree hisoblari","Binary lifting","LCA","Tree diameter","Tree DP"],unitsEn:["Tree basics","Subtree values","Binary lifting","LCA","Tree diameter","Tree DP"],cpp:"depth[to] = depth[v] + 1; dfs(to, v);",python:"depth[to] = depth[v] + 1\ndfs(to, v)",complexity:"O(n) kezish"},
 {slug:"advanced-cp",icon:"✦",color:"#ffd9a8",uz:"Ilg‘or CP va ICPC",en:"Advanced CP & ICPC",descUz:"Expert darajadagi tuzilmalar va optimallashtirishlar.",descEn:"Expert-level structures and optimizations.",level:"1900 → 3000",difficulty:"expert",cat:"Advanced",catUz:"Ilg‘or",prereqs:["dynamic-programming","graphs"],units:["Persistent segment tree","Treap va implicit treap","Mo algoritmi","Heavy-Light decomposition","FFT va NTT","O‘yinlar nazariyasi"],unitsEn:["Persistent segment tree","Treap and implicit treap","Mo's algorithm","Heavy-Light decomposition","FFT and NTT","Game theory"],cpp:"struct Node { int l, r, sum; } st[MAXN * 20];",python:"# persistent segtree nodes\nnodes = [(0, 0, 0)]",complexity:"O(log n) so‘rov"},
];

const problemIds=["A01","A02","A03","B01","B02","B03"];

export const roadmapCatalog:MasteryRoadmap[]=defs.map(d=>({
 slug:d.slug,icon:d.icon,color:d.color,titleUz:d.uz,titleEn:d.en,descriptionUz:d.descUz,descriptionEn:d.descEn,level:d.level,difficulty:d.difficulty,category:d.cat,categoryUz:d.catUz,prereqs:d.prereqs,
 prerequisiteUz:d.prereqs.length?d.prereqs.map(s=>defs.find(x=>x.slug===s)?.uz||s).join(" + "):"Yo‘q — boshlanish nuqtasi",
 prerequisiteEn:d.prereqs.length?d.prereqs.map(s=>defs.find(x=>x.slug===s)?.en||s).join(" + "):"None — starting point",
 units:d.units.map((titleUz,index)=>({
  id:`${d.slug}-${index+1}`,titleUz,titleEn:d.unitsEn[index],
  summaryUz:`${titleUz} mavzusining asosiy g‘oyasi, qachon ishlatilishi va xatolarini bosqichma-bosqich o‘rganing.`,
  summaryEn:`Learn the core idea behind ${d.unitsEn[index]}, when to use it, and the mistakes to avoid.`,
  rating:`${800+index*100} → ${1100+index*150}`,minutes:18+index*4,complexity:d.complexity,cpp:d.cpp,python:d.python,
  quiz:{questionUz:`${titleUz} uchun eng muhim birinchi qadam qaysi?`,questionEn:`What is the most important first step for ${d.unitsEn[index]}?`,choicesUz:["Cheklov va invariantni aniqlash","Tasodifiy kod yozish","Har doim O(n²) ishlatish","Testlarni e’tiborsiz qoldirish"],choicesEn:["Identify constraints and the invariant","Write random code","Always use O(n²)","Ignore test cases"],correct:0},
  problemId:problemIds[index%problemIds.length]
 }))
}));

export const roadmapCards=roadmapCatalog.map(r=>({slug:r.slug,icon:r.icon,color:r.color,uz:r.titleUz,en:r.titleEn,descUz:r.descriptionUz,descEn:r.descriptionEn,units:r.units.length,progress:0}));
