/* Per-unit illustrative code snippets. Each roadmap's 6 units previously
   shared one roadmap-level snippet (roadmap-data.ts's cpp/python); this map
   gives every unit its own, so "Merge sort" and "Quick sort" inside the same
   roadmap no longer show identical code. */

export type UnitCode = { cpp: string; python: string };

export const unitCode: Record<string, UnitCode> = {
  // ---- Programming Basics (15-stage deep track) ----
  "programming-basics-1": { cpp: "#include <bits/stdc++.h>\nusing namespace std;\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n}", python: "import sys\ninput = sys.stdin.readline" },
  "programming-basics-2": { cpp: "int n; cin >> n;\nvector<long long> a(n);\nfor (auto &x : a) cin >> x;", python: "n = int(input())\na = list(map(int, input().split()))" },
  "programming-basics-3": { cpp: "int n = 5;\nlong long big = 5000000000LL;\ndouble pi = 3.14159;\nchar c = 'A';\nbool ok = true;\nstring s = \"hello\";", python: "n = 5\nbig = 5000000000\npi = 3.14159\nc = 'A'\nok = True\ns = \"hello\"" },
  "programming-basics-4": { cpp: "long long p = 1LL * a * b;  // avoid int overflow", python: "p = a * b  # Python ints never overflow" },
  "programming-basics-5": { cpp: "double avg = (double)(a + b) / 2;\nbool even = (x % 2 == 0);\nint doubled = x << 1;", python: "avg = (a + b) / 2\neven = (x % 2 == 0)\ndoubled = x << 1" },
  "programming-basics-6": { cpp: "if (i >= 0 && i < n && a[i] == key) { /* safe */ }", python: "if 0 <= i < n and a[i] == key:\n    pass" },
  "programming-basics-7": { cpp: "switch (day) {\n  case 1: name = \"Mon\"; break;\n  case 2: name = \"Tue\"; break;\n  default: name = \"?\";\n}\nint mx = a > b ? a : b;", python: "name = {1: \"Mon\", 2: \"Tue\"}.get(day, \"?\")\nmx = a if a > b else b" },
  "programming-basics-8": { cpp: "for (int i = 0; i < n; ++i)\n  for (int j = i + 1; j < n; ++j)\n    check(a[i], a[j]);", python: "for i in range(n):\n    for j in range(i + 1, n):\n        check(a[i], a[j])" },
  "programming-basics-9": { cpp: "int steps = 0;\nwhile (x > 1) { x /= 2; ++steps; }", python: "steps = 0\nwhile x > 1:\n    x //= 2\n    steps += 1" },
  "programming-basics-10": { cpp: "const int MAXN = 1e6 + 5;\nint a[MAXN];\nfor (int i = 0; i < n; ++i) cin >> a[i];", python: "a = [0] * n\nfor i in range(n): a[i] = int(input())" },
  "programming-basics-11": { cpp: "int dx[] = {-1, 1, 0, 0}, dy[] = {0, 0, -1, 1};\nfor (int k = 0; k < 4; ++k) {\n  int ni = i + dx[k], nj = j + dy[k];\n  if (ni >= 0 && ni < n && nj >= 0 && nj < m) { /* valid */ }\n}", python: "dx, dy = [-1, 1, 0, 0], [0, 0, -1, 1]\nfor k in range(4):\n    ni, nj = i + dx[k], j + dy[k]\n    if 0 <= ni < n and 0 <= nj < m:\n        pass" },
  "programming-basics-12": { cpp: "string s = \"hello\";\nstring part = s.substr(1, 3);  // \"ell\"\nbool isPal = s == string(s.rbegin(), s.rend());", python: "s = \"hello\"\npart = s[1:4]  # \"ell\"\nis_pal = s == s[::-1]" },
  "programming-basics-13": { cpp: "long long gcd(long long a, long long b) {\n  return b ? gcd(b, a % b) : a;\n}", python: "def gcd(a, b):\n    return gcd(b, a % b) if b else a" },
  "programming-basics-14": { cpp: "void addOne(int &x) { x++; }  // reference: caller's value changes\nvoid f(const vector<int> &a) { /* read-only, no copy */ }", python: "# Python passes references to mutable objects (lists) by default\ndef add_one(lst): lst.append(1)" },
  "programming-basics-15": { cpp: "vector<int> a = {5, 3, 1, 4};\nsort(a.begin(), a.end());\nlong long s = accumulate(a.begin(), a.end(), 0LL);\nint mx = *max_element(a.begin(), a.end());", python: "a = [5, 3, 1, 4]\na.sort()\ns = sum(a)\nmx = max(a)" },

  "programming-basics-16": { cpp: "if (n & 1) { /* toq son */ }\nint half = n >> 1;          // n / 2\nbool on = (mask >> k) & 1;  // k-bit yoqilganmi\nmask |= (1 << k);           // k-bitni yoqish\nmask &= ~(1 << k);          // k-bitni o'chirish\nint bits = __builtin_popcount(mask);", python: "if n & 1:\n    pass                    # toq son\nhalf = n >> 1               # n // 2\non = (mask >> k) & 1        # k-bit yoqilganmi\nmask |= 1 << k              # yoqish\nmask &= ~(1 << k)           # o'chirish\nbits = bin(mask).count('1')" },
  "programming-basics-17": { cpp: "// cerr judgega bormaydi — debug uchun xavfsiz\ncerr << \"sum = \" << sum << '\\n';\nassert(0 <= i && i < n);", python: "import sys\nprint('debug:', x, file=sys.stderr)   # stderr judgega bormaydi\nassert 0 <= i < n" },

  // ---- Foundations & Complexity (15-stage deep track) ----
  "foundations-1": { cpp: "// same answer, wildly different speed:\n// O(n) pass vs O(n^2) all-pairs -- correctness isn't enough, speed matters", python: "# same answer, wildly different speed:\n# O(n) pass vs O(n^2) all-pairs -- correctness isn't enough, speed matters" },
  "foundations-2": { cpp: "// n <= 1e5, t <= 1e4 -> total work must respect sum(n) bound", python: "# n <= 1e5, t <= 1e4 -> check the constraints section first" },
  "foundations-3": { cpp: "// O(f(n)): upper bound   O(g(n)): lower bound (Omega)   Theta: both\n// 3n + 5 = O(n) -- constants and lower-order terms are dropped", python: "# O(f(n)): upper bound   O(g(n)): lower bound (Omega)   Theta: both\n# 3n + 5 = O(n) -- constants and lower-order terms are dropped" },
  "foundations-4": { cpp: "// linear search: best case O(1) (found first), worst case O(n) (found last/absent)\n// CP designs for the WORST case -- judges send adversarial tests", python: "# linear search: best case O(1) (found first), worst case O(n) (found last/absent)\n# CP designs for the WORST case -- judges send adversarial tests" },
  "foundations-5": { cpp: "int mid = (l + r) / 2;               // O(1)\nlong long s = 0;\nfor (int x : a) s += x;              // O(n)", python: "mid = (l + r) // 2   # O(1)\ns = sum(a)            # O(n)" },
  "foundations-6": { cpp: "int lo = 0, hi = n - 1;              // O(log n): halves the range each step\nwhile (lo < hi) { int mid = (lo+hi)/2; a[mid] < x ? lo = mid+1 : hi = mid; }", python: "lo, hi = 0, n - 1   # O(log n): halves the range each step\nwhile lo < hi:\n    mid = (lo + hi) // 2" },
  "foundations-7": { cpp: "sort(a.begin(), a.end());  // O(n log n): the CP workhorse complexity", python: "a.sort()  # O(n log n): the CP workhorse complexity" },
  "foundations-8": { cpp: "for (int i = 0; i < n; ++i)\n  for (int j = i + 1; j < n; ++j)  // O(n^2): all pairs", python: "for i in range(n):\n    for j in range(i + 1, n):  # O(n^2): all pairs\n        pass" },
  "foundations-9": { cpp: "// n <= 20-25 signals 2^n: enumerate all subsets\nfor (int mask = 0; mask < (1 << n); ++mask) { /* ... */ }", python: "# n <= 20-25 signals 2**n: enumerate all subsets\nfor mask in range(1 << n):\n    pass" },
  "foundations-10": { cpp: "for (int i = 0; i < n; ++i)\n  for (int j = 0; j < i; ++j)  // n^2/2 pairs -> still O(n^2)", python: "for i in range(n):\n    for j in range(i):  # n^2/2 pairs -> still O(n^2)\n        pass" },
  "foundations-11": { cpp: "// T(n) = 2T(n/2) + O(n)  ->  O(n log n) by the Master Theorem (merge sort)\nlong long f(int n) { return n <= 1 ? n : f(n-1) + f(n-2); }  // exponential, no cache", python: "# T(n) = 2T(n/2) + O(n)  ->  O(n log n) by the Master Theorem (merge sort)\ndef f(n):\n    return n if n <= 1 else f(n-1) + f(n-2)  # exponential, no cache" },
  "foundations-12": { cpp: "const int MAXN = 1e6 + 5;\nlong long dp[2][MAXN];  // rolling array: only the previous row needed", python: "MAXN = 10**6 + 5\ndp = [[0]*MAXN, [0]*MAXN]  # rolling array: only the previous row needed" },
  "foundations-13": { cpp: "int l = 0;\nfor (int r = 0; r < n; ++r) {          // l and r each move forward <= n times\n  while (bad()) ++l;                   // amortized O(n) total, not O(n^2)\n}", python: "l = 0\nfor r in range(n):        # l and r each move forward <= n times\n    while bad(): l += 1   # amortized O(n) total, not O(n^2)" },
  "foundations-14": { cpp: "// n<=10: anything | n<=25: 2^n | n<=5000: O(n^2) | n<=1e7: O(n log n)\n// among solutions that fit, pick the SIMPLEST one", python: "# n<=10: anything | n<=25: 2**n | n<=5000: O(n^2) | n<=1e7: O(n log n)\n# among solutions that fit, pick the SIMPLEST one" },
  "foundations-15": { cpp: "// T(n) = a*T(n/b) + f(n)  ->  barglar: n^(log_b a)\n// merge sort:    T(n) = 2T(n/2) + O(n)   -> O(n log n)\n// binary search: T(n) =  T(n/2) + O(1)   -> O(log n)\n// Karatsuba:     T(n) = 3T(n/2) + O(n)   -> O(n^1.585)", python: "# T(n) = a*T(n/b) + f(n)  ->  barglar: n^(log_b a)\n# merge sort:    T(n) = 2T(n/2) + O(n)   -> O(n log n)\n# binary search: T(n) =  T(n/2) + O(1)   -> O(log n)\n# Karatsuba:     T(n) = 3T(n/2) + O(n)   -> O(n^1.585)" },
  "foundations-16": { cpp: "// kesh: xotiradagi tartibda yuring\nfor (int i = 0; i < n; ++i)      // TEZ: qo'shni manzillar\n    for (int j = 0; j < m; ++j)\n        sum += a[i][j];\n\n// sikl ichida % o'rniga shartli ayirish\nsum += a[i];\nif (sum >= MOD) sum -= MOD;", python: "# kesh: xotiradagi tartibda yuring\nfor row in a:            # TEZ: qo'shni manzillar\n    for x in row:\n        total += x\n\n# sikl ichida % o'rniga shartli ayirish\ntotal += a[i]\nif total >= MOD:\n    total -= MOD" },
  "foundations-17": { cpp: "// prefix sum: O(n) tayyorlash, O(1) so'rov\nvector<long long> pref(n + 1, 0);\nfor (int i = 0; i < n; ++i) pref[i + 1] = pref[i] + a[i];\n// [l, r] yig'indisi (1-indeksli):\nlong long ans = pref[r] - pref[l - 1];", python: "# prefix sum: O(n) tayyorlash, O(1) so'rov\npref = [0] * (n + 1)\nfor i in range(n):\n    pref[i + 1] = pref[i] + a[i]\n# [l, r] yig'indisi (1-indeksli):\nans = pref[r] - pref[l - 1]" },

  // ---- Sorting (15-stage deep track) ----
  "sorting-1": { cpp: "sort(a.begin(), a.end());  // O(n log n), introsort", python: "a.sort()  # O(n log n), Timsort" },
  "sorting-2": { cpp: "for (int i = 0; i < n; ++i) {\n  int m = i;\n  for (int j = i+1; j < n; ++j) if (a[j] < a[m]) m = j;\n  swap(a[i], a[m]);\n}", python: "for i in range(n):\n    m = min(range(i, n), key=lambda j: a[j])\n    a[i], a[m] = a[m], a[i]" },
  "sorting-3": { cpp: "for (int i = 0; i < n; ++i) {\n  bool sw = false;\n  for (int j = 0; j+1 < n-i; ++j)\n    if (a[j] > a[j+1]) { swap(a[j], a[j+1]); sw = true; }\n  if (!sw) break;\n}", python: "for i in range(n):\n    swapped = False\n    for j in range(n - i - 1):\n        if a[j] > a[j+1]: a[j], a[j+1] = a[j+1], a[j]; swapped = True\n    if not swapped: break" },
  "sorting-4": { cpp: "for (int i = 1; i < n; ++i) {\n  int key = a[i], j = i - 1;\n  while (j >= 0 && a[j] > key) a[j + 1] = a[j--];\n  a[j + 1] = key;\n}", python: "for i in range(1, n):\n    key, j = a[i], i - 1\n    while j >= 0 and a[j] > key:\n        a[j + 1] = a[j]; j -= 1\n    a[j + 1] = key" },
  "sorting-5": { cpp: "vector<int> cnt(k+1, 0);\nfor (int x : a) cnt[x]++;\nvector<int> out;\nfor (int v = 0; v <= k; ++v) while (cnt[v]--) out.push_back(v);", python: "cnt = [0] * (k + 1)\nfor x in a: cnt[x] += 1\nout = [v for v in range(k + 1) for _ in range(cnt[v])]" },
  "sorting-6": { cpp: "void merge(vector<int>&a,int l,int m,int r){\n  vector<int> t;\n  merge(a.begin()+l,a.begin()+m,a.begin()+m,a.begin()+r,back_inserter(t));\n}", python: "def merge(a, l, m, r):\n    return sorted(a[l:m] + a[m:r])" },
  "sorting-7": { cpp: "// during merge: taking from the right side means += (mid - i + 1) inversions\nif (a[j] < a[i]) { inv += (mid - i + 1); tmp.push_back(a[j++]); }", python: "# during merge: taking from the right side means += (mid - i + 1) inversions\nif a[j] < a[i]:\n    inv += mid - i + 1\n    j += 1" },
  "sorting-8": { cpp: "int p = partition(a.begin(), a.end(), [&](int x){ return x < pivot; });", python: "pivot = a[len(a)//2]\nless = [x for x in a if x < pivot]" },
  "sorting-9": { cpp: "void siftDown(vector<int>&a,int i,int n){\n  int l=2*i+1,r=2*i+2,largest=i;\n  if(l<n&&a[l]>a[largest])largest=l;\n  if(r<n&&a[r]>a[largest])largest=r;\n  if(largest!=i){swap(a[i],a[largest]);siftDown(a,largest,n);}\n}", python: "def sift_down(a, i, n):\n    l, r, largest = 2*i+1, 2*i+2, i\n    if l < n and a[l] > a[largest]: largest = l\n    if r < n and a[r] > a[largest]: largest = r\n    if largest != i:\n        a[i], a[largest] = a[largest], a[i]\n        sift_down(a, largest, n)" },
  "sorting-10": { cpp: "// log2(n!) ~= n*log2(n) - n*log2(e)  ->  Theta(n log n) comparisons, provably minimal", python: "# log2(n!) ~= n*log2(n) - n*log2(e)  ->  Theta(n log n) comparisons, provably minimal" },
  "sorting-11": { cpp: "stable_sort(a.begin(), a.end(), cmp);  // guarantees equal elements keep their order", python: "a.sort(key=cmp_key)  # Python's sort is always stable" },
  "sorting-12": { cpp: "sort(a.begin(), a.end(), [](int x, int y){ return x > y; });  // descending", python: "a.sort(key=lambda x: -x)  # descending" },
  "sorting-13": { cpp: "sort(v.begin(), v.end(), [](auto&a, auto&b){\n  return make_tuple(-a.score, a.age, a.name) < make_tuple(-b.score, b.age, b.name);\n});", python: "v.sort(key=lambda x: (-x.score, x.age, x.name))" },
  "sorting-14": { cpp: "partial_sort(a.begin(), a.begin()+k, a.end());   // top-k, ordered\nnth_element(a.begin(), a.begin()+n/2, a.end()); // median, unordered sides", python: "import heapq\ntopk = heapq.nsmallest(k, a)  # partial_sort equivalent" },
  "sorting-15": { cpp: "sort(jobs.begin(), jobs.end(), [](auto&a, auto&b){ return a.finish < b.finish; });", python: "jobs.sort(key=lambda j: j.finish)" },
  "sorting-16": { cpp: "// LSD radix: eng oxirgi raqamdan boshlab, har bosqich BARQAROR\nfor (int shift = 0; shift < 32; shift += 8) {\n    // 256 ta idish bo'yicha counting sort\n    for (uint32_t x : a) ++cnt[((x >> shift) & 255) + 1];\n}", python: "# LSD radix: eng oxirgi raqamdan boshlab, har bosqich BARQAROR\nfor shift in range(0, 32, 8):\n    buckets = [[] for _ in range(256)]\n    for x in a:\n        buckets[(x >> shift) & 255].append(x)" },
  "sorting-17": { cpp: "vector<int> vals = a;\nsort(vals.begin(), vals.end());\nvals.erase(unique(vals.begin(), vals.end()), vals.end());\nfor (int i = 0; i < n; ++i)\n    a[i] = lower_bound(vals.begin(), vals.end(), a[i]) - vals.begin();", python: "vals = sorted(set(a))\nrank = {v: i for i, v in enumerate(vals)}\na = [rank[x] for x in a]" },
  "sorting-18": { cpp: "nth_element(v.begin(), v.begin() + k, v.end());\nint kth = v[k];        // k-chi eng kichik, o'rtacha O(n)\n\nnth_element(v.begin(), v.begin() + n / 2, v.end());\nint median = v[n / 2];", python: "import heapq\n# k-chi eng kichik: O(n) o'rtacha muqobili yo'q, lekin\nkth = heapq.nsmallest(k + 1, v)[-1]" },

  // ---- Recursion & Backtracking (15-stage deep track) ----
  "backtracking-1": { cpp: "long long fact(int n) { return n <= 1 ? 1 : n * fact(n - 1); }", python: "def fact(n):\n    return 1 if n <= 1 else n * fact(n - 1)" },
  "backtracking-2": { cpp: "// linear: one call            // multi-branch: two+ calls, exponential w/o cache\nlong long fib(int n){ return n<2?n:fib(n-1)+fib(n-2); }", python: "# linear: one call            # multi-branch: two+ calls, exponential w/o cache\ndef fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)" },
  "backtracking-3": { cpp: "// recursive: long long gcd(long long a,long long b){return b?gcd(b,a%b):a;}\nwhile (b) { long long t = b; b = a % b; a = t; }  // iterative, no stack cost", python: "while b:\n    a, b = b, a % b  # iterative, no stack cost" },
  "backtracking-4": { cpp: "void dfs(int v) { if (base(v)) return; choose(v); dfs(v + 1); undo(v); }", python: "def dfs(v):\n    if base(v): return\n    choose(v); dfs(v + 1); undo(v)" },
  "backtracking-5": { cpp: "for (int mask = 0; mask < (1<<n); ++mask) {\n  for (int i = 0; i < n; ++i) if (mask & (1<<i)) cur.push_back(a[i]);\n  process(cur); cur.clear();\n}", python: "for mask in range(1 << n):\n    cur = [a[i] for i in range(n) if mask & (1 << i)]\n    process(cur)" },
  "backtracking-6": { cpp: "void permute(vector<int>&a,int k){\n  if(k==a.size()){emit(a);return;}\n  for(int i=k;i<a.size();++i){swap(a[k],a[i]);permute(a,k+1);swap(a[k],a[i]);}\n}", python: "from itertools import permutations\nfor p in permutations(a): emit(p)" },
  "backtracking-7": { cpp: "void combine(int start,int k,vector<int>&cur){\n  if(k==0){emit(cur);return;}\n  for(int i=start;i<=n;++i){cur.push_back(i);combine(i+1,k-1,cur);cur.pop_back();}\n}", python: "from itertools import combinations\nfor c in combinations(range(1, n + 1), k): emit(c)" },
  "backtracking-8": { cpp: "bool valid(int r,int c){ return !usedCol[c] && !usedD1[r-c+n] && !usedD2[r+c]; }", python: "def valid(r, c):\n    return not used_col[c] and not used_d1[r-c+n] and not used_d2[r+c]" },
  "backtracking-9": { cpp: "int dr[]={-1,1,0,0}, dc[]={0,0,-1,1};\nfor(int k=0;k<4;++k) if(dfs(r+dr[k],c+dc[k],idx+1)) return true;", python: "dr, dc = [-1,1,0,0], [0,0,-1,1]\nfor k in range(4):\n    if dfs(r+dr[k], c+dc[k], idx+1): return True" },
  "backtracking-10": { cpp: "void dfs(int v){ if (!promising(v)) return; /* prune */ choose(v); dfs(v+1); undo(v); }", python: "def dfs(v):\n    if not promising(v): return\n    choose(v); dfs(v + 1); undo(v)" },
  "backtracking-11": { cpp: "// MRV: pick the unfilled cell with the fewest candidate values first\nint pick = *min_element(candidates.begin(), candidates.end(), byCount);", python: "# MRV: pick the unfilled cell with the fewest candidate values first\npick = min(candidates, key=lambda c: len(options[c]))" },
  "backtracking-12": { cpp: "// split n items into two halves, enumerate each half, merge with two pointers", python: "# generate subsets of each half separately, then combine results" },
  "backtracking-13": { cpp: "// same params seen twice? -> memo[state] helps. Every call unique? -> pure backtracking\nunordered_map<int,long long> memo;", python: "# same params seen twice? -> a cache helps. Every call unique? -> pure backtracking\nfrom functools import lru_cache" },
  "backtracking-14": { cpp: "bool dfs(State s){ if (done(s)) return true;\n  for (auto c : choices(s)) { apply(c); if (dfs(next(s,c))) return true; undo(c); }\n  return false; }", python: "def dfs(s):\n    if done(s): return True\n    for c in choices(s):\n        apply(c)\n        if dfs(next_state(s, c)): return True\n        undo(c)\n    return False" },
  "backtracking-15": { cpp: "// mask ning barcha submasklari, kamayish tartibida\nfor (int sub = mask; ; sub = (sub - 1) & mask) {\n    process(sub, mask ^ sub);\n    if (sub == 0) break;      // tekshiruv OXIRIDA\n}", python: "# mask ning barcha submasklari, kamayish tartibida\nsub = mask\nwhile True:\n    process(sub, mask ^ sub)\n    if sub == 0:\n        break\n    sub = (sub - 1) & mask" },
  "backtracking-16": { cpp: "// rekursiyasiz DFS: stek o'zimizda\nvector<int> st{start};\nused[start] = true;\nwhile (!st.empty()) {\n    int v = st.back(); st.pop_back();\n    for (int to : g[v])\n        if (!used[to]) { used[to] = true; st.push_back(to); }\n}", python: "# rekursiyasiz DFS: stek o'zimizda\nst, used[start] = [start], True\nwhile st:\n    v = st.pop()\n    for to in g[v]:\n        if not used[to]:\n            used[to] = True\n            st.append(to)" },
  "backtracking-17": { cpp: "// chuqurlikni bosqichma-bosqich oshiramiz\nfor (int limit = 0; limit <= maxDepth; ++limit)\n    if (dls(start, limit)) return limit;   // birinchi topilgan = eng qisqa", python: "# chuqurlikni bosqichma-bosqich oshiramiz\nfor limit in range(max_depth + 1):\n    if dls(start, limit):\n        return limit   # birinchi topilgan = eng qisqa" },
  "backtracking-18": { cpp: "// n <= 10 -> n!   |   n <= 20 -> 2^n   |   n <= 18 (bo'linish) -> 3^n\n// n <= 40 (mustaqil yarim) -> meet in the middle\n// holat takrorlansa -> memoizatsiya (DP)", python: "# n <= 10 -> n!   |   n <= 20 -> 2**n   |   n <= 18 (bo'linish) -> 3**n\n# n <= 40 (mustaqil yarim) -> meet in the middle\n# holat takrorlansa -> memoizatsiya (DP)" },

  // ---- Math & Number Theory (15-stage deep track) ----
  "math-1": { cpp: "long long m = ((a % mod) + mod) % mod;  // safe modulo", python: "m = a % mod  # Python's % is already non-negative" },
  "math-2": { cpp: "long long gcd(long long a,long long b){ return b?gcd(b,a%b):a; }\nlong long lcm=a/gcd(a,b)*b;", python: "from math import gcd\nlcm = a // gcd(a, b) * b" },
  "math-3": { cpp: "long long extgcd(long long a,long long b,long long &x,long long &y){\n  if(!b){x=1;y=0;return a;}\n  long long x1,y1,g=extgcd(b,a%b,x1,y1);\n  x=y1; y=x1-(a/b)*y1; return g;\n}", python: "def extgcd(a, b):\n    if b == 0: return a, 1, 0\n    g, x1, y1 = extgcd(b, a % b)\n    return g, y1, x1 - (a // b) * y1" },
  "math-4": { cpp: "vector<bool> sieve(N+1,true);\nfor(int i=2;i*i<=N;++i) if(sieve[i]) for(int j=i*i;j<=N;j+=i) sieve[j]=false;", python: "sieve = [True] * (N + 1)\nfor i in range(2, int(N**0.5) + 1):\n    if sieve[i]:\n        for j in range(i*i, N + 1, i): sieve[j] = False" },
  "math-5": { cpp: "vector<int> spf(N+1);\nfor(int i=2;i<=N;++i) if(!spf[i]) for(int j=i;j<=N;j+=i) if(!spf[j]) spf[j]=i;\nlong long d=1; while(n>1){int p=spf[n],a=0; while(n%p==0){n/=p;a++;} d*=(a+1);}", python: "def divisor_count(n, spf):\n    d = 1\n    while n > 1:\n        p, a = spf[n], 0\n        while n % p == 0: n //= p; a += 1\n        d *= (a + 1)\n    return d" },
  "math-6": { cpp: "long long binpow(long long a,long long e,long long m){\n  long long r=1;a%=m;\n  while(e){if(e&1)r=r*a%m;a=a*a%m;e>>=1;}\n  return r;\n}", python: "r = pow(a, e, m)  # built-in fast modular exponentiation" },
  "math-7": { cpp: "long long C(int n,int r,vector<vector<long long>>&pascal){ return pascal[n][r]; }", python: "from math import comb\nc = comb(n, r)" },
  "math-8": { cpp: "long long inv = binpow(a, mod - 2, mod);  // Fermat's little theorem", python: "inv = pow(a, mod - 2, mod)" },
  "math-9": { cpp: "// combine x=r1(mod m1), x=r2(mod m2) via extended Euclid on m1,m2\nlong long g=extgcd(m1,m2,p,q); long long x=(r1*m2%M*q + r2*m1%M*p)%M;", python: "def crt(r1, m1, r2, m2):\n    g, p, q = extgcd(m1, m2)\n    m = m1 * m2\n    return (r1 * m2 * q + r2 * m1 * p) % m" },
  "math-10": { cpp: "long long phi(long long n){\n  long long r=n;\n  for(long long p=2;p*p<=n;++p) if(n%p==0){ while(n%p==0)n/=p; r-=r/p; }\n  if(n>1) r-=r/n;\n  return r;\n}", python: "def phi(n):\n    r, p = n, 2\n    while p * p <= n:\n        if n % p == 0:\n            while n % p == 0: n //= p\n            r -= r // p\n        p += 1\n    if n > 1: r -= r // n\n    return r" },
  "math-11": { cpp: "long long g=extgcd(a,b,x0,y0);\nif(c%g!=0) { /* no solution */ } else { x0*=c/g; y0*=c/g; }", python: "g, x0, y0 = extgcd(a, b)\nif c % g != 0:\n    pass  # no solution\nelse:\n    x0, y0 = x0 * (c // g), y0 * (c // g)" },
  "math-12": { cpp: "double E = 0;\nfor (int i = 0; i < n; ++i) E += prob(i) * value(i);  // linearity: sum indicators separately", python: "E = sum(prob(i) * value(i) for i in range(n))  # linearity: sum indicators separately" },
  "math-13": { cpp: "vector<long long> C(n+1);\nC[0]=1;\nfor(int i=1;i<=n;++i) for(int j=0;j<i;++j) C[i]+=C[j]*C[i-1-j];", python: "C = [0] * (n + 1)\nC[0] = 1\nfor i in range(1, n + 1):\n    for j in range(i):\n        C[i] += C[j] * C[i-1-j]" },
  "math-14": { cpp: "using Mat=vector<vector<long long>>;\nMat mul(Mat&a,Mat&b){ /* standard O(k^3) matrix multiply, mod m */ }\nMat matpow(Mat m,long long e){ /* binpow but with mul() instead of * */ }", python: "def mat_mult(a, b, mod):\n    # standard O(k^3) matrix multiply, mod m\n    return [[sum(a[i][k]*b[k][j] for k in range(len(b))) % mod for j in range(len(b[0]))] for i in range(len(a))]" },
  "math-15": { cpp: "// signal table: mod -> inverse | gcd/lcm -> Euclid | a^b mod m -> binpow\n// C(n,k) -> combinatorics | n-th term, huge n -> matrix power", python: "# signal table: mod -> inverse | gcd/lcm -> Euclid | a^b mod m -> binpow\n# C(n,k) -> combinatorics | n-th term, huge n -> matrix power" },

  // ---- Data Structures ----
  "data-structures-1": { cpp: "stack<int> st; st.push(x); st.pop();\nqueue<int> q; q.push(x); q.pop();", python: "st = []; st.append(x); st.pop()\nfrom collections import deque\nq = deque(); q.append(x); q.popleft()" },
  "data-structures-2": { cpp: "set<int> s; s.insert(x);\nmap<int,int> m; m[x]++;", python: "s = set(); s.add(x)\nfrom collections import defaultdict\nm = defaultdict(int); m[x] += 1" },
  "data-structures-3": { cpp: "priority_queue<int> pq; pq.push(x); pq.top(); pq.pop();", python: "import heapq\npq = []; heapq.heappush(pq, x); heapq.heappop(pq)" },
  "data-structures-4": { cpp: "int find(int x){ return dsu[x]==x?x:dsu[x]=find(dsu[x]); }\nvoid unite(int a,int b){ dsu[find(a)]=find(b); }", python: "def find(x):\n    if dsu[x] != x: dsu[x] = find(dsu[x])\n    return dsu[x]" },
  "data-structures-5": { cpp: "void update(int i,int v){for(;i<=n;i+=i&-i) bit[i]+=v;}\nlong long query(int i){long long s=0;for(;i>0;i-=i&-i)s+=bit[i];return s;}", python: "def update(i, v):\n    while i <= n: bit[i] += v; i += i & -i" },
  "data-structures-6": { cpp: "void update(int node,int l,int r,int i,int v){ /* point update */ }\nlong long query(int node,int l,int r,int ql,int qr){ /* range query */ }", python: "# segment tree: build once O(n), update O(log n), query O(log n)" },

  // ---- Binary Search ----
  "binary-search-1": { cpp: "int lo=0,hi=n-1;\nwhile(lo<=hi){int mid=(lo+hi)/2;if(a[mid]==x)return mid;a[mid]<x?lo=mid+1:hi=mid-1;}", python: "lo, hi = 0, n - 1\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    if a[mid] == x: break" },
  "binary-search-2": { cpp: "auto it = lower_bound(a.begin(), a.end(), x);\nauto it2 = upper_bound(a.begin(), a.end(), x);", python: "from bisect import bisect_left, bisect_right\ni = bisect_left(a, x)\nj = bisect_right(a, x)" },
  "binary-search-3": { cpp: "int lo=0,hi=n;\nwhile(lo<hi){int mid=(lo+hi)/2;pred(mid)?hi=mid:lo=mid+1;}", python: "lo, hi = 0, n\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if pred(mid): hi = mid\n    else: lo = mid + 1" },
  "binary-search-4": { cpp: "long long lo=0,hi=1e9;\nwhile(lo<hi){long long mid=lo+(hi-lo)/2;feasible(mid)?hi=mid:lo=mid+1;}", python: "lo, hi = 0, 10**9\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if feasible(mid): hi = mid\n    else: lo = mid + 1" },
  "binary-search-5": { cpp: "double lo=0,hi=1e6;\nfor(int i=0;i<100;++i){double mid=(lo+hi)/2;f(mid)<target?lo=mid:hi=mid;}", python: "lo, hi = 0.0, 1e6\nfor _ in range(100):\n    mid = (lo + hi) / 2\n    if f(mid) < target: lo = mid\n    else: hi = mid" },
  "binary-search-6": { cpp: "// predicate must be monotonic: false...false true...true\nbool pred(long long mid) { return check(mid); }", python: "def pred(mid):\n    return check(mid)  # must stay monotonic across the range" },

  // ---- Greedy Algorithms ----
  "greedy-1": { cpp: "sort(a.begin(), a.end(), greater<int>());  // largest-first greedy choice", python: "a.sort(reverse=True)" },
  "greedy-2": { cpp: "// exchange argument: swapping any two picks never improves the answer", python: "# prove greedy correctness with an exchange argument before coding" },
  "greedy-3": { cpp: "sort(act.begin(), act.end(), [](auto&a, auto&b){ return a.finish < b.finish; });\nint last = -1, cnt = 0;\nfor (auto& x : act) if (x.start >= last) { cnt++; last = x.finish; }", python: "act.sort(key=lambda x: x.finish)\nlast, cnt = -1, 0\nfor s, f in act:\n    if s >= last: cnt += 1; last = f" },
  "greedy-4": { cpp: "sort(iv.begin(), iv.end());\nvector<pair<int,int>> merged;\nfor (auto& x : iv) { if (!merged.empty() && merged.back().second >= x.first) merged.back().second = max(merged.back().second, x.second); else merged.push_back(x); }", python: "iv.sort()\nmerged = []\nfor s, e in iv:\n    if merged and merged[-1][1] >= s: merged[-1][1] = max(merged[-1][1], e)\n    else: merged.append([s, e])" },
  "greedy-5": { cpp: "priority_queue<int, vector<int>, greater<int>> pq;  // earliest-deadline-first", python: "import heapq\npq = []  # earliest-deadline-first with a min-heap" },
  "greedy-6": { cpp: "// when a simple greedy order fails, greedy + a heap/DSU often still works", python: "# combine the greedy order with a supporting data structure" },

  // ---- Graph Algorithms ----
  "graphs-1": { cpp: "vector<vector<int>> adj(n);\nadj[u].push_back(v); adj[v].push_back(u);", python: "adj = [[] for _ in range(n)]\nadj[u].append(v); adj[v].append(u)" },
  "graphs-2": { cpp: "queue<int> q; q.push(s); dist[s]=0;\nwhile(!q.empty()){int v=q.front();q.pop();for(int to:adj[v])if(dist[to]<0){dist[to]=dist[v]+1;q.push(to);}}", python: "from collections import deque\nq = deque([s]); dist[s] = 0\nwhile q:\n    v = q.popleft()\n    for to in adj[v]:\n        if dist[to] < 0: dist[to] = dist[v] + 1; q.append(to)" },
  "graphs-3": { cpp: "void dfs(int v){ visited[v]=true; for(int to:adj[v]) if(!visited[to]) dfs(to); }", python: "def dfs(v):\n    visited[v] = True\n    for to in adj[v]:\n        if not visited[to]: dfs(to)" },
  "graphs-4": { cpp: "void dfs(int v){visited[v]=true;for(int to:adj[v])if(!visited[to])dfs(to);order.push_back(v);}\nreverse(order.begin(),order.end());", python: "order = []\ndef dfs(v):\n    visited[v] = True\n    for to in adj[v]:\n        if not visited[to]: dfs(to)\n    order.append(v)" },
  "graphs-5": { cpp: "priority_queue<pair<long long,int>,vector<pair<long long,int>>,greater<>> pq;\npq.push({0,s}); dist[s]=0;", python: "import heapq\npq = [(0, s)]; dist[s] = 0\nwhile pq:\n    d, v = heapq.heappop(pq)" },
  "graphs-6": { cpp: "sort(edges.begin(), edges.end());\nfor (auto& [w,u,v] : edges) if (find(u)!=find(v)) { unite(u,v); mst += w; }", python: "edges.sort()\nfor w, u, v in edges:\n    if find(u) != find(v): unite(u, v); mst += w" },

  // ---- String Algorithms ----
  "strings-1": { cpp: "string s = \"algo\"; s.substr(1,2); reverse(s.begin(), s.end());", python: "s = \"algo\"\ns[1:3]\ns[::-1]" },
  "strings-2": { cpp: "long long h=0, p=31, mod=1e9+7, pw=1;\nfor(char c:s){h=(h+(c-'a'+1)*pw)%mod;pw=pw*p%mod;}", python: "h, p, mod, pw = 0, 31, 10**9 + 7, 1\nfor c in s:\n    h = (h + (ord(c) - 96) * pw) % mod\n    pw = pw * p % mod" },
  "strings-3": { cpp: "vector<int> pi(s.size());\nfor(int i=1;i<(int)s.size();++i){int j=pi[i-1];while(j&&s[i]!=s[j])j=pi[j-1];if(s[i]==s[j])++j;pi[i]=j;}", python: "pi = [0] * len(s)\nfor i in range(1, len(s)):\n    j = pi[i - 1]\n    while j and s[i] != s[j]: j = pi[j - 1]\n    if s[i] == s[j]: j += 1\n    pi[i] = j" },
  "strings-4": { cpp: "// KMP: search = prefix_function(pattern + '#' + text)\nvector<int> pi = prefix_function(pattern + \"#\" + text);", python: "combo = pattern + \"#\" + text\npi = prefix_function(combo)" },
  "strings-5": { cpp: "vector<int> z(s.size());\nint l=0,r=0;\nfor(int i=1;i<(int)s.size();++i){ if(i<r) z[i]=min(r-i,z[i-l]); while(i+z[i]<(int)s.size()&&s[z[i]]==s[i+z[i]])++z[i]; if(i+z[i]>r){l=i;r=i+z[i];} }", python: "z = [0] * len(s)\nl = r = 0\nfor i in range(1, len(s)):\n    if i < r: z[i] = min(r - i, z[i - l])\n    while i + z[i] < len(s) and s[z[i]] == s[i + z[i]]: z[i] += 1\n    if i + z[i] > r: l, r = i, i + z[i]" },
  "strings-6": { cpp: "struct Trie{ Trie* next[26]{}; bool end=false; };\nvoid insert(Trie* t,string&s){ for(char c:s){ if(!t->next[c-'a']) t->next[c-'a']=new Trie(); t=t->next[c-'a']; } t->end=true; }", python: "trie = {}\nnode = trie\nfor c in s:\n    node = node.setdefault(c, {})\nnode['#'] = True" },

  // ---- Computational Geometry ----
  "geometry-1": { cpp: "struct Point{ long long x,y; };\nPoint operator-(Point a, Point b){ return {a.x-b.x, a.y-b.y}; }", python: "def sub(a, b):\n    return (a[0] - b[0], a[1] - b[1])" },
  "geometry-2": { cpp: "long long dot(Point a, Point b){ return a.x*b.x + a.y*b.y; }", python: "def dot(a, b):\n    return a[0]*b[0] + a[1]*b[1]" },
  "geometry-3": { cpp: "long long cross(Point a, Point b){ return a.x*b.y - a.y*b.x; }", python: "def cross(a, b):\n    return a[0]*b[1] - a[1]*b[0]" },
  "geometry-4": { cpp: "bool intersect(Point a,Point b,Point c,Point d){\n  return cross(b-a,c-a)*cross(b-a,d-a) < 0 && cross(d-c,a-d)*cross(d-c,b-d) < 0;\n}", python: "def intersect(a, b, c, d):\n    return cross(sub(b,a), sub(c,a)) * cross(sub(b,a), sub(d,a)) < 0" },
  "geometry-5": { cpp: "long long area2 = 0;\nfor (int i = 0; i < n; ++i) area2 += cross(p[i], p[(i+1)%n]);\ndouble area = abs(area2) / 2.0;", python: "area2 = sum(cross(p[i], p[(i+1)%n]) for i in range(n))\narea = abs(area2) / 2" },
  "geometry-6": { cpp: "sort(p.begin(), p.end());\n// Andrew's monotone chain: build lower + upper hulls with cross product", python: "p.sort()\n# monotone chain: keep popping while cross(...) <= 0" },

  // ---- Two Pointers & Sliding Window ----
  "two-pointers-1": { cpp: "int l=0,r=n-1;\nwhile(l<r){ if(a[l]+a[r]==target) return {l,r}; a[l]+a[r]<target?++l:--r; }", python: "l, r = 0, n - 1\nwhile l < r:\n    s = a[l] + a[r]\n    if s == target: break\n    if s < target: l += 1\n    else: r -= 1" },
  "two-pointers-2": { cpp: "int l=0;\nfor(int r=0;r<n;++r){ /* extend with a[r] */ while(bad()) ++l; }", python: "l = 0\nfor r in range(n):\n    while bad(): l += 1" },
  "two-pointers-3": { cpp: "int l=0; long long sum=0;\nfor(int r=0;r<n;++r){ sum+=a[r]; while(sum>k){sum-=a[l++];} }", python: "l, s = 0, 0\nfor r in range(n):\n    s += a[r]\n    while s > k: s -= a[l]; l += 1" },
  "two-pointers-4": { cpp: "int l=0,best=0;\nfor(int r=0;r<n;++r){ while(!valid(l,r)) ++l; best=max(best,r-l+1); }", python: "l, best = 0, 0\nfor r in range(n):\n    while not valid(l, r): l += 1\n    best = max(best, r - l + 1)" },
  "two-pointers-5": { cpp: "vector<long long> pre(n+1);\nfor(int i=0;i<n;++i) pre[i+1]=pre[i]+a[i];\n// window sum = pre[r+1]-pre[l]", python: "pre = [0] * (n + 1)\nfor i in range(n): pre[i+1] = pre[i] + a[i]" },
  "two-pointers-6": { cpp: "// combine sliding window with a multiset/deque for min/max in range", python: "from collections import deque\ndq = deque()  # monotonic deque for sliding window min/max" },

  // ---- Dynamic Programming (15-stage deep track) ----
  "dynamic-programming-1": { cpp: "// state:      what fully describes a subproblem?\n// transition: how do states connect?\n// base case:  the smallest state's ready answer\nlong long dp[MAXN]; // dp[state] = answer", python: "# state: what fully describes a subproblem?\n# transition: how do states connect?\n# base case: the smallest state's ready answer\ndp = {}  # dp[state] = answer" },
  "dynamic-programming-2": { cpp: "long long f(int n){ return n<2?n:f(n-1)+f(n-2); } // f(3) gets called hundreds of times for large n", python: "def f(n):\n    return n if n < 2 else f(n-1) + f(n-2)  # f(3) recurs hundreds of times for large n" },
  "dynamic-programming-3": { cpp: "// exchange argument: if A-B-C-D is shortest, A-B-C must be shortest too\nif (dist[u]+w < dist[v]) dist[v] = dist[u]+w;", python: "# exchange argument: if A-B-C-D is shortest, A-B-C must be shortest too\nif dist[u] + w < dist[v]: dist[v] = dist[u] + w" },
  "dynamic-programming-4": { cpp: "unordered_map<int,long long> memo;\nlong long f(int n){ if(n<=1) return n; if(memo.count(n)) return memo[n]; return memo[n]=f(n-1)+f(n-2); }", python: "from functools import lru_cache\n@lru_cache(None)\ndef f(n):\n    return n if n <= 1 else f(n-1) + f(n-2)" },
  "dynamic-programming-5": { cpp: "vector<long long> dp(n+1);\ndp[0]=0; dp[1]=1;\nfor(int i=2;i<=n;++i) dp[i]=dp[i-1]+dp[i-2];", python: "dp = [0] * (n + 1)\ndp[1] = 1\nfor i in range(2, n + 1): dp[i] = dp[i-1] + dp[i-2]" },
  "dynamic-programming-6": { cpp: "// wrong: dp[i] alone can't say \"was i robbed?\"\n// right: dp[i][0/1] = best up to i, i not-robbed/robbed\nlong long dp[MAXN][2];", python: "# wrong: dp[i] alone can't say \"was i robbed?\"\n# right: dp[i][state] = best up to i, given state\ndp = [[0, 0] for _ in range(n)]" },
  "dynamic-programming-7": { cpp: "// list every decision, then combine:\ndp[amount] = INF;\nfor (int c : coins) if (amount>=c) dp[amount]=min(dp[amount], dp[amount-c]+1);", python: "dp[amount] = float('inf')\nfor c in coins:\n    if amount >= c: dp[amount] = min(dp[amount], dp[amount - c] + 1)" },
  "dynamic-programming-8": { cpp: "vector<long long> dp(n);\ndp[0]=a[0]; dp[1]=max(a[0],a[1]);\nfor(int i=2;i<n;++i) dp[i]=max(dp[i-1],dp[i-2]+a[i]);", python: "dp = [0] * n\ndp[0], dp[1] = a[0], max(a[0], a[1])\nfor i in range(2, n): dp[i] = max(dp[i-1], dp[i-2] + a[i])" },
  "dynamic-programming-9": { cpp: "vector<vector<long long>> dp(n, vector<long long>(m));\ndp[0][0]=grid[0][0];\nfor(int i=0;i<n;++i)for(int j=0;j<m;++j) if(i||j) dp[i][j]=grid[i][j]+max(i?dp[i-1][j]:0,j?dp[i][j-1]:0);", python: "dp = [[0]*m for _ in range(n)]\ndp[0][0] = grid[0][0]\nfor i in range(n):\n    for j in range(m):\n        if i or j: dp[i][j] = grid[i][j] + max(dp[i-1][j] if i else 0, dp[i][j-1] if j else 0)" },
  "dynamic-programming-10": { cpp: "vector<long long> dp(cap+1);\nfor(int i=0;i<n;++i) for(int c=cap;c>=w[i];--c) dp[c]=max(dp[c],dp[c-w[i]]+v[i]);", python: "dp = [0] * (cap + 1)\nfor i in range(n):\n    for c in range(cap, w[i] - 1, -1):\n        dp[c] = max(dp[c], dp[c - w[i]] + v[i])" },
  "dynamic-programming-11": { cpp: "vector<int> dp(n, 1);\nfor(int i=0;i<n;++i) for(int j=0;j<i;++j) if(a[j]<a[i]) dp[i]=max(dp[i],dp[j]+1);", python: "dp = [1] * n\nfor i in range(n):\n    for j in range(i):\n        if a[j] < a[i]: dp[i] = max(dp[i], dp[j] + 1)" },
  "dynamic-programming-12": { cpp: "for(int len=2;len<=n;++len) for(int l=0;l+len-1<n;++l){ int r=l+len-1;\n  for(int k=l;k<r;++k) dp[l][r]=min(dp[l][r],dp[l][k]+dp[k+1][r]+cost(l,k,r));\n}", python: "for length in range(2, n + 1):\n    for l in range(n - length + 1):\n        r = l + length - 1\n        for k in range(l, r):\n            dp[l][r] = min(dp[l][r], dp[l][k] + dp[k+1][r] + cost(l, k, r))" },
  "dynamic-programming-13": { cpp: "long long dfs(int v,int p){ long long res=0; for(int to:tree[v]) if(to!=p) res+=dfs(to,v); return dp[v]=res+val[v]; }", python: "def dfs(v, p):\n    res = 0\n    for to in tree[v]:\n        if to != p: res += dfs(to, v)\n    dp[v] = res + val[v]\n    return dp[v]" },
  "dynamic-programming-14": { cpp: "vector<long long> dp(1<<n, -1);\ndp[0]=0;\nfor(int mask=0;mask<(1<<n);++mask) if(dp[mask]>=0) for(int i=0;i<n;++i) if(!(mask>>i&1)) dp[mask|1<<i]=max(dp[mask|1<<i],dp[mask]+cost(mask,i));", python: "dp = [-1] * (1 << n)\ndp[0] = 0\nfor mask in range(1 << n):\n    if dp[mask] < 0: continue\n    for i in range(n):\n        if not (mask >> i & 1): dp[mask | 1 << i] = max(dp[mask | 1 << i], dp[mask] + cost(mask, i))" },
  "dynamic-programming-15": { cpp: "deque<int> dq; // monotonic deque keeps candidates for min(dp[j]) in a sliding window\nwhile(!dq.empty() && dp[dq.back()]>=dp[i]) dq.pop_back();\ndq.push_back(i);", python: "from collections import deque\ndq = deque()  # monotonic deque keeps candidates for min(dp[j]) in a sliding window\nwhile dq and dp[dq[-1]] >= dp[i]: dq.pop()\ndq.append(i)" },

  // ---- Tree Algorithms ----
  "trees-1": { cpp: "vector<vector<int>> tree(n);\ntree[u].push_back(v); tree[v].push_back(u);", python: "tree = [[] for _ in range(n)]\ntree[u].append(v); tree[v].append(u)" },
  "trees-2": { cpp: "long long dfs(int v,int p){ long long sz=1; for(int to:tree[v]) if(to!=p) sz+=dfs(to,v); return sub[v]=sz; }", python: "def dfs(v, p):\n    sz = 1\n    for to in tree[v]:\n        if to != p: sz += dfs(to, v)\n    sub[v] = sz\n    return sz" },
  "trees-3": { cpp: "up[v][0]=parent[v];\nfor(int k=1;k<LOG;++k) up[v][k]=up[up[v][k-1]][k-1];", python: "up[v][0] = parent[v]\nfor k in range(1, LOG):\n    up[v][k] = up[up[v][k-1]][k-1]" },
  "trees-4": { cpp: "if(depth[u]<depth[v]) swap(u,v);\nfor(int k=LOG-1;k>=0;--k) if(depth[u]-(1<<k)>=depth[v]) u=up[u][k];", python: "if depth[u] < depth[v]: u, v = v, u\nfor k in range(LOG-1, -1, -1):\n    if depth[u] - (1 << k) >= depth[v]: u = up[u][k]" },
  "trees-5": { cpp: "pair<int,int> dfs(int v,int p){ int best=0,node=v; for(int to:tree[v]) if(to!=p){auto[d,n]=dfs(to,v); if(d+1>best){best=d+1;node=n;}} return {best,node}; }", python: "def dfs(v, p):\n    best, node = 0, v\n    for to in tree[v]:\n        if to != p:\n            d, n2 = dfs(to, v)\n            if d + 1 > best: best, node = d + 1, n2\n    return best, node" },
  "trees-6": { cpp: "void dfs(int v,int p){ dp[v]=1; for(int to:tree[v]) if(to!=p){dfs(to,v); dp[v]+=dp[to];} }", python: "def dfs(v, p):\n    dp[v] = 1\n    for to in tree[v]:\n        if to != p: dfs(to, v); dp[v] += dp[to]" },

  // ---- Advanced CP & ICPC ----
  "advanced-cp-1": { cpp: "struct Node{ int l,r; long long sum; };\nint update(int node,int l,int r,int i,int v){ /* create O(log n) new nodes */ }", python: "# persistent segment tree: each update clones O(log n) nodes, roots[] tracks versions" },
  "advanced-cp-2": { cpp: "struct Treap{ int priority; long long val; Treap *l,*r; };\nvoid split(Treap* t,int key,Treap*&l,Treap*&r){ /* by implicit index */ }", python: "# treap: random priority keeps the tree balanced in expectation O(log n)" },
  "advanced-cp-3": { cpp: "int block=sqrt(n);\nsort(queries.begin(),queries.end(),[&](auto&a,auto&b){ return make_pair(a.l/block,a.r) < make_pair(b.l/block,b.r); });", python: "block = int(n**0.5)\nqueries.sort(key=lambda q: (q.l // block, q.r))" },
  "advanced-cp-4": { cpp: "int heavy[N]; // dfs sets heavy child by subtree size, then chain-decompose the tree", python: "# HLD: heavy edges chain into O(log n) segments for path queries" },
  "advanced-cp-5": { cpp: "// FFT multiplies two degree-n polynomials in O(n log n) via point-value form", python: "import numpy as np\nresult = np.convolve(a, b)  # naive O(n^2); real FFT needed for large n" },
  "advanced-cp-6": { cpp: "// Sprague-Grundy: grundy(state) = mex{ grundy(next) : next reachable from state }", python: "def grundy(state):\n    reachable = {grundy(nxt) for nxt in moves(state)}\n    return mex(reachable)" },
};
