/* Deep lessons — Binary search (binary-search).
 *
 * One idea, worn as a dozen different problems. What binary search really
 * needs is not a sorted array but a MONOTONE PREDICATE: something that is
 * false for a while and then true forever. Once a learner sees that, "search
 * the answer", "search on reals", "parallel binary search" all stop being
 * separate techniques and become the same one.
 *
 * So this track spends its first three stages making the predicate visible,
 * and the rest showing where it hides.
 *
 * Original text and diagrams. Nothing copied from any source.
 */

import type { DeepLesson } from "../deep-lesson";

export const binarySearchLessons: Record<string, DeepLesson> = {

/* ── 1. Tartiblangan qidiruvning asosiy sxemasi ──────────────────────── */
"binary-search-1": { sections: [
 { titleUz: "Har savolda yarmini tashlash", titleEn: "Throwing away half with every question", blocks: [
  { t: "p",
    uz: "Tartiblangan massivda x sonini qidiryapmiz. O‘rtadagi elementga qaraymiz: agar u x dan katta bo‘lsa, x undan O‘NGDA bo‘lishi MUMKIN EMAS — chunki massiv tartiblangan va o‘ngdagilar yanada katta. Demak bitta solishtirish bilan yarmini tashlab yuboramiz.",
    en: "We are looking for x in a sorted array. Look at the middle element: if it is greater than x, then x CANNOT lie to its right — the array is sorted and everything there is larger still. So one comparison discards half the array." },
  { t: "sim", titleUz: "7 ni qidirish: [1, 3, 4, 7, 9, 11, 15]", titleEn: "Searching for 7 in [1, 3, 4, 7, 9, 11, 15]", frames: [
    { spec: { kind: "zones", label: "butun massiv nomzod", values: [1, 3, 4, 7, 9, 11, 15],
        zones: [{ from: 0, to: 6, text: "qidiruv oralig‘i", tone: "cool" }],
        ptr: [{ at: 3, text: "mid" }], note: "o‘rtadagi element — 7" },
      uz: "Butun massiv nomzod. O‘rtasiga qaraymiz: 3-indeksda 7 turibdi.",
      en: "The whole array is a candidate. We look at the middle: index 3 holds 7." },
    { spec: { kind: "zones", label: "topildi — lekin davom etaylik", values: [1, 3, 4, 7, 9, 11, 15],
        zones: [{ from: 3, to: 3, text: "topildi", tone: "ok" }],
        note: "1 ta solishtirish yetdi" },
      uz: "Omadimiz keldi — birinchi urinishdayoq topdik. Lekin mexanizmni ko‘rish uchun boshqa sonni qidirib ko‘raylik.",
      en: "We were lucky and found it on the first try. To see the mechanism, let us search for a different value." },
    { spec: { kind: "zones", label: "11 ni qidiramiz: 7 < 11", values: [1, 3, 4, 7, 9, 11, 15],
        zones: [{ from: 0, to: 3, text: "tashlandi", tone: "dim" }, { from: 4, to: 6, text: "qoldi", tone: "cool" }],
        ptr: [{ at: 3, text: "mid" }], note: "chap yarim butunlay kerak emas" },
      uz: "Endi 11 ni qidiramiz. O‘rtada 7, va 7 < 11 — demak 11 o‘ng tomonda. Chap yarim (4 ta element) BUTUNLAY tashlandi.",
      en: "Now we search for 11. The middle is 7, and 7 < 11, so 11 lies to the right. The left half — four elements — is discarded entirely." },
    { spec: { kind: "zones", label: "qolgan 3 tadan o‘rtasi", values: [1, 3, 4, 7, 9, 11, 15],
        zones: [{ from: 0, to: 3, text: "tashlandi", tone: "dim" }, { from: 5, to: 5, text: "topildi", tone: "ok" }, { from: 4, to: 4, text: "", tone: "dim" }, { from: 6, to: 6, text: "", tone: "dim" }],
        ptr: [{ at: 5, text: "mid" }], note: "2 ta solishtirish — javob" },
      uz: "Qolgan [9, 11, 15] ning o‘rtasi — 11. Topildi, jami ikkita solishtirish. Chiziqli qidiruv oltita solishtirish qilardi.",
      en: "The middle of what remains, [9, 11, 15], is 11. Found, in two comparisons. A linear scan would have made six." },
  ]},
  { t: "note", kind: "key",
    uz: "Har bir solishtirish qidiruv oralig‘ini IKKIGA bo‘ladi. n elementni 1 ga tushirish uchun log₂(n) marta bo‘lish kerak — n = 10⁹ uchun atigi 30 ta solishtirish. «Asoslar» bo‘limidagi logarifm mavzusi shu yerda ishga tushadi.",
    en: "Every comparison HALVES the range. Reducing n elements to one takes log₂(n) halvings — thirty comparisons for n = 10⁹. The logarithm stage from the Foundations track pays off here." },
 ]},
 { titleUz: "Nega bu kodni to‘g‘ri yozish qiyin", titleEn: "Why this code is hard to get right", blocks: [
  { t: "p",
    uz: "Binary search g‘oyasi bir daqiqada tushuniladi, lekin uni xatosiz yozish mashhur darajada qiyin. Uchta savol chalkashtiradi: chegara YOPIQMI yoki OCHIQ (r = n yoki n−1), sikl sharti l < r yoki l <= r, va mid topilganda l = mid mi yoki mid + 1 mi.",
    en: "The idea takes a minute to grasp, yet writing it without a bug is famously difficult. Three questions cause the trouble: is the right bound INCLUSIVE or EXCLUSIVE (r = n or n−1), is the loop condition l < r or l <= r, and after computing mid does l become mid or mid + 1." },
  { t: "codewalk", code: "// klassik: topilganda indeksni qaytaradi, aks holda -1\nint binarySearch(const vector<int>& a, int x) {\n    int l = 0, r = (int)a.size() - 1;\n    while (l <= r) {\n        int mid = l + (r - l) / 2;\n        if (a[mid] == x) return mid;\n        if (a[mid] < x) l = mid + 1;\n        else            r = mid - 1;\n    }\n    return -1;\n}",
    notes: [
      { from: 3, uz: "r = size − 1: chegara YOPIQ, ya’ni a[r] ham nomzod. Shuning uchun sikl sharti l <= r bo‘ladi — l == r holatida ham bitta nomzod qoladi va uni tekshirish kerak.",
        en: "r = size − 1 makes the bound INCLUSIVE, so a[r] is a candidate too. That is why the loop runs while l <= r: when l == r one candidate still remains and must be checked." },
      { from: 5, uz: "mid = l + (r − l) / 2, va (l + r) / 2 EMAS. Ikkalasi bir xil natija beradi, lekin ikkinchisi l va r katta bo‘lganda int dan toshib ketadi. Bu «Asoslar» bo‘limidagi klassik overflow misoli.",
        en: "mid = l + (r − l) / 2, not (l + r) / 2. They give the same value, but the second overflows an int when l and r are large — the classic overflow example from the Foundations track." },
      { from: 7, to: 8, uz: "Ikkala shoxda ham mid CHETLAB O‘TILADI: l = mid + 1 yoki r = mid − 1. Agar l = mid deb yozsangiz va oraliqda ikkita element qolsa, mid har safar l ga teng bo‘lib, sikl abadiy aylanadi.",
        en: "Both branches step PAST mid: l = mid + 1 or r = mid − 1. Write l = mid instead and, with two elements left, mid keeps equalling l and the loop spins forever." },
    ]},
  { t: "note", kind: "warn",
    uz: "Cheksiz sikl — binary search dagi eng ko‘p uchraydigan xato, va u testda emas, judge da paydo bo‘ladi. Sabab har doim bitta: oraliq QISQARMAY qolgan. Kod yozgandan keyin o‘zingizga savol bering: «har bir shoxda oraliq albatta kichrayadimi?»",
    en: "An infinite loop is the commonest binary-search bug, and it shows up on the judge rather than in your own test. The cause is always the same: the range failed to SHRINK. After writing the code ask yourself: does every branch definitely make it smaller?" },
  { t: "note", kind: "tip",
    uz: "Amalda bu kodni yozishning hojati yo‘q: C++ da lower_bound bor. Lekin uni TUSHUNISH shart, chunki keyingi bosqichlarda massiv bo‘lmagan joyda ham qidirasiz — u yerda tayyor funksiya yo‘q.",
    en: "In practice you rarely write this: C++ has lower_bound. But you must UNDERSTAND it, because later stages search where there is no array at all — and no ready-made function." },
  { t: "exercise",
    qUz: "l = 0, r = 1 bo‘lganda mid nechaga teng, va nima uchun l = mid yozish xavfli?",
    qEn: "With l = 0 and r = 1, what is mid, and why is writing l = mid dangerous?",
    aUz: "mid = 0 + (1−0)/2 = 0, ya’ni mid == l. Agar shu holatda l = mid yozsak, l o‘zgarmaydi va oraliq qisqarmaydi — cheksiz sikl. Shuning uchun yo l = mid + 1 yozish kerak, yo mid ni yuqoriga yaxlitlash (mid = l + (r − l + 1) / 2).",
    aEn: "mid = 0 + (1−0)/2 = 0, so mid equals l. Writing l = mid then leaves l unchanged and the range never shrinks — an infinite loop. Either write l = mid + 1, or round mid upward with mid = l + (r − l + 1) / 2." },
 ]},
]},

/* ── 2. Lower va upper bound ─────────────────────────────────────────── */
"binary-search-2": { sections: [
 { titleUz: "Takrorlar bo‘lganda «topish» yetarli emas", titleEn: "With duplicates, “find it” is not enough", blocks: [
  { t: "p",
    uz: "Massivda bir xil qiymat bir necha marta uchrasa, «x ni top» degan savol noaniq bo‘lib qoladi: qaysi birini? Shuning uchun ikkita aniqroq savol ishlatiladi. lower_bound — x dan KICHIK BO‘LMAGAN birinchi element. upper_bound — x dan QAT’IY KATTA birinchi element.",
    en: "When a value repeats, “find x” becomes ambiguous: which one? So two sharper questions are used instead. lower_bound is the first element NOT LESS than x; upper_bound is the first element STRICTLY GREATER than x." },
  { t: "sim", titleUz: "[1, 3, 3, 3, 7] massivida 3 ni qidirish", titleEn: "Searching for 3 in [1, 3, 3, 3, 7]", frames: [
    { spec: { kind: "array", label: "uchta 3 bor", values: [1, 3, 3, 3, 7], hi: [1, 2, 3],
        note: "qaysi birini «topish» kerak?" },
      uz: "Massivda uchta 3 bor. «3 ni top» degan savolga uchta to‘g‘ri javob bor — shuning uchun savolni aniqlashtirish kerak.",
      en: "There are three 3s. “Find 3” has three correct answers, so the question needs sharpening." },
    { spec: { kind: "array", label: "lower_bound(3)", values: [1, 3, 3, 3, 7],
        ptr: [{ at: 1, text: "lower" }], hi: [1], note: "3 dan kichik bo‘lmagan BIRINCHI" },
      uz: "lower_bound(3) birinchi 3 ni ko‘rsatadi — ya’ni «3 dan kichik bo‘lmagan birinchi element». Bu takrorlar guruhining BOSHI.",
      en: "lower_bound(3) points at the first 3 — the first element not less than 3. That is the START of the run of duplicates." },
    { spec: { kind: "array", label: "upper_bound(3)", values: [1, 3, 3, 3, 7],
        ptr: [{ at: 4, text: "upper" }], hi: [4], note: "3 dan qat’iy KATTA birinchi" },
      uz: "upper_bound(3) esa 7 ni ko‘rsatadi — «3 dan qat’iy katta birinchi element». Bu guruhning OXIRIDAN keyingi pozitsiya.",
      en: "upper_bound(3) points at the 7 — the first element strictly greater than 3. That is the position just PAST the end of the run." },
    { spec: { kind: "zones", label: "ikkalasi orasida — barcha 3 lar", values: [1, 3, 3, 3, 7],
        zones: [{ from: 1, to: 3, text: "aynan 3 lar", tone: "ok" }],
        note: "soni = upper − lower = 4 − 1 = 3" },
      uz: "Ikkala natijaning ORASIDA aynan 3 ga teng elementlar yotadi. Demak ularning soni — upper_bound − lower_bound. Bu «massivda x nechta marta uchraydi?» degan savolning yechimi.",
      en: "Between the two results lie exactly the elements equal to 3, so their count is upper_bound − lower_bound. That answers “how many times does x occur?”." },
  ]},
  { t: "code", cpp: "auto lo = lower_bound(a.begin(), a.end(), x);\nauto hi = upper_bound(a.begin(), a.end(), x);\n\nint firstIndex = lo - a.begin();       // x ning birinchi o‘rni\nint count      = hi - lo;              // x nechta marta uchraydi\nbool present   = (lo != a.end() && *lo == x);\n\n// x dan kichik eng katta element:\nif (lo != a.begin()) int below = *(lo - 1);",
    captionUz: "lo != a.end() tekshiruvi MAJBURIY: x hammasidan katta bo‘lsa, lower_bound end() qaytaradi va *lo dasturni qulatadi.",
    captionEn: "The lo != a.end() check is mandatory: if x exceeds everything, lower_bound returns end() and dereferencing it crashes the program." },
  { t: "table", headUz: ["Savol", "Ifoda"], headEn: ["Question", "Expression"],
    rows: [
      ["x bormi", "lo != end && *lo == x"],
      ["x nechta", "upper − lower"],
      ["x dan kichik nechta", "lower − begin"],
      ["x dan katta nechta", "end − upper"],
      ["x dan kichik eng kattasi", "*(lower − 1), agar lower != begin"],
      ["x dan katta eng kichigi", "*upper, agar upper != end"],
    ],
    captionUz: "Oltita savol — ikkita funksiya. Shuning uchun lower_bound va upper_bound ni yodlab olish arziydi.",
    captionEn: "Six questions from two functions — which is why lower_bound and upper_bound are worth knowing cold." },
 ]},
 { titleUz: "set va map da ham xuddi shunday", titleEn: "The same on a set and a map", blocks: [
  { t: "note", kind: "warn",
    uz: "set uchun ALBATTA a’zo funksiyani ishlating: s.lower_bound(x), std::lower_bound(s.begin(), s.end(), x) emas. Ikkinchisi ishlaydi, lekin O(n) vaqt oladi — chunki set iteratorlari tasodifiy murojaatni qo‘llab-quvvatlamaydi va funksiya ular bo‘ylab birma-bir yuradi. Bu jim sekinlik, kompilyator ogohlantirmaydi.",
    en: "For a set always use the member function s.lower_bound(x), never std::lower_bound(s.begin(), s.end(), x). The second compiles and works but takes O(n): a set's iterators are not random-access, so the algorithm walks them one by one. It is a silent slowdown with no warning." },
  { t: "p",
    uz: "Bu farq amalda juda qimmatga tushadi: n = 10⁵ ta so‘rov bilan to‘g‘ri variant 1.7·10⁶ amal, noto‘g‘risi esa 10¹⁰ — TLE. Kod deyarli bir xil ko‘rinadi, natija esa butunlay boshqa.",
    en: "In practice the difference is expensive: with 10⁵ queries the correct version does 1.7·10⁶ operations and the wrong one 10¹⁰ — a timeout. The two lines look almost identical and behave completely differently." },
  { t: "code", cpp: "set<int> s = {1, 4, 7, 9};\n\nauto it = s.lower_bound(5);            // O(log n) — TO‘G‘RI\n// auto it = lower_bound(s.begin(), s.end(), 5);   // O(n) — SEKIN\n\nif (it != s.end())   cout << *it;      // 7 — 5 dan katta eng kichigi\nif (it != s.begin()) cout << *prev(it); // 4 — 5 dan kichik eng kattasi" },
  { t: "exercise",
    qUz: "Tartiblangan massivda «x ga eng yaqin element» ni qanday topasiz?",
    qEn: "How do you find the element nearest to x in a sorted array?",
    aUz: "lower_bound(x) ni oling — bu x dan kichik bo‘lmagan birinchi element. Javob yo shu element, yo undan oldingisi. Ikkalasining x bilan farqini solishtirib, kichigini tanlaysiz. Ikkala chegarani (begin va end) tekshirishni unutmang — eng ko‘p uchraydigan xato aynan shu yerda.",
    aEn: "Take lower_bound(x), the first element not less than x. The answer is either that element or the one before it: compare their distances to x and take the smaller. Remember to check both ends (begin and end) — that is where the usual bug lives." },
 ]},
]},

/* ── 3. «Birinchi rost qiymat» universal sxemasi ─────────────────────── */
"binary-search-3": { sections: [
 { titleUz: "Massiv emas, PREDIKAT", titleEn: "Not an array — a PREDICATE", blocks: [
  { t: "p",
    uz: "Mana bu bo‘limning eng muhim g‘oyasi. Binary search ga TARTIBLANGAN MASSIV kerak emas. Unga kerak bo‘lgan narsa — MONOTON PREDIKAT: shunday shartki, u bir joyga qadar yolg‘on, undan keyin esa har doim rost. Massiv shu shartning bitta ko‘rinishi, xolos.",
    en: "Here is the most important idea in this track. Binary search does not need a SORTED ARRAY. What it needs is a MONOTONE PREDICATE: a condition that is false up to some point and true from there on. A sorted array is merely one instance of that." },
  { t: "sim", titleUz: "FFFTTT chizig‘i va chegara", titleEn: "The FFFTTT line and its boundary", frames: [
    { spec: { kind: "array", label: "predikat qiymatlari", values: ["F", "F", "F", "T", "T", "T"],
        note: "yolg‘ondan rostga BIR MARTA o‘tadi" },
      uz: "Predikat qiymatlari shunday ko‘rinadi: bir necha F, keyin faqat T. Muhimi — o‘tish AYNAN BIR MARTA sodir bo‘ladi.",
      en: "The predicate values look like this: some Fs, then only Ts. The point is that the switch happens EXACTLY ONCE." },
    { spec: { kind: "array", label: "o‘rtasiga qaraymiz", values: ["F", "F", "F", "T", "T", "T"],
        ptr: [{ at: 2, text: "mid" }], hi: [2], note: "mid da F → chegara O‘NGDA" },
      uz: "O‘rtaga qaraymiz: u yerda F. Predikat monoton bo‘lgani uchun undan CHAPDAGI hammasi ham F — demak chegara o‘ng tomonda, chap yarim tashlanadi.",
      en: "Look at the middle: it is F. Because the predicate is monotone, everything to its LEFT is F too — so the boundary is on the right and the left half is discarded." },
    { spec: { kind: "array", label: "yana o‘rtaga", values: ["F", "F", "F", "T", "T", "T"],
        ptr: [{ at: 4, text: "mid" }], hi: [4], note: "mid da T → chegara CHAPDA (yoki shu yerda)" },
      uz: "Endi T ga tushdik. Demak chegara shu yerda yoki undan chapda — o‘ng qismni tashlaymiz, lekin mid ning O‘ZINI saqlab qolamiz, chunki u javob bo‘lishi mumkin.",
      en: "Now we hit a T, so the boundary is here or to the left. We discard the right part but KEEP mid itself, since it may be the answer." },
    { spec: { kind: "array", label: "birinchi T topildi", values: ["F", "F", "F", "T", "T", "T"],
        ptr: [{ at: 3, text: "javob" }], hi: [3], note: "chegara — 3-indeks" },
      uz: "Oraliq bitta elementga tushdi: 3-indeks. Bu «birinchi T» — izlanayotgan chegara. Butun binary search shu bitta savolga keladi.",
      en: "The range narrows to a single index, 3. That is the “first T” — the boundary we were after. All of binary search reduces to this one question." },
  ]},
  { t: "note", kind: "key",
    uz: "Universal sxema: «birinchi rost qiymatni top». Boshqa har qanday savolni shunga keltirish mumkin. lower_bound(x) = «a[i] ≥ x birinchi marta qachon rost bo‘ladi». Javob bo‘yicha qidiruv = «bu javob yetarlimi birinchi marta qachon rost bo‘ladi». Bitta kod, o‘nlab masala.",
    en: "The universal scheme is “find the first true”. Every other question reduces to it: lower_bound(x) asks when a[i] ≥ x first becomes true; searching the answer asks when “is this answer good enough” first becomes true. One piece of code, dozens of problems." },
  { t: "codewalk", code: "// [lo, hi) oralig‘ida pred(i) birinchi marta rost bo‘ladigan i ni topadi\nint firstTrue(int lo, int hi, auto pred) {\n    while (lo < hi) {\n        int mid = lo + (hi - lo) / 2;\n        if (pred(mid)) hi = mid;      // mid ham nomzod — saqlaymiz\n        else           lo = mid + 1;  // mid aniq emas — chetlab o‘tamiz\n    }\n    return lo;                        // lo == hi — javob\n}",
    notes: [
      { from: 2, uz: "Yarim ochiq oraliq [lo, hi): hi javob bo‘lishi MUMKIN emas, u «chegaradan tashqari» qiymat. Agar hech qayerda rost bo‘lmasa, funksiya hi ni qaytaradi — bu «topilmadi» degani.",
        en: "A half-open range [lo, hi): hi itself is never an answer, it is the “past the end” value. If the predicate is nowhere true the function returns hi, which means “not found”." },
      { from: 5, uz: "pred(mid) rost bo‘lsa, hi = mid — mid ni SAQLAYMIZ, chunki u eng chapdagi rost bo‘lishi mumkin. hi = mid − 1 yozish javobni yo‘qotadi.",
        en: "When pred(mid) is true we set hi = mid, KEEPING mid, because it may be the leftmost true. Writing hi = mid − 1 would lose the answer." },
      { from: 6, uz: "Yolg‘on bo‘lsa, mid aniq javob emas — uni chetlab o‘tamiz. Aynan shu asimmetriya (bir tomonda mid, ikkinchisida mid + 1) siklning qisqarishini kafolatlaydi.",
        en: "When it is false, mid is definitely not the answer and we step past it. That asymmetry — mid on one side, mid + 1 on the other — is what guarantees the range shrinks." },
      { from: 8, uz: "Sikl tugaganda lo == hi va bu yagona qolgan nomzod. Alohida «topildimi» tekshiruvi kerak emas — chaqiruvchi javobni o‘zi tekshiradi.",
        en: "When the loop ends, lo == hi and that is the single remaining candidate. No separate “was it found” check is needed — the caller verifies the answer." },
    ]},
 ]},
 { titleUz: "Shu sxemani yodlab oling", titleEn: "Learn this one scheme", blocks: [
  { t: "p",
    uz: "Har xil binary search variantlarini yodlashning o‘rniga, shu bitta funksiyani eslab qoling va har safar faqat PREDIKATNI yozing. Bu yondashuv chegara xatolarini deyarli butunlay yo‘q qiladi.",
    en: "Instead of memorising several binary-search variants, remember this one function and write only the PREDICATE each time. That habit removes almost every off-by-one bug." },
  { t: "table", headUz: ["Kerakli savol", "Predikat"], headEn: ["The question", "The predicate"],
    rows: [
      ["lower_bound(x)", "a[i] >= x"],
      ["upper_bound(x)", "a[i] > x"],
      ["oxirgi «yolg‘on»", "firstTrue(...) − 1"],
      ["eng kichik yetarli javob", "check(mid) == true"],
      ["eng katta mos javob", "!check(mid) bo‘yicha firstTrue, keyin −1"],
    ],
    captionUz: "«Eng katta mos javob» kerak bo‘lsa, predikatni TESKARILANG va natijadan bitta ayiring — alohida kod yozish shart emas.",
    captionEn: "When you need the largest valid answer, INVERT the predicate and subtract one from the result — no separate code required." },
  { t: "note", kind: "warn",
    uz: "Predikat MONOTON bo‘lishi shart. Agar u T, F, T ko‘rinishida bo‘lsa, binary search ishlamaydi va u tasodifiy javob qaytaradi — xato xabari bo‘lmaydi. Kod yozishdan oldin o‘zingizga savol bering: «bu shart rost bo‘lgandan keyin har doim rost bo‘lib qoladimi?»",
    en: "The predicate must be MONOTONE. If it reads T, F, T, binary search silently returns an arbitrary answer with no error at all. Before writing the code, ask: once this condition becomes true, does it stay true?" },
  { t: "exercise",
    qUz: "[2, 4, 6, 8] massivida «a[i] > 5» predikati qanday ko‘rinadi, va firstTrue nima qaytaradi?",
    qEn: "For [2, 4, 6, 8], what does the predicate “a[i] > 5” look like, and what does firstTrue return?",
    aUz: "Predikat: F, F, T, T. firstTrue 2 ni qaytaradi — bu 6 ning indeksi, ya’ni upper_bound(5). Va e’tibor bering: predikat monoton, chunki massiv tartiblangan. Tartiblanmagan massivda bu shart F, T, F bo‘lishi mumkin va usul buziladi.",
    aEn: "The predicate is F, F, T, T and firstTrue returns 2, the index of 6 — that is upper_bound(5). Note that it is monotone because the array is sorted; on an unsorted array the same condition could read F, T, F and the method would break." },
 ]},
]},
/* ── 4. Javob bo‘yicha qidiruv ───────────────────────────────────────── */
"binary-search-4": { sections: [
 { titleUz: "Javobni topish o‘rniga, uni TAXMIN qilish", titleEn: "Guessing the answer instead of computing it", blocks: [
  { t: "p",
    uz: "Ko‘p masalalarda javobni to‘g‘ridan-to‘g‘ri hisoblash qiyin, LEKIN berilgan javobni tekshirish oson. Masalan: «eng kam qancha vaqtda ishni tugatish mumkin?» — bunga javob berish qiyin; «10 soatda ulgurish mumkinmi?» — bunga javob berish oson. Mana shu farq butun usulni beradi.",
    en: "In many problems computing the answer directly is hard, while CHECKING a given answer is easy. “What is the least time in which the work can be finished?” is hard; “can it be finished in ten hours?” is easy. That gap is the whole technique." },
  { t: "p",
    uz: "Agar «x yetarlimi?» degan savol MONOTON bo‘lsa — ya’ni x yetarli bo‘lsa, x + 1 ham albatta yetarli — u holda javoblar ustida binary search qilish mumkin. Massiv umuman kerak emas: biz javoblar oralig‘ini qidiryapmiz.",
    en: "If “is x enough?” is MONOTONE — that is, if x suffices then x + 1 certainly does — then you can binary search over the answers. No array is involved: we are searching the range of possible answers." },
  { t: "sim", titleUz: "«Eng kichik yetarli javob» ni qidirish", titleEn: "Searching for the smallest sufficient answer", frames: [
    { spec: { kind: "numberline", label: "javoblar oralig‘i", from: 1, to: 100, span: [1, 100],
        marks: [{ at: 1, text: "lo", tone: "lo" }, { at: 100, text: "hi", tone: "hi" }],
        note: "javob shu oraliqda — hali qayerdaligi noma’lum" },
      uz: "Javob 1 dan 100 gacha bo‘lgan oraliqda. Massiv yo‘q — bu shunchaki mumkin bo‘lgan javoblar to‘plami.",
      en: "The answer lies somewhere between 1 and 100. There is no array — this is simply the set of possible answers." },
    { spec: { kind: "numberline", label: "50 ni tekshiramiz", from: 1, to: 100, span: [1, 100],
        marks: [{ at: 50, text: "mid = 50", tone: "mid" }],
        note: "check(50) = rost → 50 yetarli" },
      uz: "O‘rtani olamiz: 50. check(50) ni chaqiramiz va u ROST qaytaradi — 50 yetarli. Demak javob 50 dan katta bo‘lishi mumkin emas.",
      en: "Take the middle, 50, and call check(50). It returns TRUE, so 50 suffices — which means the answer cannot exceed 50." },
    { spec: { kind: "numberline", label: "yuqori yarim tashlandi", from: 1, to: 100, span: [1, 50],
        marks: [{ at: 25, text: "mid = 25", tone: "mid" }],
        note: "check(25) = yolg‘on → 25 kam" },
      uz: "Oraliq [1, 50] ga qisqardi. Endi 25 ni tekshiramiz: yolg‘on, ya’ni 25 YETARLI EMAS. Demak javob 25 dan katta.",
      en: "The range shrinks to [1, 50]. Now check 25: false, so 25 is NOT enough and the answer is larger than 25." },
    { spec: { kind: "numberline", label: "oraliq qisqarib boradi", from: 1, to: 100, span: [26, 50],
        marks: [{ at: 38, text: "mid = 38", tone: "mid" }],
        note: "har tekshiruv oraliqni yarimlatadi" },
      uz: "Har bir tekshiruv oraliqni ikkiga bo‘ladi. 100 ta variantni ko‘rish o‘rniga atigi log₂(100) ≈ 7 marta check chaqiriladi.",
      en: "Each check halves the range. Instead of trying a hundred candidates, check is called about log₂(100) ≈ 7 times." },
  ]},
  { t: "note", kind: "key",
    uz: "Narx: O(log(oraliq) × check narxi). Agar check O(n) bo‘lsa, umumiy narx O(n log C) — bu deyarli har doim sig‘adi. Aynan shuning uchun bu usul musobaqada juda ko‘p uchraydi.",
    en: "The cost is O(log(range) × cost of check). With an O(n) check that is O(n log C), which almost always fits — and that is why the technique appears so often in contests." },
 ]},
 { titleUz: "Klassik misol va uni tanib olish", titleEn: "A classic example, and how to recognise it", blocks: [
  { t: "p",
    uz: "Masala: n ta bo‘lak yog‘och bor, ularning uzunliklari berilgan. Ulardan k ta TENG uzunlikdagi bo‘lak kesib olish kerak. Eng uzun qanday bo‘lak olish mumkin?",
    en: "The problem: there are n logs of given lengths, and you must cut k pieces of EQUAL length from them. What is the longest piece you can get?" },
  { t: "p",
    uz: "To‘g‘ridan-to‘g‘ri hisoblash qiyin. Lekin «uzunligi L bo‘lgan k ta bo‘lak olish mumkinmi?» degan savolga javob berish oson: har bir yog‘ochdan floor(aᵢ / L) ta bo‘lak chiqadi, ularni qo‘shib k bilan solishtiramiz. Va bu shart monoton: L kichrayganda bo‘laklar soni faqat ORTADI.",
    en: "Computing it directly is awkward. But “can I get k pieces of length L?” is easy: each log yields floor(aᵢ / L) pieces, and we compare their sum with k. The condition is monotone: as L shrinks, the number of pieces only GROWS." },
  { t: "codewalk", code: "bool enough(long long L, const vector<int>& a, int k) {\n    if (L == 0) return true;\n    long long cnt = 0;\n    for (int x : a) {\n        cnt += x / L;\n        if (cnt >= k) return true;      // erta chiqish — toshib ketmaydi\n    }\n    return cnt >= k;\n}\n\nlong long solve(const vector<int>& a, int k) {\n    long long lo = 1, hi = *max_element(a.begin(), a.end()) + 1;\n    while (lo < hi) {                    // [lo, hi): hi — birinchi YETMAYDIGAN\n        long long mid = lo + (hi - lo) / 2;\n        if (enough(mid, a, k)) lo = mid + 1;\n        else                   hi = mid;\n    }\n    return lo - 1;                       // oxirgi yetadigan\n}",
    notes: [
      { from: 6, uz: "Erta chiqish ikki ish qiladi: tezlashtiradi va cnt ning toshib ketishidan saqlaydi. n = 10⁵ va aᵢ = 10⁹ bo‘lsa, cnt 10¹⁴ ga yetishi mumkin — long long shart.",
        en: "The early exit does two things: it speeds the check up and it keeps cnt from overflowing. With n = 10⁵ and aᵢ = 10⁹ the count can reach 10¹⁴, so long long is mandatory." },
      { from: 13, uz: "hi ni maksimum + 1 qilib olamiz — bu ANIQ yetmaydigan qiymat. Shunday «albatta yolg‘on» chegarani tanlash sxemani soddalashtiradi.",
        en: "hi is set to the maximum plus one, a value that is certainly too large. Choosing a bound that is definitely false keeps the scheme simple." },
      { from: 16, to: 17, uz: "Bu yerda predikat «yetarli» bo‘lgani uchun shoxlar TESKARI: rost bo‘lsa oldinga suramiz. Chunki biz «birinchi rost» emas, «oxirgi rost» ni qidiryapmiz.",
        en: "Here the predicate is “sufficient”, so the branches are REVERSED: on true we move forward. We are looking for the LAST true rather than the first." },
      { from: 19, uz: "lo − 1 — oxirgi yetadigan qiymat. Bu bitta ayirish «eng katta mos javob» ni «birinchi rost» sxemasidan chiqarishning standart usuli.",
        en: "lo − 1 is the last sufficient value. That single subtraction is the standard way of deriving “the largest valid answer” from the first-true scheme." },
    ]},
  { t: "table", headUz: ["Masaladagi ibora", "Nimani bildiradi"], headEn: ["Phrase in the problem", "What it signals"],
    rows: [
      ["«eng kam vaqtni toping»", "javob bo‘yicha qidiruv, birinchi rost"],
      ["«maksimumni minimallashtiring»", "javob bo‘yicha qidiruv"],
      ["«minimumni maksimallashtiring»", "javob bo‘yicha qidiruv"],
      ["«eng katta L ni toping», shart bilan", "oxirgi rost"],
      ["«k ta bo‘lakka bo‘lish»", "check: nechta bo‘lak chiqadi"],
    ],
    captionUz: "«Minimaks» va «maksimin» iboralari deyarli har doim javob bo‘yicha qidiruvni bildiradi.",
    captionEn: "The words “minimax” and “maximin” almost always mean a binary search on the answer." },
  { t: "exercise",
    qUz: "«n ta kitobni k ta o‘quvchiga ketma-ket bo‘lib bering, eng ko‘p o‘qiydigan o‘quvchining yuki minimal bo‘lsin». Predikat nima?",
    qEn: "“Split n books among k readers in order, minimising the load of the busiest reader.” What is the predicate?",
    aUz: "check(L) = «har bir o‘quvchiga ko‘pi bilan L sahifa berib, k ta o‘quvchi bilan ulgurish mumkinmi?». Tekshirish ochko‘zlik bilan: kitoblarni ketma-ket yig‘ib, L dan oshganda yangi o‘quvchiga o‘tamiz va ularni sanaymiz. Monotonlik ravshan: L kattalashsa, kerakli o‘quvchilar soni faqat KAMAYADI. Javob — birinchi rost L.",
    aEn: "check(L) asks “can k readers finish if none takes more than L pages?”. Verify it greedily: accumulate books in order and start a new reader when the total would exceed L, counting readers. Monotonicity is clear — a larger L needs no more readers. The answer is the first L that is true." },
 ]},
]},

/* ── 5. Haqiqiy sonlar ustida qidiruv ────────────────────────────────── */
"binary-search-5": { sections: [
 { titleUz: "Butun sonlar tugaydi, haqiqiy sonlar tugamaydi", titleEn: "Integers run out, reals do not", blocks: [
  { t: "p",
    uz: "Butun sonlarda oraliq oxir-oqibat bitta qiymatga qisqaradi va sikl o‘z-o‘zidan to‘xtaydi. Haqiqiy sonlarda esa [1.0, 2.0] oralig‘ida cheksiz ko‘p son bor — l va r hech qachon TENGLASHMAYDI. Shuning uchun to‘xtash shartini o‘zimiz belgilaymiz.",
    en: "Over the integers a range eventually shrinks to one value and the loop stops by itself. Over the reals the interval [1.0, 2.0] holds infinitely many numbers and l and r never become EQUAL, so we must choose a stopping rule ourselves." },
  { t: "sim", titleUz: "√2 ni qidirish", titleEn: "Searching for √2", frames: [
    { spec: { kind: "numberline", label: "boshlang‘ich oraliq", from: 1, to: 2, span: [1, 2], ticks: 4,
        marks: [{ at: 1, text: "lo", tone: "lo" }, { at: 2, text: "hi", tone: "hi" }],
        note: "√2 shu oraliqda: 1² < 2 < 2²" },
      uz: "√2 ni qidiramiz. U [1, 2] oralig‘ida ekani aniq, chunki 1² = 1 < 2 va 2² = 4 > 2.",
      en: "We are looking for √2. It clearly lies in [1, 2], since 1² = 1 < 2 and 2² = 4 > 2." },
    { spec: { kind: "numberline", label: "1.5 ni tekshiramiz", from: 1, to: 2, span: [1, 1.5], ticks: 4,
        marks: [{ at: 1.5, text: "mid", tone: "mid" }],
        note: "1.5² = 2.25 > 2 → o‘ng yarim tashlanadi" },
      uz: "O‘rtasi 1.5, uning kvadrati 2.25 — bu 2 dan katta. Demak √2 chapda. Predikat: «mid² ≥ 2» — monoton.",
      en: "The middle is 1.5 and its square is 2.25, greater than 2, so √2 is to the left. The predicate “mid² ≥ 2” is monotone." },
    { spec: { kind: "numberline", label: "40 iteratsiyadan keyin", from: 1, to: 2, span: [1.414, 1.4143], ticks: 4,
        marks: [{ at: 1.4142, text: "1.41421", tone: "hit" }],
        note: "oraliq 2⁻⁴⁰ ga qisqardi" },
      uz: "Har iteratsiya oraliqni ikkiga bo‘ladi. 40 iteratsiyadan keyin oraliq uzunligi 1/2⁴⁰ ≈ 10⁻¹² — bu har qanday amaliy aniqlikdan ko‘p.",
      en: "Each iteration halves the interval. After forty of them its length is 1/2⁴⁰ ≈ 10⁻¹², finer than any practical requirement." },
  ]},
  { t: "note", kind: "key",
    uz: "Amaliy qoida: while (r − l > eps) o‘rniga QAT’IY SONDAGI iteratsiya yozing — masalan 100 marta. Sabab: eps juda kichik bo‘lsa (yoki sonlar katta bo‘lsa), aniqlik chegarasiga urilib sikl abadiy aylanishi mumkin. 100 iteratsiya esa har doim tugaydi va 2⁻¹⁰⁰ aniqlik beradi — bu double ning imkoniyatidan ham yuqori.",
    en: "The practical rule: instead of while (r − l > eps), run a FIXED number of iterations — a hundred, say. The reason is that with a very small eps (or large values) you can hit the limits of precision and loop forever. A hundred iterations always terminates and gives 2⁻¹⁰⁰ accuracy, beyond what a double can even represent." },
  { t: "code", cpp: "double lo = 1, hi = 2;\nfor (int iter = 0; iter < 100; ++iter) {\n    double mid = (lo + hi) / 2;\n    if (mid * mid >= 2) hi = mid;\n    else                lo = mid;\n}\ncout << fixed << setprecision(9) << lo;   // 1.414213562",
    captionUz: "Bu yerda mid + 1 yo‘q: haqiqiy sonlarda «keyingi qiymat» degan tushuncha yo‘q, shuning uchun ikkala shox ham mid ni oladi.",
    captionEn: "There is no mid + 1 here: over the reals there is no “next value”, so both branches simply take mid." },
 ]},
 { titleUz: "Aniqlik tuzoqlari", titleEn: "Precision traps", blocks: [
  { t: "table", headUz: ["Xato", "Oqibati", "To‘g‘risi"], headEn: ["Mistake", "Consequence", "Instead"],
    rows: [
      ["while (r − l > 1e-9)", "katta sonlarda cheksiz sikl", "100 ta iteratsiya"],
      ["mid² ni int da hisoblash", "overflow yoki noto‘g‘ri", "double yoki long double"],
      ["javobni eps bilan solishtirish", "chegarada xato", "fabs(a − b) < eps"],
      ["setprecision unutish", "6 xona chiqadi", "fixed << setprecision(9)"],
    ]},
  { t: "note", kind: "warn",
    uz: "Masalada «10⁻⁶ aniqlikda» deyilsa, bu MUTLAQ yoki NISBIY xato bo‘lishi mumkin. Katta javoblar uchun (10⁹ atrofida) mutlaq aniqlik 10⁻⁶ ga erishish double bilan imkonsiz — double atigi 15–16 muhim raqam beradi. Bunday holatda shart odatda nisbiy xatoni nazarda tutadi.",
    en: "When a statement says “to within 10⁻⁶”, it may mean an ABSOLUTE or a RELATIVE error. For large answers (around 10⁹) an absolute 10⁻⁶ is unreachable with a double, which carries only 15–16 significant digits — in such problems the requirement is normally relative." },
  { t: "note", kind: "tip",
    uz: "Iloji bo‘lsa, haqiqiy sonlardan UMUMAN qoching. Ko‘p masalalarda javob kasr ko‘rinishida bo‘lsa ham, uni butun sonlarda qidirish mumkin: masalan javobni 1000 ga ko‘paytirib, butun sonlarda binary search qilish. Bu aniqlik muammosini butunlay yo‘q qiladi.",
    en: "Where possible, avoid reals ENTIRELY. Even when the answer is fractional, you can often search in integers — multiply the answer by a thousand, say, and binary search over integers. That removes the precision problem altogether." },
  { t: "exercise",
    qUz: "Javob 10⁹ atrofida va 10⁻⁶ aniqlik kerak. Necha iteratsiya yetadi?",
    qEn: "The answer is around 10⁹ and 10⁻⁶ accuracy is required. How many iterations suffice?",
    aUz: "Oraliq uzunligi 10⁹, kerakli aniqlik 10⁻⁶, demak 10¹⁵ marta qisqartirish kerak: log₂(10¹⁵) ≈ 50. Ya’ni 50–60 iteratsiya yetarli, 100 esa zaxira bilan. Lekin diqqat: 10⁹ atrofidagi double ning o‘zi 10⁻⁷ dan aniqroq bo‘la olmaydi, shuning uchun shartni qayta o‘qing.",
    aEn: "The range is 10⁹ wide and the target accuracy 10⁻⁶, so it must shrink by 10¹⁵: log₂(10¹⁵) ≈ 50. Fifty to sixty iterations suffice and a hundred is comfortable. But note that a double near 10⁹ cannot resolve better than about 10⁻⁷ anyway, so re-read the statement." },
 ]},
]},

/* ── 6. Ternary search ───────────────────────────────────────────────── */
"binary-search-6": { sections: [
 { titleUz: "Monoton emas, lekin bitta cho‘qqisi bor", titleEn: "Not monotone, but with a single peak", blocks: [
  { t: "p",
    uz: "Binary search monoton predikat talab qiladi. Lekin ba’zi funksiyalar monoton emas — ular avval o‘sadi, keyin kamayadi (yoki teskarisi). Bunday funksiya UNIMODAL deyiladi, va uning ekstremumini topish uchun ternary search ishlatiladi.",
    en: "Binary search needs a monotone predicate, but some functions are not monotone: they rise and then fall (or the reverse). Such a function is UNIMODAL, and ternary search finds its extremum." },
  { t: "sim", titleUz: "Maksimumni ikkita nuqta bilan qidirish", titleEn: "Finding the maximum with two probes", frames: [
    { spec: { kind: "plot", label: "unimodal funksiya", values: [1, 4, 7, 9, 10, 8, 5, 2],
        note: "avval o‘sadi, keyin kamayadi" },
      uz: "Funksiya avval o‘sadi, keyin kamayadi. Bitta cho‘qqisi bor va biz uni qidiryapmiz. Binary search bu yerda ishlamaydi — predikat monoton emas.",
      en: "The function rises and then falls. It has a single peak, and that is what we want. Binary search cannot help here: the predicate is not monotone." },
    { spec: { kind: "plot", label: "ikkita nuqta olamiz", values: [1, 4, 7, 9, 10, 8, 5, 2],
        marks: [{ at: 2, text: "m1" }, { at: 5, text: "m2" }],
        note: "f(m1) = 7 < f(m2) = 8" },
      uz: "Oraliqni uchga bo‘lib, ikkita nuqta olamiz: m1 va m2. Ularning qiymatlarini solishtiramiz: f(m1) = 7, f(m2) = 8.",
      en: "Split the range into thirds and take two probes, m1 and m2, then compare their values: f(m1) = 7 and f(m2) = 8." },
    { spec: { kind: "plot", label: "chap bo‘lak tashlanadi", values: [1, 4, 7, 9, 10, 8, 5, 2],
        marks: [{ at: 2, text: "m1" }, { at: 5, text: "m2" }], drop: [0, 2],
        note: "f(m1) < f(m2) → maksimum m1 dan o‘ngda" },
      uz: "f(m1) < f(m2) bo‘lgani uchun maksimum m1 dan CHAPDA bo‘lishi mumkin emas. Nima uchun? Agar maksimum chapda bo‘lganida, funksiya m1 dan keyin faqat kamayardi va f(m2) < f(m1) bo‘lardi. Demak chap uchdan birini tashlaymiz.",
      en: "Since f(m1) < f(m2), the maximum cannot lie LEFT of m1. Why? If it did, the function would only fall after m1 and we would have f(m2) < f(m1). So the left third is discarded." },
    { spec: { kind: "plot", label: "oraliq qisqardi", values: [1, 4, 7, 9, 10, 8, 5, 2],
        marks: [{ at: 4, text: "cho‘qqi" }], drop: [0, 2],
        note: "har qadamda oraliq 2/3 ga qisqaradi" },
      uz: "Qolgan oraliqda jarayonni takrorlaymiz. Har qadamda oraliq 1/3 ga qisqaradi, ya’ni 2/3 qoladi. Narx O(log₁.₅ n) — binary search dan biroz sekinroq, lekin baribir logarifmik.",
      en: "Repeat on what remains. Each step removes a third, leaving two thirds. The cost is O(log₁.₅ n) — slightly slower than binary search but still logarithmic." },
  ]},
  { t: "code", cpp: "// haqiqiy sonlar uchun\ndouble lo = 0, hi = 1e9;\nfor (int iter = 0; iter < 200; ++iter) {\n    double m1 = lo + (hi - lo) / 3;\n    double m2 = hi - (hi - lo) / 3;\n    if (f(m1) < f(m2)) lo = m1;      // maksimum qidiryapmiz\n    else               hi = m2;\n}\ndouble best = f((lo + hi) / 2);",
    captionUz: "Minimum kerak bo‘lsa, solishtirishni teskari qiling: f(m1) > f(m2) bo‘lganda lo = m1.",
    captionEn: "For a minimum, invert the comparison: set lo = m1 when f(m1) > f(m2)." },
  { t: "note", kind: "warn",
    uz: "Funksiya QAT’IY unimodal bo‘lishi shart. Agar cho‘qqida bir necha teng qiymat bo‘lsa (tekislik), f(m1) == f(m2) holati paydo bo‘ladi va qaysi tomonni tashlashni bilib bo‘lmaydi. Butun sonlarda bu ayniqsa xavfli — shuning uchun diskret holatda boshqa usul ishlatiladi.",
    en: "The function must be STRICTLY unimodal. If the peak is a plateau of equal values, the case f(m1) == f(m2) arises and neither side can be safely discarded. Over the integers this is especially dangerous, which is why the discrete case uses a different method." },
 ]},
 { titleUz: "Ternary search qayerda uchraydi", titleEn: "Where ternary search shows up", blocks: [
  { t: "table", headUz: ["Masala", "Unimodal nima"], headEn: ["Problem", "What is unimodal"],
    rows: [
      ["nuqtaga eng yaqin joy", "masofa funksiyasi"],
      ["parabola ekstremumi", "kvadrat funksiya"],
      ["optimal tezlik / narx", "xarajat funksiyasi"],
      ["ikki harakatlanuvchi orasidagi min masofa", "vaqt bo‘yicha masofa"],
    ],
    captionUz: "Umumiy naqsh: «biror parametrni tanlash kerak, juda kichik ham, juda katta ham yomon».",
    captionEn: "The common pattern: “choose a parameter where both too small and too large are bad”." },
  { t: "note", kind: "tip",
    uz: "Musobaqada ternary search dan ko‘ra ko‘proq BINARY search ishlatiladi — chunki ko‘p unimodal masalalarni «hosila musbatmi?» degan MONOTON predikat orqali binary search ga keltirish mumkin. Agar f(i+1) − f(i) monoton bo‘lsa, shu ayirmaning ishorasi bo‘yicha oddiy binary search yozing: u tezroq va ishonchliroq.",
    en: "Contests use binary search far more than ternary, because many unimodal problems reduce to the MONOTONE predicate “is the slope still positive?”. If f(i+1) − f(i) is monotone, binary search on the sign of that difference — it is faster and more reliable." },
  { t: "exercise",
    qUz: "Butun sonlar ustida ternary search yozyapsiz va oraliqda 2 ta element qoldi. Nima qilasiz?",
    qEn: "You are running a ternary search over integers and two elements remain. What do you do?",
    aUz: "Uchga bo‘lish endi ishlamaydi — m1 va m2 ustma-ust tushib qolishi mumkin. Standart yechim: oraliq kichrayganda (masalan 3 tadan kam element qolganda) siklni to‘xtatib, qolgan elementlarni QO‘LDA ko‘rib chiqing. Bu bitta qator kod va barcha chegaraviy holatlarni yopadi.",
    aEn: "Splitting into thirds stops working — m1 and m2 can coincide. The standard fix is to stop the loop once the range is small (fewer than three elements, say) and check the remainder BY HAND. That is one line of code and it closes every edge case." },
 ]},
]},

/* ── 7. Diskret unimodal massivda cho‘qqi qidirish ───────────────────── */
"binary-search-7": { sections: [
 { titleUz: "Cho‘qqini binary search bilan topish", titleEn: "Finding a peak with binary search", blocks: [
  { t: "p",
    uz: "Massiv avval o‘sadi, keyin kamayadi. Cho‘qqini topish kerak. Ternary search ishlaydi, lekin butun sonlarda u chegaraviy holatlar bilan chalkash. Ancha toza yechim bor: cho‘qqi savolini MONOTON predikatga aylantirish.",
    en: "An array rises and then falls, and we want the peak. Ternary search works but is fiddly at the boundaries over integers. There is a cleaner route: turn the peak question into a MONOTONE predicate." },
  { t: "p",
    uz: "Predikat: «a[i] > a[i+1]». Cho‘qqidan CHAPDA massiv o‘sadi, demak bu shart yolg‘on. Cho‘qqidan boshlab massiv kamayadi, demak shart rost. Ya’ni predikat FFFTTT ko‘rinishida — va bu aynan «birinchi rost» sxemasi.",
    en: "The predicate: “a[i] > a[i+1]”. Left of the peak the array is rising, so it is false; from the peak onward the array falls, so it is true. The predicate reads FFFTTT — precisely the first-true scheme." },
  { t: "sim", titleUz: "[1, 4, 8, 6, 2] da cho‘qqi", titleEn: "The peak of [1, 4, 8, 6, 2]", frames: [
    { spec: { kind: "bars", label: "massiv", values: [1, 4, 8, 6, 2],
        note: "cho‘qqi — 8, lekin uni qanday topamiz?" },
      uz: "Massiv: 1, 4, 8, 6, 2. Cho‘qqi ko‘rinib turibdi, lekin uni O(log n) da topish kerak.",
      en: "The array is 1, 4, 8, 6, 2. The peak is obvious to the eye, but we need it in O(log n)." },
    { spec: { kind: "array", label: "predikat: a[i] > a[i+1]", values: ["F", "F", "T", "T", "—"],
        hi: [2, 3], note: "cho‘qqi — birinchi T ning indeksi" },
      uz: "Predikatni hisoblaymiz: 1>4 yolg‘on, 4>8 yolg‘on, 8>6 rost, 6>2 rost. FFTT — monoton! Birinchi T ning indeksi 2, va a[2] = 8 — aynan cho‘qqi.",
      en: "Evaluate it: 1>4 false, 4>8 false, 8>6 true, 6>2 true. FFTT — monotone. The first true is at index 2, and a[2] = 8 is exactly the peak." },
    { spec: { kind: "bars", label: "o‘rtaga qaraymiz", values: [1, 4, 8, 6, 2], state: { 2: "cmp", 3: "cmp" },
        note: "a[2] > a[3] → cho‘qqi shu yerda yoki chapda" },
      uz: "Binary search: o‘rtada a[2] = 8 va a[3] = 6. 8 > 6, demak biz allaqachon kamayish qismidamiz — cho‘qqi shu yerda yoki chapda.",
      en: "Binary search: at the middle a[2] = 8 and a[3] = 6. Since 8 > 6 we are already on the falling side, so the peak is here or to the left." },
    { spec: { kind: "bars", label: "topildi", values: [1, 4, 8, 6, 2], state: { 2: "key" },
        note: "log n qadam, ternary searchsiz" },
      uz: "Oraliq qisqarib, 2-indeksga keladi. Cho‘qqi topildi — atigi log n qadamda va hech qanday chegaraviy chalkashliksiz.",
      en: "The range narrows to index 2 and the peak is found — in log n steps with none of the boundary confusion." },
  ]},
  { t: "code", cpp: "int findPeak(const vector<int>& a) {\n    int lo = 0, hi = (int)a.size() - 1;\n    while (lo < hi) {\n        int mid = lo + (hi - lo) / 2;\n        if (a[mid] > a[mid + 1]) hi = mid;   // kamayish boshlandi\n        else                     lo = mid + 1;\n    }\n    return lo;\n}",
    captionUz: "mid + 1 ga murojaat xavfsiz, chunki lo < hi bo‘lganda mid < hi, ya’ni mid + 1 massiv ichida.",
    captionEn: "Reading mid + 1 is safe: while lo < hi we have mid < hi, so mid + 1 is still inside the array." },
  { t: "note", kind: "key",
    uz: "Naqsh umumiy: unimodal masalani QO‘SHNILAR FARQI orqali monoton predikatga aylantiring. f(i+1) − f(i) ning ishorasi cho‘qqiga qadar musbat, keyin manfiy — bu har doim monoton. Shu bilan ternary search o‘rniga oddiy binary search yozasiz.",
    en: "The pattern generalises: turn a unimodal problem into a monotone predicate via the DIFFERENCE OF NEIGHBOURS. The sign of f(i+1) − f(i) is positive up to the peak and negative after — always monotone. That replaces ternary search with a plain binary search." },
 ]},
 { titleUz: "Aylantirilgan tartiblangan massiv", titleEn: "A rotated sorted array", blocks: [
  { t: "p",
    uz: "Bog‘liq klassik masala: tartiblangan massiv aylantirilgan, masalan [7, 9, 1, 3, 5]. Unda x ni topish kerak. Massiv butunlay monoton emas, lekin uning ICHIDA monotonlik bor va binary search hamon ishlaydi.",
    en: "A related classic: a sorted array has been rotated, for example [7, 9, 1, 3, 5], and you must find x in it. The array is not monotone as a whole, yet monotonicity survives INSIDE it and binary search still works." },
  { t: "p",
    uz: "Kalit kuzatish: massivni o‘rtadan bo‘lsak, YARMILARDAN KAMIDA BITTASI to‘liq tartiblangan bo‘ladi. Uni a[lo] va a[mid] ni solishtirib aniqlaymiz. Keyin x o‘sha tartiblangan yarimda yotadimi yo‘qmi — buni oddiy solishtirish bilan bilamiz.",
    en: "The key observation: cut the array in the middle and AT LEAST ONE half is fully sorted. You can tell which by comparing a[lo] with a[mid]. Then a simple comparison says whether x lies inside that sorted half." },
  { t: "code", cpp: "int search(const vector<int>& a, int x) {\n    int lo = 0, hi = (int)a.size() - 1;\n    while (lo <= hi) {\n        int mid = lo + (hi - lo) / 2;\n        if (a[mid] == x) return mid;\n        if (a[lo] <= a[mid]) {                 // chap yarim tartiblangan\n            if (a[lo] <= x && x < a[mid]) hi = mid - 1;\n            else                          lo = mid + 1;\n        } else {                                // o‘ng yarim tartiblangan\n            if (a[mid] < x && x <= a[hi]) lo = mid + 1;\n            else                          hi = mid - 1;\n        }\n    }\n    return -1;\n}",
    captionUz: "Har qadamda «qaysi yarim tartiblangan» degan savolga javob berib, keyin x shu yerdami deb tekshiramiz. Narx hamon O(log n).",
    captionEn: "At each step we ask which half is sorted, then whether x lies in it. The cost is still O(log n)." },
  { t: "exercise",
    qUz: "Aylantirilgan massivda takrorlar bo‘lsa (masalan [2, 2, 2, 1, 2]) usul ishlaydimi?",
    qEn: "Does the method still work when the rotated array has duplicates, such as [2, 2, 2, 1, 2]?",
    aUz: "Yo‘q, kafolat buziladi. a[lo] == a[mid] bo‘lganda qaysi yarim tartiblanganini aniqlab bo‘lmaydi. Standart yechim — bunday holatda lo ni bittaga surish, lekin u eng yomon holatda O(n) beradi. Takrorlar bo‘lsa binary search ning kafolati yo‘qoladi.",
    aEn: "No, the guarantee breaks: when a[lo] == a[mid] you cannot tell which half is sorted. The standard fix is to advance lo by one in that case, but the worst case then degrades to O(n). With duplicates, the binary-search guarantee is lost." },
 ]},
]},
/* ── 8. Ikki o‘lchamli monoton matritsada qidiruv ────────────────────── */
"binary-search-8": { sections: [
 { titleUz: "Burchakdan boshlash", titleEn: "Starting from a corner", blocks: [
  { t: "p",
    uz: "Matritsa berilgan: har bir QATOR chapdan o‘ngga o‘sadi, har bir USTUN yuqoridan pastga o‘sadi. Unda x sonini topish kerak. Har bir qatorda alohida binary search qilish mumkin — O(n log m). Lekin O(n + m) yechim ham bor, va u ancha chiroyli.",
    en: "You are given a matrix where every ROW increases left to right and every COLUMN increases top to bottom, and you must find x. Binary searching each row gives O(n log m). But there is an O(n + m) solution, and it is far more elegant." },
  { t: "p",
    uz: "Hiyla: O‘NG YUQORI burchakdan boshlang. Bu nuqta maxsus — u o‘z qatorining ENG KATTASI va o‘z ustunining ENG KICHIGI. Shuning uchun uni x bilan solishtirish har doim aniq qaror beradi.",
    en: "The trick: start from the TOP-RIGHT corner. That cell is special — it is the LARGEST in its row and the SMALLEST in its column, so comparing it with x always yields a definite decision." },
  { t: "sim", titleUz: "7 ni qidirish", titleEn: "Searching for 7", frames: [
    { spec: { kind: "matrix", label: "o‘ng yuqori burchakdan",
        rows: [[1, 4, 8, 12], [2, 5, 9, 14], [3, 6, 11, 16], [10, 13, 15, 18]],
        hi: [[0, 3]], note: "12 > 7 → bu USTUN kerak emas" },
      uz: "O‘ng yuqori burchakda 12. U 7 dan katta. Bu ustundagi qolgan hamma element 12 dan ham katta (ustun pastga o‘sadi), demak BUTUN USTUN tashlanadi.",
      en: "The top-right corner holds 12, which exceeds 7. Everything below it in that column is larger still (columns increase downward), so the WHOLE COLUMN is discarded." },
    { spec: { kind: "matrix", label: "chapga siljidik",
        rows: [[1, 4, 8, 12], [2, 5, 9, 14], [3, 6, 11, 16], [10, 13, 15, 18]],
        hi: [[0, 2]], dim: [[0, 3], [1, 3], [2, 3], [3, 3]],
        note: "8 > 7 → yana bitta ustun tashlanadi" },
      uz: "Chapga bir qadam: 8. U ham 7 dan katta, demak bu ustun ham kerak emas. Har qadamda BUTUN qator yoki BUTUN ustun tashlanadi.",
      en: "One step left brings 8, still greater than 7, so that column goes too. Each step discards an entire row or an entire column." },
    { spec: { kind: "matrix", label: "4 < 7 → pastga",
        rows: [[1, 4, 8, 12], [2, 5, 9, 14], [3, 6, 11, 16], [10, 13, 15, 18]],
        hi: [[0, 1]], dim: [[0, 2], [0, 3], [1, 2], [1, 3], [2, 2], [2, 3], [3, 2], [3, 3]],
        note: "4 < 7 → bu QATOR kerak emas" },
      uz: "Endi 4. U 7 dan KICHIK. Bu qatorda chapdagilar 4 dan ham kichik, demak butun QATOR tashlanadi va pastga tushamiz.",
      en: "Now 4, which is LESS than 7. Everything to its left in that row is smaller still, so the whole ROW is discarded and we move down." },
    { spec: { kind: "matrix", label: "topildi",
        rows: [[1, 4, 8, 12], [2, 5, 9, 14], [3, 6, 11, 16], [10, 13, 15, 18]],
        hi: [[2, 1]], dim: [[0, 0], [0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 2], [2, 3], [3, 2], [3, 3]],
        note: "n + m qadamdan ko‘p emas" },
      uz: "Pastga tushib borib 6 ni topamiz, keyin yana pastga — 6 < 7... Har qadamda yo chapga, yo pastga yuramiz, shuning uchun jami qadamlar soni n + m dan oshmaydi.",
      en: "Descending we reach 6, then continue since 6 < 7. Every step goes either left or down, so the total number of steps never exceeds n + m." },
  ]},
  { t: "codewalk", code: "bool search2D(const vector<vector<int>>& a, int x) {\n    int r = 0, c = (int)a[0].size() - 1;      // o‘ng yuqori burchak\n    while (r < (int)a.size() && c >= 0) {\n        if (a[r][c] == x) return true;\n        if (a[r][c] > x) --c;                 // ustunni tashlaymiz\n        else             ++r;                 // qatorni tashlaymiz\n    }\n    return false;\n}",
    notes: [
      { from: 2, uz: "Boshlanish nuqtasi MUHIM. Chap yuqori burchakdan boshlasangiz, u qatorining ham, ustunining ham eng kichigi — katta bo‘lsa qayerga yurishni bilib bo‘lmaydi. O‘ng yuqori (yoki chap quyi) burchak yagona to‘g‘ri tanlov.",
        en: "The starting corner MATTERS. From the top-left, the cell is the smallest of both its row and its column, so a “too large” comparison gives no direction. Top-right (or bottom-left) is the only workable choice." },
      { from: 5, uz: "Katta bo‘lsa — ustunni tashlaymiz. Bu qaror ISHONCHLI, chunki ustun pastga o‘sadi va undagi qolgan hamma element yanada katta.",
        en: "Too large means dropping the column — a SOUND decision, because the column increases downward and everything remaining in it is larger still." },
      { from: 6, uz: "Kichik bo‘lsa — qatorni tashlaymiz. Har iteratsiyada aniq bitta qator yoki ustun yo‘qoladi, shuning uchun sikl ko‘pi bilan n + m marta aylanadi.",
        en: "Too small means dropping the row. Exactly one row or column disappears per iteration, so the loop runs at most n + m times." },
    ]},
 ]},
 { titleUz: "Qachon haqiqiy binary search kerak", titleEn: "When a real binary search is needed", blocks: [
  { t: "p",
    uz: "Yuqoridagi usul matritsa faqat qator va ustun bo‘yicha tartiblangan bo‘lganda ishlaydi. Agar matritsa TO‘LIQ tartiblangan bo‘lsa (ya’ni qator oxiri keyingi qator boshidan kichik), uni bitta uzun massiv deb qarash mumkin va oddiy binary search yetadi — O(log(n·m)).",
    en: "The method above assumes only that rows and columns are sorted. If the matrix is FULLY sorted (each row's last element is below the next row's first), it can be treated as one long array and a plain binary search suffices — O(log(n·m))." },
  { t: "code", cpp: "// to‘liq tartiblangan matritsa: bitta massiv kabi\nint lo = 0, hi = n * m - 1;\nwhile (lo <= hi) {\n    int mid = lo + (hi - lo) / 2;\n    int v = a[mid / m][mid % m];       // 1D indeksni 2D ga aylantirish\n    if (v == x) return true;\n    if (v < x) lo = mid + 1;\n    else       hi = mid - 1;\n}",
    captionUz: "mid / m — qator, mid % m — ustun. Bu «bir o‘lchovli indeksni ikki o‘lchovga aylantirish» naqshi grid masalalarida doim uchraydi.",
    captionEn: "mid / m is the row and mid % m the column. This “flatten a 2D index into 1D” idiom recurs throughout grid problems." },
  { t: "table", headUz: ["Matritsa turi", "Usul", "Narx"], headEn: ["Kind of matrix", "Method", "Cost"],
    rows: [
      ["to‘liq tartiblangan", "1D binary search", "O(log(n·m))"],
      ["qator va ustun bo‘yicha", "burchakdan yurish", "O(n + m)"],
      ["faqat qatorlar bo‘yicha", "har qatorda binary search", "O(n log m)"],
      ["tartibsiz", "hech qanday", "O(n·m)"],
    ]},
  { t: "exercise",
    qUz: "n = m = 1000 matritsa qator va ustun bo‘yicha tartiblangan. Burchakdan yurish va har qatorda binary search — qaysi biri tez?",
    qEn: "In a 1000×1000 matrix sorted by rows and columns, which is faster: walking from a corner, or binary searching each row?",
    aUz: "Burchakdan yurish: n + m = 2000 qadam. Har qatorda binary search: n · log m = 1000 × 10 = 10 000 qadam. Birinchisi besh barobar tez va kodi ham qisqaroq. Lekin ikkalasi ham amalda tez — 10⁵ ta so‘rov bo‘lsagina farq sezilarli bo‘ladi.",
    aEn: "Walking a corner takes n + m = 2000 steps; binary searching each row takes n · log m = 10 000. The first is five times faster and shorter to write. Both are fast in practice, though — the difference only tells with 10⁵ queries." },
 ]},
]},

/* ── 9. Kompozit (ko‘p shartli) predikatlar ──────────────────────────── */
"binary-search-9": { sections: [
 { titleUz: "Predikat ichida butun algoritm", titleEn: "A whole algorithm inside the predicate", blocks: [
  { t: "p",
    uz: "Oddiy masalalarda predikat bitta solishtirish edi. Murakkab masalalarda esa predikatning O‘ZI butun bir algoritm bo‘ladi: ochko‘zlik, DP, graf kezish. Binary search shunchaki tashqi qobiq bo‘lib qoladi.",
    en: "In simple problems the predicate was one comparison. In harder ones the predicate IS an entire algorithm — a greedy pass, a DP, a graph traversal — and the binary search becomes only the outer shell." },
  { t: "p",
    uz: "Muhimi shundaki, tashqi qobiq HAR DOIM bir xil: firstTrue sxemasi. O‘zgaradigani faqat check funksiyasi. Shuning uchun bunday masalalarni yechish ikki bosqichga bo‘linadi: (1) nimani qidirayotganingizni aniqlang, (2) check ni yozing.",
    en: "The point is that the outer shell NEVER changes: it is the first-true scheme. Only the check function varies. So solving these problems splits in two: decide what you are searching over, then write the check." },
  { t: "sim", titleUz: "Ikki shartli predikat", titleEn: "A predicate with two conditions", frames: [
    { spec: { kind: "table", label: "check(x) ichida ikkita talab",
        rows: [["shart", "ma’nosi"], ["vaqt <= T", "ulgurish"], ["narx <= B", "byudjet"]], hi: [1, 0],
        note: "ikkalasi ham bajarilishi kerak" },
      uz: "Predikat ikkita shartdan iborat: ishni T vaqtda ulgurish VA byudjetdan oshmaslik. check(x) ikkalasini ham tekshiradi.",
      en: "The predicate has two requirements: finish within time T AND stay inside the budget. check(x) tests both." },
    { spec: { kind: "array", label: "har ikkalasi monoton bo‘lsa", values: ["F", "F", "T", "T", "T", "T"],
        hi: [2], note: "VA amali monotonlikni saqlaydi" },
      uz: "Agar HAR IKKALA shart ham monoton bo‘lsa (x oshganda faqat yaxshilanadi), ularning VA amali ham monoton bo‘ladi. Predikat FFTTTT ko‘rinishida qoladi va binary search ishlaydi.",
      en: "If BOTH conditions are monotone — improving as x grows — then their AND is monotone too. The predicate still reads FFTTTT and binary search applies." },
    { spec: { kind: "array", label: "biri teskari bo‘lsa", values: ["F", "T", "T", "F", "F", "F"],
        hi: [1, 2], note: "monotonlik BUZILDI — binary search yaramaydi" },
      uz: "Lekin agar bir shart x oshganda yaxshilansa, ikkinchisi esa yomonlashsa, VA amali FTTFFF ko‘rinishini oladi. Monotonlik buzildi — binary search bu yerda TASODIFIY javob qaytaradi.",
      en: "But if one condition improves with x while the other worsens, their AND reads FTTFFF. Monotonicity is gone, and binary search here returns an ARBITRARY answer." },
  ]},
  { t: "note", kind: "warn",
    uz: "Bu eng nozik xato: kod ishlaydi, qulamaydi, ba’zi testlarda hatto to‘g‘ri javob beradi. Shuning uchun predikat yozgandan keyin ALBATTA o‘zingizga savol bering: «bu shart rost bo‘lgandan keyin, kattaroq x uchun ham rost bo‘lib qoladimi?» Agar javob «yo‘q» bo‘lsa, binary search yaramaydi.",
    en: "This is the subtlest bug: the code runs, does not crash, and even answers correctly on some tests. So after writing a predicate always ask: once it is true, does it stay true for larger x? If not, binary search does not apply." },
 ]},
 { titleUz: "Ochko‘zlik check sifatida", titleEn: "A greedy pass as the check", blocks: [
  { t: "p",
    uz: "Eng ko‘p uchraydigan naqsh: check ichida OCHKO‘ZLIK. Masala: n ta ish va k ta ishchi, har bir ish tᵢ vaqt oladi. Ishchilar ketma-ket ishlarni oladi. Eng kam qancha vaqtda tugatish mumkin?",
    en: "The commonest pattern is a GREEDY check. The problem: n jobs and k workers, job i taking tᵢ time, with workers taking jobs in order. What is the least total time?" },
  { t: "codewalk", code: "bool canFinish(long long T, const vector<int>& t, int k) {\n    int workers = 1;\n    long long load = 0;\n    for (int x : t) {\n        if (x > T) return false;          // bitta ish ham sig‘maydi\n        if (load + x <= T) {\n            load += x;                    // shu ishchi davom etadi\n        } else {\n            ++workers;                    // yangi ishchi\n            load = x;\n            if (workers > k) return false;\n        }\n    }\n    return true;\n}",
    notes: [
      { from: 5, uz: "Chegaraviy holat: agar bitta ishning o‘zi T dan uzun bo‘lsa, hech qanday taqsimot yordam bermaydi. Bu tekshiruvni unutish — klassik xato, va u faqat maxsus testda ko‘rinadi.",
        en: "An edge case: if a single job exceeds T, no distribution can help. Forgetting this check is a classic slip that only a targeted test exposes." },
      { from: 6, to: 8, uz: "Ochko‘zlik: joriy ishchiga imkon qadar ko‘p ish beramiz. Bu OPTIMAL, chunki ishni keyinga qoldirish hech qachon foyda bermaydi — u baribir kimgadir tushadi.",
        en: "The greedy rule: give the current worker as much as fits. That is OPTIMAL because postponing a job never helps — it still has to go to somebody." },
      { from: 10, to: 12, uz: "Yangi ishchi ochilganda ularning sonini tekshiramiz. Bu «necha ishchi kerak» degan savolga javob beradi, va uni k bilan solishtirish predikatni yakunlaydi.",
        en: "Opening a new worker updates the count. That answers “how many workers are needed”, and comparing it with k completes the predicate." },
    ]},
  { t: "note", kind: "key",
    uz: "Monotonlikni tekshiring: T kattalashsa, kerakli ishchilar soni faqat KAMAYADI (yoki o‘zgarmaydi). Demak «k ta ishchi yetadimi» sharti monoton — binary search qonuniy. Bu tekshiruvni har safar bajaring, u bir daqiqa oladi.",
    en: "Check monotonicity: as T grows, the number of workers needed only FALLS (or stays put). So “do k workers suffice” is monotone and the binary search is legitimate. Do this check every time; it takes a minute." },
  { t: "table", headUz: ["Check ichida nima", "Umumiy narx"], headEn: ["What is inside the check", "Total cost"],
    rows: [
      ["bitta solishtirish", "O(log C)"],
      ["bir yurish (ochko‘zlik)", "O(n log C)"],
      ["sortlash", "O(n log n log C)"],
      ["DP yoki graf kezish", "O(check × log C)"],
    ],
    captionUz: "log C odatda 30–60. Demak check ni 60 marta chaqirish mumkin — uni O(n) qilib yozsangiz, deyarli har doim sig‘adi.",
    captionEn: "log C is usually 30 to 60, so the check runs about sixty times. Written as O(n), it almost always fits." },
  { t: "exercise",
    qUz: "check funksiyasi O(n log n) (ichida sortlash bor) va javob oralig‘i 10⁹. n = 10⁵. Sig‘adimi?",
    qEn: "The check is O(n log n) because it sorts, the answer range is 10⁹, and n = 10⁵. Does it fit?",
    aUz: "log(10⁹) ≈ 30 marta check chaqiriladi, har biri 10⁵ × 17 ≈ 1.7·10⁶ amal — jami 5·10⁷. Chegarada, lekin sig‘adi. Yaxshilash oson: sortlashni check DAN TASHQARIGA chiqaring — u har safar bir xil natija beradi, shuning uchun bir marta bajarilsa yetadi. Shunda narx 1.7·10⁶ + 30 × 10⁵ = 5·10⁶ ga tushadi.",
    aEn: "The check runs about log(10⁹) ≈ 30 times at 10⁵ × 17 ≈ 1.7·10⁶ operations each, so 5·10⁷ in total — tight but feasible. The easy improvement is to move the sort OUTSIDE the check: it produces the same order every time, so once is enough, bringing the total to 1.7·10⁶ + 30 × 10⁵ = 5·10⁶." },
 ]},
]},

/* ── 10. Parallel binary search ──────────────────────────────────────── */
"binary-search-10": { sections: [
 { titleUz: "Ko‘p so‘rov, bitta jarayon", titleEn: "Many queries, one process", blocks: [
  { t: "p",
    uz: "Masala: q ta so‘rov bor va HAR BIRI uchun binary search qilish kerak. Lekin har bir check qimmat — masalan u butun jarayonni boshidan qayta o‘tkazishni talab qiladi. Alohida-alohida qilsak, narx q × log C × check bo‘ladi va bu sig‘maydi.",
    en: "The setting: q queries, each needing its own binary search, but where a single check is expensive — it may require replaying an entire process from the start. Done separately the cost is q × log C × check, which does not fit." },
  { t: "p",
    uz: "Parallel binary search g‘oyasi: barcha so‘rovlarni BIR VAQTDA olib borish. Har bir so‘rov o‘z [lo, hi] oralig‘ini saqlaydi. Keyin jarayonni bir marta boshidan oxirigacha o‘tkazamiz va yo‘l-yo‘lakay barcha so‘rovlarning mid nuqtalarini tekshiramiz. Shu bilan log C ta o‘tish yetadi — q × log C emas.",
    en: "The idea of parallel binary search: advance ALL the queries at once. Each keeps its own [lo, hi]. Then we replay the process from start to finish a single time, checking every query's midpoint along the way. That needs log C passes instead of q × log C." },
  { t: "sim", titleUz: "Uchta so‘rov birga qisqaradi", titleEn: "Three queries shrinking together", frames: [
    { spec: { kind: "ranges", label: "boshida: hamma oraliq to‘liq", n: 8,
        spans: [{ at: 0, from: 0, to: 7, text: "so‘rov 1" }, { at: 1, from: 0, to: 7, text: "so‘rov 2" }, { at: 2, from: 0, to: 7, text: "so‘rov 3" }],
        note: "har so‘rov o‘z [lo, hi] ini saqlaydi" },
      uz: "Uchta so‘rov, har birining o‘z oralig‘i bor va boshida hammasi to‘liq.",
      en: "Three queries, each with its own range, all starting full." },
    { spec: { kind: "ranges", label: "1-o‘tish: mid larni tekshiramiz", n: 8,
        spans: [{ at: 0, from: 0, to: 7, text: "mid = 3", on: true }, { at: 1, from: 0, to: 7, text: "mid = 3", on: true }, { at: 2, from: 0, to: 7, text: "mid = 3", on: true }],
        note: "jarayonni BIR marta o‘tkazamiz" },
      uz: "Jarayonni boshidan yuritamiz. Har bir qadamda «shu vaqtga kelib qaysi so‘rovlarning midiga yetdik?» deb qaraymiz va ularni o‘sha nuqtada tekshiramiz. Bitta o‘tishda BARCHA so‘rovlar tekshiriladi.",
      en: "We replay the process from the beginning. At each step we ask which queries have reached their midpoint and test those there. A single pass checks EVERY query." },
    { spec: { kind: "ranges", label: "oraliqlar qisqardi", n: 8,
        spans: [{ at: 0, from: 0, to: 3, text: "so‘rov 1" }, { at: 1, from: 4, to: 7, text: "so‘rov 2" }, { at: 2, from: 0, to: 3, text: "so‘rov 3" }],
        note: "har biri o‘z javobiga qarab qisqardi" },
      uz: "Natijalarga qarab har bir so‘rovning oralig‘i o‘z tomoniga qisqaradi. Endi keyingi o‘tishni boshlaymiz.",
      en: "Based on the results each query's range shrinks in its own direction, and the next pass begins." },
    { spec: { kind: "table", label: "narx", rows: [["alohida", "birga"], ["q · log C · check", "log C · (check + q)"]], hi: [1, 1],
        note: "q = 10⁵ da farq minglab barobar" },
      uz: "Farq: alohida qilsak q × log C ta check, birga qilsak esa atigi log C ta o‘tish. q = 10⁵ va log C = 20 bo‘lsa, 2·10⁶ o‘tish o‘rniga 20 ta — bu masalani mumkin qiladi.",
      en: "The difference: separately it is q × log C checks; together it is log C passes. With q = 10⁵ and log C = 20 that is twenty passes instead of two million — which is what makes the problem solvable." },
  ]},
  { t: "code", cpp: "// har so‘rov uchun [lo, hi] saqlaymiz\nvector<int> lo(q, 0), hi(q, m);\nfor (int iter = 0; iter < LOG; ++iter) {\n    vector<vector<int>> atStep(m + 1);          // qaysi so‘rov qaysi qadamda tekshiriladi\n    for (int i = 0; i < q; ++i)\n        if (lo[i] < hi[i]) atStep[(lo[i] + hi[i]) / 2].push_back(i);\n\n    reset();                                     // jarayonni boshidan\n    for (int step = 0; step <= m; ++step) {\n        applyStep(step);                         // bitta qadamni qo‘llash\n        for (int i : atStep[step])\n            if (check(i)) hi[i] = step; else lo[i] = step + 1;\n    }\n}",
    captionUz: "Tashqi sikl log C marta aylanadi, ichkarisi esa butun jarayonni bir marta o‘tadi. Jami: O(log C × (m + q)).",
    captionEn: "The outer loop runs log C times and the inner one replays the whole process once, giving O(log C × (m + q))." },
  { t: "note", kind: "key",
    uz: "Bu usul odatda DSU yoki Fenwick tree bilan birga ishlatiladi: jarayon — bu qirralarni bosqichma-bosqich qo‘shish yoki elementlarni qo‘shib borish, check esa o‘sha paytdagi holatni so‘rash. «Qachon bu ikki tugun bog‘landi?» tipidagi masalalar shu bilan yechiladi.",
    en: "The technique usually pairs with a DSU or a Fenwick tree: the process is adding edges or elements step by step, and the check queries the state at that moment. Problems like “when did these two nodes become connected?” are solved this way." },
 ]},
 { titleUz: "Qachon kerak bo‘ladi", titleEn: "When you need it", blocks: [
  { t: "table", headUz: ["Belgi", "Ma’nosi"], headEn: ["Signal", "Meaning"],
    rows: [
      ["q ta so‘rov, har biri «qachon»", "parallel binary search"],
      ["check bir marta emas, jarayon", "qayta o‘tkazish qimmat"],
      ["qirralar bosqichma-bosqich qo‘shiladi", "DSU bilan birga"],
      ["oflayn (barcha so‘rov oldindan ma’lum)", "shart — onlayn ishlamaydi"],
    ],
    captionUz: "OFLAYN sharti majburiy: barcha so‘rovlarni oldindan bilish kerak, chunki ularni birga olib boramiz.",
    captionEn: "The OFFLINE requirement is essential: all the queries must be known in advance, because they are advanced together." },
  { t: "note", kind: "warn",
    uz: "Bu bo‘limning eng murakkab mavzusi va u kamdan-kam uchraydi. Uni yodlash shart emas — muhimi, «har bir so‘rovga alohida binary search sig‘maydi» degan holatni tanib olish va bunday yo‘l borligini bilish.",
    en: "This is the hardest topic in the track and it appears rarely. There is no need to memorise it — what matters is recognising the situation “a separate binary search per query will not fit” and knowing this route exists." },
  { t: "exercise",
    qUz: "q = 10⁵ so‘rov, har biri uchun check O(n) va javob oralig‘i 10⁵. Alohida binary search sig‘adimi?",
    qEn: "With q = 10⁵ queries, an O(n) check each, and an answer range of 10⁵, does a separate binary search per query fit?",
    aUz: "Yo‘q: 10⁵ × 17 × n. Hatto n = 100 bo‘lganda ham 1.7·10⁸ — chegarada, n kattaroq bo‘lsa umuman sig‘maydi. Parallel binary search bilan esa 17 ta o‘tish × (n + q) — bu ancha kichik.",
    aEn: "No: 10⁵ × 17 × n. Even at n = 100 that is 1.7·10⁸, right on the edge, and larger n does not fit at all. Parallel binary search gives 17 passes × (n + q), which is far smaller." },
 ]},
]},
/* ── 11. Eksponensial qidiruv va cheksiz oraliq ──────────────────────── */
"binary-search-11": { sections: [
 { titleUz: "Yuqori chegara noma’lum bo‘lsa", titleEn: "When the upper bound is unknown", blocks: [
  { t: "p",
    uz: "Binary search boshlanishi uchun ikkita chegara kerak: lo va hi. Lekin ba’zan hi noma’lum. «Shu shart birinchi marta qachon bajariladi?» — javob 10 bo‘lishi ham, 10⁹ bo‘lishi ham mumkin. hi ni juda katta qilib olsak, keraksiz iteratsiyalar ketadi; kichik qilib olsak, javobni umuman topa olmaymiz.",
    en: "Binary search needs two bounds to start, lo and hi. Sometimes hi is unknown: “when does this condition first hold?” might answer 10 or 10⁹. Setting hi enormous wastes iterations; setting it small can miss the answer entirely." },
  { t: "p",
    uz: "Yechim ikki bosqichli. Avval chegarani IKKILANTIRIB qidiramiz: 1, 2, 4, 8, 16… predikat rost bo‘lguncha. Shundan keyin oddiy binary search qilamiz — endi oraliq ma’lum. Bu «eksponensial» yoki «galloping» qidiruv deb ataladi.",
    en: "The fix has two phases. First find a bound by DOUBLING: 1, 2, 4, 8, 16… until the predicate turns true. Then run an ordinary binary search, now that the range is known. This is called exponential — or galloping — search." },
  { t: "sim", titleUz: "Chegarani ikkilantirib topish", titleEn: "Doubling to find a bound", frames: [
    { spec: { kind: "numberline", label: "1 dan boshlaymiz", from: 0, to: 64, span: [0, 1], ticks: 4,
        marks: [{ at: 1, text: "hi = 1", tone: "hi" }],
        note: "check(1) = yolg‘on → kam" },
      uz: "hi = 1 dan boshlaymiz va tekshiramiz: yolg‘on. Demak javob kattaroq — chegarani ikkilantiramiz.",
      en: "Start with hi = 1 and test it: false. So the answer is larger, and we double the bound." },
    { spec: { kind: "numberline", label: "2, keyin 4, keyin 8", from: 0, to: 64, span: [0, 8], ticks: 4,
        marks: [{ at: 8, text: "hi = 8", tone: "hi" }],
        note: "hali ham yolg‘on" },
      uz: "2, 4, 8 — hammasi yolg‘on. Har qadamda chegara ikki barobar oshadi, shuning uchun kerakli qiymatga TEZ yetamiz.",
      en: "2, 4 and 8 all come back false. The bound doubles at every step, so we reach the right magnitude FAST." },
    { spec: { kind: "numberline", label: "16 da rost", from: 0, to: 64, span: [8, 16], ticks: 4,
        marks: [{ at: 8, text: "lo", tone: "lo" }, { at: 16, text: "hi", tone: "hi" }],
        note: "javob (8, 16] oralig‘ida" },
      uz: "16 da predikat ROST bo‘ldi. Endi javob (8, 16] oralig‘ida ekani aniq — chunki 8 da yolg‘on, 16 da rost edi. Oraliq topildi.",
      en: "At 16 the predicate is TRUE. The answer therefore lies in (8, 16] — false at 8, true at 16. The range is found." },
    { spec: { kind: "numberline", label: "endi oddiy binary search", from: 0, to: 64, span: [8, 12], ticks: 4,
        marks: [{ at: 12, text: "mid", tone: "mid" }],
        note: "log(oraliq) qadam" },
      uz: "Ikkinchi bosqich — shu oraliqda oddiy binary search. Umumiy narx: log(javob) ikkilantirishga + log(javob) binary search ga = O(log javob). E’tibor bering, narx JAVOBGA bog‘liq, chegaraga emas.",
      en: "The second phase is a plain binary search inside that range. The total is log(answer) doublings plus log(answer) halvings = O(log answer). Note that the cost depends on the ANSWER, not on any preset bound." },
  ]},
  { t: "codewalk", code: "long long expSearch(auto pred) {\n    long long hi = 1;\n    while (!pred(hi)) {\n        hi *= 2;\n        if (hi > LIMIT) return -1;        // javob yo‘q\n    }\n    long long lo = hi / 2;                // oxirgi yolg‘on qiymat\n\n    while (lo + 1 < hi) {                 // (lo, hi]: lo yolg‘on, hi rost\n        long long mid = lo + (hi - lo) / 2;\n        if (pred(mid)) hi = mid;\n        else           lo = mid;\n    }\n    return hi;\n}",
    notes: [
      { from: 3, to: 6, uz: "Birinchi bosqich: chegarani ikkilantirish. LIMIT tekshiruvi majburiy — aks holda predikat hech qachon rost bo‘lmasa, hi toshib ketadi va sikl abadiy aylanadi.",
        en: "Phase one doubles the bound. The LIMIT check is mandatory: if the predicate is never true, hi overflows and the loop never ends." },
      { from: 7, uz: "lo = hi / 2 — bu oxirgi tekshirilgan YOLG‘ON qiymat. Uni qayta tekshirishning hojati yo‘q, natijasi allaqachon ma’lum.",
        en: "lo = hi / 2 is the last value known to be FALSE. There is no need to re-test it; the result is already known." },
      { from: 9, uz: "Bu yerda ochiq-yopiq oraliq (lo, hi] ishlatilyapti: lo har doim yolg‘on, hi har doim rost. Sikl lo + 1 == hi bo‘lguncha davom etadi va javob — hi.",
        en: "This uses the half-open range (lo, hi]: lo is always false and hi always true. The loop runs until lo + 1 == hi, and the answer is hi." },
      { from: 11, to: 12, uz: "Bu invariantda ikkala shox ham mid ni OLADI (mid + 1 yo‘q). Sikl qisqarishi lo + 1 < hi sharti bilan kafolatlanadi.",
        en: "With this invariant both branches take mid (no mid + 1). Termination is guaranteed by the lo + 1 < hi condition instead." },
    ]},
  { t: "note", kind: "key",
    uz: "Eksponensial qidiruv narxi O(log javob), oddiy binary search esa O(log chegara). Agar javob kichik bo‘lsa (masalan 100), lekin chegara katta bo‘lsa (10¹⁸), farq 60 qadam bilan 14 qadam orasida — va check qimmat bo‘lganda bu sezilarli.",
    en: "Exponential search costs O(log answer) where a plain binary search costs O(log bound). When the answer is small (a hundred, say) but the bound is huge (10¹⁸), that is fourteen steps against sixty — and it tells when the check is expensive." },
 ]},
 { titleUz: "Boshqa qo‘llanishlari", titleEn: "Its other uses", blocks: [
  { t: "table", headUz: ["Vaziyat", "Nega ikkilantirish"], headEn: ["Situation", "Why doubling"],
    rows: [
      ["chegara noma’lum", "hi ni topish"],
      ["cheksiz oqim / massiv", "uzunlik ma’lum emas"],
      ["javob kichik, chegara katta", "log(javob) < log(chegara)"],
      ["interaktiv masala", "so‘rovlar sonini tejash"],
      ["vector::reserve yo‘q", "sig‘imni ikkilantirish"],
    ],
    captionUz: "Oxirgi qator — tanish naqsh: vector ham xuddi shu sababdan sig‘imini ikkilantiradi. G‘oya bir xil, qo‘llanishi boshqa.",
    captionEn: "The last row is a familiar pattern: a vector doubles its capacity for exactly this reason. Same idea, different application." },
  { t: "note", kind: "tip",
    uz: "Interaktiv masalalarda (siz savol berasiz, judge javob beradi) so‘rovlar soni cheklangan bo‘ladi. Eksponensial qidiruv u yerda ayniqsa qimmatli: chegarani bilmasangiz ham, so‘rovlar sonini minimal ushlab turasiz.",
    en: "In interactive problems — where you ask and the judge answers — the number of queries is capped. Exponential search is especially valuable there: it keeps the query count minimal even when you do not know the bound." },
  { t: "exercise",
    qUz: "Javob 1000 atrofida, lekin chegara 10¹⁸ deb berilgan. Oddiy va eksponensial qidiruv necha marta check chaqiradi?",
    qEn: "The answer is around 1000 but the stated bound is 10¹⁸. How many checks do the plain and exponential searches make?",
    aUz: "Oddiy: log₂(10¹⁸) ≈ 60. Eksponensial: ikkilantirish log₂(1000) ≈ 10 marta, keyin binary search yana ≈ 10 marta — jami 20. Uch barobar kam. check O(n) bo‘lsa va n = 10⁵ bo‘lsa, bu 6·10⁶ o‘rniga 2·10⁶ amal.",
    aEn: "Plain: log₂(10¹⁸) ≈ 60 checks. Exponential: about log₂(1000) ≈ 10 doublings plus another 10 for the binary search, so 20 — three times fewer. With an O(n) check at n = 10⁵ that is 2·10⁶ operations instead of 6·10⁶." },
 ]},
]},

/* ── 12. Bit bo‘yicha sakrash ────────────────────────────────────────── */
"binary-search-12": { sections: [
 { titleUz: "Javobni bitlab yig‘ish", titleEn: "Assembling the answer bit by bit", blocks: [
  { t: "p",
    uz: "Binary search ni yozishning yana bir usuli bor, va u l/r bilan ishlashdan ancha xatosizroq. G‘oya: javobni noldan boshlab, ENG KATTA bitdan eng kichigiga qarab yig‘amiz. Har bir bit uchun bitta savol beramiz: «shu bitni qo‘shsam ham shart bajariladimi?»",
    en: "There is another way to write a binary search, and it is markedly harder to get wrong than juggling l and r. The idea: build the answer from zero, from the HIGHEST bit down to the lowest, asking one question per bit — “if I add this bit, does the condition still hold?”." },
  { t: "sim", titleUz: "13 ni bitlab yig‘ish", titleEn: "Assembling 13 bit by bit", frames: [
    { spec: { kind: "bits", label: "javob = 0 dan boshlaymiz", value: 0, width: 4, names: ["1", "2", "4", "8"],
        note: "har bitni yuqoridan pastga sinaymiz" },
      uz: "Javobni 0 dan boshlaymiz. Eng katta bitdan (bu yerda 8) boshlab, har birini navbat bilan sinab ko‘ramiz.",
      en: "Start the answer at 0. Beginning with the highest bit — here 8 — we try each one in turn." },
    { spec: { kind: "bits", label: "8 ni qo‘shib ko‘ramiz", value: 8, width: 4, names: ["1", "2", "4", "8"], hi: [3],
        note: "check(8) = rost → bitni QOLDIRAMIZ" },
      uz: "0 + 8 = 8. check(8) rost — demak 8 gacha borish mumkin, bitni qoldiramiz. Javob hozircha 8.",
      en: "0 + 8 = 8, and check(8) is true, so we can reach 8 and the bit stays. The answer so far is 8." },
    { spec: { kind: "bits", label: "4 ni qo‘shib ko‘ramiz", value: 12, width: 4, names: ["1", "2", "4", "8"], hi: [2],
        note: "check(12) = rost → bu ham qoladi" },
      uz: "8 + 4 = 12. check(12) ham rost — bu bit ham qoladi. Javob 12.",
      en: "8 + 4 = 12, and check(12) is true as well, so this bit stays too. The answer is 12." },
    { spec: { kind: "bits", label: "2 ni sinaymiz", value: 12, width: 4, names: ["1", "2", "4", "8"], hi: [1],
        note: "check(14) = yolg‘on → bitni TASHLAYMIZ" },
      uz: "12 + 2 = 14. check(14) YOLG‘ON — demak 14 gacha bora olmaymiz. Bu bitni tashlaymiz va javob 12 bo‘lib qoladi.",
      en: "12 + 2 = 14, and check(14) is FALSE, so we cannot reach 14. That bit is dropped and the answer stays 12." },
    { spec: { kind: "bits", label: "1 ni sinaymiz — javob 13", value: 13, width: 4, names: ["1", "2", "4", "8"], hi: [0],
        note: "check(13) = rost → yakuniy javob 13" },
      uz: "12 + 1 = 13. check(13) rost — bit qoladi. Barcha bitlar ko‘rib chiqildi, javob 13. Diqqat: biz hech qachon orqaga qaytmadik va hech qanday chegara hisoblamadik.",
      en: "12 + 1 = 13, check(13) is true, and the bit stays. Every bit has been examined and the answer is 13. Note that we never backtracked and never computed a boundary." },
  ]},
  { t: "codewalk", code: "// eng katta x ni topamiz: pred(x) rost, pred(x+1) yolg‘on\nlong long ans = 0;\nfor (int k = 62; k >= 0; --k) {\n    long long next = ans | (1LL << k);\n    if (next <= LIMIT && pred(next)) ans = next;\n}\n// ans — oxirgi rost qiymat",
    notes: [
      { from: 3, uz: "Eng katta bitdan boshlaymiz. 62 — long long uchun xavfsiz chegara (63-bit ishora uchun).",
        en: "We start from the highest bit. 62 is the safe ceiling for a long long, since bit 63 is the sign." },
      { from: 4, uz: "ans | (1 << k) — joriy javobga k-bitni qo‘shish. Bu ans + (1 << k) bilan bir xil, chunki bit hali yoqilmagan.",
        en: "ans | (1 << k) adds bit k to the current answer. It equals ans + (1 << k) here, since that bit is not yet set." },
      { from: 5, uz: "Rost bo‘lsa bitni QOLDIRAMIZ, yolg‘on bo‘lsa shunchaki o‘tkazib yuboramiz. Hech qanday l, r, mid yo‘q — shuning uchun chegara xatosi ham yo‘q.",
        en: "If true we KEEP the bit; if false we simply skip it. There is no l, r or mid at all — and therefore no off-by-one to get wrong." },
      { from: 5, uz: "next <= LIMIT tekshiruvi overflow dan saqlaydi. Usulning yana bir afzalligi: (l + r) / 2 kabi toshib ketadigan ifoda umuman yo‘q.",
        en: "The next <= LIMIT test guards against overflow. Another advantage of the method: there is no expression like (l + r) / 2 to overflow in the first place." },
    ]},
  { t: "note", kind: "key",
    uz: "Nima uchun bu ishlaydi? Chunki har bir bit javobga MUSTAQIL hissa qo‘shadi va biz ularni kattadan kichikka qarab ko‘ramiz. Yuqori bitni olish har doim afzal — u qolgan barcha kichik bitlarning yig‘indisidan katta. Bu ochko‘zlik, va u monoton predikatda to‘g‘ri ishlaydi.",
    en: "Why does it work? Because each bit contributes INDEPENDENTLY and we consider them from high to low. Taking a higher bit is always preferable: it exceeds the sum of all lower bits together. This is a greedy argument, and it is valid for a monotone predicate." },
 ]},
 { titleUz: "Qayerda bu usul afzal", titleEn: "Where this version is preferable", blocks: [
  { t: "table", headUz: ["", "l/r sxemasi", "Bit bo‘yicha"], headEn: ["", "The l/r scheme", "Bit jumping"],
    rows: [
      ["chegara xatosi", "oson qilinadi", "umuman yo‘q"],
      ["overflow", "(l+r)/2 xavfi", "yo‘q"],
      ["iteratsiyalar", "log(oraliq)", "aniq 63 ta"],
      ["tuzilma bo‘ylab yurish", "qiyin", "tabiiy"],
    ],
    captionUz: "Oxirgi qator eng muhimi: bu usul TUZILMA bo‘ylab yurish bilan ajoyib mos tushadi.",
    captionEn: "The last row matters most: this version fits beautifully with walking a data structure." },
  { t: "p",
    uz: "Aynan shu naqsh «Ma’lumot tuzilmalari» bo‘limidagi Fenwick tree bo‘ylab tushishda ishlatilgan edi: har bir bit uchun «shu blokni qo‘shsam, yig‘indi hali ham yetarlimi?» deb so‘raymiz. Xuddi shu g‘oya daraxtlarda binary lifting (LCA topish) uchun ham ishlatiladi.",
    en: "This is exactly the pattern used for descending a Fenwick tree in the Data Structures track: for each bit we ask “if I add this block, is the sum still within range?”. The same idea powers binary lifting on trees, for instance when finding an LCA." },
  { t: "code", cpp: "// Fenwick bo‘ylab tushish: prefix >= x bo‘lgan birinchi indeks\nint findKth(long long x) {\n    int pos = 0;\n    for (int k = LOG; k >= 0; --k) {\n        int next = pos + (1 << k);\n        if (next <= n && bit[next] < x) {\n            pos = next;\n            x -= bit[next];        // qolgan miqdor\n        }\n    }\n    return pos + 1;\n}",
    captionUz: "Bitta sikl, O(log n) — bu «binary search + har qadamda prefix so‘rovi» variantidan (O(log² n)) tezroq.",
    captionEn: "One loop at O(log n) — faster than “binary search with a prefix query at each step”, which would be O(log² n)." },
  { t: "exercise",
    qUz: "Bit bo‘yicha sakrashda sikl har doim 63 marta aylanadi, l/r sxemasida esa log(oraliq) marta. Bu sekinroq degani emasmi?",
    qEn: "Bit jumping always loops 63 times while the l/r scheme runs log(range) times. Does that not make it slower?",
    aUz: "Nazariy jihatdan biroz ko‘proq iteratsiya, lekin amalda farq deyarli yo‘q: oraliq 10¹⁸ bo‘lganda l/r ham 60 marta aylanadi. Va agar chegara kichik bo‘lsa, siklni LOG = log₂(chegara) dan boshlash mumkin. Evaziga chegara xatolari va overflow xavfi butunlay yo‘qoladi — bu ancha qimmatliroq.",
    aEn: "It is a few more iterations in theory, but hardly any in practice: with a range of 10¹⁸ the l/r scheme also runs about sixty times. And when the bound is small you can start the loop at LOG = log₂(bound). In exchange, off-by-one errors and overflow risk disappear entirely — a far better trade." },
 ]},
]},

/* ── 13. Qaysi usulni tanlash ────────────────────────────────────────── */
"binary-search-13": { sections: [
 { titleUz: "Bitta savol: predikat monotonmi", titleEn: "One question: is the predicate monotone", blocks: [
  { t: "p",
    uz: "Bu bo‘limda o‘nga yaqin variant ko‘rdik, lekin ularning hammasi bitta g‘oyaning ko‘rinishlari. Masalani ko‘rganda beriladigan birinchi va eng muhim savol o‘zgarmaydi: MONOTON PREDIKAT bormi? Agar bor bo‘lsa, binary search ishlaydi; qaysi variantini yozish esa ikkinchi darajali savol.",
    en: "This track showed about ten variants, but they are all faces of one idea. The first and most important question never changes: is there a MONOTONE PREDICATE? If there is, binary search applies; which variant to write is a secondary matter." },
  { t: "table", headUz: ["Vaziyat", "Usul"], headEn: ["Situation", "Method"],
    rows: [
      ["tartiblangan massiv, qiymat qidirish", "lower_bound / upper_bound"],
      ["«birinchi rost» chegara", "firstTrue sxemasi"],
      ["javobni hisoblash qiyin, tekshirish oson", "javob bo‘yicha qidiruv"],
      ["javob kasr son", "haqiqiy sonlar, 100 iteratsiya"],
      ["funksiya unimodal (cho‘qqi bor)", "ternary search yoki qo‘shnilar farqi"],
      ["yuqori chegara noma’lum", "eksponensial qidiruv"],
      ["chegara xatosidan qo‘rqasiz", "bit bo‘yicha sakrash"],
      ["q ta so‘rov, check qimmat", "parallel binary search"],
      ["matritsa qator/ustun bo‘yicha", "burchakdan yurish O(n+m)"],
    ],
    captionUz: "Bu jadval bo‘limning xulosasi: chap ustundan o‘z holatingizni toping.",
    captionEn: "This table is the summary of the track: find your situation in the left column." },
  { t: "diagram", spec: { kind: "flow", label: "Ikkita savol yetadi",
    steps: ["predikat monotonmi?", "chegara ma’lummi?"],
    note: "birinchisi — ha/yo‘q, ikkinchisi — usulni tanlaydi" } },
 ]},
 { titleUz: "Eng ko‘p uchraydigan xatolar", titleEn: "The most common mistakes", blocks: [
  { t: "table", headUz: ["Simptom", "Sabab", "Yechim"], headEn: ["Symptom", "Cause", "Fix"],
    rows: [
      ["cheksiz sikl", "oraliq qisqarmayapti", "bir shoxda mid + 1"],
      ["javob bittaga farq qiladi", "chegara yopiq/ochiq chalkashgan", "firstTrue sxemasini yozing"],
      ["katta sonlarda noto‘g‘ri", "(l + r) toshib ketdi", "l + (r − l) / 2"],
      ["tasodifiy javob", "predikat monoton emas", "monotonlikni tekshiring"],
      ["haqiqiy sonlarda osilib qoldi", "eps juda kichik", "qat’iy 100 iteratsiya"],
      ["setda sekin", "std::lower_bound ishlatilgan", "s.lower_bound(x)"],
    ]},
  { t: "note", kind: "key",
    uz: "Ikkita odat bu bo‘limdagi xatolarning deyarli hammasini yo‘q qiladi. Birinchisi: har doim BITTA sxemani (firstTrue) yozing va faqat predikatni almashtiring. Ikkinchisi: predikat yozgandan keyin uni 3–4 ta kichik qiymatda QO‘LDA hisoblab, FFFTTT ko‘rinishida ekaniga ishonch hosil qiling.",
    en: "Two habits remove nearly every bug in this track. First, always write ONE scheme (firstTrue) and change only the predicate. Second, after writing a predicate, evaluate it BY HAND on three or four small values and confirm it really reads FFFTTT." },
  { t: "p",
    uz: "Va oxirgi fikr: binary search — bu massivda qidirish emas. Bu «javoblar fazosini yarimlatish» usuli. Massiv, javoblar oralig‘i, vaqt o‘qi, hatto graf holatlari — agar ular ustida monoton shart bo‘lsa, binary search ishlaydi. Shu qarash bilan siz uni kutilmagan joylarda ko‘ra boshlaysiz.",
    en: "And a closing thought: binary search is not about searching an array. It is a way of halving a space of answers. An array, a range of answers, a timeline, even graph states — wherever a monotone condition exists over them, binary search applies. With that view you start seeing it in unexpected places." },
  { t: "exercise",
    qUz: "Masalada: «eng kichik k ni toping, shundaki k ta eng katta elementning yig‘indisi S dan oshsin». Bu binary search masalasimi?",
    qEn: "A problem asks for “the smallest k such that the sum of the k largest elements exceeds S”. Is this a binary search problem?",
    aUz: "Ha, lekin binary search kerak emas. Predikat monoton (k oshsa yig‘indi faqat ortadi), shuning uchun binary search ishlaydi — O(n log n) sortlash + O(log n) qidiruv. Lekin sortlashdan keyin prefix yig‘indi bilan bitta chiziqli yurish yetadi: O(n log n) sortlash + O(n). Bir xil murakkablik, soddaroq kod. Binary search mumkin bo‘lgani uni ZARUR qilmaydi.",
    aEn: "Yes, but you do not need it. The predicate is monotone (the sum only grows with k), so binary search works — O(n log n) to sort plus O(log n) to search. But after sorting, a single linear pass over the prefix sums suffices: O(n log n) plus O(n). Same complexity, simpler code. That binary search is possible does not make it necessary." },
 ]},
]},
};
