/* Deep lessons — Two pointers & sliding window (two-pointers).
 *
 * This track is short and its techniques are simple, which is exactly why it
 * is usually taught badly: the code is four lines, so explanations skip the
 * only hard parts — WHY the walk is linear, and WHEN the technique is not
 * allowed at all.
 *
 * So the sliding window here is never introduced as a template to copy. Each
 * stage names the property that makes the pointers legal to move, and the
 * late stages make that property the subject: a whole stage on the amortised
 * argument and on the monotonicity two pointers silently assumes.
 *
 * Original text and diagrams. Nothing copied from any source.
 */

import type { DeepLesson } from "../deep-lesson";

export const twoPointersLessons: Record<string, DeepLesson> = {

/* ── 1. Opposite pointers ────────────────────────────────────────────── */
"two-pointers-1": { sections: [
 { titleUz: "Ikki uchdan bir-biriga qarab", titleEn: "From both ends, toward each other", blocks: [
  { t: "p",
    uz: "Eng oddiy shakl: bitta ko‘rsatkich massivning boshida, ikkinchisi oxirida, va ular bir-biriga qarab yuradi. Har qadamda BITTASI siljiydi, shuning uchun jami n qadamdan oshmaydi — O(n).",
    en: "The simplest form: one pointer at the start of the array, one at the end, moving toward each other. At every step exactly ONE of them shifts, so there are at most n steps in total — O(n)." },
  { t: "p",
    uz: "Klassik masala: tartiblangan massivda yig‘indisi X ga teng juftlikni toping. Sodda yechim barcha juftlarni ko‘radi — O(n²). Ikki ko‘rsatkich buni O(n) ga tushiradi, va sababi juda chiroyli.",
    en: "The classic problem: in a sorted array, find a pair summing to X. The naive solution checks every pair at O(n²). Two pointers bring that to O(n), and the reason is elegant." },
  { t: "sim", titleUz: "Yig‘indisi 10 bo‘lgan juftlik", titleEn: "A pair summing to 10", frames: [
    { spec: { kind: "array", label: "tartiblangan massiv, target = 10",
        values: [1, 3, 4, 6, 8, 11],
        ptr: [{ at: 0, text: "l" }, { at: 5, text: "r" }],
        note: "1 + 11 = 12 > 10" },
      uz: "l boshida, r oxirida. Yig‘indi 1 + 11 = 12, bu 10 dan KATTA. Yig‘indini kamaytirish kerak — qaysi ko‘rsatkichni siljitamiz?",
      en: "l is at the start and r at the end. Their sum is 1 + 11 = 12, which is GREATER than 10. We must reduce the sum — but which pointer do we move?" },
    { spec: { kind: "array", label: "r ni chapga suramiz",
        values: [1, 3, 4, 6, 8, 11], hi: [5],
        ptr: [{ at: 0, text: "l" }, { at: 4, text: "r" }],
        note: "11 ni umuman tashlab yubordik" },
      uz: "r ni chapga suramiz. Muhim kuzatish: 11 ni tashlab yuborar ekanmiz, biz uni HECH KIM bilan juftlashtira olmasligimizni bilamiz — chunki 1 eng kichigi edi, va 1 + 11 ham katta chiqdi. Demak 11 ni butunlay unutish mumkin.",
      en: "Move r left. The key observation: in discarding the 11 we know it can pair with NOBODY — 1 was the smallest available, and even 1 + 11 was too large. So the 11 can be forgotten entirely." },
    { spec: { kind: "array", label: "1 + 8 = 9 < 10 → l ni suramiz",
        values: [1, 3, 4, 6, 8, 11], hi: [0],
        ptr: [{ at: 1, text: "l" }, { at: 4, text: "r" }],
        note: "endi 1 ni tashlaymiz — u ham hech kimga yaramaydi" },
      uz: "Endi 1 + 8 = 9 < 10 — yig‘indi KICHIK. Simmetrik dalil: 8 eng kattasi edi, va 1 + 8 ham yetmadi, demak 1 hech kim bilan 10 bermaydi. l ni o‘ngga suramiz.",
      en: "Now 1 + 8 = 9 < 10, so the sum is too SMALL. The symmetric argument: 8 was the largest available and 1 + 8 still fell short, so 1 can reach 10 with nobody. Move l right." },
    { spec: { kind: "array", label: "topildi: 4 + 6 = 10",
        values: [1, 3, 4, 6, 8, 11], hi: [2, 3],
        ptr: [{ at: 2, text: "l" }, { at: 3, text: "r" }],
        note: "har qadamda bitta element butunlay hal bo‘ldi" },
      uz: "4 + 6 = 10 — topildi. Butun jarayonda har qadamda AYNAN BITTA element «hal bo‘ldi» va boshqa hech qachon ko‘rilmadi. Shuning uchun qadamlar soni n dan oshmaydi.",
      en: "4 + 6 = 10 — found. Throughout, each step settled EXACTLY ONE element which was never looked at again, so the number of steps cannot exceed n." },
  ]},
  { t: "codewalk", code: "sort(a.begin(), a.end());              // SHART: tartiblangan bo'lishi kerak\nint l = 0, r = n - 1;\n\nwhile (l < r) {\n    long long s = a[l] + a[r];\n    if (s == target) return {l, r};\n    if (s < target) ++l;               // kattaroq kerak\n    else            --r;               // kichikroq kerak\n}",
    notes: [
      { from: 1, uz: "TARTIBLANGANLIK — bu texnikaning butun sharti. Tartiblanmagan massivda «yig‘indi katta bo‘lsa r ni suramiz» degan qoida hech qanday ma’noga ega emas, chunki chap tomonda kattaroq son bo‘lishi mumkin.",
        en: "SORTEDNESS is the entire precondition. On an unsorted array the rule “if the sum is too large, move r” means nothing, because a larger value may sit to the left." },
      { from: 4, uz: "l < r — qat’iy tengsizlik: bitta elementni o‘zi bilan juftlashtirmaymiz. Agar masalada bunga ruxsat bo‘lsa, l <= r yozing.",
        en: "l < r is strict: an element is not paired with itself. If the statement allows that, write l <= r." },
      { from: 7, to: 8, uz: "Bu ikki qator — butun algoritm. Har biri bitta elementni butunlay chiqarib tashlaydi, va aynan shu O(n) ni beradi.",
        en: "These two lines are the whole algorithm. Each discards one element for good, and that is precisely what makes it O(n)." },
    ]},
  { t: "note", kind: "key",
    uz: "To‘g‘rilik dalili qisqa: yig‘indi target dan KATTA bo‘lsa, a[r] ni saqlash foydasiz — chunki uning eng yaxshi sherigi (a[l], eng kichigi) ham katta yig‘indi berdi. Demak a[r] ni tashlash hech narsani yo‘qotmaydi. Bu greedy bo‘limidagi exchange argument bilan bir xil shakl.",
    en: "The correctness argument is short: when the sum is too LARGE, keeping a[r] is pointless, because even its best partner — a[l], the smallest available — was still too much. So discarding a[r] loses nothing. It has the same shape as the exchange argument from the greedy track." },
 ]},
 { titleUz: "Qarama-qarshi ko‘rsatkichlarning boshqa qo‘llanishlari", titleEn: "Other uses of opposite pointers", blocks: [
  { t: "table", headUz: ["Masala", "Qoida"], headEn: ["Problem", "The rule"],
    rows: [
      ["yig‘indisi X bo‘lgan juftlik", "katta bo‘lsa r--, kichik bo‘lsa l++"],
      ["palindrom tekshiruvi", "a[l] != a[r] → yo‘q"],
      ["massivni teskari o‘girish", "swap(a[l], a[r]), ikkalasini sur"],
      ["konteyner: maksimal suv hajmi", "past devorni sur"],
      ["yig‘indisi ≤ X bo‘lgan juftliklar soni", "r − l ta juftlikni birga sana"],
      ["uch element (3-sum)", "bittasini qot, qolganiga ikki ko‘rsatkich"],
    ],
    captionUz: "Beshinchi qator muhim naqsh: bitta qadamda BIR NECHTA juftlikni birdan sanash. Bu ko‘p masalalarda O(n²) ni O(n) qiladi.",
    captionEn: "The fifth row is an important pattern: counting SEVERAL pairs in a single step. That is what turns O(n²) into O(n) in many problems." },
  { t: "p",
    uz: "Beshinchi qatorni tushuntiramiz. «Yig‘indisi ≤ X bo‘lgan juftliklar SONI» kerak bo‘lsa: agar a[l] + a[r] ≤ X bo‘lsa, demak a[l] ni l+1 dan r gacha bo‘lgan HAMMA element bilan juftlashtirish mumkin (chunki ular a[r] dan kichik). Bu r − l ta juftlik — ularni birdan qo‘shamiz va l ni suramiz.",
    en: "Take the fifth row. To COUNT the pairs with sum ≤ X: if a[l] + a[r] ≤ X, then a[l] can be paired with EVERY element from l+1 to r, since they are all no larger than a[r]. That is r − l pairs — add them all at once and move l." },
  { t: "code", cpp: "long long cnt = 0;\nint l = 0, r = n - 1;\nwhile (l < r) {\n    if (a[l] + a[r] <= X) { cnt += r - l; ++l; }   // BIR NECHTA juftlik birdan\n    else --r;\n}",
    captionUz: "cnt += r − l — bu bitta qator O(n²) sanashni O(n) ga aylantiradi.",
    captionEn: "The line cnt += r − l turns an O(n²) count into an O(n) one." },
  { t: "note", kind: "warn",
    uz: "Eng ko‘p uchraydigan xato — TARTIBLASHNI unutish. Ikki ko‘rsatkich kodi tartiblanmagan massivda ham «ishlaydi» (qulamaydi), lekin javob noto‘g‘ri chiqadi. Agar masalada indekslar kerak bo‘lsa, tartiblashdan oldin ularni saqlab qo‘ying — bu ham tez-tez unutiladi.",
    en: "The commonest bug is forgetting to SORT. The two-pointer code still “runs” on an unsorted array without crashing, but the answer is wrong. And if the problem needs original indices, store them before sorting — that too is often forgotten." },
  { t: "exercise",
    qUz: "Tartiblangan massivda yig‘indisi X ga teng juftlik topildi. Bunday juftliklar SONINI qanday sanaysiz (takrorlanuvchi elementlar bor)?",
    qEn: "In a sorted array you found a pair summing to X. How do you COUNT such pairs when duplicates exist?",
    aUz: "a[l] + a[r] == X bo‘lganda ikki holat bor. Agar a[l] != a[r] bo‘lsa: chapdan a[l] ga teng elementlar sonini (c1), o‘ngdan a[r] ga teng elementlar sonini (c2) sanaymiz, javobga c1·c2 qo‘shamiz va ikkala ko‘rsatkichni ham shu qadar suramiz. Agar a[l] == a[r] bo‘lsa (butun oraliq bir xil), oraliqdagi k ta elementdan juftlik tanlash — C(k, 2) = k(k−1)/2. Ikkinchi holni unutish eng ko‘p uchraydigan xato.",
    aEn: "When a[l] + a[r] == X there are two cases. If a[l] != a[r], count how many elements equal a[l] from the left (c1) and how many equal a[r] from the right (c2), add c1·c2 and advance both pointers past them. If a[l] == a[r], the whole range holds the same value, and choosing a pair among k of them gives C(k, 2) = k(k−1)/2. Forgetting the second case is the usual bug." },
 ]},
]},

/* ── 2. Bir yo'nalishli yurish ───────────────────────────────────────── */
"two-pointers-2": { sections: [
 { titleUz: "O‘qish va yozish ko‘rsatkichlari", titleEn: "The read and write pointers", blocks: [
  { t: "p",
    uz: "Ikkinchi shakl butunlay boshqacha: ikkala ko‘rsatkich ham BIR yo‘nalishda, chapdan o‘ngga yuradi, lekin har xil tezlikda. Biri O‘QIYDI (massivni ko‘rib chiqadi), ikkinchisi YOZADI (natijani joylashtiradi).",
    en: "The second form is quite different: both pointers move the SAME way, left to right, but at different speeds. One READS, scanning the array, while the other WRITES, placing the result." },
  { t: "p",
    uz: "Bu naqsh «massivdan biror narsani olib tashlash» masalalarida ishlatiladi va uning katta afzalligi bor: u QO‘SHIMCHA XOTIRASIZ, joyida (in-place) ishlaydi.",
    en: "This pattern is used for “remove something from the array” problems, and it has a large advantage: it works IN PLACE, with no extra memory." },
  { t: "sim", titleUz: "Takrorlarni olib tashlash", titleEn: "Removing duplicates", frames: [
    { spec: { kind: "tworow", label: "tartiblangan massiv, takrorlar bor",
        top: [1, 1, 2, 3, 3, 3], bottom: [1, "", "", "", "", ""],
        topName: "o‘qish", bottomName: "yozish", hi: [0],
        note: "birinchi element har doim qoladi" },
      uz: "Yuqori qator — asl massiv (o‘qiymiz), pastki qator — natija (yozamiz). Birinchi elementni shunchaki ko‘chiramiz.",
      en: "The top row is the original array we read from; the bottom is the result we write into. The first element is simply copied." },
    { spec: { kind: "tworow", label: "ikkinchi 1: oldingisiga teng → o‘tkazamiz",
        top: [1, 1, 2, 3, 3, 3], bottom: [1, "", "", "", "", ""],
        topName: "o‘qish", bottomName: "yozish", hi: [1],
        note: "o‘qish ko‘rsatkichi siljidi, yozish — yo‘q" },
      uz: "Ikkinchi element ham 1 — oldingisiga teng, demak takror. O‘qish ko‘rsatkichini suramiz, lekin YOZISH ko‘rsatkichi joyida qoladi. Ikkala ko‘rsatkichning har xil tezlikda yurishi shu.",
      en: "The second element is also 1, a duplicate of the previous. The read pointer advances while the WRITE pointer stays. That difference in speed is the whole idea." },
    { spec: { kind: "tworow", label: "2 yangi → yozamiz",
        top: [1, 1, 2, 3, 3, 3], bottom: [1, 2, "", "", "", ""],
        topName: "o‘qish", bottomName: "yozish", hi: [2],
        note: "yozish ko‘rsatkichi ham siljidi" },
      uz: "2 yangi element — uni yozish pozitsiyasiga qo‘yamiz va yozish ko‘rsatkichini ham suramiz. Diqqat: biz asl massivning O‘ZIGA yozyapmiz, chunki yozish ko‘rsatkichi har doim o‘qishdan orqada.",
      en: "2 is new, so we place it at the write position and advance that pointer too. Note that we write into the ORIGINAL array, which is safe because the write pointer always trails the read pointer." },
    { spec: { kind: "tworow", label: "natija: dastlabki 3 ta katak",
        top: [1, 1, 2, 3, 3, 3], bottom: [1, 2, 3, "", "", ""],
        topName: "asl", bottomName: "natija", hi: [0, 1, 2],
        note: "javob uzunligi = yozish ko‘rsatkichi" },
      uz: "Yakunda javob massivning dastlabki k ta katagida, va k — bu yozish ko‘rsatkichining oxirgi qiymati. Qolgan kataklar «axlat», lekin ular bizga kerak emas. O(n) vaqt, O(1) qo‘shimcha xotira.",
      en: "At the end the answer occupies the first k cells, where k is the final value of the write pointer. The rest is leftover junk we do not need. O(n) time and O(1) extra memory." },
  ]},
  { t: "codewalk", code: "int write = 0;\nfor (int read = 0; read < n; ++read) {\n    if (read == 0 || a[read] != a[read - 1])   // saqlash shartimi?\n        a[write++] = a[read];\n}\n// javob: a[0..write-1]",
    notes: [
      { from: 3, uz: "Butun masala shu shartda. Uni o‘zgartirsangiz, boshqa masala chiqadi: «nollarni olib tashlash» uchun a[read] != 0, «faqat juftlarni qoldirish» uchun a[read] % 2 == 0.",
        en: "The whole problem lives in this condition. Change it and you get a different problem: a[read] != 0 removes zeros, a[read] % 2 == 0 keeps only the evens." },
      { from: 4, uz: "a[write++] = a[read] — yozish va ko‘rsatkichni surish bitta ifodada. write ≤ read har doim bajariladi, shuning uchun hali o‘qilmagan ma’lumotni ustiga yozib yubormaymiz.",
        en: "a[write++] = a[read] writes and advances in one expression. The invariant write ≤ read always holds, so we never overwrite data we have not read yet." },
    ]},
  { t: "note", kind: "key",
    uz: "write ≤ read invarianti bu texnikaning XAVFSIZLIK kafolati. U har doim bajariladi, chunki write faqat read bilan birga (yoki undan sekinroq) o‘sadi. Shuning uchun joyida ishlash xavfsiz — bu ko‘p yechimlarda ravshan emas.",
    en: "The invariant write ≤ read is this technique's SAFETY guarantee. It always holds because write only ever advances together with read, or slower. That is what makes working in place safe, and it is not obvious in most implementations." },
 ]},
 { titleUz: "Bir yo‘nalishli naqshning qo‘llanishlari", titleEn: "Uses of the forward pattern", blocks: [
  { t: "table", headUz: ["Masala", "Saqlash sharti"], headEn: ["Problem", "The keep condition"],
    rows: [
      ["takrorlarni olib tashlash", "a[i] != a[i−1]"],
      ["nollarni oxiriga surish", "a[i] != 0"],
      ["berilgan qiymatni o‘chirish", "a[i] != val"],
      ["har element ko‘pi bilan 2 marta", "write < 2 || a[i] != a[write−2]"],
      ["bo‘shliqlarni siqish", "a[i] != ' ' yoki oldingisi ' ' emas"],
    ],
    captionUz: "Beshta masala, bitta kod. Farq faqat bitta shartda — bu naqshni tanib olishning eng oson yo‘li.",
    captionEn: "Five problems, one piece of code, differing only in one condition — the easiest way to recognise the pattern." },
  { t: "note", kind: "tip",
    uz: "To‘rtinchi qator hiylali va uni ko‘rish arziydi: «har element ko‘pi bilan 2 marta qolsin» sharti uchun oldingi elementga emas, ALLAQACHON YOZILGAN elementga qaraysiz: a[write−2]. Bu «yozish ko‘rsatkichi ham ma’lumot manbai» degan g‘oyaning namunasi.",
    en: "The fourth row is a nice trick worth seeing: for “keep each element at most twice” you compare not with the previous input element but with an ALREADY WRITTEN one, a[write−2]. It illustrates the idea that the write side is itself a source of information." },
  { t: "note", kind: "warn",
    uz: "Bu texnika massivning qolgan qismini O‘ZGARTIRMAYDI — a[write..n−1] da eski qiymatlar qoladi. Agar masalada «qolganini nol qiling» yoki «massiv uzunligini o‘zgartiring» deyilsa, buni ALOHIDA qiling. Ko‘p yechimlar aynan shuni unutgani uchun yiqiladi.",
    en: "The technique leaves the rest of the array UNCHANGED — old values survive in a[write..n−1]. If the statement asks you to zero the tail or resize the array, do that SEPARATELY. Many solutions fail for exactly this reason." },
  { t: "exercise",
    qUz: "«Nollarni massiv oxiriga suring, qolgan elementlarning TARTIBI saqlansin» — bu naqsh bilan qanday yechiladi?",
    qEn: "“Move the zeros to the end, preserving the ORDER of the other elements” — how does this pattern solve it?",
    aUz: "Ikki qadam. Birinchi: yuqoridagi kod bilan nolmas elementlarni oldinga siqamiz (shart a[read] != 0). Ikkinchi: a[write..n−1] ni nol bilan to‘ldiramiz. Jami O(n), qo‘shimcha xotira O(1), va tartib saqlanadi — chunki biz elementlarni ASL ketma-ketligida ko‘chiryapmiz. Agar tartib kerak bo‘lmasa, ancha tezroq yo‘l bor: qarama-qarshi ko‘rsatkichlar bilan nolni oxiridagi nolmas element bilan almashtirish, bu esa yozishlar sonini kamaytiradi.",
    aEn: "Two steps. First, compact the non-zeros forward with the code above, using the condition a[read] != 0. Second, fill a[write..n−1] with zeros. That is O(n) time and O(1) extra memory, and the order survives because we copy the elements in their ORIGINAL sequence. If order did not matter there is a faster route: use opposite pointers and swap each zero with a non-zero from the end, which performs fewer writes." },
 ]},
]},

/* ── 3. Two pointers ikki massiv ustida ──────────────────────────────── */
"two-pointers-3": { sections: [
 { titleUz: "Ikkita tartiblangan ro‘yxatni birga yurish", titleEn: "Walking two sorted lists together", blocks: [
  { t: "p",
    uz: "Uchinchi shakl: ikkita ALOHIDA tartiblangan massiv, va har biriga o‘z ko‘rsatkichi. Har qadamda ikkalasidan kichikrog‘ini olamiz va o‘sha ko‘rsatkichni suramiz. Bu merge sort ning birlashtirish qadami bilan aynan bir xil.",
    en: "The third form: two SEPARATE sorted arrays, each with its own pointer. At every step we take the smaller of the two fronts and advance that pointer — exactly the merge step of merge sort." },
  { t: "sim", titleUz: "Ikki massivni birlashtirish", titleEn: "Merging two arrays", frames: [
    { spec: { kind: "merge", label: "ikkita tartiblangan massiv",
        left: [1, 4, 7], right: [2, 3, 8], out: [], li: 0, ri: 0,
        note: "har biriga bitta ko‘rsatkich" },
      uz: "Ikkita tartiblangan massiv va ikkita ko‘rsatkich. Natija bo‘sh. Har qadamda ikkala ko‘rsatkich ostidagi elementlarni SOLISHTIRAMIZ.",
      en: "Two sorted arrays and two pointers, with an empty result. At each step we COMPARE the elements under the two pointers." },
    { spec: { kind: "merge", label: "1 < 2 → chapdan olamiz",
        left: [1, 4, 7], right: [2, 3, 8], out: [1], li: 1, ri: 0,
        note: "faqat chap ko‘rsatkich siljidi" },
      uz: "1 < 2, demak 1 ni olamiz va faqat CHAP ko‘rsatkichni suramiz. O‘ng ko‘rsatkich joyida qoladi — bu muhim, chunki 2 hali ishlatilmagan.",
      en: "1 < 2, so we take the 1 and advance only the LEFT pointer. The right one stays, which matters because the 2 has not been used yet." },
    { spec: { kind: "merge", label: "endi 4 va 2 — o‘ngdan olamiz",
        left: [1, 4, 7], right: [2, 3, 8], out: [1, 2], li: 1, ri: 1,
        note: "ko‘rsatkichlar navbat bilan siljiydi" },
      uz: "Endi 4 va 2 ni solishtiramiz: 2 kichik, uni olamiz. Ko‘rsatkichlar navbat bilan, «kim kichik bo‘lsa o‘sha» tamoyili bo‘yicha siljiydi.",
      en: "Now compare 4 and 2: the 2 is smaller and is taken. The pointers advance in turn, on the principle “whoever is smaller moves”." },
    { spec: { kind: "merge", label: "natija tartiblangan bo‘lib chiqadi",
        left: [1, 4, 7], right: [2, 3, 8], out: [1, 2, 3, 4, 7, 8], li: 3, ri: 3,
        note: "n + m qadam — har element bir marta" },
      uz: "Natija tayyor va u avtomatik ravishda tartiblangan. Umumiy qadamlar soni n + m — har element aynan bir marta olinadi. Bu O(n + m), va uni tezroq qilish mumkin emas, chunki natijani yozishning o‘zi shuncha turadi.",
      en: "The result is complete and automatically sorted. There are n + m steps in total, each element taken exactly once — O(n + m), and it cannot be faster, since merely writing the output costs that much." },
  ]},
  { t: "code", cpp: "int i = 0, j = 0;\nvector<int> res;\nres.reserve(n + m);\n\nwhile (i < n && j < m)\n    res.push_back(a[i] <= b[j] ? a[i++] : b[j++]);\n\nwhile (i < n) res.push_back(a[i++]);      // qoldiqni to'kib tashlaymiz\nwhile (j < m) res.push_back(b[j++]);",
    captionUz: "Oxirgi ikki sikl MAJBURIY: birinchi sikl bittasi tugaganda to‘xtaydi, ikkinchisida esa elementlar qolgan bo‘ladi.",
    captionEn: "The last two loops are MANDATORY: the first loop stops when one array runs out, leaving elements in the other." },
  { t: "note", kind: "key",
    uz: "a[i] <= b[j] dagi TENGLIK muhim. Agar teng elementlarni chapdan olsangiz, birlashtirish BARQAROR (stable) bo‘ladi — bir xil qiymatlarning asl tartibi saqlanadi. Merge sort ning barqarorligi aynan shu bitta belgiga bog‘liq.",
    en: "The EQUALITY in a[i] <= b[j] matters. Taking equal elements from the left makes the merge STABLE, preserving the original order among equal values. Merge sort's stability rests on that single character." },
 ]},
 { titleUz: "Birlashtirishdan boshqa masalalar", titleEn: "Beyond merging", blocks: [
  { t: "table", headUz: ["Masala", "Qoida"], headEn: ["Problem", "The rule"],
    rows: [
      ["birlashtirish", "kichigini ol"],
      ["kesishma (umumiy elementlar)", "teng bo‘lsa ol, aks holda kichigini sur"],
      ["birlashma (union)", "kichigini ol, teng bo‘lsa bittasini"],
      ["ayirma (A da bor, B da yo‘q)", "a < b bo‘lsa ol"],
      ["eng yaqin juftlik (a[i], b[j])", "farqni kuzatib, kichigini sur"],
      ["ikki massivning medianasi", "binary search bilan, O(log)"],
    ],
    captionUz: "Beshta qator bir xil skelet: ikki ko‘rsatkich, solishtirish, kichigini surish. Faqat «nima qilish» o‘zgaradi.",
    captionEn: "Five rows share one skeleton: two pointers, a comparison, advance the smaller. Only the action changes." },
  { t: "code", cpp: "// kesishma: ikkala massivda ham bor elementlar\nwhile (i < n && j < m) {\n    if (a[i] == b[j]) { res.push_back(a[i]); ++i; ++j; }   // IKKALASI ham\n    else if (a[i] < b[j]) ++i;\n    else ++j;\n}",
    captionUz: "Teng bo‘lganda IKKALA ko‘rsatkichni ham surish shart — aks holda takrorlar noto‘g‘ri sanaladi.",
    captionEn: "On equality BOTH pointers must advance, or duplicates are counted incorrectly." },
  { t: "note", kind: "tip",
    uz: "Bu naqsh set operatsiyalarini O(n + m) da bajaradi, holbuki har elementni ikkinchi massivdan qidirish O(n log m) berardi. Agar massivlar allaqachon tartiblangan bo‘lsa, ikki ko‘rsatkich har doim afzalroq. Tartiblanmagan bo‘lsa, hash to‘plam (unordered_set) tezroq bo‘lishi mumkin.",
    en: "This pattern performs set operations in O(n + m), where searching each element in the other array would cost O(n log m). When both arrays are already sorted, two pointers always win. When they are not, a hash set may be faster." },
  { t: "exercise",
    qUz: "Ikkita tartiblangan massivdan a[i] va b[j] juftligini shunday tanlangki, |a[i] − b[j]| MINIMAL bo‘lsin. Ikki ko‘rsatkich bilan qanday?",
    qEn: "From two sorted arrays choose a[i] and b[j] minimising |a[i] − b[j]|. How do two pointers do it?",
    aUz: "Har qadamda |a[i] − b[j]| ni hisoblab, eng kichigini eslab qolamiz. Keyin KICHIKROG‘INI suramiz: agar a[i] < b[j] bo‘lsa, i ni suramiz — chunki b[j] ni kamaytirib bo‘lmaydi (massiv o‘suvchi) va a[i] ni oshirish yagona yo‘l. Dalil qarama-qarshi ko‘rsatkichlardagi bilan bir xil: siljitilmaydigan variantlar hech qachon yaxshiroq javob bera olmaydi. O(n + m), va tartiblash kerak bo‘lsa O(n log n).",
    aEn: "At each step compute |a[i] − b[j]| and remember the smallest. Then advance whichever is SMALLER: if a[i] < b[j], move i, because b[j] cannot be reduced (the array is increasing) and raising a[i] is the only way to close the gap. The argument matches the opposite-pointers one: the options we skip can never do better. O(n + m), or O(n log n) if sorting is needed first." },
 ]},
]},

/* ── 4. Belgilangan uzunlikdagi oyna ─────────────────────────────────── */
"two-pointers-4": { sections: [
 { titleUz: "Uzunligi qat’iy oyna", titleEn: "A window of fixed size", blocks: [
  { t: "p",
    uz: "Endi SLIDING WINDOW ga o‘tamiz. Eng oddiy shakli: oyna uzunligi qat’iy k, va u chapdan o‘ngga BIR TEKISDA siljiydi. Har siljishda bitta element kiradi, bitta chiqadi.",
    en: "Now we turn to the SLIDING WINDOW. Its simplest form has a fixed length k and slides left to right at a STEADY pace: at each shift one element enters and one leaves." },
  { t: "p",
    uz: "Asosiy g‘oya: oynani har safar NOLDAN hisoblash shart emas. Agar oynadagi yig‘indi ma’lum bo‘lsa, keyingi oyna yig‘indisi = eski yig‘indi + yangi element − chiqqan element. Ikkita amal, O(1).",
    en: "The key idea: the window need not be recomputed FROM SCRATCH each time. If you know the current sum, the next one is old sum + entering element − leaving element. Two operations, O(1)." },
  { t: "sim", titleUz: "Uzunligi 3 bo‘lgan oyna siljiydi", titleEn: "A window of length 3 slides", frames: [
    { spec: { kind: "window", label: "birinchi oyna: [0, 2]",
        values: [2, 5, 1, 8, 3, 4], l: 0, r: 2, agg: "yig‘indi = 8",
        note: "birinchi oynani to‘liq hisoblaymiz" },
      uz: "Birinchi oynani (uzunligi 3) to‘liq hisoblaymiz: 2 + 5 + 1 = 8. Bu yagona marta to‘liq hisoblash.",
      en: "Compute the first window of length 3 in full: 2 + 5 + 1 = 8. This is the only time we compute a window from scratch." },
    { spec: { kind: "window", label: "siljiymiz: 8 kirdi, 2 chiqdi",
        values: [2, 5, 1, 8, 3, 4], l: 1, r: 3, agg: "8 + 8 − 2 = 14",
        note: "ikkita amal, hech narsa qayta hisoblanmaydi" },
      uz: "Oynani bitta o‘ngga suramiz. Yangi yig‘indi = 8 + 8 (kirgan) − 2 (chiqqan) = 14. Uchta elementni qayta qo‘shmadik — ikkita amal yetdi.",
      en: "Slide one step right. The new sum is 8 + 8 (entering) − 2 (leaving) = 14. We did not re-add three elements; two operations sufficed." },
    { spec: { kind: "window", label: "yana siljiymiz",
        values: [2, 5, 1, 8, 3, 4], l: 2, r: 4, agg: "14 + 3 − 5 = 12",
        best: [1, 3],
        note: "punktir — hozirgacha eng yaxshisi" },
      uz: "Yana siljiymiz: 14 + 3 − 5 = 12. Punktir ramka — hozirgacha topilgan eng katta yig‘indili oyna (14). Uni alohida o‘zgaruvchida saqlab boramiz.",
      en: "Slide again: 14 + 3 − 5 = 12. The dashed frame marks the best window found so far (14), which we keep in a separate variable." },
    { spec: { kind: "window", label: "oxirgi oyna",
        values: [2, 5, 1, 8, 3, 4], l: 3, r: 5, agg: "12 + 4 − 1 = 15",
        best: [3, 5],
        note: "javob 15 — n − k + 1 ta oyna ko‘rildi" },
      uz: "Oxirgi oyna: 12 + 4 − 1 = 15 — yangi rekord. Jami n − k + 1 ta oyna ko‘rildi va har biri O(1) da hisoblandi. Umumiy narx O(n), sodda yechimning O(n·k) si o‘rniga.",
      en: "The last window: 12 + 4 − 1 = 15, a new record. We examined n − k + 1 windows, each in O(1), for O(n) overall instead of the naive O(n·k)." },
  ]},
  { t: "codewalk", code: "long long sum = 0;\nfor (int i = 0; i < k; ++i) sum += a[i];      // birinchi oyna\nlong long best = sum;\n\nfor (int r = k; r < n; ++r) {\n    sum += a[r] - a[r - k];                   // kirdi - chiqdi\n    best = max(best, sum);\n}",
    notes: [
      { from: 2, uz: "Birinchi oynani alohida hisoblash — bu «tayyorlash» qadami. Uni siklga qo‘shishga urinish kodni chalkashtiradi va chegara xatolariga olib keladi.",
        en: "Computing the first window separately is a preparation step. Trying to fold it into the loop muddles the code and invites off-by-one errors." },
      { from: 6, uz: "a[r] − a[r − k] — butun texnika shu bitta qatorda. r − k — bu oynadan endigina chiqib ketgan element indeksi.",
        en: "a[r] − a[r − k] is the entire technique in one line. The index r − k is the element that has just left the window." },
      { from: 5, uz: "Sikl k dan boshlanadi, 0 dan emas — chunki birinchi k ta element allaqachon ishlangan. Bu chegara eng ko‘p xato qilinadigan joy.",
        en: "The loop starts at k rather than 0, because the first k elements are already accounted for. This boundary is the most error-prone part." },
    ]},
  { t: "note", kind: "key",
    uz: "Belgilangan oynani tanib olish oson: masalada k ANIQ berilgan bo‘ladi («k ta ketma-ket element», «uzunligi k bo‘lgan segment»). Agar uzunlik noma’lum bo‘lsa va uni topish kerak bo‘lsa — bu O‘ZGARUVCHAN oyna, keyingi bosqichning mavzusi.",
    en: "A fixed window is easy to recognise: the statement gives k EXPLICITLY (“k consecutive elements”, “a segment of length k”). If the length is unknown and must be found, that is a VARIABLE window — the next stage." },
 ]},
 { titleUz: "Yig‘indidan boshqa narsalar", titleEn: "Beyond sums", blocks: [
  { t: "p",
    uz: "Oynada yig‘indidan boshqa narsalarni ham kuzatish mumkin, lekin hammasi ham bir xil oson emas. Farq bitta savolda: chiqib ketayotgan elementni «ayirish» mumkinmi?",
    en: "A window can track more than a sum, but not all of it is equally easy. The difference comes down to one question: can the departing element be “subtracted”?" },
  { t: "table", headUz: ["Nima kuzatiladi", "Chiqishni qaytarish", "Vosita"], headEn: ["What is tracked", "Undoing the exit", "Tool"],
    rows: [
      ["yig‘indi", "ayirish — oson", "o‘zgaruvchi"],
      ["ko‘paytma", "bo‘lish — nol bilan muammo", "ehtiyot bo‘ling"],
      ["har xil elementlar soni", "chastotani kamaytirish", "map / massiv"],
      ["maksimum yoki minimum", "AYIRIB BO‘LMAYDI", "monotonik deque"],
      ["mediana", "ayirib bo‘lmaydi", "ikkita heap"],
    ],
    captionUz: "To‘rtinchi qator bu bo‘limning eng muhim tuzog‘i: maksimumni «orqaga qaytarib» bo‘lmaydi, chunki chiqqan element maksimum bo‘lsa, keyingisi kim ekanini bilmaymiz.",
    captionEn: "The fourth row is this track's most important trap: a maximum cannot be “undone”, because if the departing element was the maximum, nothing tells you what the next one is." },
  { t: "note", kind: "warn",
    uz: "Maksimum uchun har oynada qayta hisoblash O(n·k) beradi va katta k da TLE. To‘g‘ri yechim — monotonik deque, va u 6-bosqichda batafsil ko‘riladi. Bu «oynada nima kuzatish mumkin?» degan savol bu bo‘limning asosiy chizig‘i.",
    en: "Recomputing the maximum for each window is O(n·k) and gives TLE for large k. The correct tool is a monotonic deque, covered in stage 6. The question “what can a window track?” is this track's main thread." },
  { t: "code", cpp: "// har xil elementlar soni: chastota massivi bilan\nif (--cnt[a[r - k]] == 0) --distinct;      // chiqdi\nif (++cnt[a[r]] == 1)     ++distinct;      // kirdi",
    captionUz: "Nolga tushgan va birga ko‘tarilgan paytlarni tekshirish — «har xil elementlar soni» ni O(1) da yuritishning butun hiylasi.",
    captionEn: "Testing for the drop to zero and the rise to one is the whole trick for maintaining a distinct-element count in O(1)." },
  { t: "exercise",
    qUz: "Oynada MAKSIMUMNI kuzatish uchun multiset ishlatish mumkinmi? Narxi qancha?",
    qEn: "Can a multiset be used to track the window MAXIMUM? What does it cost?",
    aUz: "Ha, mumkin va bu eng oson yechim: kirgan elementni insert, chiqqanni erase(find(...)), maksimum esa *ms.rbegin(). Narx O(n log k) — monotonik deque ning O(n) sidan sekinroq, lekin yozish ancha oson va ko‘p masalalarda yetarli. Diqqat: erase(qiymat) BARCHA nusxalarni o‘chiradi, shuning uchun albatta erase(find(qiymat)) yozing — bu klassik xato.",
    aEn: "Yes, and it is the easiest solution: insert the entering element, erase(find(...)) the leaving one, and read the maximum as *ms.rbegin(). The cost is O(n log k), slower than the monotonic deque's O(n) but much easier to write and sufficient for many problems. One caution: erase(value) removes ALL copies, so always write erase(find(value)) — a classic bug." },
 ]},
]},
/* ── 5. O'zgaruvchan oyna ────────────────────────────────────────────── */
"two-pointers-5": { sections: [
 { titleUz: "Oyna cho‘ziladi va qisqaradi", titleEn: "The window stretches and shrinks", blocks: [
  { t: "p",
    uz: "Endi eng ko‘p ishlatiladigan shakl. Oyna uzunligi QAT’IY EMAS: o‘ng chegara har doim oldinga siljiydi, chap chegara esa shart buzilganda «quvib yetadi». Masala odatda shunday qo‘yiladi: «shartni buzmaydigan ENG UZUN segment».",
    en: "Now the most-used form. The window's length is NOT fixed: the right edge always advances, and the left edge catches up whenever the constraint breaks. The question is usually “the LONGEST segment that does not violate the condition”." },
  { t: "sim", titleUz: "Yig‘indisi ≤ 10 bo‘lgan eng uzun segment", titleEn: "The longest segment with sum ≤ 10", frames: [
    { spec: { kind: "window", label: "o‘ngga cho‘zamiz",
        values: [2, 3, 1, 5, 4, 2], l: 0, r: 2, agg: "yig‘indi = 6 ≤ 10 ✓",
        note: "shart bajarilyapti — cho‘zishda davom" },
      uz: "O‘ng chegarani surib, oynani cho‘zamiz. Yig‘indi 6, shart bajarilyapti — davom etamiz. Chap chegara qimirlamaydi.",
      en: "We stretch the window by advancing the right edge. The sum is 6 and the condition holds, so we continue; the left edge does not move." },
    { spec: { kind: "window", label: "5 kirdi: 11 > 10 — SHART BUZILDI",
        values: [2, 3, 1, 5, 4, 2], l: 0, r: 3, agg: "yig‘indi = 11 > 10 ✗", bad: true,
        note: "endi chap chegarani surishimiz kerak" },
      uz: "5 kirgach yig‘indi 11 bo‘ldi — shart buzildi. Endi oynani QISQARTIRAMIZ: chap chegarani o‘ngga surib, shart tiklanguncha elementlarni chiqaramiz.",
      en: "With the 5 inside, the sum reaches 11 and the condition breaks. Now we SHRINK: advance the left edge, removing elements until the condition holds again." },
    { spec: { kind: "window", label: "2 ni chiqardik: 9 ≤ 10 ✓",
        values: [2, 3, 1, 5, 4, 2], l: 1, r: 3, agg: "yig‘indi = 9 ≤ 10 ✓",
        best: [0, 2],
        note: "uzunlik 3 — hozirgi rekord bilan teng" },
      uz: "2 ni chiqardik, yig‘indi 9 — shart tiklandi. Oyna uzunligi 3, bu hozirgi rekord bilan teng. Punktir — eng yaxshi topilgani.",
      en: "Removing the 2 brings the sum to 9 and the condition holds again. The window's length is 3, matching the current record shown by the dashed frame." },
    { spec: { kind: "window", label: "davom etamiz: 4 kirdi",
        values: [2, 3, 1, 5, 4, 2], l: 2, r: 4, agg: "yig‘indi = 10 ≤ 10 ✓",
        best: [2, 4],
        note: "yana uzunlik 3" },
      uz: "4 kirgach yana qisqartirish kerak bo‘ldi, va oyna [2, 4] bo‘lib qoldi — yig‘indi aynan 10, shart chegarada bajarilyapti.",
      en: "Adding the 4 forced another shrink, leaving the window at [2, 4] with a sum of exactly 10 — the condition holds, just barely." },
    { spec: { kind: "window", label: "yakun: har ko‘rsatkich n qadam yurdi",
        values: [2, 3, 1, 5, 4, 2], l: 3, r: 5, agg: "eng uzun segment = 3",
        note: "l va r ikkalasi ham faqat OLDINGA" },
      uz: "Yakuniy javob 3. Muhimi: l va r ikkalasi ham faqat OLDINGA yurdi va har biri ko‘pi bilan n qadam qildi. Shuning uchun ichki while sikliga qaramay, umumiy narx O(n).",
      en: "The final answer is 3. What matters: both l and r only ever moved FORWARD, each at most n steps. So despite the inner while loop, the total cost is O(n)." },
  ]},
  { t: "codewalk", code: "int l = 0, best = 0;\nlong long sum = 0;\n\nfor (int r = 0; r < n; ++r) {\n    sum += a[r];                       // KENGAYTIRISH\n    while (sum > S) sum -= a[l++];     // QISQARTIRISH\n    best = max(best, r - l + 1);       // hisobga olish\n}",
    notes: [
      { from: 5, uz: "Har iteratsiyada r bitta oldinga. Bu qat’iy: o‘ng chegara HECH QACHON orqaga qaytmaydi va hech qachon to‘xtamaydi.",
        en: "Each iteration advances r by one. This is unconditional: the right edge never goes back and never pauses." },
      { from: 6, uz: "while, if EMAS. Bitta yangi element bir nechta eskisini chiqarib yuborishi mumkin — masalan katta son kirganda.",
        en: "A while, not an if: one new element can force out several old ones, for instance when a large value enters." },
      { from: 6, uz: "Nega bu O(n²) emas? Chunki l ham faqat oldinga yuradi va jami n dan ko‘p siljiy olmaydi. Ichki sikl iteratsiyalarining UMUMIY soni n dan oshmaydi — bu amortizatsiyalangan tahlil, 11-bosqichning mavzusi.",
        en: "Why is this not O(n²)? Because l also only moves forward and cannot shift more than n times in total. The TOTAL number of inner iterations is bounded by n — an amortised argument, and the subject of stage 11." },
      { from: 7, uz: "r − l + 1 — oyna uzunligi. Uni QISQARTIRISHDAN KEYIN hisoblash shart, aks holda yaroqsiz oynani hisobga olib qo‘yasiz.",
        en: "r − l + 1 is the window length, and it must be measured AFTER the shrink, or you record a window that violates the condition." },
    ]},
  { t: "note", kind: "warn",
    uz: "Bu texnika MANFIY sonlarda ISHLAMAYDI. Sabab: manfiy son qo‘shilsa, yig‘indi KAMAYISHI mumkin, ya’ni «cho‘zish yig‘indini oshiradi» degan farazimiz buziladi. Manfiylar bo‘lsa prefiks yig‘indi + map ishlating (8-bosqich).",
    en: "This technique FAILS with NEGATIVE numbers, because adding one can DECREASE the sum, breaking the assumption that stretching only increases it. With negatives, use prefix sums with a map (stage 8)." },
 ]},
 { titleUz: "O‘zgaruvchan oynaning ikki turi", titleEn: "The two kinds of variable window", blocks: [
  { t: "p",
    uz: "Ikkita ko‘rinishni ajratib olish kerak, chunki ular kod jihatidan biroz farq qiladi va ularni chalkashtirish tez-tez uchraydi.",
    en: "Two variants must be told apart: they differ slightly in code and confusing them is a frequent mistake." },
  { t: "table", headUz: ["", "Eng UZUN", "Eng QISQA"], headEn: ["", "LONGEST", "SHORTEST"],
    rows: [
      ["savol", "shartni buzmaydigan eng uzun", "shartni bajaradigan eng qisqa"],
      ["qisqartirish", "shart BUZILGANDA", "shart BAJARILGANDA"],
      ["javobni olish", "qisqartirishdan keyin", "qisqartirish ichida"],
      ["misol", "yig‘indi ≤ S", "yig‘indi ≥ S"],
    ],
    captionUz: "Ikkinchi va uchinchi qatorlar — butun farq. «Eng qisqa» da javobni while ICHIDA olasiz.",
    captionEn: "Rows two and three are the whole difference. For the SHORTEST variant you record the answer INSIDE the while." },
  { t: "code", cpp: "// eng QISQA: yig'indi >= S bo'lgan eng qisqa segment\nint l = 0, best = INT_MAX;\nlong long sum = 0;\nfor (int r = 0; r < n; ++r) {\n    sum += a[r];\n    while (sum >= S) {                          // shart BAJARILGANDA\n        best = min(best, r - l + 1);            // javobni ICHKARIDA olamiz\n        sum -= a[l++];\n    }\n}",
    captionUz: "Ikkita farq: while sharti teskari, va best ni while ichida yangilaymiz. Bu ikkitasini chalkashtirish eng ko‘p uchraydigan xato.",
    captionEn: "Two differences: the while condition is inverted, and best is updated inside it. Mixing these up is the commonest error." },
  { t: "note", kind: "key",
    uz: "Umumiy qoida: while sikli oynani YAROQLI holatga keltirish uchun ishlaydi. «Eng uzun» da yaroqlilik — shartni buzmaslik, shuning uchun buzilganda qisqartiramiz. «Eng qisqa» da esa biz yaroqli oynani topgan zahoti uni QISQARTIRISHGA urinamiz, chunki kichikroq javob qidiryapmiz.",
    en: "The general rule: the while loop exists to restore VALIDITY. For LONGEST, validity means not violating the condition, so we shrink when it breaks. For SHORTEST, the moment a valid window appears we try to SHRINK it, because we are looking for a smaller answer." },
  { t: "exercise",
    qUz: "«Yig‘indisi aynan S ga teng eng uzun segment» — bu oyna bilan yechiladimi?",
    qEn: "“The longest segment with sum exactly S” — can a sliding window solve it?",
    aUz: "Faqat barcha sonlar musbat bo‘lsa. U holda yig‘indi oyna cho‘zilganda qat’iy o‘sadi, shuning uchun «≥ S bo‘lguncha cho‘z, > S bo‘lsa qisqart, == S bo‘lsa hisobga ol» ishlaydi. Agar nol yoki manfiy sonlar bo‘lsa — YO‘Q, chunki monotonlik yo‘qoladi. Bu holda prefiks yig‘indi va map kerak: pre[r] − pre[l−1] = S, ya’ni pre[l−1] = pre[r] − S ni map dan qidiramiz. 8-bosqichda batafsil.",
    aEn: "Only if every number is positive. Then the sum strictly increases as the window stretches, so “stretch until ≥ S, shrink while > S, record when == S” works. With zeros or negatives it does NOT, because monotonicity is lost, and you need prefix sums with a map instead: pre[r] − pre[l−1] = S means looking up pre[r] − S. Stage 8 covers it." },
 ]},
]},

/* ── 6. Oynada monotonik deque: min/max ──────────────────────────────── */
"two-pointers-6": { sections: [
 { titleUz: "Maksimumni «orqaga qaytarib» bo‘lmaydi", titleEn: "A maximum cannot be undone", blocks: [
  { t: "p",
    uz: "4-bosqichda ko‘rgan muammoga qaytamiz: yig‘indini oynadan chiqarish oson (ayirasiz), lekin MAKSIMUMNI chiqarib bo‘lmaydi. Agar chiqib ketgan element maksimum bo‘lsa, keyingi maksimum kim ekanini bilmaymiz.",
    en: "Back to the problem from stage 4: removing an element from a sum is easy (you subtract), but a MAXIMUM cannot be removed. If the departing element was the maximum, nothing tells you what the next one is." },
  { t: "note", kind: "key",
    uz: "Yechim: oynadagi barcha elementlarni saqlamaymiz, faqat MAKSIMUMGA NOMZOD bo‘la oladiganlarini saqlaymiz. Agar x elementi y dan chapda va x ≤ y bo‘lsa, x HECH QACHON maksimum bo‘lolmaydi — chunki y oynada x dan uzoqroq turadi. Demak x ni butunlay tashlab yuborish mumkin.",
    en: "The fix: do not keep every element of the window, only those that can still BECOME the maximum. If x sits to the left of y and x ≤ y, then x can NEVER be the maximum, because y stays in the window longer than x does. So x can be discarded outright." },
  { t: "sim", titleUz: "Deque kamayuvchi tartibda", titleEn: "The deque stays decreasing", frames: [
    { spec: { kind: "bars", label: "massiv va uzunligi 3 bo‘lgan oyna",
        values: [3, 1, 4, 1, 5, 2],
        brace: [{ from: 0, to: 2, text: "oyna" }],
        note: "har oynadagi maksimumni topmoqchimiz" },
      uz: "Massiv va uzunligi 3 bo‘lgan siljuvchi oyna. Har oyna uchun maksimumni O(1) da topmoqchimiz.",
      en: "An array and a sliding window of length 3. We want each window's maximum in O(1)." },
    { spec: { kind: "queue", label: "deque: [3] — birinchi element",
        items: [3], front: 0, back: 0,
        note: "indekslarni saqlaymiz, qiymatlarni emas" },
      uz: "Deque ga 3 ni qo‘yamiz. Diqqat: aslida INDEKSLARNI saqlaymiz, chunki keyin «bu element oynadan chiqdimi?» deb tekshirish kerak bo‘ladi.",
      en: "Push the 3 into the deque. In practice we store INDICES, because later we must ask “has this element left the window?”." },
    { spec: { kind: "queue", label: "1 keldi: 3 dan kichik — orqaga qo‘shiladi",
        items: [3, 1], front: 0, back: 1,
        note: "kamayuvchi tartib saqlanmoqda" },
      uz: "1 keldi va u 3 dan kichik — hech kimni chiqarmaydi, shunchaki orqaga qo‘shiladi. Deque kamayuvchi tartibda: [3, 1].",
      en: "The 1 arrives and, being smaller than 3, evicts nobody — it is simply appended. The deque stays decreasing: [3, 1]." },
    { spec: { kind: "queue", label: "4 keldi: 1 va 3 ni chiqarib tashlaydi",
        items: [4], front: 0, back: 0,
        note: "4 dan kichiklar endi hech qachon maksimum bo‘lolmaydi" },
      uz: "4 keldi — u 1 dan ham, 3 dan ham katta. Ikkalasi ham endi hech qachon maksimum bo‘lolmaydi (4 oynada ulardan uzoqroq turadi), shuning uchun ikkalasini ORQADAN chiqarib tashlaymiz. Deque: [4].",
      en: "The 4 arrives, larger than both the 1 and the 3. Neither can ever be the maximum again (the 4 outlives them in the window), so both are popped from the BACK. The deque is now [4]." },
    { spec: { kind: "queue", label: "oynadan chiqqanini OLDIDAN olamiz",
        items: [5, 2], front: 0, back: 1,
        note: "har element bir marta kiradi, bir marta chiqadi → O(n)" },
      uz: "Oyna siljiganda oldingi elementlar chiqib ketadi — ularni deque ning OLDIDAN olamiz (agar ular hali u yerda bo‘lsa). Maksimum har doim deque ning oldida turadi. Har element deque ga bir marta kiradi va bir marta chiqadi, shuning uchun umumiy narx O(n).",
      en: "As the window slides, elements fall off the left — we pop them from the FRONT if they are still there. The maximum always sits at the front. Each element enters and leaves the deque once, so the total cost is O(n)." },
  ]},
  { t: "codewalk", code: "deque<int> dq;                       // INDEKSLAR, kamayuvchi qiymatlar bo'yicha\nfor (int r = 0; r < n; ++r) {\n    while (!dq.empty() && dq.front() <= r - k) dq.pop_front();   // oynadan chiqdi\n    while (!dq.empty() && a[dq.back()] <= a[r]) dq.pop_back();   // keraksiz\n    dq.push_back(r);\n    if (r >= k - 1) answer[r - k + 1] = a[dq.front()];           // maksimum\n}",
    notes: [
      { from: 1, uz: "Deque da INDEKSLAR saqlanadi, qiymatlar emas. Faqat indeks bilan «bu element oynadan chiqib ketdimi?» degan savolga javob berish mumkin.",
        en: "The deque stores INDICES, not values. Only an index lets you answer “has this element left the window?”." },
      { from: 3, uz: "Birinchi while — oynadan chiqib ketganlarni tozalash. Bu OLDIDAN bo‘ladi, chunki eng eski element eng oldinda.",
        en: "The first while clears elements that have left the window, popping from the FRONT because the oldest sits there." },
      { from: 4, uz: "Ikkinchi while — «keraksizlarni» tozalash. Bu ORQADAN bo‘ladi va aynan shu deque ni monoton ushlab turadi. <= belgisi teng elementlarni ham chiqaradi; agar teng qiymatlar bir necha marta kerak bo‘lsa < ishlating.",
        en: "The second while removes the useless candidates, popping from the BACK, and this is what keeps the deque monotonic. The <= also evicts equal values; use < if equal values must be kept separately." },
      { from: 6, uz: "if (r >= k − 1) — oyna to‘lgandan keyingina javob yozamiz. Buni unutish massivning boshida noto‘g‘ri javoblar beradi.",
        en: "The if (r >= k − 1) guard records an answer only once the window is full. Forgetting it produces wrong answers at the start of the array." },
    ]},
 ]},
 { titleUz: "Monotonik deque qayerda kerak", titleEn: "Where a monotonic deque is needed", blocks: [
  { t: "table", headUz: ["Vosita", "Narx", "Qachon"], headEn: ["Tool", "Cost", "When"],
    rows: [
      ["monotonik deque", "O(n)", "faqat min yoki max kerak"],
      ["multiset", "O(n log k)", "yozish oson, boshqa so‘rovlar ham"],
      ["sparse table", "O(n log n) + O(1)", "oyna emas, ixtiyoriy oraliq"],
      ["segment tree", "O(n log n)", "o‘zgaruvchan massiv"],
      ["ikkita stek", "O(n)", "deque o‘rniga, ba’zan qulayroq"],
    ],
    captionUz: "Birinchi qator eng tez, lekin faqat bitta narsani (min yoki max) bera oladi. Ikkinchisi sekinroq, lekin ancha moslashuvchan.",
    captionEn: "The first row is fastest but yields only one thing, a minimum or a maximum. The second is slower and far more flexible." },
  { t: "note", kind: "tip",
    uz: "Monotonik deque faqat oyna uchun emas. U «keyingi kattaroq element», «gistogrammadagi eng katta to‘rtburchak», «DP o‘tishini tezlashtirish» masalalarida ham asosiy vosita. Stringlar bo‘limidagi monoton stek bilan bir xil g‘oya, faqat ikki tomonlama.",
    en: "The monotonic deque is not only for windows. It is the main tool for “next greater element”, “largest rectangle in a histogram” and speeding up DP transitions. It is the same idea as the monotonic stack from the strings track, made double-ended." },
  { t: "code", cpp: "// DP ni tezlashtirish: dp[i] = max(dp[i-k..i-1]) + a[i]\nwhile (!dq.empty() && dq.front() < i - k) dq.pop_front();\ndp[i] = (dq.empty() ? 0 : dp[dq.front()]) + a[i];\nwhile (!dq.empty() && dp[dq.back()] <= dp[i]) dq.pop_back();\ndq.push_back(i);",
    captionUz: "Aynan o‘sha kod, faqat a[] o‘rniga dp[] bo‘yicha. O(n·k) ni O(n) ga tushiradi.",
    captionEn: "The very same code, applied to dp[] instead of a[]. It turns O(n·k) into O(n)." },
  { t: "exercise",
    qUz: "Nima uchun deque dagi elementlar har doim kamayuvchi tartibda bo‘ladi?",
    qEn: "Why are the deque's elements always in decreasing order?",
    aUz: "Chunki biz uni SHUNDAY ushlab turamiz: yangi element kelganda undan kichik yoki teng bo‘lgan barcha elementlarni orqadan chiqarib tashlaymiz. Demak qo‘shishdan keyin ham tartib buzilmaydi — bu INVARIANT. Va invariantning foydasi shu: kamayuvchi ketma-ketlikning eng katta elementi har doim ENG OLDIDA turadi, ya’ni maksimumni O(1) da o‘qish mumkin. Monoton tuzilmalarning butun mantig‘i shu: invariantni saqlash uchun keraksizlarni tashlaymiz, evaziga so‘rov O(1) bo‘ladi.",
    aEn: "Because we deliberately maintain it: when a new element arrives we pop every element from the back that is smaller than or equal to it, so the order survives the insertion — that is the INVARIANT. And its benefit is that the largest element of a decreasing sequence always sits at the FRONT, making the maximum an O(1) read. That is the whole logic of monotonic structures: discard what can never matter, and queries become constant time." },
 ]},
]},

/* ── 7. «Aynan K» ni «ko'pi bilan K» orqali ──────────────────────────── */
"two-pointers-7": { sections: [
 { titleUz: "Nega «aynan K» qiyin", titleEn: "Why “exactly K” is hard", blocks: [
  { t: "p",
    uz: "Oyna texnikasi «ko‘pi bilan K» tipidagi shartlar bilan ajoyib ishlaydi, chunki bunday shart MONOTON: oynani qisqartirsak, shart faqat yaxshilanadi. Lekin «AYNAN K» sharti monoton emas — qisqartirish uni ham buzishi mumkin.",
    en: "The window technique works beautifully with “at most K” conditions, because such a condition is MONOTONE: shrinking the window can only help. But “EXACTLY K” is not monotone — shrinking can break it too." },
  { t: "note", kind: "key",
    uz: "Yechim ajoyib darajada sodda va u butun bir masalalar sinfini yopadi: aynan(K) = ko‘pi bilan(K) − ko‘pi bilan(K−1). Ikkita oddiy oyna yuritamiz va natijalarini ayiramiz. Har bittasi O(n), jami ham O(n).",
    en: "The fix is beautifully simple and covers an entire class of problems: exactly(K) = atMost(K) − atMost(K−1). Run two ordinary windows and subtract the results. Each is O(n), and so is the pair." },
  { t: "sim", titleUz: "Ikkita oyna, bitta ayirma", titleEn: "Two windows, one subtraction", frames: [
    { spec: { kind: "bars", label: "masala: aynan 2 xil element bo‘lgan segmentlar soni",
        values: [1, 2, 1, 3, 2],
        note: "«aynan 2 xil» — to‘g‘ridan-to‘g‘ri qiyin" },
      uz: "Masala: nechta segmentda AYNAN 2 xil element bor? To‘g‘ridan-to‘g‘ri oyna bilan yechish qiyin, chunki shart monoton emas.",
      en: "The problem: how many segments contain EXACTLY two distinct elements? A direct window is hard, because the condition is not monotone." },
    { spec: { kind: "window", label: "1-oyna: ko‘pi bilan 2 xil",
        values: [1, 2, 1, 3, 2], l: 0, r: 2, agg: "≤ 2 xil ✓ → 3 ta segment",
        note: "har r uchun r − l + 1 ta segment qo‘shamiz" },
      uz: "Birinchi oyna: «ko‘pi bilan 2 xil element». Bu shart MONOTON — qisqartirish har doim yordam beradi. Har r uchun r − l + 1 ta segment qo‘shamiz (o‘ng uchi r bo‘lgan barcha yaroqli segmentlar).",
      en: "The first window: “at most two distinct elements”. That condition IS monotone, so shrinking always helps. For each r we add r − l + 1 segments — all the valid ones ending at r." },
    { spec: { kind: "window", label: "2-oyna: ko‘pi bilan 1 xil",
        values: [1, 2, 1, 3, 2], l: 2, r: 2, agg: "≤ 1 xil ✓ → 1 ta segment",
        note: "aynan o‘sha kod, K = 1 bilan" },
      uz: "Ikkinchi oyna: «ko‘pi bilan 1 xil». Aynan o‘sha kod, faqat K = 1. Hech narsa o‘zgartirilmaydi — funksiyani ikki marta chaqirasiz.",
      en: "The second window: “at most one distinct element” — the very same code with K = 1. Nothing is modified; you simply call the function twice." },
    { spec: { kind: "bars", label: "ayirma: aynan 2 xil",
        values: [9, 5, 4],
        brace: [{ from: 2, to: 2, text: "javob" }],
        note: "9 − 5 = 4" },
      uz: "«Ko‘pi bilan 2» 9 ta segment berdi, «ko‘pi bilan 1» 5 ta. Ayirma 4 — bu AYNAN 2 xil element bo‘lgan segmentlar soni. Sabab ravshan: «ko‘pi bilan 2» to‘plamidan «ko‘pi bilan 1» to‘plamini ayirsak, aynan «2 xil» qoladi.",
      en: "“At most two” gave nine segments and “at most one” gave five. The difference, four, is the number with EXACTLY two distinct elements — because subtracting the “at most one” set from the “at most two” set leaves precisely those with two." },
  ]},
  { t: "code", cpp: "long long atMost(int K) {\n    int l = 0, distinct = 0;\n    long long cnt = 0;\n    vector<int> freq(MAXV, 0);\n    for (int r = 0; r < n; ++r) {\n        if (freq[a[r]]++ == 0) ++distinct;\n        while (distinct > K)\n            if (--freq[a[l++]] == 0) --distinct;\n        cnt += r - l + 1;                  // o'ng uchi r bo'lgan segmentlar\n    }\n    return cnt;\n}\nlong long exactly = atMost(K) - atMost(K - 1);",
    captionUz: "cnt += r − l + 1 — bu naqshning yuragi: har r uchun o‘ng uchi r bo‘lgan BARCHA yaroqli segmentlarni birdan sanaymiz.",
    captionEn: "cnt += r − l + 1 is the heart of the pattern: for each r we count ALL valid segments ending at r in one step." },
  { t: "note", kind: "warn",
    uz: "atMost funksiyasini ikki marta chaqirganda freq massivini QAYTA TOZALASH kerak. Uni funksiya ichida e’lon qilish eng xavfsiz yo‘l; global massiv ishlatsangiz, tozalashni unutish jimgina noto‘g‘ri javob beradi.",
    en: "Calling atMost twice means the freq array must be RESET. Declaring it inside the function is the safest option; with a global array, forgetting to clear it silently produces a wrong answer." },
 ]},
 { titleUz: "Naqshning kengroq qo‘llanishi", titleEn: "The pattern's wider use", blocks: [
  { t: "table", headUz: ["Masala", "Qanday ayiriladi"], headEn: ["Problem", "How to subtract"],
    rows: [
      ["aynan K xil element", "atMost(K) − atMost(K−1)"],
      ["aynan K ta toq son", "atMost(K) − atMost(K−1)"],
      ["yig‘indisi aynan S", "prefiks + map (oyna emas)"],
      ["aynan K marta uchraydi", "atMost(K) − atMost(K−1)"],
      ["[L, R] oralig‘idagi qiymatlar", "atMost(R) − atMost(L−1)"],
    ],
    captionUz: "Beshinchi qator o‘sha g‘oyaning boshqa shakli — bu «prefiks ayirmasi» tamoyili, u butun CP bo‘ylab uchraydi.",
    captionEn: "The fifth row is the same idea in another guise — the prefix-difference principle, which recurs throughout competitive programming." },
  { t: "p",
    uz: "Uchinchi qatorga e’tibor bering: u ISTISNO. «Yig‘indisi aynan S» ni oyna bilan yechib bo‘lmaydi, chunki manfiy sonlar bo‘lsa monotonlik yo‘q. Lekin agar barcha sonlar musbat bo‘lsa, atMost(S) − atMost(S−1) hiylasi bu yerda ham ishlaydi.",
    en: "Note the third row: it is the EXCEPTION. “Sum exactly S” cannot be done with a window, because with negatives there is no monotonicity. But if every number is positive, the atMost(S) − atMost(S−1) trick works here too." },
  { t: "note", kind: "tip",
    uz: "Bu naqshni tanib olish belgisi — masalada «AYNAN» so‘zi. Uni ko‘rsangiz darhol so‘rang: «ko‘pi bilan» varianti oyna bilan yechiladimi? Agar ha bo‘lsa, ikkita chaqiruv va bitta ayirma — masala tugadi.",
    en: "The signal for this pattern is the word “EXACTLY” in the statement. On seeing it, immediately ask whether the “at most” version yields to a window. If it does, two calls and one subtraction finish the problem." },
  { t: "exercise",
    qUz: "«Aynan K xil element» uchun atMost(K) − atMost(K−1) formulasi nima uchun to‘g‘ri ekanini isbotlang.",
    qEn: "Prove that atMost(K) − atMost(K−1) is correct for “exactly K distinct elements”.",
    aUz: "atMost(K) — bu 0, 1, 2, …, K xil elementli segmentlar sonining YIG‘INDISI. atMost(K−1) esa 0 dan K−1 gacha. Ayirsak, faqat «aynan K xil» qoladi. Formal: atMost(K) = Σ(i = 0..K) exactly(i), demak atMost(K) − atMost(K−1) = exactly(K). Bu «teleskopik ayirma» tamoyili va u prefiks yig‘indilar bilan bir xil g‘oya — shuning uchun jadvalning oxirgi qatori ham shu naqshga tegishli.",
    aEn: "atMost(K) is the SUM of the counts of segments with 0, 1, 2, …, K distinct elements, while atMost(K−1) sums 0 through K−1. Subtracting leaves exactly K. Formally atMost(K) = Σ over i = 0..K of exactly(i), so atMost(K) − atMost(K−1) = exactly(K). This is the telescoping-difference principle, the same idea as prefix sums — which is why the table's last row belongs to the same pattern." },
 ]},
]},

/* ── 8. Prefix bilan birga ───────────────────────────────────────────── */
"two-pointers-8": { sections: [
 { titleUz: "Oyna ishlamaganda", titleEn: "When the window does not work", blocks: [
  { t: "p",
    uz: "Bu bosqich oldingi bosqichlar qoldirgan bo‘shliqni to‘ldiradi. Oyna texnikasi MANFIY sonlarda ishlamaydi, chunki «cho‘zish yig‘indini oshiradi» degan faraz buziladi. Lekin masalalar ko‘pincha aynan manfiy sonlar bilan beriladi.",
    en: "This stage fills the gap the previous ones left. The window technique fails with NEGATIVE numbers, because the assumption “stretching increases the sum” breaks — and problems are often posed with negatives on purpose." },
  { t: "note", kind: "key",
    uz: "Yechim — PREFIKS YIG‘INDI va MAP. [l, r] oralig‘ining yig‘indisi pre[r+1] − pre[l] ga teng. Demak «yig‘indisi S bo‘lgan oraliq bormi?» savoli «pre[r+1] − S qiymatiga teng pre[l] bormi?» ga aylanadi — va bu map dan qidirish, ya’ni O(1).",
    en: "The answer is PREFIX SUMS with a MAP. The sum of [l, r] equals pre[r+1] − pre[l], so “is there a range summing to S?” becomes “is there a pre[l] equal to pre[r+1] − S?” — a map lookup, that is O(1)." },
  { t: "sim", titleUz: "Prefiks yig‘indi va map", titleEn: "Prefix sums and a map", frames: [
    { spec: { kind: "dptable", label: "massiv va prefiks yig‘indilar",
        rows: [["a", "3", "−1", "2", "−4", "5"], ["pre", "3", "2", "4", "0", "5"]],
        done: [[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]],
        note: "pre[i] = a[0] + … + a[i]" },
      uz: "Massivda manfiy sonlar bor, shuning uchun oyna ishlamaydi. Prefiks yig‘indilarni hisoblaymiz: pre[i] = birinchi i + 1 ta element yig‘indisi. E’tibor bering, pre monoton EMAS — u kamayishi ham mumkin.",
      en: "The array has negatives, so a window will not do. We compute prefix sums, pre[i] being the sum of the first i + 1 elements. Note that pre is NOT monotone — it can decrease." },
    { spec: { kind: "hashtable", label: "map: qaysi prefiks qiymatlar uchradi",
        slots: [["0 → 1 marta"], ["3 → 1"], ["2 → 1"], null, null],
        hi: [0],
        note: "boshida map ga 0 ni qo‘yamiz" },
      uz: "Map da har prefiks qiymat necha marta uchraganini saqlaymiz. MUHIM: boshida map ga 0 ni qo‘yamiz — bu «bo‘sh prefiks» ni ifodalaydi va massiv boshidan boshlanuvchi oraliqlarni topish imkonini beradi.",
      en: "The map records how often each prefix value has occurred. IMPORTANT: seed it with 0, representing the empty prefix, so that ranges starting at the very beginning can be found." },
    { spec: { kind: "hashtable", label: "S = 1 qidiryapmiz: pre[r] − 1 bormi?",
        slots: [["0"], ["3"], ["2"], null, ["4 ← hozir"]],
        hi: [2],
        note: "pre = 3 va S = 1 → 2 ni qidiramiz — bor!" },
      uz: "Hozirgi prefiks 3 va biz yig‘indisi 1 bo‘lgan oraliq qidiryapmiz. Demak map dan 3 − 1 = 2 ni qidiramiz. U bor — demak yig‘indisi 1 bo‘lgan oraliq topildi.",
      en: "The current prefix is 3 and we want a range summing to 1, so we look up 3 − 1 = 2 in the map. It is there, so a range summing to 1 exists." },
    { spec: { kind: "dptable", label: "topilgan oraliq",
        rows: [["a", "3", "−1", "2", "−4", "5"], ["pre", "3", "2", "4", "0", "5"]],
        path: [[1, 3], [1, 4]],
        note: "har element bir marta ko‘rildi → O(n)" },
      uz: "Topilgan oraliq: pre farqidan kelib chiqadi. Butun algoritm bitta yurishda ishlaydi va har element bir marta ko‘riladi — O(n) vaqt, O(n) xotira (map uchun).",
      en: "The range follows from the difference of prefixes. The whole algorithm is a single pass touching each element once — O(n) time and O(n) memory for the map." },
  ]},
  { t: "codewalk", code: "unordered_map<long long, int> seen;\nseen[0] = 1;                          // BO'SH prefiks — majburiy\nlong long pre = 0, cnt = 0;\n\nfor (int i = 0; i < n; ++i) {\n    pre += a[i];\n    cnt += seen[pre - S];             // yig'indisi S bo'lgan oraliqlar\n    ++seen[pre];\n}",
    notes: [
      { from: 2, uz: "seen[0] = 1 — eng ko‘p unutiladigan qator. Usiz massiv BOSHIDAN boshlanuvchi oraliqlar topilmaydi, va javob kam chiqadi.",
        en: "seen[0] = 1 is the most forgotten line. Without it, ranges starting at the very beginning are never found and the answer comes out too small." },
      { from: 7, uz: "TARTIB muhim: avval qidiramiz, keyin qo‘shamiz. Aks holda S = 0 bo‘lganda oraliqning o‘zini o‘zi bilan hisoblab yuboramiz.",
        en: "The ORDER matters: look up first, then insert. Otherwise, when S = 0, an element is matched against itself." },
      { from: 8, uz: "++seen[pre] — hozirgi prefiksni ro‘yxatga qo‘shamiz, u keyingi indekslar uchun nomzod bo‘ladi.",
        en: "++seen[pre] registers the current prefix so it can serve as a candidate for later indices." },
    ]},
 ]},
 { titleUz: "Oyna yoki prefiks — qaysi biri", titleEn: "Window or prefix: which one", blocks: [
  { t: "table", headUz: ["Vaziyat", "Vosita", "Nega"], headEn: ["Situation", "Tool", "Why"],
    rows: [
      ["barcha sonlar musbat, «≤ S»", "oyna", "monotonlik bor"],
      ["manfiy sonlar bor", "prefiks + map", "monotonlik yo‘q"],
      ["«aynan S»", "prefiks + map", "shart monoton emas"],
      ["«eng uzun, yig‘indi ≤ S», musbat", "oyna", "O(n), xotira O(1)"],
      ["«nechta oraliq, yig‘indi = S»", "prefiks + map", "sanash uchun ideal"],
      ["2D matritsada", "prefiks + oyna birga", "qatorlarni siqib, 1D ga"],
    ],
    captionUz: "Birinchi ikki qator butun tanlovni belgilaydi: MANFIY SON BORMI degan savol.",
    captionEn: "The first two rows settle the choice entirely: the question is whether NEGATIVES are present." },
  { t: "note", kind: "warn",
    uz: "Prefiks yig‘indilarda OVERFLOW xavfi katta: n = 10⁵ va qiymatlar 10⁹ bo‘lsa, yig‘indi 10¹⁴ ga yetadi. long long ishlating. Bu «ishlaydi, lekin ba’zi testlarda noto‘g‘ri» turidagi eng ko‘p uchraydigan xato.",
    en: "Prefix sums carry a real OVERFLOW risk: with n = 10⁵ and values up to 10⁹ the sum reaches 10¹⁴. Use long long. This is the classic “works, but wrong on some tests” bug." },
  { t: "note", kind: "tip",
    uz: "Oltinchi qator kuchli naqsh: 2D matritsada «yig‘indisi S bo‘lgan to‘rtburchak» masalasini yechish uchun ikkita qator chegarasini qotirasiz, ustunlar bo‘yicha yig‘indini 1D massivga siqasiz, va shu 1D masalani prefiks + map bilan yechasiz. Narx O(n²·m).",
    en: "The sixth row is a powerful pattern: to find a rectangle summing to S in a 2D matrix, fix a pair of row bounds, collapse the columns into a 1D array of sums, and solve that 1D problem with prefix sums and a map. The cost is O(n²·m)." },
  { t: "exercise",
    qUz: "«Yig‘indisi K ga bo‘linadigan eng uzun oraliq» — bu qanday yechiladi?",
    qEn: "“The longest range whose sum is divisible by K” — how is that solved?",
    aUz: "Prefiks yig‘indining QOLDIG‘I bilan. Agar pre[r] % K == pre[l] % K bo‘lsa, ularning ayirmasi (ya’ni [l, r] oralig‘ining yig‘indisi) K ga bo‘linadi. Demak har qoldiq uchun uning ENG BIRINCHI uchragan indeksini map da saqlaymiz va har r da r − birinchi[pre % K] ni hisoblaymiz. Diqqat: C++ da manfiy sonning qoldig‘i manfiy bo‘lishi mumkin, shuning uchun ((pre % K) + K) % K yozing. Va bo‘sh prefiks uchun map[0] = −1 qo‘ying.",
    aEn: "Through the REMAINDER of the prefix sum. If pre[r] % K == pre[l] % K then their difference — the sum of [l, r] — is divisible by K. So store the FIRST index at which each remainder appeared and, at each r, take r − first[pre % K]. Careful: in C++ a negative value's remainder can be negative, so write ((pre % K) + K) % K. And seed the map with map[0] = −1 for the empty prefix." },
 ]},
]},
/* ── 9. Uch ko'rsatkich va k-sum ─────────────────────────────────────── */
"two-pointers-9": { sections: [
 { titleUz: "Bittasini qotirib, qolganiga ikki ko‘rsatkich", titleEn: "Fix one, two-point the rest", blocks: [
  { t: "p",
    uz: "1-bosqichda ikkita elementning yig‘indisini O(n) da topdik. Endi UCHTA element kerak: a[i] + a[j] + a[k] = X. Sodda yechim O(n³). Hiyla oddiy: bitta elementni QOTIRAMIZ va qolgan ikkitasini ikki ko‘rsatkich bilan qidiramiz.",
    en: "In stage 1 we found two elements summing to a target in O(n). Now we need THREE: a[i] + a[j] + a[k] = X. The naive solution is O(n³). The trick is simple: FIX one element and find the other two with two pointers." },
  { t: "math", uz: "3-sum:  n ta i uchun × O(n) ikki ko‘rsatkich  =  O(n²)" },
  { t: "sim", titleUz: "3-sum: nolga teng uchlik", titleEn: "3-sum: a triple summing to zero", frames: [
    { spec: { kind: "array", label: "tartiblangan massiv, target = 0",
        values: [-4, -1, -1, 0, 1, 2],
        ptr: [{ at: 0, text: "i" }],
        note: "i ni qotiramiz: −4 kerak, qolgani +4" },
      uz: "Massivni tartiblaymiz. i = 0 ni qotiramiz: a[i] = −4. Endi qolgan qismda yig‘indisi +4 bo‘lgan juftlik kerak — bu 1-bosqichdagi masala.",
      en: "Sort the array and fix i = 0, so a[i] = −4. In the remaining part we now need a pair summing to +4 — precisely the stage-1 problem." },
    { spec: { kind: "array", label: "qolgan qismda ikki ko‘rsatkich",
        values: [-4, -1, -1, 0, 1, 2],
        ptr: [{ at: 0, text: "i" }, { at: 1, text: "l" }, { at: 5, text: "r" }],
        note: "−1 + 2 = 1 < 4 → l ni suramiz" },
      uz: "l ni i dan keyin, r ni oxirga qo‘yamiz. −1 + 2 = 1, bu 4 dan kichik — l ni o‘ngga suramiz. Ichki qism butunlay 1-bosqichdagi algoritm.",
      en: "Place l just after i and r at the end. −1 + 2 = 1, less than 4, so l moves right. The inner part is exactly the stage-1 algorithm." },
    { spec: { kind: "array", label: "i = 1 ga o‘tamiz",
        values: [-4, -1, -1, 0, 1, 2], hi: [1],
        ptr: [{ at: 1, text: "i" }, { at: 2, text: "l" }, { at: 5, text: "r" }],
        note: "a[i] = −1, endi juftlik +1 berishi kerak" },
      uz: "Birinchi i uchun yechim topilmadi — keyingisiga o‘tamiz. Endi a[i] = −1 va juftlik +1 berishi kerak. Har i uchun ichki qism O(n), demak jami O(n²).",
      en: "No solution for the first i, so we move on. Now a[i] = −1 and the pair must sum to +1. The inner walk is O(n) for each i, so O(n²) overall." },
    { spec: { kind: "array", label: "topildi: −1 + (−1) + 2 = 0",
        values: [-4, -1, -1, 0, 1, 2], hi: [1, 2, 5],
        ptr: [{ at: 1, text: "i" }, { at: 2, text: "l" }, { at: 5, text: "r" }],
        note: "endi TAKRORLARNI o‘tkazib yuborish kerak" },
      uz: "Uchlik topildi. Endi eng nozik qism: agar masala HAR XIL uchliklarni so‘rasa, takrorlarni o‘tkazib yuborish kerak — chunki massivda bir xil qiymatlar bor.",
      en: "A triple is found. Now the subtlest part: if the problem asks for DISTINCT triples, duplicates must be skipped, because the array contains repeated values." },
  ]},
  { t: "codewalk", code: "sort(a.begin(), a.end());\nfor (int i = 0; i + 2 < n; ++i) {\n    if (i > 0 && a[i] == a[i-1]) continue;        // i bo'yicha takror\n    int l = i + 1, r = n - 1;\n    while (l < r) {\n        long long s = a[i] + a[l] + a[r];\n        if (s == 0) {\n            report(i, l, r);\n            while (l < r && a[l] == a[l+1]) ++l;  // l bo'yicha takror\n            while (l < r && a[r] == a[r-1]) --r;  // r bo'yicha takror\n            ++l; --r;\n        }\n        else if (s < 0) ++l;\n        else --r;\n    }\n}",
    notes: [
      { from: 3, uz: "i bo‘yicha takrorni o‘tkazish: a[i] == a[i−1] bo‘lsa, bu i allaqachon ko‘rilgan uchliklarni beradi. Bu qatorsiz javob takrorlar bilan to‘lib ketadi.",
        en: "Skipping duplicates in i: if a[i] == a[i−1], this i produces triples already reported. Without this line the answer fills with repeats." },
      { from: 9, to: 10, uz: "l va r bo‘yicha ham takrorlarni o‘tkazish. Uchta joyda uchta tekshiruv — va ularning barchasi kerak. 3-sum masalasining butun qiyinligi shu takrorlarda.",
        en: "Duplicates must be skipped for l and r as well: three places, three checks, and all of them are needed. The whole difficulty of 3-sum lies in these duplicates." },
      { from: 11, uz: "++l; --r; — yechim topilgandan keyin IKKALASINI ham surish shart. Faqat bittasini sursangiz, o‘sha juftlikni qayta topasiz va cheksiz sikl bo‘lishi mumkin.",
        en: "After a hit, BOTH pointers must advance. Moving only one refinds the same pair, and can loop forever." },
    ]},
  { t: "note", kind: "key",
    uz: "Umumiy qoida: k-sum masalasini (k−1)-sum ga keltirish mumkin — bitta elementni qotirib, qolganini rekursiv yechish. Narx: 2-sum O(n), 3-sum O(n²), 4-sum O(n³). Har qo‘shimcha element bitta n omilini qo‘shadi.",
    en: "The general rule: k-sum reduces to (k−1)-sum by fixing one element and solving the rest recursively. The costs: 2-sum O(n), 3-sum O(n²), 4-sum O(n³) — each extra element adds one factor of n." },
 ]},
 { titleUz: "Tezroq variantlar", titleEn: "Faster variants", blocks: [
  { t: "table", headUz: ["Masala", "Ikki ko‘rsatkich", "Boshqa yo‘l"], headEn: ["Problem", "Two pointers", "Alternative"],
    rows: [
      ["2-sum, tartiblangan", "O(n)", "—"],
      ["2-sum, tartiblanmagan", "O(n log n)", "hash map, O(n)"],
      ["3-sum", "O(n²)", "yo‘q (chegara shu)"],
      ["4-sum", "O(n³)", "meet in the middle, O(n²)"],
      ["3-sum, eng yaqin", "O(n²)", "—"],
      ["k-sum, k katta", "O(n^{k−1})", "meet in the middle"],
    ],
    captionUz: "To‘rtinchi qator qiziq: 4-sum uchun barcha juftliklarning yig‘indisini map ga yig‘ib, O(n²) ga tushirish mumkin.",
    captionEn: "The fourth row is interesting: for 4-sum you can hash the sums of all pairs and bring it down to O(n²)." },
  { t: "p",
    uz: "«Meet in the middle» g‘oyasi: 4-sum uchun barcha juftliklarning yig‘indisini hisoblab, map ga (yig‘indi → juftliklar ro‘yxati) joylashtiramiz. Keyin har juftlik uchun X − yig‘indi ni map dan qidiramiz. Juftliklar soni n²/2, shuning uchun narx O(n²) — O(n³) o‘rniga.",
    en: "The meet-in-the-middle idea: for 4-sum, compute every pair's sum and store it in a map from sum to the list of pairs. Then for each pair look up X − sum. There are about n²/2 pairs, so the cost is O(n²) instead of O(n³)." },
  { t: "note", kind: "warn",
    uz: "3-sum uchun O(n²) dan tezroq umumiy algoritm MA’LUM EMAS — bu «3SUM gipotezasi» deb ataladi va murakkablik nazariyasida ochiq muammo. Shuning uchun masalada n = 10⁵ bo‘lsa va 3-sum kerak bo‘lsa, siz masalani noto‘g‘ri tushungan bo‘lishingiz mumkin.",
    en: "No general algorithm faster than O(n²) is KNOWN for 3-sum — this is the 3SUM conjecture, an open problem in complexity theory. So if a statement gives n = 10⁵ and seems to require 3-sum, you have probably misread it." },
  { t: "exercise",
    qUz: "3-sum da takrorlarni o‘tkazish uchun uchta tekshiruv kerak edi. Agar masala «indekslar juftligi» ni so‘rasa (qiymatlar emas), nima o‘zgaradi?",
    qEn: "3-sum needed three duplicate checks. What changes if the problem asks for INDEX triples rather than value triples?",
    aUz: "Takrorlarni o‘tkazish KERAK EMAS — har xil indekslar har xil javob hisoblanadi, hatto qiymatlar bir xil bo‘lsa ham. Lekin unda ikki ko‘rsatkich to‘g‘ridan-to‘g‘ri ishlamaydi: bir xil qiymatli elementlarni ALOHIDA sanash kerak, ya’ni topilgan juftlik uchun chapdagi va o‘ngdagi teng elementlar sonini ko‘paytirish (1-bosqichdagi mashqning aynan o‘zi). Bu farq masala shartini diqqat bilan o‘qish qanchalik muhimligini ko‘rsatadi: «har xil uchliklar» va «indekslar uchligi» — ikki xil masala.",
    aEn: "The duplicate skipping is NOT needed — distinct indices count as distinct answers even when the values coincide. But then two pointers do not apply directly: equal values must be counted SEPARATELY, multiplying the counts of equal elements on the left and right of a hit (exactly the stage-1 exercise). The difference shows how much depends on reading the statement: “distinct triples” and “index triples” are two different problems." },
 ]},
]},

/* ── 10. Stringlarda oyna: chastota bilan ────────────────────────────── */
"two-pointers-10": { sections: [
 { titleUz: "Oynada chastotalarni yuritish", titleEn: "Maintaining frequencies in a window", blocks: [
  { t: "p",
    uz: "Oyna texnikasining eng ko‘p uchraydigan qo‘llanishi — stringlar. Bu yerda oynada yig‘indi emas, HARFLAR CHASTOTASI kuzatiladi, va bu bir necha yangi naqshni ochadi.",
    en: "The most common application of the window technique is to strings. There the window tracks not a sum but the FREQUENCY of characters, and that opens several new patterns." },
  { t: "sim", titleUz: "Takrorsiz eng uzun bo‘lak", titleEn: "The longest substring without repeats", frames: [
    { spec: { kind: "window", label: "«abcabcbb» — takrorsiz bo‘lak qidiramiz",
        values: ["a", "b", "c"], l: 0, r: 2, agg: "hammasi har xil ✓",
        note: "oyna ichida takror yo‘q" },
      uz: "«abcabcbb» stringida takrorlanmaydigan eng uzun bo‘lakni qidiramiz. Oyna [a, b, c] — hammasi har xil, uzunlik 3.",
      en: "In “abcabcbb” we look for the longest substring with no repeated character. The window [a, b, c] has all distinct characters, length 3." },
    { spec: { kind: "buckets", label: "chastotalar: har harf 1 marta",
        keys: ["a", "b", "c"], counts: [1, 1, 1],
        note: "chastota massivi oynani tavsiflaydi" },
      uz: "Oynani chastota massivi bilan tavsiflaymiz: har harf necha marta uchraydi. Hozircha hammasi 1 — takror yo‘q.",
      en: "The window is described by a frequency table: how often each character occurs. So far every count is 1, so there is no repeat." },
    { spec: { kind: "buckets", label: "yana «a» keldi: chastota 2 bo‘ldi",
        keys: ["a", "b", "c"], counts: [2, 1, 1], hi: [0],
        note: "shart buzildi — qisqartirish kerak" },
      uz: "Yangi «a» kirdi va uning chastotasi 2 bo‘ldi — takror paydo bo‘ldi. Endi chap chegarani surib, ESKI «a» chiqib ketguncha qisqartiramiz.",
      en: "A new “a” enters and its count reaches 2 — a repeat. Now we advance the left edge, shrinking until the OLD “a” has left." },
    { spec: { kind: "window", label: "chap chegara surildi",
        values: ["b", "c", "a"], l: 0, r: 2, agg: "yana hammasi har xil ✓",
        best: [0, 2],
        note: "uzunlik yana 3 — rekord o‘zgarmadi" },
      uz: "Eski «a» chiqdi, oyna [b, c, a] bo‘ldi va shart tiklandi. Uzunlik yana 3. Butun jarayon davomida chap chegara faqat oldinga yurdi.",
      en: "The old “a” is gone, the window is [b, c, a] and the condition holds again, with length 3. Throughout, the left edge only moved forward." },
  ]},
  { t: "code", cpp: "vector<int> cnt(256, 0);\nint l = 0, best = 0;\nfor (int r = 0; r < n; ++r) {\n    ++cnt[s[r]];\n    while (cnt[s[r]] > 1) --cnt[s[l++]];      // takror yo'qolguncha\n    best = max(best, r - l + 1);\n}",
    captionUz: "while sharti aniq: faqat ENDIGINA KIRGAN harfning takrori muammo — boshqa harflarni tekshirish shart emas.",
    captionEn: "The while condition is precise: only the character that just entered can be the duplicate, so no other needs checking." },
  { t: "note", kind: "key",
    uz: "Chastota massivi — oynaning «xotirasi». Uni to‘g‘ri yuritish bu bosqichning butun mohiyati: element KIRGANDA ++cnt, CHIQQANDA −−cnt. Ikkalasini simmetrik yozish odat bo‘lsin — asimmetriya eng ko‘p uchraydigan xato manbai.",
    en: "The frequency table is the window's memory, and maintaining it correctly is the whole substance of this stage: ++cnt on entry, --cnt on exit. Make writing them symmetrically a habit — asymmetry is the main source of bugs here." },
 ]},
 { titleUz: "String oynasining klassik masalalari", titleEn: "Classic string-window problems", blocks: [
  { t: "table", headUz: ["Masala", "Oynadagi shart"], headEn: ["Problem", "The window condition"],
    rows: [
      ["takrorsiz eng uzun bo‘lak", "har chastota ≤ 1"],
      ["ko‘pi bilan k xil harf", "har xil harflar soni ≤ k"],
      ["anagrammani topish", "chastotalar aynan mos"],
      ["eng qisqa qamrovchi bo‘lak", "barcha kerakli harflar bor"],
      ["k marta almashtirish bilan", "uzunlik − eng ko‘p uchragan ≤ k"],
      ["muvozanatli bo‘lak", "chastotalar teng"],
    ],
    captionUz: "To‘rtinchi qator — «minimum window substring», intervyu va musobaqalarda eng mashhur oyna masalasi.",
    captionEn: "The fourth row is the “minimum window substring”, the best-known window problem in interviews and contests." },
  { t: "p",
    uz: "To‘rtinchi qatorni ko‘rib chiqamiz. «t stringidagi barcha harflarni qamrab oluvchi eng qisqa bo‘lakni toping» — bu «eng QISQA» tipidagi oyna (5-bosqich). Chastotalarni to‘liq solishtirish o‘rniga bitta hisoblagich yuritamiz: «nechta kerakli harf yetarli miqdorda to‘plandi». U t dagi har xil harflar soniga yetganda oyna yaroqli bo‘ladi.",
    en: "Take the fourth row: “find the shortest substring covering every character of t”. This is a SHORTEST-type window (stage 5). Instead of comparing whole frequency tables, keep a single counter of how many required characters have reached their needed count; when it equals the number of distinct characters in t, the window is valid." },
  { t: "code", cpp: "int have = 0, need = distinctInT;\nfor (int r = 0; r < n; ++r) {\n    if (++cnt[s[r]] == want[s[r]]) ++have;      // yana bittasi to'ldi\n    while (have == need) {\n        best = min(best, r - l + 1);\n        if (cnt[s[l]]-- == want[s[l]]) --have;  // buzildi\n        ++l;\n    }\n}",
    captionUz: "have hisoblagichi butun chastota jadvalini solishtirishni bitta taqqoslashga aylantiradi — O(26) o‘rniga O(1).",
    captionEn: "The have counter reduces a full frequency comparison to a single test — O(1) instead of O(26)." },
  { t: "note", kind: "warn",
    uz: "Ikkita nozik joyga e’tibor bering. Birinchi: == belgisi (>= emas) — hisoblagich AYNAN kerakli miqdorga yetganda bir marta oshadi, aks holda u bir necha marta oshib ketadi. Ikkinchi: cnt[s[l]]-- == want[s[l]] — bu yerda ham aynan chegaradan o‘tayotgan paytni ushlaymiz.",
    en: "Two subtleties. First, the == (not >=): the counter increments once, exactly when the required count is reached; otherwise it would increment repeatedly. Second, cnt[s[l]]-- == want[s[l]] catches exactly the moment the count falls back below the requirement." },
  { t: "exercise",
    qUz: "«k marta harf almashtirish mumkin, eng uzun bir xil harfli bo‘lakni toping» — oyna sharti nima?",
    qEn: "“You may change up to k characters; find the longest run of one character” — what is the window condition?",
    aUz: "Oyna yaroqli, agar (oyna uzunligi − oynadagi eng ko‘p uchragan harf soni) ≤ k bo‘lsa. Ya’ni almashtirilishi kerak bo‘lgan harflar soni k dan oshmasin. Nozik joy: «eng ko‘p uchragan» qiymatini oyna qisqarganda kamaytirish SHART EMAS — u biroz katta bo‘lib qolsa ham javob buzilmaydi, chunki biz faqat MAKSIMAL uzunlikni qidiryapmiz va noto‘g‘ri katta qiymat oynani qisqartirmaydi. Bu mashhur va nozik optimallashtirish; agar ishonchsiz bo‘lsangiz, har qadamda maksimumni qayta hisoblang — O(26·n) baribir tez.",
    aEn: "The window is valid when (its length − the count of its most frequent character) ≤ k, that is, at most k characters need changing. A subtlety: the “most frequent” value need NOT be decreased when the window shrinks — leaving it slightly stale does not break the answer, because we only seek the MAXIMUM length and a stale-high value never shrinks the window. It is a famous and delicate optimisation; if unsure, recompute the maximum each step at O(26·n), which is still fast." },
 ]},
]},

/* ── 11. Nega O(n): monotonlik va uning chegaralari ──────────────────── */
"two-pointers-11": { sections: [
 { titleUz: "Ichki sikl bor, lekin narx chiziqli", titleEn: "There is an inner loop, yet the cost is linear", blocks: [
  { t: "p",
    uz: "Oyna kodini birinchi marta ko‘rgan har bir odam bir xil savol beradi: ichkarida while sikli bor, tashqarida for — demak bu O(n²) emasmi? Yo‘q, va sababini tushunish bu bo‘limdagi eng muhim narsa.",
    en: "Everyone seeing window code for the first time asks the same question: there is a while inside a for, so is this not O(n²)? No — and understanding why is the most important thing in this track." },
  { t: "note", kind: "key",
    uz: "Dalil: ichki sikl har aylanganda l bittaga OSHADI. l esa 0 dan boshlanadi va n dan oshmaydi. Demak ichki sikl BUTUN dastur davomida ko‘pi bilan n marta aylanadi — har tashqi iteratsiyada emas. Bu AMORTIZATSIYALANGAN tahlil: biz alohida qadamlarni emas, UMUMIY ishni sanaymiz.",
    en: "The argument: every turn of the inner loop INCREASES l by one, and l starts at 0 and never exceeds n. So the inner loop runs at most n times over the WHOLE program, not per outer iteration. This is AMORTISED analysis: we count the TOTAL work rather than the cost of individual steps." },
  { t: "sim", titleUz: "Ko‘rsatkichlar traektoriyasi", titleEn: "The trajectory of the pointers", frames: [
    { spec: { kind: "ptrace", label: "r bir tekis, l sakrab yuradi", n: 8,
        steps: [{ l: 0, r: 0 }, { l: 0, r: 1 }, { l: 0, r: 2 }, { l: 2, r: 3 }, { l: 2, r: 4 },
                { l: 2, r: 5 }, { l: 5, r: 6 }, { l: 5, r: 7 }],
        note: "ikkalasi ham faqat YUQORIGA — hech qachon pastga emas" },
      uz: "Bu rasm butun dalilni ko‘rsatadi. Ko‘k chiziq — r, u har qadamda bittaga oshadi. Yashil chiziq — l, u ba’zan turadi, ba’zan sakraydi. Lekin IKKALASI HAM hech qachon pastga tushmaydi.",
      en: "This picture is the whole argument. The blue line is r, rising by one each step. The green line is l, sometimes flat and sometimes jumping. But NEITHER ever goes down." },
    { spec: { kind: "ptrace", label: "l ning sakrashlari yig‘indisi ≤ n", n: 8,
        steps: [{ l: 0, r: 0 }, { l: 0, r: 3 }, { l: 3, r: 4 }, { l: 3, r: 6 }, { l: 6, r: 7 }],
        note: "katta sakrashlar bo‘lsa ham, jami n dan oshmaydi" },
      uz: "l ba’zan katta sakraydi — bu «qimmat» qadam ko‘rinadi. Lekin katta sakrashdan keyin l uzoq vaqt turadi. Barcha sakrashlarning YIG‘INDISI n dan oshmaydi, chunki l oxirida ko‘pi bilan n ga yetadi.",
      en: "Sometimes l jumps far, which looks like an expensive step. But after a big jump it stays put for a long time. The SUM of all jumps cannot exceed n, because l ends at n at the most." },
    { spec: { kind: "ptrace", label: "eng yomon hol ham chiziqli", n: 8,
        steps: [{ l: 0, r: 0 }, { l: 1, r: 1 }, { l: 2, r: 2 }, { l: 3, r: 3 }, { l: 4, r: 4 },
                { l: 5, r: 5 }, { l: 6, r: 6 }, { l: 7, r: 7 }],
        note: "l har qadamda siljisa ham — jami 2n amal" },
      uz: "Eng yomon holat: l har qadamda siljiydi. Bu ham muammo emas — jami 2n amal (r uchun n, l uchun n). O(n) qoladi. Amortizatsiyalangan tahlilning kuchi shunda: alohida qadam qimmat bo‘lsa ham, umumiy narx chiziqli.",
      en: "The worst case has l moving at every step, and even that is fine: 2n operations in total, n for r and n for l. It remains O(n). That is the power of amortised analysis — individual steps may be expensive while the total stays linear." },
  ]},
  { t: "table", headUz: ["Naqsh", "Nima o‘smaydi", "Narx"], headEn: ["Pattern", "What never decreases", "Cost"],
    rows: [
      ["oyna (l va r)", "ikkala ko‘rsatkich", "O(n)"],
      ["monotonik deque", "har element bir marta kiradi/chiqadi", "O(n)"],
      ["Eyler yo‘li (it[v])", "qo‘shni ko‘rsatkichi", "O(n + m)"],
      ["Z algoritmi (r)", "o‘ng chegara", "O(n)"],
      ["Manacher (r)", "o‘ng chegara", "O(n)"],
      ["DSU (path compression)", "chuqurlik kamayadi", "O(α(n))"],
    ],
    captionUz: "Oltita algoritm, bitta dalil. Bu ro‘yxatni ko‘rish amortizatsiyalangan tahlilni «hiyla» emas, USUL sifatida tanishga yordam beradi.",
    captionEn: "Six algorithms, one argument. Seeing the list helps you recognise amortised analysis as a METHOD rather than a trick." },
 ]},
 { titleUz: "Qachon ikki ko‘rsatkich ISHLAMAYDI", titleEn: "When two pointers do NOT work", blocks: [
  { t: "p",
    uz: "Endi teskari savol, va u bo‘limdagi eng qimmatli qism. Ikki ko‘rsatkich yashirin FARAZGA tayanadi: chap chegarani surish oynani faqat YAXSHILAYDI (yoki faqat yomonlashtiradi) — ya’ni shart MONOTON. Bu faraz buzilsa, algoritm jimgina noto‘g‘ri javob beradi.",
    en: "Now the reverse question, and the most valuable part of the track. Two pointers rest on a hidden ASSUMPTION: moving the left edge only ever improves the window (or only ever worsens it) — the condition is MONOTONE. When that fails, the algorithm silently returns a wrong answer." },
  { t: "sim", titleUz: "Monotonlik buzilgan misol", titleEn: "An example where monotonicity breaks", frames: [
    { spec: { kind: "window", label: "manfiy sonlar bor: [2, −1, 3]",
        values: [2, -1, 3, -5, 4], l: 0, r: 2, agg: "yig‘indi = 4",
        note: "yig‘indi ≤ 4 shartini tekshiramiz" },
      uz: "Massivda manfiy sonlar bor. Oyna [2, −1, 3], yig‘indi 4. «Yig‘indi ≤ 4» sharti bajarilyapti.",
      en: "The array contains negatives. The window [2, −1, 3] sums to 4, and the condition “sum ≤ 4” holds." },
    { spec: { kind: "window", label: "cho‘zamiz: −5 kirdi, yig‘indi KAMAYDI",
        values: [2, -1, 3, -5, 4], l: 0, r: 3, agg: "yig‘indi = −1 (kamaydi!)", bad: true,
        note: "cho‘zish yig‘indini oshirishi SHART EMAS" },
      uz: "Oynani cho‘zdik va yig‘indi 4 dan −1 ga KAMAYDI. Bu asosiy farazni buzadi: musbat sonlarda cho‘zish yig‘indini faqat oshirardi, endi esa yo‘q.",
      en: "Stretching the window dropped the sum from 4 to −1. That breaks the core assumption: with positive numbers, stretching could only increase the sum, and now it does not." },
    { spec: { kind: "window", label: "algoritm qisqartirmaydi — va javobni boy beradi",
        values: [2, -1, 3, -5, 4], l: 0, r: 4, agg: "yig‘indi = 3 ≤ 4 ✓",
        note: "«qisqartirish yordam beradi» qoidasi endi yolg‘on" },
      uz: "Endi «shart buzilsa qisqartir» qoidasi ma’nosini yo‘qotadi: chap chegarani surish yig‘indini OSHIRISHI ham mumkin (manfiy son chiqib ketsa). Algoritm yaroqli oynalarni butunlay o‘tkazib yuboradi.",
      en: "Now the rule “shrink when the condition breaks” is meaningless: advancing the left edge can INCREASE the sum, if a negative leaves. The algorithm skips valid windows entirely." },
  ]},
  { t: "table", headUz: ["Shart", "Monotonmi", "Vosita"], headEn: ["Condition", "Monotone", "Tool"],
    rows: [
      ["yig‘indi ≤ S, musbatlar", "ha", "oyna"],
      ["yig‘indi ≤ S, manfiylar bor", "yo‘q", "prefiks + map yoki set"],
      ["har xil elementlar ≤ k", "ha", "oyna"],
      ["ko‘paytma ≤ P, musbatlar", "ha", "oyna"],
      ["ko‘paytma ≤ P, nol bor", "yo‘q", "nollar bo‘yicha bo‘lish"],
      ["yig‘indi aynan S", "yo‘q", "prefiks + map"],
    ],
    captionUz: "Har oyna masalasidan oldin shu jadvalning ikkinchi ustunini tekshiring. Bu bir daqiqa oladi va noto‘g‘ri yechimdan saqlaydi.",
    captionEn: "Before every window problem, check this table's second column. It takes a minute and prevents a wrong solution." },
  { t: "note", kind: "warn",
    uz: "Monotonlik buzilganini payqashning belgisi: yechim kichik testlarda to‘g‘ri, lekin manfiy sonlar yoki nollar bo‘lgan testlarda noto‘g‘ri. Debugga tushishdan oldin so‘rang: «chap chegarani surish shartni faqat bir tomonga o‘zgartiradimi?» Agar javob yo‘q bo‘lsa, oyna EMAS.",
    en: "The sign that monotonicity broke: the solution is right on small tests and wrong on tests with negatives or zeros. Before debugging, ask: “does moving the left edge change the condition in only one direction?” If not, it is NOT a window problem." },
  { t: "exercise",
    qUz: "«Ko‘paytmasi ≤ P bo‘lgan eng uzun oraliq, barcha sonlar musbat» — oyna ishlaydimi? Massivda 1 lar bo‘lsa-chi?",
    qEn: "“The longest range with product ≤ P, all numbers positive” — does a window work? What if the array contains 1s?",
    aUz: "Ha, ishlaydi. Musbat sonlarda cho‘zish ko‘paytmani faqat oshiradi (yoki 1 lar bo‘lsa o‘zgartirmaydi), qisqartirish esa faqat kamaytiradi — monotonlik saqlanadi. 1 lar muammo emas: ular ko‘paytmani o‘zgartirmaydi, ya’ni shart «kamaymaydigan» bo‘lib qoladi, va bu yetarli. Lekin NOL bo‘lsa halokat: nol kirsa ko‘paytma 0 ga tushadi va chiqsa keskin oshadi — monotonlik yo‘qoladi. Yechim: massivni nollar bo‘yicha bo‘laklarga ajratib, har bo‘lakni alohida yechish.",
    aEn: "Yes. With positive numbers, stretching can only increase the product (or leave it unchanged for 1s) and shrinking only decreases it, so monotonicity holds. The 1s are harmless: they leave the product unchanged, so the condition is still non-decreasing, which suffices. A ZERO, however, is fatal: entering one collapses the product to 0 and removing it makes it jump, destroying monotonicity. The fix is to split the array at the zeros and solve each piece separately." },
 ]},
]},

/* ── 12. Qaysi usulni tanlash ────────────────────────────────────────── */
"two-pointers-12": { sections: [
 { titleUz: "Signal jadvali", titleEn: "The signal table", blocks: [
  { t: "p",
    uz: "O‘n bir bosqich, lekin ularning hammasi bitta g‘oyaning ko‘rinishlari: ikkita indeks, ikkalasi ham faqat oldinga. Masalani o‘qib bo‘lgach qaraladigan jadval — u avval MONOTONLIKNI, keyin usulni so‘raydi.",
    en: "Eleven stages, all faces of one idea: two indices, both moving only forward. The table to consult after reading a problem asks first about MONOTONICITY and only then about the method." },
  { t: "table", headUz: ["Masala matnidagi belgi", "Usul"], headEn: ["The sign in the statement", "Method"],
    rows: [
      ["tartiblangan massiv, juftlik", "qarama-qarshi ko‘rsatkichlar"],
      ["massivdan elementlarni olib tashlash", "o‘qish/yozish ko‘rsatkichlari"],
      ["ikkita tartiblangan massiv", "birlashtirish naqshi"],
      ["«k ta ketma-ket element»", "belgilangan oyna"],
      ["«eng uzun/qisqa segment, shart bilan»", "o‘zgaruvchan oyna"],
      ["oynada min yoki max", "monotonik deque"],
      ["«AYNAN K»", "atMost(K) − atMost(K−1)"],
      ["manfiy sonlar bor", "prefiks + map"],
      ["uchta yoki k ta element", "bittasini qot + ikki ko‘rsatkich"],
      ["stringda harflar sharti", "oyna + chastota massivi"],
      ["shart monoton emas", "oyna EMAS — boshqa yo‘l"],
    ],
    captionUz: "Oxirgi qator ham javob: ikki ko‘rsatkichni RAD ETISH ham to‘g‘ri qaror bo‘lishi mumkin.",
    captionEn: "The last row is also an answer: rejecting two pointers can be the right decision." },
  { t: "diagram", spec: { kind: "flow", label: "Ikkita savol, tartib bilan",
    steps: ["shart monotonmi?", "nima kuzatiladi?"],
    note: "birinchisi — ha/yo‘q, ikkinchisi vositani tanlaydi" } },
  { t: "note", kind: "key",
    uz: "Birinchi savol har doim bir xil: CHAP CHEGARANI SURISH SHARTNI FAQAT BIR TOMONGA O‘ZGARTIRADIMI? Ha bo‘lsa — oyna ishlaydi. Yo‘q bo‘lsa — prefiks, map, yoki boshqa texnika. Bu savolni bermay kod yozish bu bo‘limdagi eng ko‘p uchraydigan xato.",
    en: "The first question is always the same: DOES MOVING THE LEFT EDGE CHANGE THE CONDITION IN ONLY ONE DIRECTION? If yes, a window works. If no, reach for prefix sums, a map or another technique. Writing code without asking it is the commonest mistake in this track." },
 ]},
 { titleUz: "Xatolar va yakuniy fikr", titleEn: "Bugs, and a closing thought", blocks: [
  { t: "table", headUz: ["Simptom", "Sabab", "Yechim"], headEn: ["Symptom", "Cause", "Fix"],
    rows: [
      ["manfiylarda WA", "monotonlik yo‘q", "prefiks + map"],
      ["javob bittaga katta/kichik", "r − l + 1 xato", "kichik testda sanang"],
      ["TLE", "ichki sikl while emas, for", "l ni orqaga qaytarmang"],
      ["cheksiz sikl", "yechim topilgach ko‘rsatkich surilmagan", "ikkalasini ham suring"],
      ["takroriy javoblar (3-sum)", "takrorlar o‘tkazilmagan", "uchta joyda tekshiring"],
      ["chastota noto‘g‘ri", "kirish/chiqish asimmetrik", "++cnt va −−cnt juft yozing"],
      ["prefiksda WA", "seen[0] = 1 unutilgan", "bo‘sh prefiksni qo‘shing"],
    ]},
  { t: "p",
    uz: "Yakuniy fikr. Bu bo‘limdagi kod har doim qisqa — to‘rt-besh qator. Aynan shuning uchun uni «shablon» sifatida yodlab olish vasvasasi kuchli. Lekin shablon sizga qaysi masalada u ISHLAMASLIGINI aytmaydi. Bo‘limdan olib ketiladigan asosiy narsa — kod emas, MONOTONLIK savoli.",
    en: "A closing thought. The code in this track is always short — four or five lines — which makes it tempting to memorise as a template. But a template never tells you which problem it does NOT fit. What to carry away from this track is not the code but the MONOTONICITY question." },
  { t: "note", kind: "tip",
    uz: "Amaliyot uchun: Codeforces da «two pointers» tegi bilan 1200–1500 reytingli 15 ta masalani ishlang, va har birida kod yozishdan oldin bitta jumla yozing: «chap chegarani surganda ___ faqat ___ bo‘ladi». Agar bu jumlani to‘ldira olmasangiz, masala oyna masalasi emas.",
    en: "For practice: solve fifteen Codeforces problems tagged “two pointers” rated 1200–1500, and before coding each one write a single sentence: “when the left edge moves, ___ can only ___”. If you cannot complete it, the problem is not a window problem." },
  { t: "exercise",
    qUz: "«Massivda yig‘indisi ≥ S bo‘lgan eng qisqa oraliq» — sonlar musbat bo‘lsa oyna, manfiy bo‘lsa nima?",
    qEn: "“The shortest range with sum ≥ S” — a window if the numbers are positive; what if they are negative?",
    aUz: "Manfiylar bo‘lsa prefiks yig‘indi va MONOTONIK DEQUE kerak. G‘oya: pre[r] − pre[l] ≥ S ni qidiramiz, ya’ni har r uchun pre[l] ≤ pre[r] − S shartini bajaruvchi eng KATTA l ni topish kerak. Buning uchun prefikslarni o‘suvchi tartibda deque da saqlaymiz: oldidan shartni bajaruvchilarni olamiz, orqadan esa keyingi prefikslardan katta bo‘lganlarni chiqarib tashlaymiz (ular hech qachon kerak bo‘lmaydi). Narx O(n). Bu 6-bosqichdagi monotonik deque ning aynan o‘sha g‘oyasi, faqat prefikslar ustida — va u ikki ko‘rsatkich bo‘limining eng chiroyli yakuni.",
    aEn: "With negatives you need prefix sums and a MONOTONIC DEQUE. The idea: we want pre[r] − pre[l] ≥ S, so for each r we need the LARGEST l with pre[l] ≤ pre[r] − S. Keep the prefixes in a deque in increasing order: pop from the front those that satisfy the condition, and pop from the back any prefix larger than a newer one, since it can never be needed. The cost is O(n). It is exactly the monotonic deque of stage 6 applied to prefixes — and the most elegant possible ending for this track." },
 ]},
]},
};
