-- 027: the remaining 99 problems enter the duel pool.
--
-- The pool has held the same 101 problems since 016, because those were the
-- only ones with a reference solution the bot could play. All 200 now have a
-- verified solution and hidden tests, so the pool can finally match the bank
-- the learner actually browses.
--
-- Generated from app/ui/problem-bank.ts. Regenerate rather than hand-edit: a
-- duel must select on the same rating the bank shows.

insert into public.duel_problem_pool(problem_key, rating, difficulty, topic) values
  ('cond-grade', 800, 'easy', 'programming-basics'),
  ('func-min-of-three', 800, 'easy', 'programming-basics'),
  ('io-echo-sum', 800, 'easy', 'programming-basics'),
  ('loop-multiples', 800, 'easy', 'programming-basics'),
  ('var-swap', 800, 'easy', 'programming-basics'),
  ('array-count-greater', 900, 'easy', 'programming-basics'),
  ('array-index-query', 900, 'easy', 'programming-basics'),
  ('loop-power-table', 900, 'easy', 'programming-basics'),
  ('string-count-char', 900, 'easy', 'programming-basics'),
  ('string-upper', 900, 'easy', 'programming-basics'),
  ('complexity-ops', 1000, 'easy', 'foundations'),
  ('matrix-row-sums', 1000, 'easy', 'programming-basics'),
  ('sort-descending', 1000, 'easy', 'sorting'),
  ('stl-sort-unique', 1000, 'easy', 'programming-basics'),
  ('worst-case-scan', 1000, 'easy', 'foundations'),
  ('constraint-pick', 1100, 'easy', 'foundations'),
  ('log-steps', 1100, 'easy', 'foundations'),
  ('memory-estimate', 1100, 'easy', 'foundations'),
  ('amortized-doubling', 1200, 'medium', 'foundations'),
  ('bt-generate-binary', 1200, 'medium', 'backtracking'),
  ('geo-distance-int', 1200, 'medium', 'geometry'),
  ('graph-degree-max', 1200, 'medium', 'graphs'),
  ('point-in-rect', 1200, 'medium', 'geometry'),
  ('sort-abs', 1200, 'medium', 'sorting'),
  ('sort-by-length', 1200, 'medium', 'sorting'),
  ('bs-first-bad', 1300, 'medium', 'binary-search'),
  ('geo-perimeter', 1300, 'medium', 'geometry'),
  ('graph-path-exists', 1300, 'medium', 'graphs'),
  ('graph-weight-total', 1300, 'medium', 'graphs'),
  ('greedy-coin-canonical', 1300, 'medium', 'greedy'),
  ('map-word-freq', 1300, 'medium', 'data-structures'),
  ('queue-rotate', 1300, 'medium', 'data-structures'),
  ('set-missing-smallest', 1300, 'medium', 'data-structures'),
  ('str-longest-common-prefix', 1300, 'medium', 'strings'),
  ('str-reverse-words', 1300, 'medium', 'strings'),
  ('tree-height', 1300, 'medium', 'trees'),
  ('bs-count-occurrences', 1400, 'medium', 'binary-search'),
  ('geo-collinear', 1400, 'medium', 'geometry'),
  ('geo-manhattan-circle', 1400, 'medium', 'geometry'),
  ('graph-count-edges-tree', 1400, 'medium', 'graphs'),
  ('graph-indegree-zero', 1400, 'medium', 'graphs'),
  ('greedy-max-pairs', 1400, 'medium', 'greedy'),
  ('merge-sort-manual', 1400, 'medium', 'sorting'),
  ('sort-kth-smallest', 1400, 'medium', 'sorting'),
  ('sort-median-pairs', 1400, 'medium', 'sorting'),
  ('stack-postfix', 1400, 'medium', 'data-structures'),
  ('subset-generate-count', 1400, 'medium', 'backtracking'),
  ('tree-parent-depth', 1400, 'medium', 'trees'),
  ('bt-count-paths-grid', 1500, 'medium', 'backtracking'),
  ('bt-string-permutations', 1500, 'medium', 'backtracking'),
  ('bt-sudoku-row', 1500, 'medium', 'backtracking'),
  ('bucket-by-key', 1500, 'medium', 'sorting'),
  ('geo-rect-overlap', 1500, 'medium', 'geometry'),
  ('greedy-max-events', 1500, 'medium', 'greedy'),
  ('polygon-area2', 1500, 'medium', 'geometry'),
  ('sort-anagram-group', 1500, 'medium', 'sorting'),
  ('sort-relative-order', 1500, 'medium', 'sorting'),
  ('bs-sqrt-real', 1600, 'medium', 'binary-search'),
  ('bt-no-adjacent-ones', 1600, 'medium', 'backtracking'),
  ('bt-place-rooks', 1600, 'medium', 'backtracking'),
  ('bt-sum-combinations', 1600, 'medium', 'backtracking'),
  ('dsu-largest-set', 1600, 'medium', 'data-structures'),
  ('geo-grid-lattice', 1600, 'medium', 'geometry'),
  ('graph-farthest', 1600, 'medium', 'graphs'),
  ('greedy-min-jumps-fuel', 1600, 'medium', 'greedy'),
  ('greedy-station-cover', 1600, 'medium', 'greedy'),
  ('grid-count-islands', 1600, 'medium', 'graphs'),
  ('sort-count-pairs-less', 1600, 'medium', 'sorting'),
  ('tree-count-paths-len2', 1600, 'medium', 'trees'),
  ('tree-sum-subtree', 1600, 'medium', 'trees'),
  ('bs-rotated-min', 1700, 'medium', 'binary-search'),
  ('bt-knight-moves', 1700, 'medium', 'backtracking'),
  ('bt-word-paths', 1700, 'medium', 'backtracking'),
  ('graph-bfs-bipartite-sides', 1700, 'medium', 'graphs'),
  ('greedy-remove-digits', 1700, 'medium', 'greedy'),
  ('heap-merge-cost', 1700, 'medium', 'data-structures'),
  ('permutation-rank', 1700, 'medium', 'backtracking'),
  ('tree-is-balanced', 1700, 'medium', 'trees'),
  ('bs-min-capacity', 1800, 'hard', 'binary-search'),
  ('bs-peak-ternary', 1800, 'hard', 'binary-search'),
  ('bt-partition-into-k', 1800, 'hard', 'backtracking'),
  ('deque-window-min', 1800, 'hard', 'data-structures'),
  ('game-nim', 1800, 'hard', 'advanced-cp'),
  ('prefix-2d-sum', 1800, 'hard', 'data-structures'),
  ('bit-fenwick-sum', 1900, 'hard', 'data-structures'),
  ('bs-max-min-distance', 1900, 'hard', 'binary-search'),
  ('convex-hull-size', 1900, 'hard', 'geometry'),
  ('dijkstra-all-dist', 1900, 'hard', 'graphs'),
  ('dp-max-product-subarray', 1900, 'hard', 'dynamic-programming'),
  ('sparse-min', 1900, 'hard', 'advanced-cp'),
  ('tree-centroid', 1900, 'hard', 'trees'),
  ('adv-expected-rolls', 2000, 'hard', 'advanced-cp'),
  ('adv-inversions-fast', 2000, 'hard', 'advanced-cp'),
  ('adv-lis-nlogn', 2000, 'hard', 'advanced-cp'),
  ('matrix-power-fib', 2000, 'hard', 'advanced-cp'),
  ('mo-offline-distinct', 2000, 'hard', 'advanced-cp'),
  ('adv-digit-dp-count', 2100, 'hard', 'advanced-cp'),
  ('hld-path-sum', 2100, 'hard', 'advanced-cp'),
  ('two-sat-simple', 2100, 'hard', 'advanced-cp')
on conflict (problem_key) do update set rating = excluded.rating,
  difficulty = excluded.difficulty, topic = excluded.topic;

-- 021 marked the then-current pool bot-ready in one sweep. These rows arrived
-- after that ran, and default to false, so they need the same mark -- without
-- it they are enabled but the bot filter skips them, and they would only ever
-- appear in human-vs-human duels.
update public.duel_problem_pool set bot_ready = true where enabled;
