-- 032: 102 new problems enter the duel pool.
--
-- The bank grew from 200 to 302. A duel can only select a problem the pool
-- knows about, so without this the new problems would be browsable and
-- solvable but never appear in a round -- and the whole point of writing a
-- reference solution for each of them is that the bot can play them.
--
-- Generated from app/ui/problem-bank.ts, taking every judge key not already
-- inserted by 016 or 027. Regenerate rather than hand-edit: a duel must select
-- on the same rating the bank shows, and the difficulty here is derived from
-- that rating by the same rule as difficultyOf in app/ui/rating.ts (031 moved
-- the insane boundary to 2100).

insert into public.duel_problem_pool(problem_key, rating, difficulty, topic) values
  ('array-alternating-sum', 800, 'easy', 'programming-basics'),
  ('array-shift-left-one', 800, 'easy', 'programming-basics'),
  ('leap-year-check', 800, 'easy', 'math'),
  ('string-swap-case', 800, 'easy', 'strings'),
  ('max-adjacent-difference', 900, 'easy', 'programming-basics'),
  ('reverse-number-digits', 900, 'easy', 'math'),
  ('sum-multiples-two', 900, 'easy', 'math'),
  ('armstrong-number', 1000, 'easy', 'math'),
  ('count-words-with-prefix', 1000, 'easy', 'strings'),
  ('matrix-identity-check', 1000, 'easy', 'data-structures'),
  ('gcd-of-array', 1100, 'easy', 'math'),
  ('nested-loop-iterations', 1100, 'easy', 'foundations'),
  ('set-union-intersection', 1100, 'easy', 'data-structures'),
  ('str-capitalize-words', 1100, 'easy', 'strings'),
  ('hash-two-sum-indices', 1200, 'medium', 'data-structures'),
  ('prefix-equilibrium-index', 1200, 'medium', 'data-structures'),
  ('queue-from-two-stacks', 1200, 'medium', 'data-structures'),
  ('sort-min-abs-difference', 1200, 'medium', 'sorting'),
  ('sorted-squares', 1200, 'medium', 'two-pointers'),
  ('base-convert-any', 1300, 'medium', 'math'),
  ('bs-matrix-search', 1300, 'medium', 'binary-search'),
  ('greedy-lemonade-change', 1300, 'medium', 'greedy'),
  ('stack-min-tracking', 1300, 'medium', 'data-structures'),
  ('str-is-subsequence', 1300, 'medium', 'strings'),
  ('str-roman-to-int', 1300, 'medium', 'strings'),
  ('tree-level-order', 1300, 'medium', 'trees'),
  ('greedy-boat-pairs', 1400, 'medium', 'greedy'),
  ('sort-h-index', 1400, 'medium', 'sorting'),
  ('sort-relative-ranks', 1400, 'medium', 'sorting'),
  ('bs-monotone-cube-root', 1500, 'medium', 'binary-search'),
  ('min-swaps-group-ones', 1500, 'medium', 'two-pointers'),
  ('tree-path-sum-exists', 1500, 'medium', 'trees'),
  ('bs-ship-capacity', 1600, 'medium', 'binary-search'),
  ('greedy-min-refuel', 1600, 'medium', 'greedy'),
  ('greedy-task-cooldown', 1600, 'medium', 'greedy'),
  ('longest-ones-k-flips', 1600, 'medium', 'two-pointers'),
  ('bs-kth-multiplication-table', 1700, 'medium', 'binary-search'),
  ('min-window-substring', 1700, 'medium', 'two-pointers'),
  ('three-sum-zero-count', 1700, 'medium', 'two-pointers'),
  ('tree-diameter-weighted', 1700, 'medium', 'trees'),
  ('diff-array-range-add', 1800, 'hard', 'data-structures'),
  ('interval-stabbing', 1800, 'hard', 'greedy'),
  ('largest-concatenation', 1800, 'hard', 'sorting'),
  ('longest-k-distinct', 1800, 'hard', 'two-pointers'),
  ('multi-source-bfs', 1800, 'hard', 'graphs'),
  ('prefix-sum-2d', 1800, 'hard', 'data-structures'),
  ('job-deadline-profit', 1900, 'hard', 'greedy'),
  ('longest-common-substring', 1900, 'hard', 'strings'),
  ('max-min-spacing', 1900, 'hard', 'binary-search'),
  ('sliding-window-min', 1900, 'hard', 'two-pointers'),
  ('ternary-search-lines', 1900, 'hard', 'binary-search'),
  ('tree-kth-ancestor', 1900, 'hard', 'trees'),
  ('graph-girth', 2000, 'hard', 'graphs'),
  ('max-submatrix-sum', 2000, 'hard', 'dynamic-programming'),
  ('meet-in-middle-subset', 2000, 'hard', 'backtracking'),
  ('zero-one-bfs', 2000, 'hard', 'graphs'),
  ('bellman-negative-cycle', 2100, 'insane', 'graphs'),
  ('euler-phi-sum', 2100, 'insane', 'math'),
  ('ext-gcd-diophantine', 2100, 'insane', 'math'),
  ('floyd-all-pairs', 2100, 'insane', 'graphs'),
  ('segtree-point-max', 2100, 'insane', 'data-structures'),
  ('string-all-borders', 2100, 'insane', 'strings'),
  ('string-min-period', 2100, 'insane', 'strings'),
  ('topo-lexicographic', 2100, 'insane', 'graphs'),
  ('bitmask-assignment', 2200, 'insane', 'dynamic-programming'),
  ('dijkstra-count-paths', 2200, 'insane', 'graphs'),
  ('euler-tour-subtree-sum', 2200, 'insane', 'trees'),
  ('picks-theorem-interior', 2200, 'insane', 'geometry'),
  ('segment-intersection', 2200, 'insane', 'geometry'),
  ('sparse-table-rmq', 2200, 'insane', 'data-structures'),
  ('tree-dp-independent-set', 2200, 'insane', 'trees'),
  ('trie-max-xor', 2200, 'insane', 'data-structures'),
  ('z-function-sum', 2200, 'insane', 'strings'),
  ('count-coprime-pairs', 2300, 'insane', 'math'),
  ('fenwick-kth-element', 2300, 'insane', 'data-structures'),
  ('grundy-subtraction-game', 2300, 'insane', 'math'),
  ('lca-binary-lifting', 2300, 'insane', 'trees'),
  ('manacher-longest-pal', 2300, 'insane', 'strings'),
  ('matrix-power-linear-rec', 2300, 'insane', 'math'),
  ('minimax-path', 2300, 'insane', 'graphs'),
  ('point-in-convex-polygon', 2300, 'insane', 'geometry'),
  ('scc-count', 2300, 'insane', 'graphs'),
  ('tsp-bitmask', 2300, 'insane', 'dynamic-programming'),
  ('articulation-count', 2400, 'insane', 'graphs'),
  ('bipartite-matching-kuhn', 2400, 'insane', 'graphs'),
  ('bridges-count', 2400, 'insane', 'graphs'),
  ('count-palindromic-substrings', 2400, 'insane', 'strings'),
  ('crt-two-congruences', 2400, 'insane', 'math'),
  ('miller-rabin-prime', 2400, 'insane', 'math'),
  ('polygon-diameter', 2400, 'insane', 'geometry'),
  ('segtree-lazy-range-add', 2400, 'insane', 'data-structures'),
  ('closest-pair-points', 2500, 'insane', 'geometry'),
  ('tree-rerooting-distances', 2500, 'insane', 'trees'),
  ('aho-corasick-count', 2600, 'insane', 'strings'),
  ('dinic-max-flow', 2600, 'insane', 'graphs'),
  ('divide-conquer-dp-split', 2600, 'insane', 'advanced-cp'),
  ('subtree-distinct-colors', 2600, 'insane', 'trees'),
  ('convex-hull-trick-dp', 2700, 'insane', 'advanced-cp'),
  ('slope-trick-nondecreasing', 2700, 'insane', 'advanced-cp'),
  ('suffix-array-lrs', 2700, 'insane', 'advanced-cp'),
  ('centroid-paths-within-k', 2800, 'insane', 'advanced-cp'),
  ('ntt-polynomial-multiply', 2800, 'insane', 'advanced-cp')
-- Re-running this migration must be harmless: 027 and 016 already hold 200 of
-- the keys, and a duplicate insert would abort the whole statement.
on conflict (problem_key) do nothing;
