-- 035: the 50 problems of A303-C352 enter the duel pool.
--
-- The bank grew from 302 to 352. A duel selects only from duel_problem_pool,
-- so without this the new problems are browsable and solvable but never turn
-- up in a round -- and a reference solution was written for each of them
-- precisely so the bot can play them.
--
-- Generated by tools/problem-authoring alongside the problems themselves, so
-- the rating here is the rating the bank shows and the difficulty is derived
-- from it by the same rule as difficultyOf in app/ui/rating.ts. Regenerate
-- rather than hand-edit.

insert into public.duel_problem_pool(problem_key, rating, difficulty, topic) values
  ('count-digits', 800, 'easy', 'programming-basics'),
  ('digit-product', 800, 'easy', 'math'),
  ('nth-triangular', 800, 'easy', 'math'),
  ('sum-even-positions', 800, 'easy', 'programming-basics'),
  ('sum-range-formula', 800, 'easy', 'math'),
  ('count-letter-case', 900, 'easy', 'strings'),
  ('count-multiples-range', 900, 'easy', 'math'),
  ('hamming-distance', 900, 'easy', 'strings'),
  ('is-prime-single', 1000, 'easy', 'math'),
  ('string-first-unique', 1000, 'easy', 'strings'),
  ('string-remove-vowels', 1000, 'easy', 'strings'),
  ('average-drop-extremes', 1100, 'easy', 'foundations'),
  ('count-pairs-divisible-k', 1200, 'medium', 'math'),
  ('geo-point-on-segment', 1200, 'medium', 'geometry'),
  ('sort-largest-gap', 1200, 'medium', 'sorting'),
  ('dp-min-cost-stairs', 1300, 'medium', 'dynamic-programming'),
  ('longest-alternating-parity', 1300, 'medium', 'two-pointers'),
  ('prefix-count-less-than', 1300, 'medium', 'data-structures'),
  ('count-subarrays-odd-sum', 1400, 'medium', 'data-structures'),
  ('min-ops-equalise', 1400, 'medium', 'greedy'),
  ('str-longest-repeating-replace', 1400, 'medium', 'two-pointers'),
  ('bs-min-days-bouquets', 1500, 'medium', 'binary-search'),
  ('bs-min-max-pages', 1500, 'medium', 'binary-search'),
  ('greedy-max-units-boxes', 1500, 'medium', 'greedy'),
  ('stack-remove-adjacent-equal', 1500, 'medium', 'data-structures'),
  ('grid-count-rectangles-ones', 1600, 'medium', 'data-structures'),
  ('tree-count-depth-k', 1600, 'medium', 'trees'),
  ('greedy-min-arrows-balloons', 1700, 'medium', 'greedy'),
  ('count-trailing-zeros-factorial', 1800, 'hard', 'math'),
  ('dp-count-lis', 1800, 'hard', 'dynamic-programming'),
  ('graph-eulerian-path', 1800, 'hard', 'graphs'),
  ('dp-partition-min-diff', 1900, 'hard', 'dynamic-programming'),
  ('graph-count-components-size-k', 1900, 'hard', 'graphs'),
  ('knapsack-bounded', 1900, 'hard', 'dynamic-programming'),
  ('tree-sum-distances-root', 1900, 'hard', 'trees'),
  ('count-inversions-pairs-far', 2000, 'hard', 'data-structures'),
  ('dp-longest-zigzag', 2000, 'hard', 'dynamic-programming'),
  ('greedy-min-rooms-lectures', 2000, 'hard', 'greedy'),
  ('string-count-distinct-rotations', 2000, 'hard', 'strings'),
  ('bitmask-min-cost-cover', 2100, 'insane', 'advanced-cp'),
  ('count-good-substrings-mod', 2100, 'insane', 'strings'),
  ('digit-dp-divisible-sum', 2100, 'insane', 'advanced-cp'),
  ('sparse-max-queries', 2100, 'insane', 'advanced-cp'),
  ('count-subarrays-k-distinct', 2200, 'insane', 'two-pointers'),
  ('matrix-power-tribonacci', 2200, 'insane', 'advanced-cp'),
  ('tree-dp-max-matching', 2200, 'insane', 'trees'),
  ('count-paths-dag-mod', 2300, 'insane', 'graphs'),
  ('dsu-offline-connectivity', 2300, 'insane', 'advanced-cp'),
  ('count-binary-no-k-ones', 2400, 'insane', 'advanced-cp'),
  ('mo-range-mode-count', 2400, 'insane', 'advanced-cp')
on conflict (problem_key) do update set rating = excluded.rating,
  difficulty = excluded.difficulty, topic = excluded.topic;

-- 021 marked the then-current pool bot-ready in one sweep and later additions
-- default to false, which would leave these enabled but reachable only in
-- human-vs-human duels.
update public.duel_problem_pool set bot_ready = true where enabled;
