-- 037: the 48 problems of A453-C500 enter the duel pool.
--
-- The bank grew from 452 to 500. A duel selects only from duel_problem_pool,
-- so without this the new problems are browsable and solvable but never turn
-- up in a round -- and a reference solution was written for each of them
-- precisely so the bot can play them.
--
-- Generated by tools/problem-authoring alongside the problems themselves, so
-- the rating here is the rating the bank shows and the difficulty is derived
-- from it by the same rule as difficultyOf in app/ui/rating.ts. Regenerate
-- rather than hand-edit.

insert into public.duel_problem_pool(problem_key, rating, difficulty, topic) values
  ('array-count-sign-changes', 800, 'easy', 'programming-basics'),
  ('array-longest-increasing-prefix', 800, 'easy', 'programming-basics'),
  ('array-running-max-differences', 800, 'easy', 'programming-basics'),
  ('num-count-digit-occurrences', 800, 'easy', 'programming-basics'),
  ('num-round-to-nearest-ten', 800, 'easy', 'programming-basics'),
  ('array-count-distinct-pairs-equal', 1000, 'easy', 'foundations'),
  ('date-day-of-year', 1000, 'easy', 'foundations'),
  ('math-arith-progression-sum', 1000, 'easy', 'math'),
  ('sort-second-smallest-distinct', 1000, 'easy', 'sorting'),
  ('math-count-trailing-zeros-power', 1100, 'easy', 'math'),
  ('math-count-primes-in-range', 1200, 'medium', 'math'),
  ('str-int-to-roman', 1200, 'medium', 'strings'),
  ('str-shortest-repeating-unit', 1200, 'medium', 'strings'),
  ('dp-min-steps-to-one', 1300, 'medium', 'dp'),
  ('str-most-frequent-word', 1300, 'medium', 'strings'),
  ('greedy-max-items-within-budget', 1400, 'medium', 'greedy'),
  ('greedy-min-platforms-meetings', 1400, 'medium', 'greedy'),
  ('str-longest-word-chain-prefix', 1400, 'medium', 'strings'),
  ('str-min-deletions-sorted', 1400, 'medium', 'strings'),
  ('greedy-min-refills-to-reach', 1500, 'medium', 'greedy'),
  ('grid-count-saddle-points', 1500, 'medium', 'foundations'),
  ('two-pointers-longest-sum-at-most', 1500, 'medium', 'two-pointers'),
  ('bit-subset-xor-basis-size', 1600, 'medium', 'math'),
  ('stack-score-of-brackets', 1600, 'medium', 'data-structures'),
  ('bs-min-max-adjacent-after-inserts', 1700, 'medium', 'binary-search'),
  ('dp-count-tilings-2xn', 1700, 'medium', 'dp'),
  ('greedy-max-sum-k-negations', 1700, 'medium', 'greedy'),
  ('two-pointers-count-triangles', 1700, 'medium', 'two-pointers'),
  ('dp-longest-chain-of-pairs', 1800, 'hard', 'dp'),
  ('dp-max-profit-two-trades', 1800, 'hard', 'dp'),
  ('graph-topo-count-fixed-order', 1800, 'hard', 'graphs'),
  ('graph-count-paths-fixed-length-dag', 1900, 'hard', 'graphs'),
  ('grid-shortest-with-one-wall-break', 1900, 'hard', 'graphs'),
  ('tree-count-leaves-per-depth-max', 1900, 'hard', 'trees'),
  ('graph-cheapest-path-k-stops', 2000, 'hard', 'graphs'),
  ('matrix-power-count-walks', 2000, 'hard', 'math'),
  ('segtree-range-min-queries', 2000, 'hard', 'data-structures'),
  ('dp-weighted-interval-schedule', 2100, 'insane', 'dp'),
  ('dsu-earliest-all-connected', 2100, 'insane', 'graphs'),
  ('tree-max-edge-on-path-queries', 2100, 'insane', 'trees'),
  ('adv-min-adjacent-swaps-to-sort', 2200, 'insane', 'advanced-cp'),
  ('adv-min-cost-assign-two-groups', 2200, 'insane', 'advanced-cp'),
  ('adv-bitmask-min-cover-sets', 2300, 'insane', 'advanced-cp'),
  ('adv-count-distinct-subsequences', 2300, 'insane', 'advanced-cp'),
  ('adv-count-subarrays-bounded-max', 2300, 'insane', 'advanced-cp'),
  ('adv-longest-repeated-substring-hash', 2300, 'insane', 'advanced-cp'),
  ('adv-count-subarrays-sum-divisible', 2400, 'insane', 'advanced-cp'),
  ('adv-digit-dp-count-no-repeat', 2400, 'insane', 'advanced-cp')
on conflict (problem_key) do update set rating = excluded.rating,
  difficulty = excluded.difficulty, topic = excluded.topic;

-- 021 marked the then-current pool bot-ready in one sweep and later additions
-- default to false, which would leave these enabled but reachable only in
-- human-vs-human duels.
update public.duel_problem_pool set bot_ready = true where enabled;
