-- 041: the 20 problems of A501-C520 enter the duel pool.
--
-- The bank grew from 500 to 520. A duel selects only from duel_problem_pool,
-- so without this the new problems are browsable and solvable but never turn
-- up in a round -- and a reference solution was written for each of them
-- precisely so the bot can play them.
--
-- Generated by tools/problem-authoring alongside the problems themselves, so
-- the rating here is the rating the bank shows and the difficulty is derived
-- from it by the same rule as difficultyOf in app/ui/rating.ts. Regenerate
-- rather than hand-edit.
--
-- Run AFTER 001-040.

insert into public.duel_problem_pool(problem_key, rating, difficulty, topic) values
  ('array-count-above-average', 800, 'easy', 'programming-basics'),
  ('str-alternating-case-check', 900, 'easy', 'strings'),
  ('geo-quadrant-counts', 1000, 'easy', 'geometry'),
  ('matrix-max-line-sum', 1000, 'easy', 'foundations'),
  ('math-count-digit-sum-divisible', 1000, 'easy', 'math'),
  ('sort-min-total-waiting', 1200, 'medium', 'sorting'),
  ('greedy-max-content-children', 1200, 'medium', 'greedy'),
  ('bs-count-in-range-queries', 1300, 'medium', 'binary-search'),
  ('stack-previous-smaller-index', 1400, 'medium', 'data-structures'),
  ('tree-deepest-level-sum', 1500, 'medium', 'trees'),
  ('bt-split-digits-bounded', 1600, 'medium', 'backtracking'),
  ('grid-knight-shortest', 1600, 'medium', 'graphs'),
  ('geo-count-axis-right-triangles', 1700, 'medium', 'geometry'),
  ('bt-brackets-with-fixed', 1700, 'medium', 'backtracking'),
  ('two-pointers-longest-spread-at-most-k', 1800, 'hard', 'two-pointers'),
  ('dp-count-subseq-occurrences', 1800, 'hard', 'dynamic-programming'),
  ('bs-kth-smallest-pair-distance', 1900, 'hard', 'binary-search'),
  ('dp-merge-adjacent-min-cost', 2100, 'insane', 'dynamic-programming'),
  ('graph-min-edges-strongly-connected', 2300, 'insane', 'graphs'),
  ('adv-count-pairs-xor-at-most', 2300, 'insane', 'advanced-cp')
on conflict (problem_key) do update set rating = excluded.rating,
  difficulty = excluded.difficulty, topic = excluded.topic;

-- 021 marked the then-current pool bot-ready in one sweep and later additions
-- default to false, which would leave these enabled but reachable only in
-- human-vs-human duels.
update public.duel_problem_pool set bot_ready = true where enabled;
